/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Mathlib.Analysis.SpecialFunctions.Log.PosLog
public import Mathlib.NumberTheory.Height.NumberField
public import Mathlib.NumberTheory.Height.Projectivization
public import Mathlib.RingTheory.Ideal.Norm.RelNorm
public import Mathlib.LinearAlgebra.ExteriorPower.Basis
public import Mathlib.LinearAlgebra.Matrix.Rank
public import Mathlib.NumberTheory.Height.MvPolynomial
public import Mathlib.Algebra.Module.ZLattice.Basic
public import Mathlib.MeasureTheory.Measure.Haar.Unique
public import Mathlib.Algebra.Module.ZLattice.Covolume
public import Mathlib.MeasureTheory.Group.GeometryOfNumbers
public import Mathlib.MeasureTheory.Measure.Haar.Disintegration
public import Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls
public import Mathlib.NumberTheory.NumberField.CanonicalEmbedding.Basic
public import Mathlib.RingTheory.Complex
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.NumberTheory.NumberField.Discriminant.Basic
public import Mathlib.Analysis.Matrix.LDL
public import Mathlib.Algebra.Module.LinearMap.Rat
public import Mathlib.Data.Matrix.ColumnRowPartitioned
public import Mathlib.Data.Finsupp.MonomialOrder
public import Mathlib.RingTheory.Polynomial.GaussNorm
public import Mathlib.Analysis.Polynomial.MahlerMeasure
public import Mathlib.Data.Finsupp.Interval
public import Mathlib.Algebra.Order.Antidiag.FinsuppEquiv
public import Mathlib.Algebra.MvPolynomial.Coeff
public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.Analysis.Normed.Algebra.GelfandMazur
public import Mathlib.Analysis.Normed.Field.Instances
public import Mathlib.NumberTheory.NumberField.Completion.InfinitePlace
import Mathlib.NumberTheory.NumberField.Completion.Ramification
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
public import Mathlib.RingTheory.DedekindDomain.SInteger
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.RingTheory.DedekindDomain.SelmerGroup
public import Mathlib.NumberTheory.NumberField.Units.Regulator
import Mathlib.Algebra.FiniteSupport.Basic
import Mathlib.NumberTheory.Ostrowski
public import Mathlib.NumberTheory.NumberField.House
import Mathlib.LinearAlgebra.LinearIndependent.BaseChange
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Data.Sym.Card
import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.Algebra.Order.Hom.Lattice
public import Mathlib.Algebra.MvPolynomial.NoZeroDivisors
public import Mathlib.RingTheory.Polynomial.Wronskian
public import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Algebra.Order.Sub.Prod
import Mathlib.Combinatorics.Nullstellensatz
import Mathlib.Data.Finsupp.PWO
public import Mathlib.RingTheory.Nullstellensatz
import Mathlib.RingTheory.GradedAlgebra.Radical
public import Mathlib.RingTheory.Ideal.AssociatedPrime.Basic
public import Mathlib.RingTheory.Ideal.Height
import Mathlib.GroupTheory.CosetCover
import Mathlib.RingTheory.Ideal.AssociatedPrime.Finiteness
import Mathlib.RingTheory.Ideal.AssociatedPrime.Localization
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.RegularLocalRing.Polynomial
import Mathlib.RingTheory.Depth.Rees
import Mathlib.RingTheory.KrullDimension.Regular
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Square
import Mathlib.LinearAlgebra.TensorProduct.Submodule
import Mathlib.Probability.Distributions.Gaussian.Multivariate
import Mathlib.Probability.Distributions.Gaussian.Fernique
import Mathlib.Topology.Algebra.MvPolynomial
import Mathlib.RingTheory.TensorProduct.IsBaseChangeRightExact
import Mathlib.RingTheory.TensorProduct.IsBaseChangeFree
import Mathlib.Algebra.Module.LocalizedModule.Exact
import Mathlib.Algebra.MvPolynomial.Nilpotent
import Mathlib.RingTheory.MvPolynomial.IrreducibleQuadratic
import Mathlib.RingTheory.Valuation.LocalSubring
import Mathlib.LinearAlgebra.Matrix.Permutation
public import Mathlib.Topology.Compactification.OnePoint.Basic

/-!
# QuantitativeSubspace: the statements of record

Generated by `scripts/make-challenge.py --paper QuantitativeSubspace` from the library
`QuantitativeSubspace` and the libraries it builds on; do not edit. Each `-- <module>` part repeats,
verbatim, the definitions of that module the certified theorems mention, and states the theorems
with `sorry`. Each part opens by clearing Lean's auxiliary-proof cache, as a module boundary does,
and some lower instances locally to restore their module's tie-break. See `COMPARATOR.md`.
-/

-- ArithmeticHeights.Affine
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
public section
open Function Real
namespace Height
variable {K : Type*} [Field K] [AdmissibleAbsValues K] {ι ι' : Type*}
@[expose] noncomputable def mulHeightAff (x : ι → K) : ℝ := mulHeight fun o : Option ι ↦ o.elim 1 x
end Height
end
end
-- DiophantineApproximation.ApproximationDomain
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Module NumberField NumberField.mixedEmbedding NumberField.InfinitePlace Matrix Filter
  Topology
open scoped Pointwise
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] {ι : Type*}
def approxDomain (Sfin : Finset (FinitePlace K)) (L : AbsoluteValue K ℝ → ι → Dual K (ι → K))
    (c : AbsoluteValue K ℝ → ι → ℝ) (Q : ℝ) : Set (ι → K) :=
  {x | (∀ (v : InfinitePlace K) (i : ι), v (L v.1 i x) ≤ Q ^ c v.1 i) ∧
    (∀ v ∈ Sfin, ∀ i : ι, v (L v.1 i x) ≤ Q ^ c v.1 i) ∧
    ∀ v : FinitePlace K, v ∉ Sfin → ∀ j : ι, v (x j) ≤ 1}
variable [Fintype ι]
noncomputable def approxWeight (Sfin : Finset (FinitePlace K)) (c : AbsoluteValue K ℝ → ι → ℝ) :
    ℝ :=
  ∑ v : InfinitePlace K, v.mult * ∑ i, c v.1 i + ∑ v ∈ Sfin, ∑ i, c v.1 i
end NumberField
end
end
-- DiophantineApproximation.FormBaseChange
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Matrix Module
namespace Module.Dual
variable {ι : Type*} [Fintype ι] [DecidableEq ι]
variable {F E : Type*} [CommRing F] [CommRing E]
def compRingHom (M : Dual F (ι → F)) (f : F →+* E) : Dual E (ι → E) :=
  ∑ j, f (M (Pi.single j 1)) • (LinearMap.proj j : Dual E (ι → E))
end Module.Dual
end
end
-- DiophantineApproximation.LocalExtension
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
attribute [local instance 999] SubsemiringClass.toSubmonoidClass
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
public section
open IsDedekindDomain NumberField Module
namespace NumberField.FinitePlace
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
protected abbrev LiesOver (w : FinitePlace F) (v : FinitePlace K) : Prop :=
  w.maximalIdeal.asIdeal.LiesOver v.maximalIdeal.asIdeal
variable (K) in
@[expose] noncomputable def localDegree (w : FinitePlace F) : ℕ :=
  w.maximalIdeal.asIdeal.ramificationIdx (𝓞 K) * w.maximalIdeal.asIdeal.inertiaDeg (𝓞 K)
variable (F) in
def placesOver (v : FinitePlace K) : Set (FinitePlace F) := {w | w.LiesOver v}
variable (F) in
theorem finite_placesOver (v : FinitePlace K) : (placesOver F v).Finite := by
  refine Set.Finite.subset
    ((Algebra.QuasiFinite.finite_primesOver (S := 𝓞 F) v.maximalIdeal.asIdeal).preimage
      (Function.Injective.injOn
        (HeightOneSpectrum.asIdeal_injective.comp FinitePlace.maximalIdeal_injective))) ?_
  exact fun w hw => ⟨w.maximalIdeal.isPrime, hw⟩
variable (F) in
noncomputable def placesOverFinset (v : FinitePlace K) : Finset (FinitePlace F) :=
  (finite_placesOver F v).toFinset
end NumberField.FinitePlace
end
end
-- DiophantineApproximation.ExtensionApproxProd
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
attribute [local instance 999] SubsemiringClass.toSubmonoidClass
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Module NumberField
namespace NumberField
variable {K E : Type*} [Field K] [NumberField K] [Field E] [NumberField E] [Algebra K E]
variable {ι : Type*} [Fintype ι] [DecidableEq ι]
open scoped Classical in
noncomputable def conjSystem (Sinf : Finset (InfinitePlace K)) (Sfin : Finset (FinitePlace K))
    (w' : AbsoluteValue K ℝ → AbsoluteValue E ℝ) (L : AbsoluteValue K ℝ → ι → Dual E (ι → E))
    (U : AbsoluteValue E ℝ) : ι → Dual E (ι → E) :=
  if h : ∃ p : InfinitePlace K × InfinitePlace E × (E ≃ₐ[K] E),
      p.1 ∈ Sinf ∧ p.2.1.1 = U ∧ ∀ z : E, p.2.1 (p.2.2 z) = w' p.1.1 z then
    fun i ↦ (L h.choose.1.1 i).compRingHom (h.choose.2.2 : E →+* E)
  else if h' : ∃ p : FinitePlace K × FinitePlace E × (E ≃ₐ[K] E),
      p.1 ∈ Sfin ∧ p.2.1.1 = U ∧
        ∀ z : E, p.2.1 (p.2.2 z) = w' p.1.1 z ^ p.2.1.localDegree K then
    fun i ↦ (L h'.choose.1.1 i).compRingHom (h'.choose.2.2 : E →+* E)
  else fun i ↦ LinearMap.proj i
end NumberField
end
end
-- DiophantineApproximation.SubspaceKeyInequality
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Module
noncomputable section
namespace NumberField
variable {K : Type*} [Field K] {ι : Type*} [Fintype ι] [DecidableEq ι]
def formMatrix (L : AbsoluteValue K ℝ → ι → Dual K (ι → K)) (v : AbsoluteValue K ℝ) :
    Matrix ι ι K := LinearMap.toMatrix' (LinearMap.pi (L v))
variable [NumberField K]
def sPlace (Sfin : Finset (FinitePlace K)) :
    InfinitePlace K ⊕ ↥Sfin → AbsoluteValue K ℝ :=
  Sum.elim (fun w ↦ w.1) fun w ↦ (w : FinitePlace K).1
end NumberField
end
end
end
-- DiophantineApproximation.PenultimateMinimum
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Module
universe u v
noncomputable section
namespace NumberField
open MvPolynomial Height exteriorPower
variable {K : Type*} [Field K] [NumberField K] {ι : Type u} [Fintype ι] [DecidableEq ι]
  [LinearOrder ι] [Nonempty ι]
variable (Sfin : Finset (FinitePlace K)) (L : AbsoluteValue K ℝ → ι → Dual K (ι → K)) in
noncomputable def formCount : ℕ :=
  (Set.range fun q : (InfinitePlace K ⊕ ↥Sfin) × ι ↦ L (sPlace Sfin q.1) q.2).ncard
end NumberField
end
end
end
-- DiophantineApproximation.SubspaceSystem
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
noncomputable def systemPlace (S : Finset (HeightOneSpectrum (𝓞 K))) :
    InfinitePlace K ⊕ S → AbsoluteValue K ℝ
  | .inl v => v.1
  | .inr v => (FinitePlace.mk v.1).1
noncomputable def systemMult (S : Finset (HeightOneSpectrum (𝓞 K))) : InfinitePlace K ⊕ S → ℕ
  | .inl v => v.mult
  | .inr _ => 1
noncomputable def systemAbs (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (p : InfinitePlace K ⊕ S) (a : F) : ℝ :=
  w (systemPlace S p) a ^ systemMult S p
noncomputable def systemValue (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (p : InfinitePlace K ⊕ S) (i : ι) (x : ι → K) : ℝ :=
  systemAbs S w p (L (systemPlace S p) i fun j ↦ algebraMap K F (x j))
def systemSet (S : Finset (HeightOneSpectrum (𝓞 K))) (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F)) (C : InfinitePlace K ⊕ S → ℝ)
    (c : InfinitePlace K ⊕ S → ι → ℝ) : Set (ι → K) :=
  {x | (∀ j, x j ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) ∧
    ∀ p i, systemValue S w L p i x ≤ C p * mulHeightAff x ^ c p i}
noncomputable def systemWeight {S : Finset (HeightOneSpectrum (𝓞 K))}
    (c : InfinitePlace K ⊕ S → ι → ℝ) : ℝ :=
  ∑ p, ∑ i, c p i
noncomputable def systemConst {S : Finset (HeightOneSpectrum (𝓞 K))}
    (C : InfinitePlace K ⊕ S → ℝ) : ℝ :=
  ∏ p, C p
noncomputable def systemDet (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (L : AbsoluteValue K ℝ → ι → Dual F (ι → F)) :
    ℝ :=
  ∏ p, systemAbs S w p (LinearMap.det (LinearMap.pi (L (systemPlace S p))))
noncomputable def systemExponent (S : Finset (HeightOneSpectrum (𝓞 K))) :
    InfinitePlace K ⊕ S → ℝ
  | .inl v => v.mult / finrank ℚ K
  | .inr _ => 0
structure IsNormalizedSystem (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (C : InfinitePlace K ⊕ S → ℝ) (c : InfinitePlace K ⊕ S → ι → ℝ) (H : ℝ) (D R : ℕ)
    (δ : ℝ) : Prop where
  /-- The coefficients have absolute height at most `H`. -/
  height_le : ∀ p i j, absMulHeight₁ (L (systemPlace S p) i (Pi.basisFun F ι j)) ≤ H
  /-- The coefficients have degree at most `D` over `K`. -/
  degree_le : ∀ p i j, (minpoly K (L (systemPlace S p) i (Pi.basisFun F ι j))).natDegree ≤ D
  /-- At most `R` distinct forms occur. -/
  ncard_le : (Set.range fun q : (InfinitePlace K ⊕ S) × ι ↦ L (systemPlace S q.1) q.2).ncard ≤ R
  /-- The constants are positive. -/
  const_pos : ∀ p, 0 < C p
  /-- The product of the constants is at most `(∏ |det L v|_v) ^ (1 / n)`. -/
  const_le : systemConst C ≤ systemDet S w L ^ (Fintype.card ι : ℝ)⁻¹
  delta_pos : 0 < δ
  delta_le_one : δ ≤ 1
  /-- The weight is at most `-δ`. -/
  weight_le : systemWeight c ≤ -δ
  /-- No exponent exceeds the normalized local degree. -/
  exponent_le : ∀ p i, c p i ≤ systemExponent S p
  /-- Some exponent at every place attains it. -/
  exists_exponent_eq : ∀ p, ∃ i, c p i = systemExponent S p
end NumberField
end
end
-- DiophantineApproximation.SystemDomain
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
attribute [local instance 999] SubsemiringClass.toSubmonoidClass
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Module NumberField IsDedekindDomain Height
namespace NumberField
variable {K E : Type*} [Field K] [NumberField K] [Field E] [NumberField E] [Algebra K E]
variable {ι : Type*} [Fintype ι]
variable (E) in
open scoped Classical in
noncomputable def systemPlacesOver (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Finset (FinitePlace E) :=
  S.attach.biUnion fun p ↦ FinitePlace.placesOverFinset E (FinitePlace.mk p.1)
noncomputable def approxSupWeight {F : Type*} [Field F] [NumberField F]
    (Sfin : Finset (FinitePlace F)) (c : AbsoluteValue F ℝ → ι → ℝ) : ℝ :=
  (∑ v : InfinitePlace F, v.mult * ⨆ i, c v.1 i) + ∑ v ∈ Sfin, ⨆ i, c v.1 i
end NumberField
end
end
-- DiophantineApproximation.ThresholdHeights
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Module Height
namespace NumberField
variable {K : Type*} [Field K] [NumberField K]
section Forms
open NumberField.InfinitePlace NumberField.mixedEmbedding MeasureTheory
variable {ι : Type*} [Fintype ι] [DecidableEq ι]
variable (Sfin : Finset (FinitePlace K)) (L : AbsoluteValue K ℝ → ι → Dual K (ι → K))
noncomputable def formLogHeight : ℝ :=
  ∑ t : (InfinitePlace K ⊕ ↥Sfin) × ι × ι,
    logHeight₁ (formMatrix L (sPlace Sfin t.1) t.2.1 t.2.2)
end Forms
end NumberField
end
end
-- DiophantineApproximation.SystemSubspaceCount
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
attribute [local instance 999] SubsemiringClass.toSubmonoidClass
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Module NumberField IsDedekindDomain Height
universe u
namespace NumberField
variable {K E : Type*} [Field K] [NumberField K] [Field E] [NumberField E] [Algebra K E]
variable {ι : Type u} [Fintype ι]
noncomputable def systemEps (e : ℕ) (δ : ℝ) : ℝ :=
  e * δ / 4
noncomputable def systemAbsBound (e n : ℕ) : ℝ :=
  e * (2 * n + 2)
variable (K) in
noncomputable def scalarConst (S : Finset (HeightOneSpectrum (𝓞 K))) : ℝ :=
  2 ^ finrank ℚ K * (∏ q ∈ S, (Ideal.absNorm q.asIdeal : ℝ)) * √|(discr K : ℝ)|
noncomputable def systemHeightThreshold (n d t : ℕ) (δ H μ : ℝ) : ℝ :=
  (2 * n * μ + 4 * t * (Real.log n.factorial + n * (d * Real.log H))) / δ
noncomputable def systemMiddleRatio (d n : ℕ) (H δ X : ℝ) : ℝ :=
  max 1 (X / (d * Real.log (max (2 * H) ((n : ℝ) ^ (2 * n / δ)))))
end NumberField
end
end
-- ForMathlib.LinearAlgebra.WeightFiltration
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Module
namespace Submodule
variable {k M : Type*} [DivisionRing k] [AddCommGroup M] [Module k M] [FiniteDimensional k M]
noncomputable def weightSlope (w : Submodule k M → ℝ) (U V : Submodule k M) : ℝ :=
  (w V - w U) / ((finrank k V : ℝ) - finrank k U)
variable {w : Submodule k M → ℝ} {U V T : Submodule k M}
structure IsDestabilizing (w : Submodule k M → ℝ) (V T : Submodule k M) : Prop where
  lt : T < V
  le : ∀ U < V, weightSlope w T V ≤ weightSlope w U V
  least : ∀ U < V, weightSlope w U V = weightSlope w T V → T ≤ U
end Submodule
end
end
-- QuantitativeSubspace.TwistedHeight
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Function Module Matrix IsDedekindDomain
namespace NumberField
namespace FinitePlace
variable {K E F : Type*} [Field K] [NumberField K] [Field E] [NumberField E] [Algebra K E]
  [Field F] [NumberField F] [Algebra K F] [Algebra E F] [IsScalarTower K E F]
variable (K) in
noncomputable def under (w : FinitePlace E) : FinitePlace K :=
  FinitePlace.mk (w.maximalIdeal.under (𝓞 K))
end FinitePlace
variable (K : Type*) [Field K] [NumberField K] (ι : Type*) [Fintype ι] [DecidableEq ι]
namespace Twist
variable {K ι}
variable {E F : Type*} [Field E] [NumberField E] [Algebra K E]
  [Field F] [NumberField F] [Algebra K F] [Algebra E F] [IsScalarTower K E F]
section Absolute
open IntermediateField
variable {Ω : Type*} [Field Ω] [Algebra K Ω] [Algebra.IsAlgebraic K Ω]
omit [Fintype ι] [DecidableEq ι] in
theorem numberField_adjoin_range [Finite ι] (x : ι → Ω) : NumberField (adjoin K (Set.range x)) :=
  have : CharZero Ω := charZero_of_injective_algebraMap (algebraMap K Ω).injective
  have : FiniteDimensional K (adjoin K (Set.range x)) :=
    finiteDimensional_adjoin fun y _ ↦ (Algebra.IsAlgebraic.isAlgebraic (R := K) y).isIntegral
  { to_finiteDimensional := Module.Finite.trans K _ }
end Absolute
end Twist
end NumberField
end
end
-- QuantitativeSubspace.FormHeight
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Function Module Matrix IsDedekindDomain
namespace NumberField
variable (K : Type*) [Field K] [NumberField K] (ι : Type*) [Fintype ι] [DecidableEq ι]
structure FormSystem where
  /-- The forms at the infinite places. -/
  arch : InfinitePlace K → Matrix ι ι K
  arch_det_ne_zero : ∀ v, (arch v).det ≠ 0
  /-- The forms at the finite places. -/
  fin : FinitePlace K → Matrix ι ι K
  fin_det_ne_zero : ∀ v, (fin v).det ≠ 0
  finite_range_fin : (Set.range fin).Finite
structure FormWeight where
  /-- The weights at the infinite places. -/
  arch : InfinitePlace K → ι → ℝ
  arch_pos : ∀ v i, 0 < arch v i
  /-- The weights at the finite places. -/
  fin : FinitePlace K → ι → ℝ
  fin_pos : ∀ v i, 0 < fin v i
  finite_setOf_fin_ne_one : {v | fin v ≠ 1}.Finite
namespace FormSystem
variable {K ι} (L : FormSystem K ι) (a : FormWeight K ι)
variable {E F : Type*} [Field E] [NumberField E] [Algebra K E]
  [Field F] [NumberField F] [Algebra K F] [Algebra E F] [IsScalarTower K E F]
noncomputable def archFactor (w : InfinitePlace E) (x : ι → E) : ℝ :=
  ⨆ i, w ((((L.arch (w.comap (algebraMap K E))).map (algebraMap K E)) *ᵥ x) i) /
    a.arch (w.comap (algebraMap K E)) i
noncomputable def finFactor (w : FinitePlace E) (x : ι → E) : ℝ :=
  ⨆ i, w ((((L.fin (w.under K)).map (algebraMap K E)) *ᵥ x) i) /
    a.fin (w.under K) i ^ w.localDegree K
noncomputable def mulHeight (x : ι → E) : ℝ :=
  (∏ w : InfinitePlace E, L.archFactor a w x ^ w.mult) * ∏ᶠ w : FinitePlace E, L.finFactor a w x
section Absolute
open IntermediateField
variable {Ω : Type*} [Field Ω] [Algebra K Ω] [Algebra.IsAlgebraic K Ω]
noncomputable def absMulHeight (x : ι → Ω) : ℝ :=
  haveI := Twist.numberField_adjoin_range (K := K) x
  L.mulHeight a (fun i ↦ (⟨x i, subset_adjoin K _ ⟨i, rfl⟩⟩ : adjoin K (Set.range x))) ^
    ((finrank ℚ (adjoin K (Set.range x)) : ℝ))⁻¹
end Absolute
section Det
noncomputable def mulDet : ℝ :=
  (∏ v : InfinitePlace K, v (L.arch v).det ^ v.mult) * ∏ᶠ v : FinitePlace K, v (L.fin v).det
noncomputable def absDet : ℝ :=
  L.mulDet ^ ((finrank ℚ K : ℝ))⁻¹
end Det
section Forms
def formSet : Set (ι → K) := {f | ∃ v i, L.arch v i = f} ∪ {f | ∃ v i, L.fin v i = f}
theorem finite_formSet : L.formSet.Finite := by
  refine Set.Finite.union ?_ ?_
  · refine (Set.finite_range fun p : InfinitePlace K × ι ↦ L.arch p.1 p.2).subset ?_
    rintro f ⟨v, i, h⟩
    exact ⟨(v, i), h⟩
  · have : Finite (Set.range L.fin) := L.finite_range_fin
    refine (Set.finite_iUnion fun M : Set.range L.fin ↦ Set.finite_range M.1).subset ?_
    rintro f ⟨v, i, h⟩
    exact Set.mem_iUnion.mpr ⟨⟨_, v, rfl⟩, i, h⟩
noncomputable def forms : Finset (ι → K) := L.finite_formSet.toFinset
open scoped Classical in
noncomputable def detSet : Finset K :=
  (Fintype.piFinset fun _ : ι ↦ L.forms).image fun M ↦ (Matrix.of M).det
noncomputable def mulFormHeight : ℝ :=
  (∏ v : InfinitePlace K, (⨆ e : L.detSet, v e) ^ v.mult) *
    ∏ᶠ v : FinitePlace K, ⨆ e : L.detSet, v e
noncomputable def absFormHeight : ℝ :=
  L.mulFormHeight ^ ((finrank ℚ K : ℝ))⁻¹
end Forms
end FormSystem
structure FormExponent where
  /-- The exponents at the infinite places. -/
  arch : InfinitePlace K → ι → ℝ
  /-- The exponents at the finite places. -/
  fin : FinitePlace K → ι → ℝ
  finite_setOf_fin_ne_zero : {v | fin v ≠ 0}.Finite
namespace FormExponent
variable {K ι} (c : FormExponent K ι) {Q : ℝ} (hQ : 0 < Q)
noncomputable def weight : FormWeight K ι where
  arch v i := Q ^ (c.arch v i * finrank ℚ K / v.mult)
  arch_pos _ _ := Real.rpow_pos_of_pos hQ _
  fin v i := Q ^ (c.fin v i * finrank ℚ K)
  fin_pos _ _ := Real.rpow_pos_of_pos hQ _
  finite_setOf_fin_ne_one := c.finite_setOf_fin_ne_zero.subset fun v hv h ↦ hv <| by
    funext i
    simp [h]
end FormExponent
end NumberField
end
end
-- QuantitativeSubspace.FormSuccessiveInfima
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Module Submodule
namespace NumberField
section Generic
variable {ι : Type*} (Ω : Type*) [Field Ω] (h : (ι → Ω) → ℝ)
noncomputable def heightSpace (lam : ℝ) : Submodule Ω (ι → Ω) :=
  span Ω {x | h x ≤ lam}
noncomputable def heightInf (i : ℕ) : ℝ :=
  sInf {lam | 0 ≤ lam ∧ i ≤ finrank Ω (heightSpace Ω h lam)}
end Generic
namespace FormSystem
variable {K ι : Type*} [Field K] [NumberField K] [Fintype ι] [DecidableEq ι]
  (L : FormSystem K ι) (a : FormWeight K ι)
  (Ω : Type*) [Field Ω] [Algebra K Ω] [Algebra.IsAlgebraic K Ω]
noncomputable abbrev successiveInf (i : ℕ) : ℝ :=
  heightInf Ω (L.absMulHeight a) i
end FormSystem
end NumberField
end
end
-- QuantitativeSubspace.FormMinkowski
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Finset Function Module Matrix IsDedekindDomain
namespace NumberField
variable {K ι : Type*} [Field K] [NumberField K] [Fintype ι]
namespace FormExponent
variable (c : FormExponent K ι)
noncomputable def sum : ℝ :=
  ∑ v, ∑ i, c.arch v i + ∑ᶠ v, ∑ i, c.fin v i
end FormExponent
end NumberField
end
end
-- QuantitativeSubspace.FormSubspaceWeight
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Module Finset
namespace Submodule
section Greedy
variable {k W : Type*} [Field k] [AddCommGroup W] [Module k W] [FiniteDimensional k W]
  (f : ℕ → Module.Dual k W)
noncomputable def spanFirst (j : ℕ) : Submodule k (Module.Dual k W) := span k (f '' Set.Iio j)
end Greedy
section FormWeight
variable {k V ι : Type*} [Field k] [AddCommGroup V] [Module k V] [FiniteDimensional k V]
  [Finite ι] (ℓ : ι → Module.Dual k V) (c : ι → ℝ)
def IsFormBasis (U : Submodule k V) (I : Finset ι) : Prop :=
  #I = finrank k U ∧ LinearIndepOn k (fun i ↦ (ℓ i).domRestrict U) (I : Set ι)
noncomputable def formWeight (U : Submodule k V) : ℝ :=
  sInf ((fun I : Finset ι ↦ ∑ i ∈ I, c i) '' {I | IsFormBasis ℓ U I})
end FormWeight
end Submodule
namespace NumberField
open Submodule
namespace FormSystem
variable {K ι : Type*} [Field K] [NumberField K] [Fintype ι] [DecidableEq ι]
  (L : FormSystem K ι) (c : FormExponent K ι)
variable {Ω : Type*} [Field Ω] [Algebra K Ω]
noncomputable def matrixForms (A : Matrix ι ι K) (i : ι) : Module.Dual Ω (ι → Ω) :=
  (LinearMap.proj i).comp (A.map (algebraMap K Ω)).mulVecLin
noncomputable def subspaceWeight (U : Submodule Ω (ι → Ω)) : ℝ :=
  ∑ v, formWeight (matrixForms (L.arch v)) (c.arch v) U +
    ∑ᶠ v, formWeight (matrixForms (L.fin v)) (c.fin v) U
end FormSystem
end NumberField
end
end
-- QuantitativeSubspace.FormInfimaGap
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 0] IsRegularLocalRing.toIsLocalRing
@[expose] public section
open Module Finset Matrix Submodule
namespace NumberField
namespace FormSystem
variable {K : Type*} [Field K] [NumberField K] {n : ℕ}
structure IsNormalSemistable (L : FormSystem K (Fin n)) (c : FormExponent K (Fin n))
    (Ω : Type*) [Field Ω] [Algebra K Ω] : Prop where
  sum_arch : ∀ v, ∑ i, c.arch v i = 0
  sum_fin : ∀ v, ∑ i, c.fin v i = 0
  sum_iSup_le : (∑ v, ⨆ i, c.arch v i) + ∑ᶠ v, ⨆ i, c.fin v i ≤ 1
  exists_v₀ : ∃ v₀ : FinitePlace K, L.fin v₀ = 1 ∧ c.fin v₀ = 0
  subspaceWeight_le : ∀ U : Submodule Ω (Fin n → Ω), U ≠ ⊤ → L.subspaceWeight c U ≤ 0
end FormSystem
end NumberField
end
end
-- QuantitativeSubspace.FormSemistableGap
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Finset Module Real
namespace NumberField.FormSystem
variable {K : Type*} [Field K] [NumberField K] {n : ℕ} (L : FormSystem K (Fin n))
variable {L} {R : ℕ}
noncomputable def thetaOneA (n m : ℕ) (ε : ℝ) : ℝ :=
  2 ^ n + 2 ^ n * (m / ε) ^ m * (20 * m ^ 3 + m + 2 * m ^ 2 * (2 * 2 ^ n + n ^ 2))
noncomputable def thetaOneB (n m R : ℕ) (ε : ℝ) : ℝ :=
  2 ^ n * (m / ε) ^ m * (2 * m ^ 2 * (2 * n * R ^ n))
noncomputable def thetaTwoA (n : ℕ) (ε : ℝ) : ℝ :=
  5 * 2 ^ n + 2 * n ^ 2 + 1 + 2 ^ n * (2 ^ n / ε + 1)
noncomputable def thetaTwoB (n R : ℕ) : ℝ := 4 * n * R ^ n
noncomputable def gapEps (n : ℕ) (δ : ℝ) : ℝ := δ / (40 * n ^ 2 * 2 ^ n)
noncomputable def gapChain (n R : ℕ) (δ : ℝ) : ℕ :=
  ⌈2 / gapEps n δ ^ 2 * Real.log (2 * ((R : ℝ) ^ n * (n / gapEps n δ + 2) ^ n + 1))⌉₊
noncomputable def gapBlocks (n R : ℕ) (δ : ℝ) : ℕ := gapChain n R δ + 1
noncomputable def gapRatio (n R : ℕ) (δ : ℝ) : ℝ := 4 * (gapBlocks n R δ : ℝ) / gapEps n δ
noncomputable def gapIntervals (n R : ℕ) (δ : ℝ) : ℕ := (n - 1) * gapChain n R δ
noncomputable def gapThreshold (n R : ℕ) (δ ℓ : ℝ) : ℝ :=
  (n ^ 2 + R ^ n * ℓ) / δ + (3 * n ^ 2 + 3 * n * R ^ n * ℓ) + (3 * n ^ 2 + 6 * ℓ) +
    4 * n ^ 3 + n ^ 2 * 2 ^ n * (3 * n ^ 3 + ℓ) / δ +
    3 * n * R ^ n * (3 * n ^ 2 + ℓ) / δ +
    3 * R ^ n / δ * (thetaOneA n (gapBlocks n R δ) (gapEps n δ) +
      thetaOneB n (gapBlocks n R δ) R (gapEps n δ) * ℓ + 1) +
    2 * n * 2 ^ n / δ * (1 + 2 * thetaTwoA n (gapEps n δ) + 2 * thetaTwoB n R * ℓ)
end NumberField.FormSystem
namespace NumberField.FormSystem
variable {K : Type} [Field K] [NumberField K] {n : ℕ} {Ω : Type*} [Field Ω] [Algebra K Ω]
  [Algebra.IsAlgebraic K Ω] [IsAlgClosed Ω] (L : FormSystem K (Fin n)) (c : FormExponent K (Fin n))
theorem exists_intervals (hLs : L.IsNormalSemistable c Ω) (hn : 2 ≤ n) {R : ℕ}
    (hR : #L.forms ≤ R) (hnR : n ≤ R) {δ : ℝ} (hδ : 0 < δ) (hδ1 : δ ≤ 1) :
    ∃ a : Fin (gapIntervals n R δ) → ℝ, (∀ i, 1 < a i) ∧ ∀ (Q : ℝ) (hQ : 1 < Q),
      Real.exp (gapThreshold n R δ (Real.log L.absFormHeight)) ≤ Q →
      L.successiveInf (c.weight (zero_lt_one.trans hQ)) Ω 1 ≤ Q ^ (-δ) →
      ∃ i, a i ≤ Q ∧ Q ≤ a i ^ (2 * gapRatio n R δ) := by
  sorry
end NumberField.FormSystem
end
-- QuantitativeSubspace.FormIntervalResult
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Finset Module Matrix
namespace Real
noncomputable def cutCount (θ ω : ℝ) : ℕ := ⌊Real.log θ / Real.log ω⌋₊ + 1
end Real
namespace NumberField.FormSystem
noncomputable def quotThreshold (n R : ℕ) (δ ℓ : ℝ) : ℝ :=
  (∑ p ∈ Icc 1 n, gapThreshold p (R ^ n) (δ / (2 * n)) ((8 * R) ^ n * (Real.log 2 + ℓ))) +
    2 * n / δ * (Real.log n + (4 * R) ^ n * (Real.log 2 + ℓ) + ℓ) +
    2 * n / δ * ((8 * R) ^ n * R ^ n * (Real.log 2 + ℓ)) + 1
noncomputable def cutRatio (R : ℕ) (δ : ℝ) : ℝ := Real.log (3 * R) / δ
noncomputable def intervalBound (n R : ℕ) (δ : ℝ) : ℝ :=
  quotThreshold n R δ 0 * δ / Real.log 2 + R * (quotThreshold n R δ 1 - quotThreshold n R δ 0)
noncomputable def intervalCount (n R : ℕ) (δ : ℝ) : ℕ :=
  Real.cutCount (intervalBound n R δ) (cutRatio R δ) +
    (Icc 1 n).sup fun p ↦ gapIntervals p (R ^ n) (δ / (2 * n)) *
      Real.cutCount (2 * gapRatio p (R ^ n) (δ / (2 * n))) (cutRatio R δ)
section Reduction
variable {K : Type} [Field K] [NumberField K] {n k m : ℕ} {Ω : Type*} [Field Ω] [Algebra K Ω] [Algebra.IsAlgebraic K Ω] [IsAlgClosed Ω] (L : FormSystem K (Fin n)) (c : FormExponent K (Fin n))
theorem exists_intervals_cover (hn : 2 ≤ n) (hc : c.sum = 0)
    (hsup : (∑ v, ⨆ i, c.arch v i) + ∑ᶠ v, ⨆ i, c.fin v i ≤ 1) {R : ℕ} (hR : #L.forms ≤ R)
    {δ : ℝ} (hδ : 0 < δ) (hδ1 : δ ≤ 1) {T : Submodule Ω (Fin n → Ω)}
    (hT : Submodule.IsDestabilizing (L.subspaceWeight c) ⊤ T) :
    ∃ s : Finset ℝ, #s ≤ intervalCount n R δ ∧
      (∀ b ∈ s, max (L.absFormHeight ^ ((R : ℝ)⁻¹)) ((n : ℝ) ^ δ⁻¹) ≤ b) ∧
      ∀ (Q : ℝ) (hQ : 1 ≤ Q), max (L.absFormHeight ^ ((R : ℝ)⁻¹)) ((n : ℝ) ^ δ⁻¹) ≤ Q →
      ∀ x : Fin n → Ω, x ∉ T → L.absMulHeight (c.weight (zero_lt_one.trans_le hQ)) x ≤
        L.absDet ^ ((n : ℝ)⁻¹) * Q ^ (-δ) →
      ∃ b ∈ s, b ≤ Q ∧ Q < b ^ cutRatio R δ := by
  sorry
end Reduction
end NumberField.FormSystem
end
-- QuantitativeSubspace.FormDomainSystem
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Finset Module Matrix
namespace NumberField
variable {K : Type} [Field K] {ι : Type*} [Fintype ι] {n : ℕ}
section Interval
noncomputable def domainDelta (n : ℕ) (ε A : ℝ) : ℝ := ε / (4 * n * A)
noncomputable def domainThreshold (n d s : ℕ) (ε A F : ℝ) : ℝ :=
  d / (2 * A) * ((Real.log n.factorial + n * F / d) + Real.log n / domainDelta n ε A +
    ((s + n).choose n : ℝ) * (Real.log n.factorial + n * F / d) / (n * domainDelta n ε A))
variable (K) (e : ι ≃ Fin n) {Ω : Type*} [Field Ω] [Algebra K Ω]
open scoped Classical in
theorem exists_forall_mem_interval_approxDomain_ef [Nontrivial ι] [DecidableEq ι] [NumberField K]
    {Sfin : Finset (FinitePlace K)} {L : AbsoluteValue K ℝ → ι → Dual K (ι → K)}
    (hLInf : ∀ w : InfinitePlace K, LinearIndependent K (L w.1))
    (hLFin : ∀ v ∈ Sfin, LinearIndependent K (L v.1)) {c : AbsoluteValue K ℝ → ι → ℝ}
    {ε : ℝ} (hε : 0 < ε) (hc : approxWeight Sfin c ≤ -ε) {A : ℝ}
    (hεA : ε ≤ 4 * Fintype.card ι * A)
    (hA : approxSupWeight Sfin c - approxWeight Sfin c / Fintype.card ι ≤ 2 * A) {s : ℕ}
    (hs : formCount Sfin L ≤ s) {X₀ : ℝ}
    (hX₀ : domainThreshold (Fintype.card ι) (finrank ℚ K) s ε A (formLogHeight Sfin L) ≤ X₀) :
    ∃ T : Finset (Submodule K (ι → K)), #T ≤ 1 ∧ (∀ W ∈ T, W ≠ ⊤) ∧
      ∃ 𝒯 : Finset ℝ,
        #𝒯 ≤ FormSystem.intervalCount (Fintype.card ι) (s + Fintype.card ι)
          (domainDelta (Fintype.card ι) ε A) ∧
        (∀ t ∈ 𝒯, X₀ ≤ t) ∧ ∀ Q : ℝ, 1 < Q → X₀ ≤ Real.log Q →
          (∃ W ∈ T, approxDomain Sfin L c Q ⊆ W) ∨
            ∃ t ∈ 𝒯, t ≤ Real.log Q ∧ Real.log Q <
              FormSystem.cutRatio (s + Fintype.card ι) (domainDelta (Fintype.card ι) ε A) * t := by
  sorry
end Interval
end NumberField
end
-- QuantitativeSubspace.FormIntervalCount
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Finset
namespace NumberField.FormSystem
noncomputable def chainBound (n R : ℕ) (δ : ℝ) : ℝ :=
  64000 * n ^ 8 * 4 ^ n / δ ^ 2 * Real.log (64 * n * R / δ) + 2
section ClosedForm
variable {n R : ℕ} {δ : ℝ}
theorem intervalCount_le (hn : 2 ≤ n) (hR : 2 ≤ R) (hδ : 0 < δ) (hδ1 : δ ≤ 1) :
    (intervalCount n R δ : ℝ) ≤ 60 * n * (n + 3) * chainBound n R δ := by
  sorry
end ClosedForm
end NumberField.FormSystem
end
-- QuantitativeSubspace.FormSystemCount
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Finset Module NumberField IsDedekindDomain Height
namespace NumberField
noncomputable def efEps (e : ℕ) (δ : ℝ) : ℝ := e * δ / 2
noncomputable def efSpread (e n : ℕ) (δ : ℝ) : ℝ := e * (1 + δ / n) / 2
noncomputable def efSystemDelta (n : ℕ) (δ : ℝ) : ℝ := δ / (4 * (n + δ))
noncomputable def efLargeCount (n e r : ℕ) (δ : ℝ) : ℝ :=
  1 + FormSystem.intervalCount n (r * e + n) (efSystemDelta n δ) *
    (1 + Real.log (FormSystem.cutRatio (r * e + n) (efSystemDelta n δ)) /
      Real.log (1 + δ / (2 * n)))
variable {K E : Type} [Field K] [NumberField K] [Field E] [NumberField E] [Algebra K E]
variable {ι : Type*} [Fintype ι]
variable (E) in
open scoped Classical in
noncomputable def efSystemThreshold (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue E ℝ) (L : AbsoluteValue K ℝ → ι → Dual E (ι → E))
    (r : ℕ) (H δ : ℝ) : ℝ :=
  max (domainThreshold (Fintype.card ι) (finrank ℚ E) (r * finrank K E)
      (efEps (finrank K E) δ) (efSpread (finrank K E) (Fintype.card ι) δ)
      (formLogHeight (systemPlacesOver E S) (conjSystem univ (S.image FinitePlace.mk) w L)))
    (max (finrank ℚ K * (2 * Fintype.card ι / δ) * Real.log (Fintype.card ι))
      (systemHeightThreshold (Fintype.card ι) (finrank ℚ E) (Fintype.card (InfinitePlace K) + #S)
        δ H (Real.log (scalarConst K S))))
open scoped Classical in
theorem exists_finset_submodule_of_efSystemThreshold_le [IsGalois K E]
    (S : Finset (HeightOneSpectrum (𝓞 K))) (w : AbsoluteValue K ℝ → AbsoluteValue E ℝ)
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    {L : AbsoluteValue K ℝ → ι → Dual E (ι → E)} {C : InfinitePlace K ⊕ S → ℝ}
    {c : InfinitePlace K ⊕ S → ι → ℝ} {H : ℝ} {D R : ℕ} {δ : ℝ}
    (hN : IsNormalizedSystem S w L C c H D R δ) :
    ∃ T : Finset (Submodule K (ι → K)),
      (#T : ℝ) ≤ efLargeCount (Fintype.card ι) (finrank K E) R δ ∧
      (∀ U ∈ T, U ≠ ⊤) ∧
      ∀ x ∈ systemSet S w L C c,
        efSystemThreshold E S w L R H δ ≤ Real.log (mulHeightAff x) → ∃ U ∈ T, x ∈ U := by
  sorry
open scoped Classical in
theorem exists_finset_submodule_of_isNormalizedSystem_ef [IsGalois K E]
    (S : Finset (HeightOneSpectrum (𝓞 K))) (w : AbsoluteValue K ℝ → AbsoluteValue E ℝ)
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    {L : AbsoluteValue K ℝ → ι → Dual E (ι → E)} {C : InfinitePlace K ⊕ S → ℝ}
    {c : InfinitePlace K ⊕ S → ι → ℝ} {H : ℝ} {D R : ℕ} {δ : ℝ}
    (hN : IsNormalizedSystem S w L C c H D R δ) :
    ∃ T : Finset (Submodule K (ι → K)),
      (#T : ℝ) ≤ δ⁻¹ * ((10 ^ 3 * Fintype.card ι) ^ (Fintype.card ι * finrank ℚ K) +
          4 * Fintype.card ι * Real.log (Real.log (4 * H))) +
        (1 + Real.log (systemMiddleRatio (finrank ℚ K) (Fintype.card ι) H δ
            (efSystemThreshold E S w L R H δ)) /
              Real.log (1 + δ / (2 * Fintype.card ι))) +
        efLargeCount (Fintype.card ι) (finrank K E) R δ ∧
      (∀ U ∈ T, U ≠ ⊤) ∧ ∀ x ∈ systemSet S w L C c, ∃ U ∈ T, x ∈ U := by
  sorry
open scoped Classical in
theorem efSystemThreshold_le [IsGalois K E] {S : Finset (HeightOneSpectrum (𝓞 K))}
    {w : AbsoluteValue K ℝ → AbsoluteValue E ℝ}
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    {L : AbsoluteValue K ℝ → ι → Dual E (ι → E)} {C : InfinitePlace K ⊕ S → ℝ}
    {c : InfinitePlace K ⊕ S → ι → ℝ} {H : ℝ} {D R : ℕ} {δ : ℝ}
    (hN : IsNormalizedSystem S w L C c H D R δ) :
    efSystemThreshold E S w L R H δ ≤
      max (domainThreshold (Fintype.card ι) (finrank ℚ E) (R * finrank K E)
          (efEps (finrank K E) δ) (efSpread (finrank K E) (Fintype.card ι) δ)
          ((Fintype.card (InfinitePlace E) + #(systemPlacesOver E S)) * Fintype.card ι ^ 2 *
            (finrank ℚ E * Real.log H)))
        (max (finrank ℚ K * (2 * Fintype.card ι / δ) * Real.log (Fintype.card ι))
          (systemHeightThreshold (Fintype.card ι) (finrank ℚ E)
            (Fintype.card (InfinitePlace K) + #S) δ H (Real.log (scalarConst K S)))) := by
  sorry
theorem efLargeCount_le_shape {n : ℕ} (e r : ℕ) (hn : 2 ≤ n) {δ : ℝ} (hδ : 0 < δ)
    (hδ1 : δ ≤ 1) :
    efLargeCount n e r δ ≤ 3 * 10 ^ 9 * 4 ^ n * n ^ 13 / δ ^ 3 *
      Real.log (64 * n * (r * e + n : ℕ) / efSystemDelta n δ) *
      Real.log (FormSystem.cutRatio (r * e + n) (efSystemDelta n δ)) := by
  sorry
theorem efLargeCount_le_ef {n e r : ℕ} (hn : 2 ≤ n) (he : 1 ≤ e) (hr : 1 ≤ r) {δ : ℝ}
    (hδ : 0 < δ) (hδ1 : δ ≤ 1) :
    efLargeCount n e r δ ≤ 2 * 10 ^ 13 * 4 ^ n * n ^ 14 / δ ^ 3 *
      Real.log (3 * (r * e : ℕ) / δ) * Real.log (Real.log (3 * (r * e : ℕ)) / δ) := by
  sorry
end NumberField
end
