/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Mathlib.Analysis.SpecialFunctions.Log.PosLog
public import Mathlib.NumberTheory.Height.NumberField
public import Mathlib.NumberTheory.Height.Projectivization
public import Mathlib.RingTheory.Ideal.Norm.RelNorm
public import Mathlib.LinearAlgebra.ExteriorPower.Basis
public import Mathlib.LinearAlgebra.Matrix.Rank
public import Mathlib.NumberTheory.Height.MvPolynomial
public import Mathlib.Algebra.Module.ZLattice.Basic
public import Mathlib.MeasureTheory.Measure.Haar.Unique
public import Mathlib.Algebra.Module.ZLattice.Covolume
public import Mathlib.MeasureTheory.Group.GeometryOfNumbers
public import Mathlib.MeasureTheory.Measure.Haar.Disintegration
public import Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls
public import Mathlib.NumberTheory.NumberField.CanonicalEmbedding.Basic
public import Mathlib.RingTheory.Complex
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.NumberTheory.NumberField.Discriminant.Basic
public import Mathlib.Analysis.Matrix.LDL
public import Mathlib.Algebra.Module.LinearMap.Rat
public import Mathlib.Data.Matrix.ColumnRowPartitioned
public import Mathlib.Algebra.Order.Antidiag.FinsuppEquiv
public import Mathlib.LinearAlgebra.LinearIndependent.BaseChange
public import Mathlib.NumberTheory.NumberField.House
public import Mathlib.Analysis.Normed.Algebra.GelfandMazur
public import Mathlib.Analysis.Normed.Field.Instances
public import Mathlib.NumberTheory.NumberField.Completion.InfinitePlace
public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
public import Mathlib.RingTheory.DedekindDomain.SInteger
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.RingTheory.DedekindDomain.SelmerGroup
public import Mathlib.NumberTheory.NumberField.Units.Regulator
public import Mathlib.NumberTheory.Ostrowski
public import Mathlib.Data.Finsupp.MonomialOrder
public import Mathlib.RingTheory.Polynomial.GaussNorm
public import Mathlib.Analysis.Polynomial.MahlerMeasure
public import Mathlib.Data.Finsupp.Interval
public import Mathlib.RingTheory.Polynomial.Wronskian
public import Mathlib.Algebra.MvPolynomial.NoZeroDivisors
public import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Algebra.FiniteSupport.Basic
public import Mathlib.Algebra.MvPolynomial.Coeff
public import Mathlib.Algebra.MvPolynomial.Funext
public import Mathlib.Topology.Compactification.OnePoint.Basic
public import Mathlib.NumberTheory.Transcendental.Liouville.LiouvilleWith
import Mathlib.NumberTheory.DiophantineApproximation.Basic
import Mathlib.NumberTheory.Transcendental.Liouville.LiouvilleNumber
import Mathlib.NumberTheory.NumberField.Completion.Ramification

/-!
# Siegel's lemma, Roth's theorem and the Subspace Theorem: the statements of record

Generated by `scripts/make-challenge.py` from the libraries `ArithmeticHeights` and
`DiophantineApproximation`; do not edit. Each `-- <module>` part repeats, verbatim, the definitions
of that module the certified theorems mention, and states the theorems with `sorry`. Each part
opens by clearing Lean's auxiliary-proof cache, as a module boundary does, and some lower
instances locally to restore their module's tie-break. See `COMPARATOR.md`.
-/

-- ArithmeticHeights.Arakelov
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
namespace NumberField
open Finset Function Height Real
variable {K : Type*} [Field K] [NumberField K] {ι ι' : Type*} [Fintype ι] [Fintype ι']
@[expose] noncomputable def arakelovMulHeight (x : ι → K) : ℝ :=
  have : Decidable (x = 0) := Classical.propDecidable _
  if x = 0 then 1 else
    (∏ v : InfinitePlace K, (∑ i, v (x i) ^ 2) ^ (v.mult / 2 : ℝ)) *
      ∏ᶠ v : FinitePlace K, ⨆ i, v (x i)
end NumberField
end
-- ArithmeticHeights.Absolute
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
namespace NumberField
open Function IntermediateField Module
section Def
variable {K : Type*} [Field K] [CharZero K] {ι : Type*} [Finite ι]
open scoped Classical in
@[expose] noncomputable def absMulHeight (x : ι → K) : ℝ :=
  if hx : ∀ i, IsIntegral ℚ (x i) then
    haveI : FiniteDimensional ℚ (adjoin ℚ (Set.range x)) :=
      finiteDimensional_adjoin fun y hy ↦ by obtain ⟨i, rfl⟩ := hy; exact hx i
    haveI : NumberField (adjoin ℚ (Set.range x)) := {}
    Height.mulHeight (fun i ↦ (⟨x i, subset_adjoin ℚ _ ⟨i, rfl⟩⟩ : adjoin ℚ (Set.range x)))
      ^ ((finrank ℚ (adjoin ℚ (Set.range x)) : ℝ))⁻¹
  else 1
end Def
end NumberField
end
-- ArithmeticHeights.Affine
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Function Real
namespace Height
variable {K : Type*} [Field K] [AdmissibleAbsValues K] {ι ι' : Type*}
@[expose] noncomputable def mulHeightAff (x : ι → K) : ℝ := mulHeight fun o : Option ι ↦ o.elim 1 x
end Height
end
-- ArithmeticHeights.Plucker
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Module
namespace exteriorPower
section Plucker
variable {R : Type*} [CommRing R] {ι : Type*} [Fintype ι] [LinearOrder ι]
@[expose] noncomputable def plucker (k : ℕ) (v : Fin k → (ι → R)) : Set.powersetCard ι k → R :=
  ((Pi.basisFun R ι).exteriorPower k).equivFun (ιMulti R k v)
end Plucker
end exteriorPower
end
-- ArithmeticHeights.Matrix
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Finset Function Height AdmissibleAbsValues Real
namespace Matrix
variable {K : Type*} [Field K] [AdmissibleAbsValues K] {m n p m' n' : Type*}
@[expose] noncomputable def mulHeight (A : Matrix m n K) : ℝ :=
  Height.mulHeight fun q : m × n ↦ A q.1 q.2
end Matrix
end
-- ArithmeticHeights.BombieriVaalerEntries
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Finset Matrix Module NumberField Real
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Fintype ι] [LinearOrder ι] {m : ℕ}
open scoped Classical in
theorem exists_ne_zero_mem_ker_absMulHeight_le (A : Matrix (Fin m) ι K)
    (hm : A.rank < Fintype.card ι) :
    ∃ x : ι → K, x ≠ 0 ∧ A.mulVec x = 0 ∧ (∀ j, IsIntegral ℤ (x j)) ∧
      absMulHeight x ≤
        |(NumberField.discr K : ℝ)| ^ (2 * finrank ℚ K : ℝ)⁻¹
          * (Real.sqrt (Fintype.card ι) * A.mulHeight ^ (finrank ℚ K : ℝ)⁻¹) ^
              ((A.rank : ℝ) / (Fintype.card ι - A.rank)) := by
  sorry
end NumberField
end
-- ArithmeticHeights.BombieriVaalerRelative
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Finset Matrix Module NumberField Real
namespace NumberField
variable {K F : Type*} [Field K] [Field F] [NumberField K] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι] [LinearOrder ι] {m : ℕ}
open scoped Classical in
theorem exists_linearIndependent_mem_ker_prod_absMulHeight_le (A : Matrix (Fin m) ι F)
    (hmn : finrank K F * m < Fintype.card ι) :
    ∃ x : Fin (Fintype.card ι - finrank K F * m) → (ι → K),
      LinearIndependent K x ∧
      (∀ l, A.mulVec (fun j ↦ algebraMap K F (x l j)) = 0) ∧
      (∀ l j, IsIntegral ℤ (x l j)) ∧
      (∏ l, absMulHeight (x l)) ≤
        |(NumberField.discr K : ℝ)| ^
            ((Fintype.card ι - finrank K F * m : ℝ) / (2 * finrank ℚ K))
          * ∏ i, (arakelovMulHeight (A i) ^ (finrank ℚ F : ℝ)⁻¹) ^ finrank K F := by
  sorry
end NumberField
end
-- ArithmeticHeights.Polynomial
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
namespace MvPolynomial
open Height
section General
variable {K : Type*} [Field K] [AdmissibleAbsValues K] {σ : Type*}
@[expose] noncomputable def mulHeight (p : MvPolynomial σ K) : ℝ := Finsupp.mulHeight p.coeff
end General
end MvPolynomial
end
-- ArithmeticHeights.MonomialIndex
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Finsupp Height Module
namespace Finsupp
variable {σ : Type*}
instance instFiniteSubtypeDegreeLE [Finite σ] (D : ℕ) : Finite {m : σ →₀ ℕ // m.degree ≤ D} :=
  (Finsupp.finite_of_degree_le D).to_subtype
noncomputable instance instFintypeSubtypeDegreeLE [Finite σ] (D : ℕ) :
    Fintype {m : σ →₀ ℕ // m.degree ≤ D} :=
  Fintype.ofFinite _
end Finsupp
end
-- ArithmeticHeights.AuxiliaryPolynomial
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Finsupp Matrix Module MvPolynomial NumberField Real
namespace MvPolynomial
section Absolute
variable {K : Type*} [Field K] [NumberField K] {σ : Type*} [Finite σ] {N D : ℕ}
theorem exists_ne_zero_mem_ker_mulHeight_rpow_le
    (A : Matrix (Fin N) {m : σ →₀ ℕ // m.degree ≤ D} K)
    (hA : A.rank < Fintype.card {m : σ →₀ ℕ // m.degree ≤ D}) :
    ∃ P : MvPolynomial σ K, P ≠ 0 ∧ P.totalDegree ≤ D ∧
      (∀ m, IsIntegral ℤ (P.coeff m)) ∧
      A.mulVec (fun m ↦ P.coeff (m : σ →₀ ℕ)) = 0 ∧
      P.mulHeight ^ ((finrank ℚ K : ℝ))⁻¹ ≤
        |(NumberField.discr K : ℝ)| ^ (2 * finrank ℚ K : ℝ)⁻¹ *
          (Real.sqrt (Fintype.card {m : σ →₀ ℕ // m.degree ≤ D}) *
              A.mulHeight ^ ((finrank ℚ K : ℝ))⁻¹) ^
            ((A.rank : ℝ) / (Fintype.card {m : σ →₀ ℕ // m.degree ≤ D} - A.rank)) := by
  sorry
end Absolute
end MvPolynomial
end
-- ArithmeticHeights.Siegel
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Finset Height Matrix
attribute [local instance] Matrix.seminormedAddCommGroup
namespace Int.Matrix
variable {α β : Type*} [Fintype α] [Fintype β] (A : Matrix α β ℤ)
theorem exists_ne_zero_mulVec_eq_zero_iSup_abs_le {B : ℤ} (hB : 1 ≤ B) (hA : ∀ i j, |A i j| ≤ B)
    (hn : Fintype.card α < Fintype.card β) (hm : 0 < Fintype.card α) :
    ∃ x : β → ℤ, x ≠ 0 ∧ A *ᵥ x = 0 ∧
      ((⨆ j, |x j| : ℤ) : ℝ) ≤ ((Fintype.card β : ℝ) * B) ^
        ((Fintype.card α : ℝ) / ((Fintype.card β : ℝ) - Fintype.card α)) := by
  sorry
end Int.Matrix
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Finite ι]
open scoped Classical in
theorem exists_forall_exists_ne_zero_mulVec_eq_zero_absMulHeight_le (K : Type*) [Field K]
    [NumberField K] :
    ∃ C : ℝ, ∀ (p q : ℕ) (a : Matrix (Fin p) (Fin q) (𝓞 K)) (A : ℝ), a ≠ 0 → 0 < p → p < q →
      (∀ k l, house ((a k l : K)) ≤ A) →
      ∃ ξ : Fin q → 𝓞 K, ξ ≠ 0 ∧ a *ᵥ ξ = 0 ∧
        absMulHeight (fun l ↦ ((ξ l : K))) ≤ C * ((C * q * A) ^ ((p : ℝ) / (q - p))) := by
  sorry
end NumberField
end
-- ArithmeticHeights.BombieriVaaler
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
public section
open Finset MeasureTheory Module Submodule Matrix exteriorPower
open scoped ENNReal Pointwise
namespace Int.Matrix
variable {ι : Type*} [Fintype ι] [LinearOrder ι] {m : ℕ}
noncomputable def minorGcd (A : _root_.Matrix (Fin m) ι ℤ) : ℤ :=
  (univ : Finset (Set.powersetCard ι m)).gcd (plucker m A.row)
theorem exists_linearIndependent_mulVec_eq_zero_prod_iSup_abs_le (A : _root_.Matrix (Fin m) ι ℤ)
    (hA : LinearIndependent ℚ (A.map ((↑) : ℤ → ℚ)).row) :
    ∃ x : Fin (Fintype.card ι - m) → (ι → ℤ), LinearIndependent ℤ x ∧ (∀ l, A *ᵥ x l = 0) ∧
      (∏ l, ((⨆ i, |x l i| : ℤ) : ℝ)) ≤
        Real.sqrt (((A * Aᵀ).det : ℤ) : ℝ) / ((minorGcd A : ℤ) : ℝ) := by
  sorry
theorem exists_ne_zero_mulVec_eq_zero_iSup_abs_le_det_rpow (A : _root_.Matrix (Fin m) ι ℤ)
    (hA : LinearIndependent ℚ (A.map ((↑) : ℤ → ℚ)).row) (hmn : m < Fintype.card ι) :
    ∃ x : ι → ℤ, x ≠ 0 ∧ A *ᵥ x = 0 ∧
      ((⨆ i, |x i| : ℤ) : ℝ) ≤
        (Real.sqrt (((A * Aᵀ).det : ℤ) : ℝ) / ((minorGcd A : ℤ) : ℝ)) ^
          (((Fintype.card ι : ℝ) - m)⁻¹) := by
  sorry
end Int.Matrix
end
end
-- DiophantineApproximation.RothTheorem
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Height MvPolynomial Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
noncomputable def rothEps (κ : ℝ) : ℝ := (1 / 2 - 1 / κ) / 16
noncomputable def rothClassSize (κ : ℝ) (s : ℕ) : ℕ := ⌈2 * (s : ℝ) / (1 / 2 - 1 / κ)⌉₊ + 1
noncomputable def rothChainLength (κ : ℝ) (s r : ℕ) : ℕ :=
  ⌈Real.log (2 * (r : ℝ) * s + 1) / (6 * rothEps κ ^ 2)⌉₊
noncomputable def rothRatio (κ : ℝ) (s r : ℕ) : ℝ := 2 / rothEps κ ^ 2 ^ rothChainLength κ s r
theorem finite_setOf_prod_min_one_le (Sinf : Finset (InfinitePlace K))
    (Sfin : Finset (FinitePlace K)) (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v ∈ Sinf, (w v.1).LiesOver v.1) (hwFin : ∀ v ∈ Sfin, (w v.1).LiesOver v.1)
    (α : AbsoluteValue K ℝ → F) {κ : ℝ} (hκ : 2 < κ) :
    {β : K | (∏ v ∈ Sinf, min 1 (w v.1 (algebraMap K F β - α v.1)) ^ v.mult) *
        ∏ v ∈ Sfin, min 1 (w v.1 (algebraMap K F β - α v.1)) ≤ mulHeight₁ β ^ (-κ)}.Finite := by
  sorry
end NumberField
end
-- DiophantineApproximation.RothInfinity
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Height OnePoint
namespace AbsoluteValue
variable {F : Type*} [Field F] (W : AbsoluteValue F ℝ)
noncomputable def onePointApprox : OnePoint F → F → ℝ
  | ∞, β => (max 1 (W β))⁻¹
  | (a : F), β => min 1 (W (β - a))
end AbsoluteValue
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
open AbsoluteValue
theorem finite_setOf_prod_onePointApprox_le (Sinf : Finset (InfinitePlace K))
    (Sfin : Finset (FinitePlace K)) (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v ∈ Sinf, (w v.1).LiesOver v.1) (hwFin : ∀ v ∈ Sfin, (w v.1).LiesOver v.1)
    (α : AbsoluteValue K ℝ → OnePoint F) {κ : ℝ} (hκ : 2 < κ) :
    {β : K | (∏ v ∈ Sinf, (w v.1).onePointApprox (α v.1) (algebraMap K F β) ^ v.mult) *
        ∏ v ∈ Sfin, (w v.1).onePointApprox (α v.1) (algebraMap K F β)
      ≤ mulHeight₁ β ^ (-κ)}.Finite := by
  sorry
end NumberField
end
end
-- DiophantineApproximation.ApproxProd
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Height Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
noncomputable def approxProd (Sinf : Finset (InfinitePlace K)) (Sfin : Finset (FinitePlace K))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F)) (x : ι → K) : ℝ :=
  (∏ v ∈ Sinf, (∏ i, w v.1 (L v.1 i fun j ↦ algebraMap K F (x j)) / ⨆ j, v (x j)) ^ v.mult) *
    ∏ v ∈ Sfin, ∏ i, w v.1 (L v.1 i fun j ↦ algebraMap K F (x j)) / ⨆ j, v (x j)
end NumberField
end
end
-- DiophantineApproximation.AffineProd
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
noncomputable def affineProd (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F)) (x : ι → K) : ℝ :=
  (∏ v : InfinitePlace K, (∏ i, w v.1 (L v.1 i fun j ↦ algebraMap K F (x j))) ^ v.mult) *
    ∏ v ∈ S, ∏ i, w (FinitePlace.mk v).1
      (L (FinitePlace.mk v).1 i fun j ↦ algebraMap K F (x j))
end NumberField
end
end
-- DiophantineApproximation.ApproximationDomain
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Module NumberField NumberField.mixedEmbedding NumberField.InfinitePlace Matrix Filter
  Topology
open scoped Pointwise
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] {ι : Type*}
def approxDomain (Sfin : Finset (FinitePlace K)) (L : AbsoluteValue K ℝ → ι → Dual K (ι → K))
    (c : AbsoluteValue K ℝ → ι → ℝ) (Q : ℝ) : Set (ι → K) :=
  {x | (∀ (v : InfinitePlace K) (i : ι), v (L v.1 i x) ≤ Q ^ c v.1 i) ∧
    (∀ v ∈ Sfin, ∀ i : ι, v (L v.1 i x) ≤ Q ^ c v.1 i) ∧
    ∀ v : FinitePlace K, v ∉ Sfin → ∀ j : ι, v (x j) ≤ 1}
variable [Fintype ι]
noncomputable def approxWeight (Sfin : Finset (FinitePlace K)) (c : AbsoluteValue K ℝ → ι → ℝ) :
    ℝ :=
  ∑ v : InfinitePlace K, v.mult * ∑ i, c v.1 i + ∑ v ∈ Sfin, ∑ i, c v.1 i
end NumberField
end
-- DiophantineApproximation.RationalPlaces
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open NumberField Height
instance Nat.Primes.instFactPrime (p : Nat.Primes) : Fact (p : ℕ).Prime := ⟨p.2⟩
end
end
-- DiophantineApproximation.GeneralPosition
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Finset Module Set
namespace Module.Dual
variable {F : Type*} [Field F] {ι κ : Type*}
def IsGeneralPosition (F : Type*) [Field F] {ι κ : Type*} (B : Finset κ)
    (M : κ → Dual F (ι → F)) : Prop :=
  ∀ s ⊆ B, s.card ≤ Nat.card ι → LinearIndependent F fun k : s ↦ M k
end Module.Dual
end
-- DiophantineApproximation.IrrationalityExponent
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
public section
open Filter
open scoped ENNReal NNReal
namespace Real
@[expose] noncomputable def irrationalityExponent (ξ : ℝ) : ℝ≥0∞ :=
  ⨆ (p : ℝ≥0) (_ : LiouvilleWith p ξ), (p : ℝ≥0∞)
end Real
end
-- DiophantineApproximation.MovingTargets
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Asymptotics Filter Height Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
theorem finite_setOf_prod_min_one_le_of_isLittleO (Sinf : Finset (InfinitePlace K))
    (Sfin : Finset (FinitePlace K)) (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v ∈ Sinf, (w v.1).LiesOver v.1) (hwFin : ∀ v ∈ Sfin, (w v.1).LiesOver v.1)
    {κ : ℝ} (hκ : 2 < κ) (α : ℕ → AbsoluteValue K ℝ → F) (β : ℕ → K)
    (hα : (fun j ↦ 1 + ∑ v ∈ Sinf, absLogHeight₁ (α j v.1) + ∑ v ∈ Sfin, absLogHeight₁ (α j v.1))
      =o[atTop] fun j ↦ absLogHeight₁ (β j)) :
    {j : ℕ | (∏ v ∈ Sinf, min 1 (w v.1 (algebraMap K F (β j) - α j v.1)) ^ v.mult) *
        ∏ v ∈ Sfin, min 1 (w v.1 (algebraMap K F (β j) - α j v.1))
          ≤ mulHeight₁ (β j) ^ (-κ)}.Finite := by
  sorry
end NumberField
end
-- DiophantineApproximation.ParametricSubspace
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter Finset Module NumberField NumberField.mixedEmbedding exteriorPower
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Fintype ι]
  {Sfin : Finset (FinitePlace K)} {L : AbsoluteValue K ℝ → ι → Dual K (ι → K)}
open scoped Classical in
theorem exists_finset_submodule_forall_approxDomain_subset [Nontrivial ι]
    (hLInf : ∀ w : InfinitePlace K, LinearIndependent K (L w.1))
    (hLFin : ∀ v ∈ Sfin, LinearIndependent K (L v.1)) {c : AbsoluteValue K ℝ → ι → ℝ}
    (hc : approxWeight Sfin c < 0) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ W ∈ T, W ≠ ⊤) ∧
      ∃ Q₀ : ℝ, ∀ Q ≥ Q₀, ∃ W ∈ T, approxDomain Sfin L c Q ⊆ W := by
  sorry
end NumberField
end
-- DiophantineApproximation.RothRational
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Height NumberField IntermediateField Filter
open scoped ENNReal NNReal
theorem Real.irrationalityExponent_eq_two {ξ : ℝ} (hirr : Irrational ξ)
    (halg : IsAlgebraic ℚ ξ) : irrationalityExponent ξ = 2 := by
  sorry
end
-- DiophantineApproximation.Ridout
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Height NumberField AbsoluteValue OnePoint IntermediateField
namespace Rat
variable {F : Type*} [Field F] [NumberField F]
theorem finite_setOf_apply_intCast_sub_le (p : Nat.Primes) (w : AbsoluteValue F ℝ)
    (hw : w.LiesOver (AbsoluteValue.padic (p : ℕ))) (α : F) {ε : ℝ} (hε : 0 < ε) :
    {n : ℤ | w ((n : F) - α) ≤ |(n : ℝ)| ^ (-1 - ε)}.Finite := by
  sorry
theorem finite_setOf_ridout {ξ : ℝ} (halg : IsAlgebraic ℚ ξ) (S₁ S₂ : Finset Nat.Primes)
    {ε : ℝ} (hε : 0 < ε) :
    {β : ℚ | |ξ - (β : ℝ)| * (∏ l ∈ S₁, ((padicNorm (l : ℕ) β.num : ℚ) : ℝ))
        * ∏ l ∈ S₂, ((padicNorm (l : ℕ) β.den : ℚ) : ℝ)
      ≤ (max β.num.natAbs β.den : ℝ) ^ (-2 - ε)}.Finite := by
  sorry
end Rat
end
end
-- DiophantineApproximation.RothProjective
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Height Module AbsoluteValue
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
theorem exists_finset_submodule_of_approxProd_le_card_two {ι : Type*} [Fintype ι]
    (hcard : Fintype.card ι = 2)
    (Sinf : Finset (InfinitePlace K)) (Sfin : Finset (FinitePlace K))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v ∈ Sinf, (w v.1).LiesOver v.1) (hwFin : ∀ v ∈ Sfin, (w v.1).LiesOver v.1)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (hLInf : ∀ v ∈ Sinf, LinearIndependent F (L v.1))
    (hLFin : ∀ v ∈ Sfin, LinearIndependent F (L v.1))
    {ε : ℝ} (hε : 0 < ε) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ V ∈ T, V ≠ ⊤) ∧
      ∀ x : ι → K, x ≠ 0 →
        approxProd Sinf Sfin w L x ≤ mulHeight x ^ (-(Fintype.card ι : ℝ) - ε) →
        ∃ V ∈ T, x ∈ V := by
  sorry
theorem finite_setOf_prod_min_one_le_card_two (Sinf : Finset (InfinitePlace K))
    (Sfin : Finset (FinitePlace K)) (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v ∈ Sinf, (w v.1).LiesOver v.1) (hwFin : ∀ v ∈ Sfin, (w v.1).LiesOver v.1)
    (α : AbsoluteValue K ℝ → F) {κ : ℝ} (hκ : 2 < κ) :
    {β : K | (∏ v ∈ Sinf, min 1 (w v.1 (algebraMap K F β - α v.1)) ^ v.mult) *
        ∏ v ∈ Sfin, min 1 (w v.1 (algebraMap K F β - α v.1)) ≤ mulHeight₁ β ^ (-κ)}.Finite := by
  sorry
end NumberField
end
end
-- DiophantineApproximation.SubspaceTheorem
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Finset Height Module
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Fintype ι]
open scoped Classical in
theorem exists_finset_submodule_of_approxProd_le [Nontrivial ι]
    (Sinf : Finset (InfinitePlace K)) (Sfin : Finset (FinitePlace K))
    (L : AbsoluteValue K ℝ → ι → Dual K (ι → K))
    (hLInf : ∀ v ∈ Sinf, LinearIndependent K (L v.1))
    (hLFin : ∀ v ∈ Sfin, LinearIndependent K (L v.1))
    {ε : ℝ} (hε : 0 < ε) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ W ∈ T, W ≠ ⊤) ∧
      ∀ x : ι → K, x ≠ 0 →
        approxProd Sinf Sfin (fun v ↦ v) L x ≤ mulHeight x ^ (-(Fintype.card ι : ℝ) - ε) →
        ∃ W ∈ T, x ∈ W := by
  sorry
end NumberField
end
end
-- DiophantineApproximation.SubspaceAlgebraic
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Finset Height Module NumberField
namespace NumberField
variable {K E : Type*} [Field K] [NumberField K] [Field E] [NumberField E] [Algebra K E]
variable {ι : Type*} [Fintype ι]
section Extension
variable {F : Type*} [Field F] [NumberField F] [Algebra K F]
open scoped Classical in
theorem exists_finset_submodule_of_approxProd_le_extension [Nontrivial ι]
    (Sinf : Finset (InfinitePlace K)) (Sfin : Finset (FinitePlace K))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwI : ∀ v ∈ Sinf, (w v.1).LiesOver v.1) (hwF : ∀ v ∈ Sfin, (w v.1).LiesOver v.1)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (hLI : ∀ v ∈ Sinf, LinearIndependent F (L v.1))
    (hLF : ∀ v ∈ Sfin, LinearIndependent F (L v.1))
    {ε : ℝ} (hε : 0 < ε) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ W ∈ T, W ≠ ⊤) ∧
      ∀ x : ι → K, x ≠ 0 →
        approxProd Sinf Sfin w L x ≤ mulHeight x ^ (-(Fintype.card ι : ℝ) - ε) →
        ∃ W ∈ T, x ∈ W := by
  sorry
end Extension
end NumberField
end
end
-- DiophantineApproximation.SubspaceAffine
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Finset Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
open scoped Classical in
theorem exists_finset_submodule_of_integer_of_affineProd_le [Nontrivial ι]
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (hLInf : ∀ v : InfinitePlace K, LinearIndependent F (L v.1))
    (hLFin : ∀ v ∈ S, LinearIndependent F (L (FinitePlace.mk v).1))
    {ε : ℝ} (hε : 0 < ε) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ W ∈ T, W ≠ ⊤) ∧
      ∀ x : ι → K, x ≠ 0 → (∀ j, x j ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) →
        affineProd S w L x ≤ mulHeight x ^ (-ε) → ∃ W ∈ T, x ∈ W := by
  sorry
end NumberField
end
end
-- DiophantineApproximation.SubspaceSystem
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
noncomputable def systemPlace (S : Finset (HeightOneSpectrum (𝓞 K))) :
    InfinitePlace K ⊕ S → AbsoluteValue K ℝ
  | .inl v => v.1
  | .inr v => (FinitePlace.mk v.1).1
noncomputable def systemMult (S : Finset (HeightOneSpectrum (𝓞 K))) : InfinitePlace K ⊕ S → ℕ
  | .inl v => v.mult
  | .inr _ => 1
noncomputable def systemAbs (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (p : InfinitePlace K ⊕ S) (a : F) : ℝ :=
  w (systemPlace S p) a ^ systemMult S p
noncomputable def systemValue (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (p : InfinitePlace K ⊕ S) (i : ι) (x : ι → K) : ℝ :=
  systemAbs S w p (L (systemPlace S p) i fun j ↦ algebraMap K F (x j))
def systemSet (S : Finset (HeightOneSpectrum (𝓞 K))) (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F)) (C : InfinitePlace K ⊕ S → ℝ)
    (c : InfinitePlace K ⊕ S → ι → ℝ) : Set (ι → K) :=
  {x | (∀ j, x j ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) ∧
    ∀ p i, systemValue S w L p i x ≤ C p * mulHeightAff x ^ c p i}
noncomputable def systemWeight {S : Finset (HeightOneSpectrum (𝓞 K))}
    (c : InfinitePlace K ⊕ S → ι → ℝ) : ℝ :=
  ∑ p, ∑ i, c p i
noncomputable def systemConst {S : Finset (HeightOneSpectrum (𝓞 K))}
    (C : InfinitePlace K ⊕ S → ℝ) : ℝ :=
  ∏ p, C p
noncomputable def systemDet (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (L : AbsoluteValue K ℝ → ι → Dual F (ι → F)) :
    ℝ :=
  ∏ p, systemAbs S w p (LinearMap.det (LinearMap.pi (L (systemPlace S p))))
noncomputable def systemExponent (S : Finset (HeightOneSpectrum (𝓞 K))) :
    InfinitePlace K ⊕ S → ℝ
  | .inl v => v.mult / finrank ℚ K
  | .inr _ => 0
structure IsNormalizedSystem (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (C : InfinitePlace K ⊕ S → ℝ) (c : InfinitePlace K ⊕ S → ι → ℝ) (H : ℝ) (D R : ℕ)
    (δ : ℝ) : Prop where
  /-- The coefficients have absolute height at most `H`. -/
  height_le : ∀ p i j, absMulHeight₁ (L (systemPlace S p) i (Pi.basisFun F ι j)) ≤ H
  /-- The coefficients have degree at most `D` over `K`. -/
  degree_le : ∀ p i j, (minpoly K (L (systemPlace S p) i (Pi.basisFun F ι j))).natDegree ≤ D
  /-- At most `R` distinct forms occur. -/
  ncard_le : (Set.range fun q : (InfinitePlace K ⊕ S) × ι ↦ L (systemPlace S q.1) q.2).ncard ≤ R
  /-- The constants are positive. -/
  const_pos : ∀ p, 0 < C p
  /-- The product of the constants is at most `(∏ |det L v|_v) ^ (1 / n)`. -/
  const_le : systemConst C ≤ systemDet S w L ^ (Fintype.card ι : ℝ)⁻¹
  delta_pos : 0 < δ
  delta_le_one : δ ≤ 1
  /-- The weight is at most `-δ`. -/
  weight_le : systemWeight c ≤ -δ
  /-- No exponent exceeds the normalized local degree. -/
  exponent_le : ∀ p i, c p i ≤ systemExponent S p
  /-- Some exponent at every place attains it. -/
  exists_exponent_eq : ∀ p, ∃ i, c p i = systemExponent S p
def IsLargeSolution (H δ : ℝ) (x : ι → K) : Prop :=
  max (2 * H) ((Fintype.card ι : ℝ) ^ (2 * Fintype.card ι / δ)) ≤
    mulHeightAff x ^ ((finrank ℚ K : ℝ)⁻¹)
open scoped Classical in
theorem exists_finset_submodule_of_systemWeight_neg [Nontrivial ι]
    (S : Finset (HeightOneSpectrum (𝓞 K))) (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (hLInf : ∀ v : InfinitePlace K, LinearIndependent F (L v.1))
    (hLFin : ∀ v ∈ S, LinearIndependent F (L (FinitePlace.mk v).1))
    {C : InfinitePlace K ⊕ S → ℝ} (hC : ∀ p, 0 ≤ C p) {c : InfinitePlace K ⊕ S → ι → ℝ}
    (hc : systemWeight c < 0) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ W ∈ T, W ≠ ⊤) ∧
      ∀ x ∈ systemSet S w L C c, x ≠ 0 → ∃ W ∈ T, x ∈ W := by
  sorry
end NumberField
end
-- DiophantineApproximation.SubspaceIntervals
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
theorem exists_finset_submodule_of_forall_mem_interval (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    {L : AbsoluteValue K ℝ → ι → Dual F (ι → F)} {C : InfinitePlace K ⊕ S → ℝ}
    {c : InfinitePlace K ⊕ S → ι → ℝ} {H : ℝ} {D R : ℕ} {δ : ℝ}
    (hN : IsNormalizedSystem S w L C c H D R δ) (U₀ : Submodule K (ι → K)) {m : ℕ}
    (Q : Fin m → ℝ) (hQ : ∀ i, (Fintype.card ι : ℝ) ^ (2 * Fintype.card ι / δ) ≤ Q i) {ω : ℝ}
    (hω : 1 ≤ ω)
    (hint : ∀ x ∈ systemSet S w L C c, x ∉ U₀ → ∃ i, Q i ≤ mulHeightAff x ^ ((finrank ℚ K : ℝ)⁻¹) ∧
      mulHeightAff x ^ ((finrank ℚ K : ℝ)⁻¹) < Q i ^ ω) :
    ∃ T : Finset (Submodule K (ι → K)),
      (T.card : ℝ) ≤ m * (1 + Real.log ω / Real.log (1 + δ / (2 * Fintype.card ι))) ∧
      (∀ U ∈ T, U ≠ ⊤) ∧ ∀ x ∈ systemSet S w L C c, x ∉ U₀ → ∃ U ∈ T, x ∈ U := by
  sorry
end NumberField
end
-- DiophantineApproximation.RothSubspaceCount
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
theorem exists_finset_submodule_of_card_eq_two {ι : Type*} [Fintype ι]
    (hι : Fintype.card ι = 2) (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    {L : AbsoluteValue K ℝ → ι → Dual F (ι → F)} {C : InfinitePlace K ⊕ S → ℝ}
    {c : InfinitePlace K ⊕ S → ι → ℝ} {H : ℝ} {D R : ℕ} {δ : ℝ}
    (hN : IsNormalizedSystem S w L C c H D R δ) :
    ∃ X₀ : ℝ, ∃ T : Finset (Submodule K (ι → K)),
      (T.card : ℝ) ≤ ((Fintype.card (InfinitePlace K) + S.card + 1 : ℕ) : ℝ) +
        ((rothChainLength (2 + δ / 2) (Fintype.card (InfinitePlace K) + S.card) (finrank K F) *
          (rothClassSize (2 + δ / 2) (Fintype.card (InfinitePlace K) + S.card) +
            (Fintype.card (InfinitePlace K) + S.card)).choose
              (Fintype.card (InfinitePlace K) + S.card) : ℕ) : ℝ) *
          (1 + Real.log (3 * ((finrank K F * (Fintype.card (InfinitePlace K) + S.card) : ℕ) : ℝ) *
            rothRatio (2 + δ / 2) (Fintype.card (InfinitePlace K) + S.card) (finrank K F)) /
            Real.log (1 + δ / 4)) ∧
      (∀ U ∈ T, U ≠ ⊤) ∧
      ∀ x ∈ systemSet S w L C c, X₀ ≤ mulHeightAff x ^ ((finrank ℚ K : ℝ)⁻¹) →
        ∃ U ∈ T, x ∈ U := by
  sorry
end NumberField
end
-- DiophantineApproximation.SubspaceGeneralPosition
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Finset Height Module Module.Dual
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [Algebra K F] {ι κ : Type*}
noncomputable def generalProd (Sinf : Finset (InfinitePlace K)) (Sfin : Finset (FinitePlace K))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ) (B : AbsoluteValue K ℝ → Finset κ)
    (L : AbsoluteValue K ℝ → κ → Dual F (ι → F)) (x : ι → K) : ℝ :=
  (∏ v ∈ Sinf, (∏ k ∈ B v.1, w v.1 (L v.1 k fun j ↦ algebraMap K F (x j)) / ⨆ j, v (x j))
      ^ v.mult) *
    ∏ v ∈ Sfin, ∏ k ∈ B v.1, w v.1 (L v.1 k fun j ↦ algebraMap K F (x j)) / ⨆ j, v (x j)
variable [NumberField F] [Fintype ι]
open scoped Classical in
theorem exists_finset_submodule_of_generalProd_le [Nontrivial ι] [Finite κ]
    (Sinf : Finset (InfinitePlace K)) (Sfin : Finset (FinitePlace K))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwI : ∀ v ∈ Sinf, (w v.1).LiesOver v.1) (hwF : ∀ v ∈ Sfin, (w v.1).LiesOver v.1)
    (B : AbsoluteValue K ℝ → Finset κ) (L : AbsoluteValue K ℝ → κ → Dual F (ι → F))
    (hLI : ∀ v ∈ Sinf, IsGeneralPosition F (B v.1) (L v.1))
    (hLF : ∀ v ∈ Sfin, IsGeneralPosition F (B v.1) (L v.1))
    {ε : ℝ} (hε : 0 < ε) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ W ∈ T, W ≠ ⊤) ∧
      ∀ x : ι → K, x ≠ 0 →
        generalProd Sinf Sfin w B L x ≤ mulHeight x ^ (-(Fintype.card ι : ℝ) - ε) →
        ∃ W ∈ T, x ∈ W := by
  sorry
end NumberField
end
end
-- DiophantineApproximation.SubspaceConsistency
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 998] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 999] IsLocalRing.toNontrivial
@[expose] public section
open Height Module AbsoluteValue
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
theorem exists_finset_submodule_of_approxProd_le_card_two_of_extension
    (hcard : Fintype.card ι = 2)
    (Sinf : Finset (InfinitePlace K)) (Sfin : Finset (FinitePlace K))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v ∈ Sinf, (w v.1).LiesOver v.1) (hwFin : ∀ v ∈ Sfin, (w v.1).LiesOver v.1)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (hLInf : ∀ v ∈ Sinf, LinearIndependent F (L v.1))
    (hLFin : ∀ v ∈ Sfin, LinearIndependent F (L v.1))
    {ε : ℝ} (hε : 0 < ε) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ V ∈ T, V ≠ ⊤) ∧
      ∀ x : ι → K, x ≠ 0 →
        approxProd Sinf Sfin w L x ≤ mulHeight x ^ (-(Fintype.card ι : ℝ) - ε) →
        ∃ V ∈ T, x ∈ V := by
  sorry
end NumberField
end
end
-- DiophantineApproximation.SubspaceSmall
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
theorem exists_finset_submodule_of_not_isLargeSolution (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    {L : AbsoluteValue K ℝ → ι → Dual F (ι → F)} {C : InfinitePlace K ⊕ S → ℝ}
    {c : InfinitePlace K ⊕ S → ι → ℝ} {H : ℝ} {D R : ℕ} {δ : ℝ}
    (hN : IsNormalizedSystem S w L C c H D R δ) :
    ∃ T : Finset (Submodule K (ι → K)),
      (T.card : ℝ) ≤ δ⁻¹ * ((10 ^ 3 * Fintype.card ι) ^ (Fintype.card ι * finrank ℚ K) +
        4 * Fintype.card ι * Real.log (Real.log (4 * H))) ∧
      (∀ U ∈ T, U ≠ ⊤) ∧
      ∀ x ∈ systemSet S w L C c, ¬ IsLargeSolution H δ x → ∃ U ∈ T, x ∈ U := by
  sorry
end NumberField
namespace Rat
open NumberField
variable {F : Type*} [Field F] [NumberField F] [Algebra ℚ F] {ι : Type*} [Fintype ι]
theorem exists_finset_submodule_of_not_isLargeSolution (S : Finset (HeightOneSpectrum (𝓞 ℚ)))
    (w : AbsoluteValue ℚ ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v : InfinitePlace ℚ, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    {L : AbsoluteValue ℚ ℝ → ι → Dual F (ι → F)} {C : InfinitePlace ℚ ⊕ S → ℝ}
    {c : InfinitePlace ℚ ⊕ S → ι → ℝ} {H : ℝ} {D R : ℕ} {δ : ℝ}
    (hN : IsNormalizedSystem S w L C c H D R δ) :
    ∃ T : Finset (Submodule ℚ (ι → ℚ)),
      (T.card : ℝ) ≤ δ⁻¹ * (10 ^ (3 * Fintype.card ι) +
        4 * Fintype.card ι * Real.log (Real.log (4 * H))) ∧
      (∀ U ∈ T, U ≠ ⊤) ∧
      ∀ x ∈ systemSet S w L C c, ¬ IsLargeSolution H δ x → ∃ U ∈ T, x ∈ U := by
  sorry
end Rat
end
