/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Mathlib.Data.List.Infix
public import Mathlib.Algebra.Order.Archimedean.Real.Basic
public import Mathlib.Data.Set.Card
public import Mathlib.Order.Filter.AtTopBot.Basic
import Mathlib.Data.Set.Finite.Range
import Mathlib.Data.Fintype.Pigeonhole
public import Mathlib.Analysis.Real.OfDigits
public import Mathlib.NumberTheory.Real.Irrational
import Mathlib.Tactic.LinearCombination
public import Mathlib.Algebra.Order.Ring.IsNonarchimedean
public import Mathlib.Analysis.AbsoluteValue.Equivalence
import Mathlib.Analysis.MeanInequalitiesPow
public import Mathlib.NumberTheory.NumberField.Completion.FinitePlace
public import Mathlib.Analysis.Normed.Algebra.GelfandMazur
public import Mathlib.Analysis.Normed.Field.Instances
public import Mathlib.NumberTheory.NumberField.Completion.InfinitePlace
public import Mathlib.Analysis.SpecialFunctions.Log.PosLog
public import Mathlib.NumberTheory.Height.NumberField
public import Mathlib.NumberTheory.Height.Projectivization
public import Mathlib.RingTheory.Ideal.Norm.RelNorm
public import Mathlib.LinearAlgebra.ExteriorPower.Basis
public import Mathlib.LinearAlgebra.Matrix.Rank
public import Mathlib.NumberTheory.Height.MvPolynomial
public import Mathlib.Algebra.Module.ZLattice.Basic
public import Mathlib.MeasureTheory.Measure.Haar.Unique
public import Mathlib.Algebra.Module.ZLattice.Covolume
public import Mathlib.MeasureTheory.Group.GeometryOfNumbers
public import Mathlib.MeasureTheory.Measure.Haar.Disintegration
public import Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls
public import Mathlib.NumberTheory.NumberField.CanonicalEmbedding.Basic
public import Mathlib.RingTheory.Complex
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.NumberTheory.NumberField.Discriminant.Basic
public import Mathlib.Analysis.Matrix.LDL
public import Mathlib.Algebra.Module.LinearMap.Rat
public import Mathlib.Data.Matrix.ColumnRowPartitioned
public import Mathlib.Data.Finsupp.MonomialOrder
public import Mathlib.RingTheory.Polynomial.GaussNorm
public import Mathlib.Analysis.Polynomial.MahlerMeasure
public import Mathlib.Data.Finsupp.Interval
public import Mathlib.RingTheory.Polynomial.Wronskian
public import Mathlib.Algebra.MvPolynomial.NoZeroDivisors
public import Mathlib.Analysis.Complex.ExponentialBounds
public import Mathlib.Algebra.Order.Antidiag.FinsuppEquiv
public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
public import Mathlib.RingTheory.DedekindDomain.SInteger
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.RingTheory.DedekindDomain.SelmerGroup
public import Mathlib.NumberTheory.NumberField.Units.Regulator
public import Mathlib.Topology.Compactification.OnePoint.Basic
import Mathlib.NumberTheory.NumberField.Completion.Ramification
import Mathlib.Algebra.FiniteSupport.Basic
public import Mathlib.NumberTheory.Ostrowski
public import Mathlib.NumberTheory.NumberField.House
import Mathlib.LinearAlgebra.LinearIndependent.BaseChange
public import Mathlib.Algebra.MvPolynomial.Coeff
public import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.NumberTheory.Transcendental.Liouville.LiouvilleWith
import Mathlib.NumberTheory.DiophantineApproximation.Basic
import Mathlib.NumberTheory.Transcendental.Liouville.LiouvilleNumber
public import Mathlib.NumberTheory.Padics.PadicNumbers
import Mathlib.Topology.Algebra.InfiniteSum.Nonarchimedean
public import Mathlib.NumberTheory.Real.GoldenRatio
public import Mathlib.NumberTheory.Padics.RingHoms
public import Mathlib.RingTheory.PowerSeries.Expand
import Mathlib.RingTheory.PowerSeries.NoZeroDivisors
import Mathlib.RingTheory.PowerSeries.WellKnown
import Mathlib.RingTheory.PowerSeries.Inverse

/-!
# AdamczewskiBugeaud2007: the statements of record

Generated by `scripts/make-challenge.py --paper AdamczewskiBugeaud2007` from the library
`AdamczewskiBugeaud2007` and the libraries it builds on; do not edit. Each `-- <module>` part repeats,
verbatim, the definitions of that module the certified theorems mention, and states the theorems
with `sorry`. Each part opens by clearing Lean's auxiliary-proof cache, as a module boundary does,
and some lower instances locally to restore their module's tie-break. See `COMPARATOR.md`.
-/

-- AdamczewskiBugeaud2007.AutomaticSequence
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
namespace Function
variable {α β : Type*}
def kKernel (k : ℕ) (a : ℕ → α) : Set (ℕ → α) :=
  {s | ∃ i r, r < k ^ i ∧ s = fun n ↦ a (k ^ i * n + r)}
def IsAutomatic (a : ℕ → α) : Prop :=
  ∃ k, 2 ≤ k ∧ (kKernel k a).Finite
end Function
end
-- DiophantineApproximation.StammeringWords
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
namespace List
variable {α : Type*}
noncomputable def rpow (V : List α) (w : ℝ) : List α :=
  (replicate ⌊w⌋₊ V).flatten ++ V.take ⌈(w - ⌊w⌋₊) * V.length⌉₊
end List
namespace Function
variable {α : Type*}
def IsEventuallyPeriodic (a : ℕ → α) : Prop :=
  ∃ N p : ℕ, 0 < p ∧ ∀ n, N ≤ n → a (n + p) = a n
def IsStammeringWith (w : ℝ) (a : ℕ → α) : Prop :=
  ∃ U V : ℕ → List α,
    (∀ k i, i < (U k ++ (V k).rpow w).length → (U k ++ (V k).rpow w)[i]? = some (a i)) ∧
    BddAbove (Set.range fun k ↦ ((U k).length : ℝ) / (V k).length) ∧
    StrictMono fun k ↦ (V k).length
def IsStammering (a : ℕ → α) : Prop := ∃ w : ℝ, 1 < w ∧ IsStammeringWith w a
end Function
end
-- DiophantineApproximation.FactorComplexity
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter
namespace Function
variable {α : Type*}
def factor (a : ℕ → α) (i n : ℕ) : List α := List.ofFn fun j : Fin n ↦ a (i + j)
def factors (a : ℕ → α) (n : ℕ) : Set (List α) := Set.range fun i ↦ factor a i n
noncomputable def complexity (a : ℕ → α) (n : ℕ) : ℕ := (factors a n).ncard
end Function
end
-- DiophantineApproximation.ComplexityTranscendence
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter
namespace Real
variable {b : ℕ}
theorem tendsto_complexity_div_atTop (hb : 2 ≤ b) {a : ℕ → Fin b}
    (hirr : Irrational (ofDigits a)) (halg : IsAlgebraic ℚ (ofDigits a)) :
    Tendsto (fun n ↦ (Function.complexity a n : ℝ) / n) atTop atTop := by
  sorry
end Real
end
-- AdamczewskiBugeaud2007.AutomaticComplexity
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter
namespace Function
variable {α : Type*}
theorem IsAutomatic.exists_complexity_le {a : ℕ → α} (h : IsAutomatic a) :
    ∃ C : ℕ, ∀ n, 1 ≤ n → complexity a n ≤ C * n := by
  sorry
theorem IsAutomatic.isStammering [Finite α] {a : ℕ → α} (h : IsAutomatic a) : IsStammering a := by
  sorry
end Function
namespace Real
theorem transcendental_ofDigits_of_isAutomatic {b : ℕ} (hb : 2 ≤ b) {a : ℕ → Fin b}
    (hauto : Function.IsAutomatic a) (hirr : Irrational (ofDigits a)) :
    Transcendental ℚ (ofDigits a) := by
  sorry
end Real
end
-- AdamczewskiBugeaud2007.Automaton
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
namespace Function
variable {α : Type*}
def automatonRun {k : ℕ} {Q : Type*} (δ : Q → Fin k → Q) (q : Q) (W : List ℕ) : Q :=
  W.foldl (fun q d ↦ if h : d < k then δ q ⟨d, h⟩ else q) q
def IsGeneratedByAutomaton (k : ℕ) (a : ℕ → α) : Prop :=
  ∃ (N : ℕ) (δ : Fin N → Fin k → Fin N) (q₀ : Fin N) (τ : Fin N → α),
    ∀ n, a n = τ (automatonRun δ q₀ (Nat.digits k n))
theorem finite_kKernel_iff_isGeneratedByAutomaton {k : ℕ} (hk : 2 ≤ k) {a : ℕ → α} :
    (kKernel k a).Finite ↔ IsGeneratedByAutomaton k a := by
  sorry
end Function
namespace Real
theorem transcendental_ofDigits_of_isGeneratedByAutomaton {b : ℕ} (hb : 2 ≤ b) {a : ℕ → Fin b}
    {k : ℕ} (hk : 2 ≤ k) (hauto : Function.IsGeneratedByAutomaton k a)
    (hirr : Irrational (ofDigits a)) : Transcendental ℚ (ofDigits a) := by
  sorry
end Real
end
-- AdamczewskiBugeaud2007.BetaApproximation
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open Finset
namespace Polynomial
noncomputable def digitPoly (a : ℕ → ℤ) (n : ℕ) : ℤ[X] :=
  ∑ k ∈ range n, C (a k) * X ^ (n - 1 - k)
end Polynomial
open Polynomial
namespace Real
variable {β : ℝ}
theorem abs_sub_le_of_periodic (hβ : 1 < β) {a : ℕ → ℤ} {M : ℝ} (hM : ∀ k, |(a k : ℝ)| ≤ M)
    {w : ℝ} {r s : ℕ} (h : ∀ i, r ≤ i → i + s < r + ⌈w * s⌉₊ → a (i + s) = a i) :
    |(β ^ (r + s) - β ^ r) * ∑' k, (a k : ℝ) / β ^ (k + 1)
        - (aeval β (digitPoly a (r + s)) - aeval β (digitPoly a r))|
      ≤ 2 * M / ((β - 1) * β ^ (⌈w * s⌉₊ - s)) := by
  sorry
end Real
end
end
-- AdamczewskiBugeaud2007.Morphism
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter
namespace Function
variable {α : Type*}
def morphismIter (φ : α → List α) (n : ℕ) (W : List α) : List α :=
  (fun W ↦ W.flatMap φ)^[n] W
variable {φ : α → List α}
def IsProlongable (φ : α → List α) (c : α) : Prop :=
  ∃ W, φ c = c :: W ∧ ∀ k, morphismIter φ k W ≠ []
def HasPrefix (a : ℕ → α) (L : List α) : Prop :=
  ∀ i < L.length, L[i]? = some (a i)
def IsGeneratedByMorphism (φ : α → List α) (a : ℕ → α) : Prop :=
  IsProlongable φ (a 0) ∧ ∀ k, HasPrefix a (morphismIter φ k [a 0])
def IsRecurrent (a : ℕ → α) : Prop :=
  ∀ i, ∃ j, j ≠ i ∧ a j = a i
end Function
end
-- ForMathlib.NumberTheory.PisotNumber
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] instFaithfulSMul_1
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open Polynomial
def IsPisot (α : ℝ) : Prop :=
  1 < α ∧ IsIntegral ℤ α ∧ ∀ z ∈ (minpoly ℚ α).aroots ℂ, z ≠ (α : ℂ) → ‖z‖ < 1
def IsSalem (τ : ℝ) : Prop :=
  1 < τ ∧ IsIntegral ℤ τ ∧ (∀ z ∈ (minpoly ℚ τ).aroots ℂ, z ≠ (τ : ℂ) → ‖z‖ ≤ 1) ∧
    ∃ z ∈ (minpoly ℚ τ).aroots ℂ, z ≠ (τ : ℂ) ∧ ‖z‖ = 1
end
end
-- AdamczewskiBugeaud2007.PisotTranscendence
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] IsLocalRing.toNontrivial
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open Filter Finset IntermediateField NumberField Polynomial
namespace Real
open scoped Classical in
theorem mem_adjoin_of_isStammering {β : ℝ} (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1) {a : ℕ → ℤ}
    (hbdd : BddAbove (Set.range fun k ↦ |a k|)) (hst : Function.IsStammering a)
    (halg : IsAlgebraic ℚ (∑' k, (a k : ℝ) / β ^ (k + 1))) :
    ∑' k, (a k : ℝ) / β ^ (k + 1) ∈ ℚ⟮β⟯ := by
  sorry
theorem mem_adjoin_or_transcendental_of_isPisot {β : ℝ} (hβ : IsPisot β) {a : ℕ → ℤ}
    (hbdd : BddAbove (Set.range fun k ↦ |a k|)) (hst : Function.IsStammering a) :
    ∑' k, (a k : ℝ) / β ^ (k + 1) ∈ ℚ⟮β⟯ ∨
      Transcendental ℚ (∑' k, (a k : ℝ) / β ^ (k + 1)) := by
  sorry
theorem mem_adjoin_or_transcendental_of_isSalem {β : ℝ} (hβ : IsSalem β) {a : ℕ → ℤ}
    (hbdd : BddAbove (Set.range fun k ↦ |a k|)) (hst : Function.IsStammering a) :
    ∑' k, (a k : ℝ) / β ^ (k + 1) ∈ ℚ⟮β⟯ ∨
      Transcendental ℚ (∑' k, (a k : ℝ) / β ^ (k + 1)) := by
  sorry
theorem tsum_mem_adjoin_of_isEventuallyPeriodic {β : ℝ} (hβ : 1 < β) {a : ℕ → ℤ}
    (hbdd : BddAbove (Set.range fun k ↦ |a k|)) (hper : Function.IsEventuallyPeriodic a) :
    ∑' k, (a k : ℝ) / β ^ (k + 1) ∈ ℚ⟮β⟯ := by
  sorry
end Real
end
end
-- ForMathlib.Analysis.Real.BetaExpansion
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open Filter Topology
namespace Real
variable {β x : ℝ}
noncomputable def betaTransform (β x : ℝ) : ℝ := Int.fract (β * x)
noncomputable def betaDigits (β x : ℝ) (k : ℕ) : ℕ := ⌊β * (betaTransform β)^[k] x⌋₊
end Real
end
end
-- AdamczewskiBugeaud2007.SchmidtPeriodicity
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open IntermediateField Polynomial Finset
namespace Real
variable {β x : ℝ}
theorem isEventuallyPeriodic_betaDigits_of_mem_adjoin (hβ : IsPisot β)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (hxK : x ∈ ℚ⟮β⟯) :
    Function.IsEventuallyPeriodic (betaDigits β x) := by
  sorry
end Real
end
end
-- AdamczewskiBugeaud2007.BetaDigitsTranscendence
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter
namespace Real
open IntermediateField
variable {β x : ℝ}
noncomputable def betaDigitsFin (β x : ℝ) (k : ℕ) : Fin (⌊β⌋₊ + 1) :=
  ⟨min (betaDigits β x k) ⌊β⌋₊, Nat.lt_succ_of_le (min_le_right _ _)⟩
theorem tendsto_complexity_betaDigitsFin_div_atTop (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) :
    Tendsto (fun n ↦ (Function.complexity (betaDigitsFin β x) n : ℝ) / n) atTop atTop := by
  sorry
theorem not_isAutomatic_betaDigitsFin (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) :
    ¬ Function.IsAutomatic (betaDigitsFin β x) := by
  sorry
theorem not_isGeneratedByAutomaton_betaDigitsFin (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) {k : ℕ}
    (hk : 2 ≤ k) : ¬ Function.IsGeneratedByAutomaton k (betaDigitsFin β x) := by
  sorry
theorem not_isGeneratedByMorphism_of_betaDigits (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) {a : ℕ → Fin 2}
    (ha : ∀ k, (a k : ℕ) = betaDigits β x k) (φ : Fin 2 → List (Fin 2)) :
    ¬ Function.IsGeneratedByMorphism φ a := by
  sorry
theorem not_isGeneratedByMorphism_betaDigitsFin_of_isRecurrent (hβ : 1 < β)
    (hint : IsIntegral ℤ β) (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯)
    (φ : Fin (⌊β⌋₊ + 1) → List (Fin (⌊β⌋₊ + 1)))
    (hrec : Function.IsRecurrent (betaDigitsFin β x)) :
    ¬ Function.IsGeneratedByMorphism φ (betaDigitsFin β x) := by
  sorry
theorem transcendental_of_isStammering_betaDigits (hβ : IsPisot β) (hx : x ∈ Set.Ico (0 : ℝ) 1)
    (hst : Function.IsStammering (betaDigits β x))
    (hper : ¬ Function.IsEventuallyPeriodic (betaDigits β x)) : Transcendental ℚ x := by
  sorry
end Real
end
-- AdamczewskiBugeaud2007.Christol
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open Finset Polynomial
namespace PowerSeries
variable {K : Type*} [Field K] [Fintype K] {f : K⟦X⟧}
theorem finite_kKernel_coeff_of_isAlgebraic (hf : IsAlgebraic K[X] f) :
    (Function.kKernel (Fintype.card K) fun m ↦ coeff m f).Finite := by
  sorry
end PowerSeries
end
end
-- AdamczewskiBugeaud2007.ChristolTranscendence
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Polynomial PowerSeries Filter
namespace Real
theorem isAlgebraic_and_isAlgebraic_iff {b p : ℕ} [Fact p.Prime] (hb : 2 ≤ b) {u : ℕ → ℕ}
    (hub : ∀ k, u k < b) (hup : ∀ k, u k < p) :
    IsAlgebraic (ZMod p)[X] (PowerSeries.mk fun k ↦ (u k : ZMod p)) ∧
        IsAlgebraic ℚ (∑' k, (u k : ℝ) / b ^ k) ↔
      (∃ P Q : (ZMod p)[X], Q ≠ 0 ∧
          (Q : (ZMod p)⟦X⟧) * PowerSeries.mk (fun k ↦ (u k : ZMod p)) = P) ∧
        ∑' k, (u k : ℝ) / b ^ k ∈ Set.range ((↑) : ℚ → ℝ) := by
  sorry
end Real
theorem exists_counterexample_theorem7 :
    ∃ u : ℕ → ℕ, (∀ k, u k < 4) ∧
      IsAlgebraic (ZMod 5)[X] (PowerSeries.mk fun k ↦ (u k : ZMod 5)) ∧
      ∑' k, (u k : ℝ) / 2 ^ k = 1 ∧
      ¬ ∃ P Q : (ZMod 5)[X], Q ≠ 0 ∧
        (Q : (ZMod 5)⟦X⟧) * PowerSeries.mk (fun k ↦ (u k : ZMod 5)) = P := by
  sorry
theorem not_forall_theorem7_as_printed :
    ¬ ∀ u : ℕ → ℕ,
      IsAlgebraic (ZMod 5)[X] (PowerSeries.mk fun k ↦ (u k : ZMod 5)) ∧
          IsAlgebraic ℚ (∑' k, (u k : ℝ) / 2 ^ k) →
        (∃ P Q : (ZMod 5)[X], Q ≠ 0 ∧
            (Q : (ZMod 5)⟦X⟧) * PowerSeries.mk (fun k ↦ (u k : ZMod 5)) = P) ∧
          ∑' k, (u k : ℝ) / 2 ^ k ∈ Set.range ((↑) : ℚ → ℝ) := by
  sorry
end
-- AdamczewskiBugeaud2007.HenselExpansion
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
namespace Padic
variable {p : ℕ} [Fact p.Prime]
noncomputable def ofDigits (a : ℕ → Fin p) : ℚ_[p] :=
  ∑' n, ((a n : ℕ) : ℚ_[p]) * (p : ℚ_[p]) ^ n
end Padic
end
end
-- AdamczewskiBugeaud2007.PadicTranscendence
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter
namespace Padic
variable {p : ℕ} [Fact p.Prime]
theorem transcendental_ofDigits_of_isStammering {a : ℕ → Fin p}
    (hst : Function.IsStammering a) (hper : ¬ Function.IsEventuallyPeriodic a) :
    Transcendental ℚ (ofDigits a) := by
  sorry
theorem tendsto_complexity_div_atTop {a : ℕ → Fin p}
    (hirr : ofDigits a ∉ Set.range ((↑) : ℚ → ℚ_[p])) (halg : IsAlgebraic ℚ (ofDigits a)) :
    Tendsto (fun n ↦ (Function.complexity a n : ℝ) / n) atTop atTop := by
  sorry
theorem transcendental_ofDigits_of_isAutomatic {a : ℕ → Fin p}
    (hauto : Function.IsAutomatic a) (hirr : ofDigits a ∉ Set.range ((↑) : ℚ → ℚ_[p])) :
    Transcendental ℚ (ofDigits a) := by
  sorry
end Padic
end
-- AdamczewskiBugeaud2007.HenselDigits
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter
variable {p : ℕ} [Fact p.Prime]
namespace PadicInt
noncomputable def henselDigits (x : ℤ_[p]) (k : ℕ) : Fin p :=
  ⟨x.appr (k + 1) / p ^ k, Nat.div_lt_of_lt_mul (by rw [← pow_succ]; exact x.appr_lt _)⟩
end PadicInt
namespace Padic
noncomputable def henselShift (α : ℚ_[p]) : ℕ := (-α.valuation).toNat
theorem norm_pow_henselShift_mul_le_one (α : ℚ_[p]) :
    ‖(p : ℚ_[p]) ^ henselShift α * α‖ ≤ 1 := by
  rcases eq_or_ne α 0 with rfl | hα
  · simp
  have hp : (1 : ℝ) ≤ p := Nat.one_le_cast.mpr (Fact.out : p.Prime).one_lt.le
  rw [norm_mul, norm_p_pow, norm_eq_zpow_neg_valuation hα, ← zpow_add₀ (by positivity)]
  refine zpow_le_one_of_nonpos₀ hp ?_
  simp only [henselShift]
  linarith [Int.self_le_toNat (-α.valuation)]
noncomputable def henselDigits (α : ℚ_[p]) : ℕ → Fin p :=
  PadicInt.henselDigits ⟨(p : ℚ_[p]) ^ henselShift α * α, norm_pow_henselShift_mul_le_one α⟩
theorem tendsto_complexity_henselDigits_div_atTop {α : ℚ_[p]}
    (hirr : α ∉ Set.range ((↑) : ℚ → ℚ_[p])) (halg : IsAlgebraic ℚ α) :
    Tendsto (fun n ↦ (Function.complexity (henselDigits α) n : ℝ) / n) atTop atTop := by
  sorry
theorem transcendental_of_isStammering_henselDigits {α : ℚ_[p]}
    (hst : Function.IsStammering fun k ↦ henselDigits α (k + (henselShift α + 1)))
    (hper : ¬ Function.IsEventuallyPeriodic fun k ↦ henselDigits α (k + (henselShift α + 1))) :
    Transcendental ℚ α := by
  sorry
end Padic
end
-- AdamczewskiBugeaud2007.MorphicTranscendence
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter
namespace Real
theorem transcendental_ofDigits_of_isGeneratedByMorphism {a : ℕ → Fin 2}
    {φ : Fin 2 → List (Fin 2)} (h : Function.IsGeneratedByMorphism φ a)
    (hirr : Irrational (ofDigits a)) : Transcendental ℚ (ofDigits a) := by
  sorry
theorem transcendental_ofDigits_of_isGeneratedByMorphism_of_isRecurrent {b : ℕ} (hb : 2 ≤ b)
    {a : ℕ → Fin b} {φ : Fin b → List (Fin b)} (h : Function.IsGeneratedByMorphism φ a)
    (hrec : Function.IsRecurrent a) (hirr : Irrational (ofDigits a)) :
    Transcendental ℚ (ofDigits a) := by
  sorry
theorem tendsto_complexity_sub_atTop {b : ℕ} (hb : 2 ≤ b) {a : ℕ → Fin b}
    (hirr : Irrational (ofDigits a)) (halg : IsAlgebraic ℚ (ofDigits a)) :
    Tendsto (fun n ↦ (Function.complexity a n : ℝ) - n) atTop atTop := by
  sorry
end Real
namespace Padic
theorem transcendental_ofDigits_of_isGeneratedByMorphism {a : ℕ → Fin 2}
    {φ : Fin 2 → List (Fin 2)} (h : Function.IsGeneratedByMorphism φ a)
    (hirr : ofDigits a ∉ Set.range ((↑) : ℚ → ℚ_[2])) : Transcendental ℚ (ofDigits a) := by
  sorry
theorem transcendental_ofDigits_of_isGeneratedByMorphism_of_isRecurrent {p : ℕ} [Fact p.Prime]
    {a : ℕ → Fin p} {φ : Fin p → List (Fin p)} (h : Function.IsGeneratedByMorphism φ a)
    (hrec : Function.IsRecurrent a) (hirr : ofDigits a ∉ Set.range ((↑) : ℚ → ℚ_[p])) :
    Transcendental ℚ (ofDigits a) := by
  sorry
end Padic
end
