/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Mathlib.Analysis.Complex.Polynomial.Basic
public import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
public import Mathlib.NumberTheory.Real.Irrational
public import Mathlib.Algebra.GCDMonoid.IntegrallyClosed
public import Mathlib.NumberTheory.NumberField.Basic
import Mathlib.Algebra.Algebra.Hom.Rat
public import Mathlib.NumberTheory.NumberField.InfinitePlace.Ramification
public import Mathlib.Algebra.Order.Ring.IsNonarchimedean
public import Mathlib.NumberTheory.NumberField.Completion.FinitePlace
public import Mathlib.Analysis.Normed.Algebra.GelfandMazur
public import Mathlib.Analysis.Normed.Field.Instances
public import Mathlib.NumberTheory.NumberField.Completion.InfinitePlace
public import Mathlib.Analysis.SpecialFunctions.Log.PosLog
public import Mathlib.NumberTheory.Height.NumberField
public import Mathlib.NumberTheory.Height.Projectivization
public import Mathlib.RingTheory.Ideal.Norm.RelNorm
public import Mathlib.LinearAlgebra.ExteriorPower.Basis
public import Mathlib.LinearAlgebra.Matrix.Rank
public import Mathlib.NumberTheory.Height.MvPolynomial
public import Mathlib.Algebra.Module.ZLattice.Basic
public import Mathlib.MeasureTheory.Measure.Haar.Unique
public import Mathlib.Algebra.Module.ZLattice.Covolume
public import Mathlib.MeasureTheory.Group.GeometryOfNumbers
public import Mathlib.MeasureTheory.Measure.Haar.Disintegration
public import Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls
public import Mathlib.NumberTheory.NumberField.CanonicalEmbedding.Basic
public import Mathlib.RingTheory.Complex
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.NumberTheory.NumberField.Discriminant.Basic
public import Mathlib.Analysis.Matrix.LDL
public import Mathlib.Algebra.Module.LinearMap.Rat
public import Mathlib.Data.Matrix.ColumnRowPartitioned
public import Mathlib.Data.Finsupp.MonomialOrder
public import Mathlib.RingTheory.Polynomial.GaussNorm
public import Mathlib.Analysis.Polynomial.MahlerMeasure
public import Mathlib.Data.Finsupp.Interval
public import Mathlib.RingTheory.Polynomial.Wronskian
public import Mathlib.Algebra.MvPolynomial.NoZeroDivisors
public import Mathlib.Analysis.Complex.ExponentialBounds
public import Mathlib.Algebra.Order.Antidiag.FinsuppEquiv
public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
public import Mathlib.RingTheory.DedekindDomain.SInteger
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.RingTheory.DedekindDomain.SelmerGroup
public import Mathlib.NumberTheory.NumberField.Units.Regulator
public import Mathlib.Topology.Compactification.OnePoint.Basic
import Mathlib.NumberTheory.NumberField.Completion.Ramification
import Mathlib.Algebra.FiniteSupport.Basic
import Mathlib.NumberTheory.Ostrowski
import Mathlib.NumberTheory.NumberField.House
import Mathlib.LinearAlgebra.LinearIndependent.BaseChange
import Mathlib.Algebra.MvPolynomial.Coeff
import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.NumberTheory.Transcendental.Liouville.LiouvilleWith
import Mathlib.NumberTheory.DiophantineApproximation.Basic
import Mathlib.NumberTheory.Transcendental.Liouville.LiouvilleNumber
import Mathlib.GroupTheory.FiniteAbelian.Basic
public import Mathlib.Algebra.ContinuedFractions.Computation.Basic
import Mathlib.Algebra.ContinuedFractions.Computation.ApproximationCorollaries
import Mathlib.LinearAlgebra.Matrix.FixedDetMatrices
import Mathlib.NumberTheory.Modular

/-!
# CorvajaZannier2004: the statements of record

Generated by `scripts/make-challenge.py --paper CorvajaZannier2004` from the library
`CorvajaZannier2004` and the libraries it builds on; do not edit. Each `-- <module>` part repeats,
verbatim, the definitions of that module the certified theorems mention, and states the theorems
with `sorry`. Each part opens by clearing Lean's auxiliary-proof cache, as a module boundary does,
and some lower instances locally to restore their module's tie-break. See `COMPARATOR.md`.
-/

-- CorvajaZannier2004.PseudoPisot
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Polynomial
def IsPseudoPisot (α : ℝ) : Prop :=
  1 < |α| ∧ IsAlgebraic ℚ α ∧ (∀ z ∈ (minpoly ℚ α).aroots ℂ, z ≠ (α : ℂ) → ‖z‖ < 1) ∧
    ∃ n : ℤ, ((minpoly ℚ α).aroots ℂ).sum = n
def IsPisot (α : ℝ) : Prop :=
  1 < α ∧ IsIntegral ℤ α ∧ ∀ z ∈ (minpoly ℚ α).aroots ℂ, z ≠ (α : ℂ) → ‖z‖ < 1
end
-- CorvajaZannier2004.IntegralPowerSums
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] IsLocalRing.toNontrivial
attribute [local instance 999] SubsemiringClass.toSubmonoidClass
@[expose] public section
open IsDedekindDomain Height Module
open Filter Topology IntermediateField Module
theorem isIntegral_of_trace_mul_pow {α : ℂ} (hα : IsAlgebraic ℚ α) {Ξ : Set ℕ}
    (hΞ : Ξ.Infinite) {q : ℕ → ℕ} (hq : ∀ n ∈ Ξ, 0 < q n)
    (hlog : Tendsto (fun n : ℕ ↦ Real.log (q n) / n) (atTop ⊓ 𝓟 Ξ) (𝓝 0))
    (htr : ∀ n ∈ Ξ, ∃ t : ℤ, t ≠ 0 ∧
      Algebra.trace ℚ ℚ⟮α⟯ (q n * AdjoinSimple.gen ℚ α ^ n) = t) :
    IsIntegral ℤ α := by
  sorry
theorem isIntegral_or_exists_pow_eq_ratCast {α : ℂ} (hα : IsAlgebraic ℚ α) {Ξ : Set ℕ}
    (hΞ : Ξ.Infinite) {q : ℕ → ℕ} (hq : ∀ n ∈ Ξ, 0 < q n)
    (hlog : Tendsto (fun n : ℕ ↦ Real.log (q n) / n) (atTop ⊓ 𝓟 Ξ) (𝓝 0))
    (htr : ∀ n ∈ Ξ, ∃ t : ℤ, t ≠ 0 ∧
      Algebra.trace ℚ ℚ⟮α⟯ (q n * AdjoinSimple.gen ℚ α ^ n) = t) :
    (∃ h : ℕ, 0 < h ∧ ∃ r : ℚ, α ^ h = r) ∨ IsIntegral ℤ α := by
  sorry
end
end
-- CorvajaZannier2004.MainTheorem
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open IsDedekindDomain Height Module IntermediateField
open NumberField
theorem finite_setOf_not_isPseudoPisot {Γ : Subgroup ℝˣ} (hΓ : Γ.FG)
    (hΓalg : ∀ u ∈ Γ, IsAlgebraic ℚ (u : ℝ)) {δ : ℝ} (hδ : IsAlgebraic ℚ δ) (hδ0 : δ ≠ 0)
    {ε : ℝ} (hε : 0 < ε) :
    {p : ℤ × Γ | 1 < |δ * p.1 * ((p.2 : ℝˣ) : ℝ)| ∧
      ¬ IsPseudoPisot (δ * p.1 * ((p.2 : ℝˣ) : ℝ)) ∧
      0 < |δ * p.1 * ((p.2 : ℝˣ) : ℝ) - round (δ * p.1 * ((p.2 : ℝˣ) : ℝ))| ∧
      |δ * p.1 * ((p.2 : ℝˣ) : ℝ) - round (δ * p.1 * ((p.2 : ℝˣ) : ℝ))| <
        absMulHeight₁ ((p.2 : ℝˣ) : ℝ) ^ (-ε) *
          |(p.1 : ℝ)| ^ (-(finrank ℚ ℚ⟮((p.2 : ℝˣ) : ℝ)⟯ : ℝ) - ε)}.Finite := by
  sorry
end
-- CorvajaZannier2004.PisotPowers
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter Module IntermediateField NumberField
theorem exists_isPisot_pow_of_frequently {α l : ℝ} (hα : 1 < α) (halg : IsAlgebraic ℚ α)
    (hl0 : 0 < l) (hl1 : l < 1) (h : ∃ᶠ n : ℕ in atTop, |α ^ n - round (α ^ n)| < l ^ n) :
    (∃ n, 0 < n ∧ IsPisot (α ^ n)) ∧ IsIntegral ℤ α := by
  sorry
end
-- CorvajaZannier2004.Appendix
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter Topology
namespace Real
theorem exists_frequently_not_isPisot :
    ∃ α : ℝ, 1 < α ∧ (∃ᶠ n : ℕ in atTop, |α ^ n - round (α ^ n)| ≤ 1 / 2 ^ n) ∧
      ∀ d, 0 < d → ¬ IsPisot (α ^ d) := by
  sorry
theorem exists_transcendental_frequently_not_isPisot :
    ∃ α : ℝ, 1 < α ∧ (∃ᶠ n : ℕ in atTop, |α ^ n - round (α ^ n)| ≤ 1 / 2 ^ n) ∧
      (∀ d, 0 < d → ¬ IsPisot (α ^ d)) ∧ Transcendental ℚ α := by
  sorry
end Real
end
-- CorvajaZannier2004.ContinuedFraction
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] SubsemiringClass.toSubmonoidClass
@[expose] public section
open GenContFract Matrix
open scoped MatrixGroups
namespace Real
noncomputable def gaussMap (y : ℝ) : ℝ := (Int.fract y)⁻¹
noncomputable def cfTail (x : ℝ) (n : ℕ) : ℝ := gaussMap^[n] x
noncomputable def cfQuot (x : ℝ) (n : ℕ) : ℤ := ⌊cfTail x n⌋
noncomputable def cfPeriod (x : ℝ) : ℕ :=
  sInf {r : ℕ | 0 < r ∧ ∃ N, ∀ i ≥ N,
    (GenContFract.of x).partDens.get? (i + r) = (GenContFract.of x).partDens.get? i}
end Real
end
end
-- CorvajaZannier2004.QuadraticIrrational
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] SubsemiringClass.toSubmonoidClass
@[expose] public section
open scoped MatrixGroups
namespace Real
def IsQuadraticIrrational (x : ℝ) : Prop :=
  Irrational x ∧ ∃ a b c : ℚ, a ≠ 0 ∧ a * x ^ 2 + b * x + c = 0
end Real
end
end
-- CorvajaZannier2004.PartialQuotients
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter Topology Module IntermediateField NumberField
namespace Real
variable {α : ℝ}
theorem isPisot_or_tendsto_log_cfQuot (hα : IsQuadraticIrrational α) (h1 : 1 < α)
    (hsq : ∀ r : ℚ, α ^ 2 ≠ r) :
    IsPisot α ∨ ∀ i, 0 < i →
      Tendsto (fun n : ℕ ↦ Real.log (cfQuot (α ^ n) i) / n) atTop (𝓝 0) := by
  sorry
theorem isPisot_or_tendsto_log_cfQuot_odd (hα : IsQuadraticIrrational α) (h1 : 1 < α) :
    IsPisot α ∨ ∀ i, 0 < i → Tendsto (fun n : ℕ ↦ Real.log (cfQuot (α ^ (2 * n + 1)) i) /
      ((2 * n + 1 : ℕ) : ℝ)) atTop (𝓝 0) := by
  sorry
end Real
end
-- CorvajaZannier2004.PeriodLength
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Filter Topology
namespace Real
variable {x z β : ℝ}
theorem tendsto_cfPeriod_pow {α : ℝ} (hα : IsQuadraticIrrational α) (hsq : ∀ r : ℚ, α ^ 2 ≠ r)
    (hunit : ¬ (IsIntegral ℤ α ∧ IsIntegral ℤ α⁻¹)) :
    Tendsto (fun n ↦ cfPeriod (α ^ n)) atTop atTop := by
  sorry
theorem tendsto_cfPeriod_pow_odd {α : ℝ} (hα : IsQuadraticIrrational α) (h0 : 0 < α)
    (hsq : ∃ r : ℚ, α ^ 2 = r) :
    Tendsto (fun n : ℕ ↦ cfPeriod (α ^ (2 * n + 1))) atTop atTop := by
  sorry
end Real
end
-- CorvajaZannier2004.UnitPowers
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] SubsemiringClass.toSubmonoidClass
@[expose] public section
namespace Real
variable {β : ℝ}
theorem bddAbove_cfPeriod_pow {α : ℝ} (hα : IsQuadraticIrrational α) (h0 : 0 < α)
    (hunit : IsIntegral ℤ α ∧ IsIntegral ℤ α⁻¹) :
    BddAbove (Set.range fun n : ℕ ↦ cfPeriod (α ^ n)) := by
  sorry
end Real
end
end
