/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Challenge.ArithmeticHeights.Arakelov
public import Challenge.ArithmeticHeights.Absolute
public import Challenge.ArithmeticHeights.Affine
public import Challenge.ArithmeticHeights.Plucker
public import Challenge.ArithmeticHeights.Matrix
public import Challenge.ArithmeticHeights.BombieriVaalerEntries
public import Challenge.ArithmeticHeights.BombieriVaalerRelative
public import Challenge.ArithmeticHeights.Polynomial
public import Challenge.ArithmeticHeights.MonomialIndex
public import Challenge.ArithmeticHeights.AuxiliaryPolynomial
public import Challenge.ArithmeticHeights.Siegel
public import Challenge.ArithmeticHeights.BombieriVaaler
public import Challenge.DiophantineApproximation.RothTheorem
public import Challenge.DiophantineApproximation.RothInfinity
public import Challenge.DiophantineApproximation.ApproxProd
public import Challenge.DiophantineApproximation.AffineProd
public import Challenge.DiophantineApproximation.ApproximationDomain
public import Challenge.DiophantineApproximation.RationalPlaces
public import Challenge.DiophantineApproximation.GeneralPosition
public import Challenge.DiophantineApproximation.IrrationalityExponent
public import Challenge.DiophantineApproximation.MovingTargets
public import Challenge.DiophantineApproximation.ParametricSubspace
public import Challenge.DiophantineApproximation.RothRational
public import Challenge.DiophantineApproximation.Ridout
public import Challenge.DiophantineApproximation.RothIntervals
public import Challenge.DiophantineApproximation.RothProjective
public import Challenge.DiophantineApproximation.SubspaceTheorem
public import Challenge.DiophantineApproximation.SubspaceAlgebraic
public import Challenge.DiophantineApproximation.SubspaceAffine
public import Challenge.DiophantineApproximation.SubspaceSystem
public import Challenge.DiophantineApproximation.SubspaceIntervals
public import Challenge.DiophantineApproximation.RothSubspaceCount
public import Challenge.DiophantineApproximation.SubspaceGeneralPosition
public import Challenge.DiophantineApproximation.SubspaceConsistency
public import Challenge.DiophantineApproximation.SubspaceSmall
