/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Mathlib.Algebra.Order.Ring.IsNonarchimedean
public import Mathlib.Analysis.AbsoluteValue.Equivalence
import Mathlib.Analysis.MeanInequalitiesPow
public import Mathlib.NumberTheory.NumberField.Completion.FinitePlace
public import Mathlib.Analysis.Normed.Algebra.GelfandMazur
public import Mathlib.Analysis.Normed.Field.Instances
public import Mathlib.NumberTheory.NumberField.Completion.InfinitePlace
public import Mathlib.Analysis.SpecialFunctions.Log.PosLog
public import Mathlib.NumberTheory.Height.NumberField
public import Mathlib.NumberTheory.Height.Projectivization
public import Mathlib.RingTheory.Ideal.Norm.RelNorm
public import Mathlib.LinearAlgebra.ExteriorPower.Basis
public import Mathlib.LinearAlgebra.Matrix.Rank
public import Mathlib.NumberTheory.Height.MvPolynomial
public import Mathlib.Algebra.Module.ZLattice.Basic
public import Mathlib.MeasureTheory.Measure.Haar.Unique
public import Mathlib.Algebra.Module.ZLattice.Covolume
public import Mathlib.MeasureTheory.Group.GeometryOfNumbers
public import Mathlib.MeasureTheory.Measure.Haar.Disintegration
public import Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls
public import Mathlib.NumberTheory.NumberField.CanonicalEmbedding.Basic
public import Mathlib.RingTheory.Complex
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.NumberTheory.NumberField.Discriminant.Basic
public import Mathlib.Analysis.Matrix.LDL
public import Mathlib.Algebra.Module.LinearMap.Rat
public import Mathlib.Data.Matrix.ColumnRowPartitioned
public import Mathlib.Data.Finsupp.MonomialOrder
public import Mathlib.RingTheory.Polynomial.GaussNorm
public import Mathlib.Analysis.Polynomial.MahlerMeasure
public import Mathlib.Data.Finsupp.Interval
public import Mathlib.RingTheory.Polynomial.Wronskian
public import Mathlib.Algebra.MvPolynomial.NoZeroDivisors
public import Mathlib.Analysis.Complex.ExponentialBounds
public import Mathlib.Algebra.Order.Antidiag.FinsuppEquiv
public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
public import Mathlib.RingTheory.DedekindDomain.SInteger
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.RingTheory.DedekindDomain.SelmerGroup
public import Mathlib.NumberTheory.NumberField.Units.Regulator
public import Mathlib.Topology.Compactification.OnePoint.Basic
import Mathlib.NumberTheory.NumberField.Completion.Ramification
import Mathlib.Algebra.FiniteSupport.Basic
public import Mathlib.NumberTheory.Ostrowski
public import Mathlib.NumberTheory.NumberField.House
import Mathlib.LinearAlgebra.LinearIndependent.BaseChange
public import Mathlib.Algebra.MvPolynomial.Coeff
public import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.GroupTheory.FiniteAbelian.Basic
public import Mathlib.Algebra.Polynomial.Homogenize
import Mathlib.NumberTheory.MahlerMeasure

/-!
# Evertse1984: the statements of record

Generated by `scripts/make-challenge.py --paper Evertse1984` from the library
`Evertse1984` and the libraries it builds on; do not edit. Each `-- <module>` part repeats,
verbatim, the definitions of that module the certified theorems mention, and states the theorems
with `sorry`. Each part opens by clearing Lean's auxiliary-proof cache, as a module boundary does,
and some lower instances locally to restore their module's tie-break. See `COMPARATOR.md`.
-/

-- DiophantineApproximation.AffineProd
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
noncomputable def affineProd (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F)) (x : ι → K) : ℝ :=
  (∏ v : InfinitePlace K, (∏ i, w v.1 (L v.1 i fun j ↦ algebraMap K F (x j))) ^ v.mult) *
    ∏ v ∈ S, ∏ i, w (FinitePlace.mk v).1
      (L (FinitePlace.mk v).1 i fun j ↦ algebraMap K F (x j))
end NumberField
end
-- DiophantineApproximation.SubspaceAffine
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
@[expose] public section
open Finset Height IsDedekindDomain Module
namespace NumberField
variable {K F : Type*} [Field K] [NumberField K] [Field F] [NumberField F] [Algebra K F]
variable {ι : Type*} [Fintype ι]
open scoped Classical in
theorem exists_finset_submodule_of_integer_of_affineProd_le [Nontrivial ι]
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    (w : AbsoluteValue K ℝ → AbsoluteValue F ℝ)
    (hwInf : ∀ v : InfinitePlace K, (w v.1).LiesOver v.1)
    (hwFin : ∀ v ∈ S, (w (FinitePlace.mk v).1).LiesOver (FinitePlace.mk v).1)
    (L : AbsoluteValue K ℝ → ι → Dual F (ι → F))
    (hLInf : ∀ v : InfinitePlace K, LinearIndependent F (L v.1))
    (hLFin : ∀ v ∈ S, LinearIndependent F (L (FinitePlace.mk v).1))
    {ε : ℝ} (hε : 0 < ε) :
    ∃ T : Finset (Submodule K (ι → K)), (∀ W ∈ T, W ≠ ⊤) ∧
      ∀ x : ι → K, x ≠ 0 → (∀ j, x j ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) →
        affineProd S w L x ≤ mulHeight x ^ (-ε) → ∃ W ∈ T, x ∈ W := by
  sorry
end NumberField
end
-- Evertse1984.PlaceProd
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] EuclideanDomain.toNontrivial
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open IsDedekindDomain Height Module
namespace NumberField
variable {K : Type*} [Field K] [NumberField K]
noncomputable def placeProd (S : Finset (HeightOneSpectrum (𝓞 K))) (T : Set (AbsoluteValue K ℝ))
    (g : AbsoluteValue K ℝ → ℝ) : ℝ :=
  (∏ v : InfinitePlace K, T.mulIndicator g v.1 ^ v.mult) *
    ∏ P ∈ S, T.mulIndicator g (FinitePlace.mk P).1
end NumberField
end
end
-- Evertse1984.SUnitSums
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] EuclideanDomain.toNontrivial
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open IsDedekindDomain Height Module
namespace NumberField
universe u
variable {K : Type*} [Field K] [NumberField K]
variable (S : Finset (HeightOneSpectrum (𝓞 K)))
theorem exists_pos_forall_placeProd_le (ι : Type*) [Fintype ι] {ε : ℝ} (hε : 0 < ε) :
    ∃ C > 0, ∀ (T : Set (AbsoluteValue K ℝ)) (x : ι → K), (∀ i, IsIntegral ℤ (x i)) →
      (∀ I : Finset ι, I.Nonempty → ∑ i ∈ I, x i ≠ 0) →
      C * placeProd S T (fun v ↦ ⨆ i, v (x i)) * (⨆ i, house (x i)) ^ (-ε) ≤
        (∏ i, placeProd S Set.univ (fun v ↦ v (x i))) *
          placeProd S T (fun v ↦ v (∑ i, x i)) := by
  sorry
end NumberField
open NumberField in
def EvertseTheorem1 : Prop :=
  ∀ (K : Type) [Field K] [NumberField K] (ι : Type) [Fintype ι]
    (S : Finset (HeightOneSpectrum (𝓞 K))) (c d : ℝ), 0 < c → 0 ≤ d → d < 1 →
    {X : Projectivization K (ι → K) | ∃ (x : ι → K) (hx : x ≠ 0), Projectivization.mk K x hx = X ∧
      (∀ i, x i ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) ∧
      ∏ i, NumberField.placeProd S Set.univ (fun v ↦ v (x i)) ≤ c * mulHeight x ^ d ∧
      ∑ i, x i = 0 ∧ ∀ I : Finset ι, I.Nonempty → I ≠ Finset.univ → ∑ i ∈ I, x i ≠ 0}.Finite
end
end
-- Evertse1984.AdmissiblePoints
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] EuclideanDomain.toNontrivial
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open IsDedekindDomain Height Module
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] (S : Finset (HeightOneSpectrum (𝓞 K)))
theorem finite_setOf_admissible_sum_eq_zero (ι : Type*) [Fintype ι] {c d : ℝ} (hd0 : 0 ≤ d)
    (hd1 : d < 1) :
    {X : Projectivization K (ι → K) | ∃ (x : ι → K) (hx : x ≠ 0), Projectivization.mk K x hx = X ∧
      (∀ i, x i ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) ∧
      ∏ i, placeProd S Set.univ (fun v ↦ v (x i)) ≤ c * mulHeight x ^ d ∧
      ∑ i, x i = 0 ∧ ∀ I : Finset ι, I.Nonempty → I ≠ Finset.univ → ∑ i ∈ I, x i ≠ 0}.Finite := by
  sorry
end NumberField
theorem evertseTheorem1 : EvertseTheorem1 := by
  sorry
end
end
-- Evertse1984.Corollaries
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] EuclideanDomain.toNontrivial
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open IsDedekindDomain Height Module
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] (S : Finset (HeightOneSpectrum (𝓞 K)))
theorem exists_pos_forall_placeProd_iInf_le (ι : Type*) [Fintype ι] {ε : ℝ} (hε : 0 < ε) :
    ∃ C > 0, ∀ (T : Set (AbsoluteValue K ℝ)) (x : ι → K), (∀ i, IsIntegral ℤ (x i)) →
      (∀ i, x i ≠ 0) → ∑ i, x i ≠ 0 →
      C * placeProd S T (fun v ↦ ⨅ i, v (x i)) * (⨆ i, house (x i)) ^ (-ε) ≤
        (∏ i, placeProd S Set.univ (fun v ↦ v (x i))) *
          placeProd S T (fun v ↦ v (∑ i, x i)) := by
  sorry
end NumberField
namespace Rat
open NumberField
theorem finite_setOf_sum_eq_zero_of_gcd_eq_one (ι : Type*) [Fintype ι] (S₀ : Finset Nat.Primes)
    {c d : ℝ} (hd0 : 0 ≤ d) (hd1 : d < 1) :
    {x : ι → ℤ | ∑ i, x i = 0 ∧
      (∀ I : Finset ι, I.Nonempty → I ≠ Finset.univ → ∑ i ∈ I, x i ≠ 0) ∧
      Finset.univ.gcd x = 1 ∧
      ∏ k, ((|x k| : ℝ) * ∏ p ∈ S₀, (padicNorm (p : ℕ) (x k) : ℝ)) ≤
        c * ((⨆ k, |x k| : ℤ) : ℝ) ^ d}.Finite := by
  sorry
end Rat
end
end
-- Evertse1984.PolynomialValues
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] EuclideanDomain.toNontrivial
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open IsDedekindDomain Height Module Polynomial
namespace NumberField
variable {K : Type*} [Field K] [NumberField K]
variable (S : Finset (HeightOneSpectrum (𝓞 K))) (T : Set (AbsoluteValue K ℝ))
theorem exists_pos_forall_placeProd_eval_intCast (f : K[X]) :
    ∃ C > 0, ∀ (T : Set (AbsoluteValue K ℝ)) (r : ℤ), f.eval (r : K) ≠ 0 →
      (C * max |(r : ℝ)| 1 ^ (finrank ℚ K * f.natDegree))⁻¹ ≤
          placeProd S T (fun v ↦ v (f.eval (r : K))) ∧
        placeProd S T (fun v ↦ v (f.eval (r : K))) ≤
          C * max |(r : ℝ)| 1 ^ (finrank ℚ K * f.natDegree) := by
  sorry
end NumberField
end
end
-- Evertse1984.Recurrences
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] EuclideanDomain.toNontrivial
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open IsDedekindDomain Height Module Polynomial
namespace NumberField
variable {K : Type*} [Field K] [NumberField K]
noncomputable def powerSum {ι : Type*} [Fintype ι] (α : ι → K) (f : ι → K[X]) (k : ℕ) : K :=
  ∑ i, (f i).eval (k : K) * α i ^ k
variable (S : Finset (HeightOneSpectrum (𝓞 K)))
def powerSumPairs {ι : Type*} [Fintype ι] (α : ι → K) (f : ι → K[X]) : Set (ℕ × ℕ) :=
  {p | p.2 < p.1 ∧ powerSum α f p.2 ≠ 0 ∧ (powerSum α f p.1 = 0 ∨
    ∃ w : Kˣ, w ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
      (w : K) = powerSum α f p.1 / powerSum α f p.2)}
end NumberField
end
end
-- Evertse1984.GeneralRoots
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
section
attribute [local instance 999] Module.Free.instFaithfulSMulOfNontrivial
attribute [local instance 998] instFaithfulSMul_1
attribute [local instance 999] EuclideanDomain.toNontrivial
attribute [local instance 999] SubgroupClass.toSubmonoidClass
@[expose] public section
open IsDedekindDomain Polynomial
namespace NumberField
variable {K : Type*} [Field K] [NumberField K] {L : Type*} [Field L] [NumberField L]
  [Algebra K L]
theorem finite_setOf_eval_div_eval_mem_unit (S : Finset (HeightOneSpectrum (𝓞 K))) {f g : K[X]}
    (hfg : ∀ h : ℤ, h ≠ 0 → ¬ f.comp (X + C (h : K)) ∣ g ∧ ¬ g ∣ f.comp (X + C (h : K)))
    {β γ : ℝ} (hβ : 0 < β) (hγ0 : 0 ≤ γ) (hγ : γ < 1 / (f.natDegree + g.natDegree + 2)) :
    {p : ℤ × ℤ | p.1 ≠ p.2 ∧ |(p.1 : ℝ) - p.2| ≤ β * |(p.1 : ℝ)| ^ γ ∧
      ∃ u : Kˣ, u ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
        (u : K) = f.eval (p.1 : K) / g.eval (p.2 : K)}.Finite := by
  sorry
theorem finite_setOf_powerSum_div_mem_unit (S : Finset (HeightOneSpectrum (𝓞 K))) {ι : Type*}
    [Fintype ι] [Nontrivial ι] {α : ι → K} {f : ι → K[X]} (hα0 : ∀ i, α i ≠ 0)
    (hnd : ∀ i j, i ≠ j → ∀ n : ℕ, 0 < n → (α i / α j) ^ n ≠ 1) (hf0 : ∀ i, f i ≠ 0) :
    (powerSumPairs S α f).Finite := by
  sorry
theorem finite_setOf_div_mem_unit_of_eq_powerSum (S : Finset (HeightOneSpectrum (𝓞 K)))
    {u : ℕ → K} {ι : Type*} [Fintype ι] [Nontrivial ι] {α : ι → L} {f : ι → L[X]}
    (hu : ∀ k, algebraMap K L (u k) = powerSum α f k) (hα0 : ∀ i, α i ≠ 0)
    (hnd : ∀ i j, i ≠ j → ∀ n : ℕ, 0 < n → (α i / α j) ^ n ≠ 1) (hf0 : ∀ i, f i ≠ 0) :
    {p : ℕ × ℕ | p.2 < p.1 ∧ u p.2 ≠ 0 ∧ (u p.1 = 0 ∨
      ∃ w : Kˣ, w ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
        (w : K) = u p.1 / u p.2)}.Finite := by
  sorry
theorem finite_setOf_powerSum_mem_unit (S : Finset (HeightOneSpectrum (𝓞 K))) {ι : Type*}
    [Fintype ι] [Nontrivial ι] {α : ι → K} {f : ι → K[X]} (hα0 : ∀ i, α i ≠ 0)
    (hnd : ∀ i j, i ≠ j → ∀ n : ℕ, 0 < n → (α i / α j) ^ n ≠ 1) (hf0 : ∀ i, f i ≠ 0) :
    {r : ℕ | powerSum α f r = 0 ∨ ∃ w : Kˣ, w ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
      (w : K) = powerSum α f r}.Finite := by
  sorry
theorem finite_setOf_mem_unit_of_eq_powerSum (S : Finset (HeightOneSpectrum (𝓞 K)))
    {u : ℕ → K} {ι : Type*} [Fintype ι] [Nontrivial ι] {α : ι → L} {f : ι → L[X]}
    (hu : ∀ k, algebraMap K L (u k) = powerSum α f k) (hα0 : ∀ i, α i ≠ 0)
    (hnd : ∀ i j, i ≠ j → ∀ n : ℕ, 0 < n → (α i / α j) ^ n ≠ 1) (hf0 : ∀ i, f i ≠ 0) :
    {r : ℕ | u r = 0 ∨ ∃ w : Kˣ, w ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
      (w : K) = u r}.Finite := by
  sorry
theorem finite_setOf_powerSum_eq {ι : Type*} [Fintype ι] [Nonempty ι] {α : ι → K}
    {f : ι → K[X]} (hα0 : ∀ i, α i ≠ 0)
    (hnd : ∀ i j, i ≠ j → ∀ n : ℕ, 0 < n → (α i / α j) ^ n ≠ 1) (hf0 : ∀ i, f i ≠ 0)
    (hone : Subsingleton ι → ∀ i, 0 < (f i).natDegree ∨ ∀ n : ℕ, 0 < n → α i ^ n ≠ 1) :
    {p : ℕ × ℕ | p.2 < p.1 ∧ powerSum α f p.1 = powerSum α f p.2}.Finite := by
  sorry
omit [NumberField K] in
theorem finite_setOf_eq_of_eq_powerSum {u : ℕ → K} {ι : Type*} [Fintype ι] [Nonempty ι]
    {α : ι → L} {f : ι → L[X]} (hu : ∀ k, algebraMap K L (u k) = powerSum α f k)
    (hα0 : ∀ i, α i ≠ 0)
    (hnd : ∀ i j, i ≠ j → ∀ n : ℕ, 0 < n → (α i / α j) ^ n ≠ 1) (hf0 : ∀ i, f i ≠ 0)
    (hone : Subsingleton ι → ∀ i, 0 < (f i).natDegree ∨ ∀ n : ℕ, 0 < n → α i ^ n ≠ 1) :
    {p : ℕ × ℕ | p.2 < p.1 ∧ u p.1 = u p.2}.Finite := by
  sorry
end NumberField
end
end
