/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Mathlib.RingTheory.Polynomial.GaussLemma

-- Used only inside proofs.
import Mathlib.RingTheory.Localization.Integral
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# Ideals of `R[X]` lying over zero

Let `R` be a unique factorization domain and `𝔓` an ideal of `R[X]` with `𝔓 ∩ R = 0`. Then
`𝔓` is generated by any prime element `x ∈ 𝔓` (`Ideal.eq_span_singleton_of_comap_C_eq_bot`).
Indeed `x` is primitive, hence irreducible over the fraction field `K` by Gauss's lemma. For
`g ∈ 𝔓` not divisible by `x` in `K[X]`, a Bézout relation `a x + b g = 1` in `K[X]`, with the
denominators cleared, puts a nonzero constant in `𝔓`. So `x ∣ g` in `K[X]`, hence in `R[X]`.

This is the last step of G. Rémond's proof of the principality of eliminant ideals
(*Élimination multihomogène*, Chapter 5 of Nesterenko–Philippon (eds.), *Introduction to
algebraic independence theory*, LNM 1752 (2001), Theorem 2.13 (2)).
-/

@[expose] public section

open Polynomial

namespace Ideal

variable {R : Type*} [CommRing R] [IsDomain R] [UniqueFactorizationMonoid R]

/-- **An ideal of `R[X]` lying over zero is generated by any prime element in it**, for a
unique factorization domain `R`. -/
theorem eq_span_singleton_of_comap_C_eq_bot {P : Ideal R[X]}
    (hP : P.comap (C : R →+* R[X]) = ⊥) {x : R[X]} (hx : x ∈ P) (hxp : Prime x) :
    P = Ideal.span {x} := by
  classical
  set K := FractionRing R
  have hC : ∀ r : R, C r ∈ P → r = 0 := fun r hr ↦ by
    have : r ∈ P.comap (C : R →+* R[X]) := hr
    rwa [hP, Ideal.mem_bot] at this
  have hprim : x.IsPrimitive := by
    intro r ⟨y, hy⟩
    rcases hxp.dvd_or_dvd (show x ∣ C r * y from hy ▸ dvd_rfl) with h | h
    · have hr := hC r (P.mem_of_dvd h hx)
      rw [hr, map_zero, zero_mul] at hy
      exact absurd hy hxp.ne_zero
    · obtain ⟨t, rfl⟩ := h
      have : C r * t = 1 := by
        have h1 : x * 1 = x * (C r * t) := by rw [mul_one]; nth_rw 1 [hy]; ring
        exact (mul_left_cancel₀ hxp.ne_zero h1).symm
      exact isUnit_C.mp (IsUnit.of_mul_eq_one _ this)
  have hirr : Irreducible (x.map (algebraMap R K)) :=
    (hprim.irreducible_iff_irreducible_map_fraction_map).mp hxp.irreducible
  refine le_antisymm (fun g hg ↦ ?_) (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr hx))
  rw [Ideal.mem_span_singleton]
  refine hprim.dvd_of_fraction_map_dvd_fraction_map (K := K) (by_contra fun hdvd ↦ ?_)
  obtain ⟨a, b, hab⟩ := (hirr.coprime_iff_not_dvd).mpr hdvd
  obtain ⟨s₁, hs₁, ha⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors R) a
  obtain ⟨s₂, hs₂, hb⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors R) b
  set a' := IsLocalization.integerNormalization (nonZeroDivisors R) a
  set b' := IsLocalization.integerNormalization (nonZeroDivisors R) b
  have hmap : (C s₂ * a' * x + C s₁ * b' * g).map (algebraMap R K) =
      (C (s₁ * s₂)).map (algebraMap R K) := by
    simp only [Polynomial.map_add, Polynomial.map_mul, Polynomial.map_C, ha, hb]
    have h1 : C (algebraMap R K s₂) * (s₁ • a) * x.map (algebraMap R K) +
        C (algebraMap R K s₁) * (s₂ • b) * g.map (algebraMap R K) =
        C (algebraMap R K (s₁ * s₂)) * (a * x.map (algebraMap R K) +
          b * g.map (algebraMap R K)) := by
      simp only [Algebra.smul_def, Polynomial.algebraMap_apply, map_mul]
      ring
    rw [h1, hab, mul_one]
  have heq := map_injective _ (IsFractionRing.injective R K) hmap
  have hmem : C (s₁ * s₂) ∈ P := by
    rw [← heq]
    exact P.add_mem (P.mul_mem_left _ hx) (P.mul_mem_left _ hg)
  exact mul_ne_zero (nonZeroDivisors.ne_zero hs₁) (nonZeroDivisors.ne_zero hs₂) (hC _ hmem)

end Ideal

end
