/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ForMathlib.RingTheory.MvPolynomial.BaseChange
public import Mathlib.RingTheory.Nullstellensatz

-- Used only inside proofs.
import Mathlib.Algebra.Order.Sub.Prod
import Mathlib.LinearAlgebra.Matrix.Adjugate
import Mathlib.LinearAlgebra.Matrix.ToLinearEquiv
import Mathlib.LinearAlgebra.LinearIndependent.Lemmas

/-!
# Multihomogeneous elimination

This file starts G. Rémond's theory of multihomogeneous elimination (*Élimination
multihomogène*, Chapter 5 of Nesterenko–Philippon (eds.), *Introduction to algebraic independence
theory*, LNM 1752 (2001), §2.1), the basis of his multiprojective heights (Chapter 7).

The variables of `R[X]` are split into blocks by `b : σ → ι`, one block for each factor of
`ℙ^{n_1} × ⋯ × ℙ^{n_q}`. For an index `d = (d_l)_{l ∈ κ}` of multidegrees (Rémond's
`(d_1, …, d_r)`, indexed by any type `κ`), `A[d] = R[u]` is the polynomial ring in the
coefficients `u^{(l)}_m` of the generic forms `U_l = ∑_m u^{(l)}_m X^m` of multidegrees `d_l`.
For an ideal `I` of `R[X]`, `I[d]` is the ideal of `A[d][X]` generated by `I` and the `U_l`, the
*characteristic ideal* `𝔄_d(I)` is its saturation by the irrelevant ideal `𝔪_ε` (generated by
the monomials of multidegree `(1, …, 1)`), and the *eliminant ideal* is
`𝔈_d(I) = 𝔄_d(I) ∩ A[d]`. Specializing `u` in a field, `𝔈_d(I)` vanishes
exactly when the specialized forms have a common zero on `V(I)` with a nonzero coordinate in
every block (the elimination theorem).

## Main definitions

* `MvPolynomial.genericForm`, `MvPolynomial.genericIdeal`: `U_l` and `I[d]`.
* `MvPolynomial.irrelevantIdeal`: `𝔪_ε`.
* `MvPolynomial.charIdeal`, `MvPolynomial.elimIdeal`: `𝔄_d(I)` and `𝔈_d(I)` (Def. 2.1).
* `MvPolynomial.subst`: Rémond's substitution `δ`,
  `u^{(l)}_m ↦ ∑_{m'} (s_{m,m'} - s_{m',m}) X^{m'}`, which kills every `U_l`.

## Main statements

* `Submodule.exists_smul_single_mem_of_span_eq_top`: the determinant trick.
* `MvPolynomial.elimIdeal_le_ker_iff`: **the elimination theorem** (Thm 2.2) over an
  algebraically closed field, for a multihomogeneous `I`. The hard direction combines the
  Nullstellensatz with the determinant trick in one multidegree.
* `MvPolynomial.mem_charIdeal_iff_subst`: Rémond's Lemma 2.3, `f ∈ 𝔄_d(I)` if and only if `δ(f)`
  is in the saturation of `I 𝔖B[d]`. The proof inverts `∏_i X_{t_i}` and undoes `δ` modulo the
  `U_l`.
* `MvPolynomial.isPrime_charIdeal`, `MvPolynomial.isPrime_elimIdeal`,
  `MvPolynomial.comap_map_C_charIdeal`, `MvPolynomial.charIdeal_inf`,
  `MvPolynomial.elimIdeal_inf`: Lemma 2.4. For a prime `𝔭` not containing `𝔪_ε`, `𝔄_d(𝔭)` and
  `𝔈_d(𝔭)` are prime and `𝔄_d(𝔭) ∩ R[X] = 𝔭`; both ideals commute with intersections.
-/

@[expose] public section

open Module Finset

/-- **The determinant trick.** If the images under `ρ : R → L` of a submodule `N` of `R^ι` span
`L^ι`, then some `Δ` with `ρ Δ ≠ 0` multiplies every unit vector into `N`: take `Δ` the
determinant of `|ι|` vectors of `N` whose images are a basis, and use the adjugate. -/
theorem Submodule.exists_smul_single_mem_of_span_eq_top {R L ι : Type*} [CommRing R] [Field L]
    [Finite ι] [DecidableEq ι] (ρ : R →+* L) (N : Submodule R (ι → R))
    (hN : Submodule.span L ((fun v ↦ ρ ∘ v) '' (N : Set (ι → R))) = ⊤) :
    ∃ Δ : R, ρ Δ ≠ 0 ∧ ∀ i, Δ • Pi.single i 1 ∈ N := by
  have := Fintype.ofFinite ι
  obtain ⟨t, hts, hspan, hli⟩ :=
    exists_linearIndependent L ((fun v ↦ ρ ∘ v) '' (N : Set (ι → R)))
  rw [hN] at hspan
  let B : Basis t L (ι → L) := Basis.mk hli (by rw [Subtype.range_coe_subtype, Set.ofPred_mem_eq,
    hspan])
  let e : ι ≃ t := (Pi.basisFun L ι).indexEquiv B
  have hv : ∀ i, ∃ v ∈ N, ρ ∘ v = (e i : ι → L) := fun i ↦ hts (e i).2
  choose v hvN hvρ using hv
  let A : Matrix ι ι R := fun i j ↦ v i j
  refine ⟨A.det, ?_, fun i ↦ ?_⟩
  · rw [RingHom.map_det]
    have hrows : LinearIndependent L (fun i ↦ (ρ.mapMatrix A) i) := by
      have : (fun i ↦ (ρ.mapMatrix A) i) = fun i ↦ ((e i : t) : ι → L) := by
        funext i
        rw [← hvρ i]
        rfl
      rw [this]
      exact hli.comp e e.injective
    exact (Matrix.isUnit_iff_isUnit_det _).mp
      (Matrix.linearIndependent_rows_iff_isUnit.mp hrows) |>.ne_zero
  · have hrow : A.det • (Pi.single i 1 : ι → R) = ∑ j, A.adjugate i j • v j := by
      funext k
      have := congrFun (congrFun (Matrix.adjugate_mul A) i) k
      simp only [Matrix.mul_apply, Matrix.smul_apply, Matrix.one_apply, smul_eq_mul] at this
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, Pi.single_apply, mul_ite,
        mul_one, mul_zero]
      change _ = ∑ j, A.adjugate i j * A j k
      rw [this]
      by_cases hki : k = i
      · subst hki
        simp
      · simp [hki, Ne.symm hki]
    rw [hrow]
    exact Submodule.sum_mem _ fun j _ ↦ Submodule.smul_mem _ _ (hvN j)

namespace MvPolynomial

section Extension

variable {σ R P : Type*} [CommRing R]

/-- Extending coefficients `R → R[P]` is, after commuting the variables, extending along
`C : R[X] → R[X][P]`. -/
theorem map_map_C_eq (I : Ideal (MvPolynomial σ R)) :
    I.map (map (C : R →+* MvPolynomial P R)) =
      (I.map (C : MvPolynomial σ R →+* MvPolynomial P (MvPolynomial σ R))).map
        ((commAlgEquiv R P σ).toRingEquiv : MvPolynomial P (MvPolynomial σ R) →+*
          MvPolynomial σ (MvPolynomial P R)) := by
  rw [Ideal.map_map]
  congr 1
  exact (RingHom.ext fun p ↦ commAlgEquiv_C p).symm

theorem mem_map_map_C_iff {I : Ideal (MvPolynomial σ R)}
    {p : MvPolynomial σ (MvPolynomial P R)} :
    p ∈ I.map (map (C : R →+* MvPolynomial P R)) ↔
      ∀ m, ((commAlgEquiv R P σ).symm p).coeff m ∈ I := by
  rw [map_map_C_eq, Ideal.map_comap_of_equiv, Ideal.mem_comap, MvPolynomial.mem_map_C_iff]
  rfl

theorem isPrime_map_map_C {S : Type*} [CommRing S] {I : Ideal (MvPolynomial σ S)} [I.IsPrime] :
    (I.map (map (C : S →+* MvPolynomial P S))).IsPrime := by
  rw [map_map_C_eq]
  have : (I.map (C : MvPolynomial σ S →+* MvPolynomial P (MvPolynomial σ S))).IsPrime := by
    rw [← Ideal.mk_ker (I := I), ← MvPolynomial.ker_map]
    exact RingHom.ker_isPrime _
  exact Ideal.map_isPrime_of_equiv _

theorem comap_map_C_map_map_C {I : Ideal (MvPolynomial σ R)} :
    (I.map (map (C : R →+* MvPolynomial P R))).comap (map C) = I := by
  ext p
  rw [Ideal.mem_comap, mem_map_map_C_iff]
  have : (commAlgEquiv R P σ).symm (map C p) = C p := by
    rw [AlgEquiv.symm_apply_eq, commAlgEquiv_C]
  simp only [this]
  classical
  constructor
  · intro h
    simpa using h 0
  · intro h m
    rw [coeff_C]
    split_ifs
    · exact h
    · exact I.zero_mem

theorem map_map_C_inf {I J : Ideal (MvPolynomial σ R)} :
    (I ⊓ J).map (map (C : R →+* MvPolynomial P R)) =
      I.map (map C) ⊓ J.map (map C) := by
  ext p
  simp only [Submodule.mem_inf, mem_map_map_C_iff]
  exact ⟨fun h ↦ ⟨fun m ↦ (h m).1, fun m ↦ (h m).2⟩, fun h m ↦ ⟨h.1 m, h.2 m⟩⟩

end Extension

section Generic

variable {σ ι : Type*} [Fintype σ] [Fintype ι] [DecidableEq ι]
variable (R : Type*) [CommRing R] (b : σ → ι) {κ : Type*} (d : κ → ι → ℕ)

/-- The coefficient variables `u^{(l)}_m` (`l ∈ κ`, `m` a monomial of multidegree `d l`) of the
generic forms of multidegrees `d`. -/
abbrev GenericVar : Type _ := Σ l : κ, blockMonomials b (d l)

/-- The generic form `U_l = ∑_m u^{(l)}_m X^m` of multidegree `d l`, in `A[d][X]` with
`A[d] = R[u]`. -/
noncomputable def genericForm (l : κ) : MvPolynomial σ (MvPolynomial (GenericVar b d) R) :=
  ∑ m : blockMonomials b (d l), monomial (m : σ →₀ ℕ) (X ⟨l, m⟩)

/-- The ideal `I[d]` of `A[d][X]` generated by `I` and the generic forms `U_l`. -/
noncomputable def genericIdeal (I : Ideal (MvPolynomial σ R)) :
    Ideal (MvPolynomial σ (MvPolynomial (GenericVar b d) R)) :=
  I.map (map C) ⊔ Ideal.span (Set.range (genericForm R b d))

/-- The irrelevant ideal `𝔪_ε` of `ℙ^{n_1} × ⋯ × ℙ^{n_q}`, generated by the monomials of
multidegree `(1, …, 1)`. -/
noncomputable def irrelevantIdeal : Ideal (MvPolynomial σ R) :=
  Ideal.span ((fun c ↦ monomial c 1) '' (blockMonomials b 1 : Set (σ →₀ ℕ)))

/-- **The characteristic ideal** `𝔄_d(I)` of index `d` (LNM 1752, Ch. 5, Def. 2.1): the
saturation of `I[d]` by the irrelevant ideal. -/
noncomputable def charIdeal (I : Ideal (MvPolynomial σ R)) :
    Ideal (MvPolynomial σ (MvPolynomial (GenericVar b d) R)) :=
  ⨆ n : ℕ, (genericIdeal R b d I).colon
    (irrelevantIdeal (MvPolynomial (GenericVar b d) R) b ^ n : Set _)

/-- **The eliminant ideal** `𝔈_d(I) = 𝔄_d(I) ∩ A[d]` of index `d` (LNM 1752, Ch. 5,
Def. 2.1). -/
noncomputable def elimIdeal (I : Ideal (MvPolynomial σ R)) :
    Ideal (MvPolynomial (GenericVar b d) R) :=
  (charIdeal R b d I).comap C

variable {R b d}

theorem monomial_mem_irrelevantIdeal {S : Type*} [CommRing S] {c : σ →₀ ℕ}
    (hc : c ∈ blockMonomials b 1) : monomial c (1 : S) ∈ irrelevantIdeal S b :=
  Ideal.subset_span ⟨c, hc, rfl⟩

theorem irrelevantIdeal_fg (S : Type*) [CommRing S] : (irrelevantIdeal S b).FG := by
  classical
  exact ⟨(blockMonomials b 1).image fun c ↦ monomial c 1, by simp [irrelevantIdeal]⟩

theorem mem_charIdeal {I : Ideal (MvPolynomial σ R)} {f} :
    f ∈ charIdeal R b d I ↔ ∃ n, ∀ g ∈ irrelevantIdeal _ b ^ n, g * f ∈ genericIdeal R b d I := by
  rw [charIdeal, Submodule.mem_iSup_of_directed]
  · simp [Submodule.mem_colon, mul_comm]
  · refine Monotone.directed_le fun m n hmn ↦ Submodule.colon_mono le_rfl ?_
    exact Ideal.pow_le_pow_right hmn

theorem mem_elimIdeal {I : Ideal (MvPolynomial σ R)} {f} :
    f ∈ elimIdeal R b d I ↔
      ∃ n, ∀ g ∈ irrelevantIdeal _ b ^ n, g * C f ∈ genericIdeal R b d I := by
  rw [elimIdeal, Ideal.mem_comap, mem_charIdeal]

theorem isWeightedHomogeneous_genericForm (l : κ) :
    IsWeightedHomogeneous (multiWeight b) (genericForm R b d l) (d l) :=
  IsWeightedHomogeneous.sum _ _ _ fun m _ ↦
    isWeightedHomogeneous_monomial _ _ _ (mem_blockMonomials.mp m.2)

theorem isWeightedHomogeneous_genericIdeal {I : Ideal (MvPolynomial σ R)}
    (hI : I.IsWeightedHomogeneous (multiWeight b)) :
    (genericIdeal R b d I).IsWeightedHomogeneous (multiWeight b) := by
  refine (hI.map C).sup (isWeightedHomogeneous_span fun g hg ↦ ?_)
  obtain ⟨l, rfl⟩ := hg
  exact ⟨d l, isWeightedHomogeneous_genericForm l⟩

omit [Fintype σ] in
/-- A monomial of multidegree `(1, …, 1)`: one variable from each block. -/
theorem weight_sum_single_one {t : ι → σ} (ht : ∀ i, b (t i) = i) :
    Finsupp.weight (multiWeight b) (∑ i, Finsupp.single (t i) 1) = 1 := by
  classical
  simp only [map_sum, Finsupp.weight_single, one_smul, multiWeight, ht]
  exact Finset.univ_sum_single 1

variable (R b) in
/-- A monomial of multidegree `≥ (n, …, n)` lies in `𝔪_ε ^ n`. -/
theorem monomial_mem_irrelevantIdeal_pow_of_le (n : ℕ) {c : σ →₀ ℕ}
    (hc : ∀ i, n ≤ Finsupp.weight (multiWeight b) c i) :
    monomial c (1 : R) ∈ irrelevantIdeal R b ^ n := by
  classical
  induction n generalizing c with
  | zero => simp
  | succ n ih =>
    have hex : ∀ i, ∃ s, b s = i ∧ c s ≠ 0 := by
      intro i
      have h := hc i
      rw [weight_multiWeight_apply] at h
      have h0 : ∑ s with b s = i, c s ≠ 0 := by omega
      obtain ⟨s, hs, hcs⟩ := Finset.exists_ne_zero_of_sum_ne_zero h0
      exact ⟨s, (Finset.mem_filter.mp hs).2, hcs⟩
    choose t ht hct using hex
    set c' : σ →₀ ℕ := ∑ i, Finsupp.single (t i) 1 with hc'
    have hc'le : c' ≤ c := by
      intro s
      rw [hc', Finsupp.coe_finsetSum, Finset.sum_apply]
      rw [Finset.sum_eq_single (b s)]
      · rw [Finsupp.single_apply]
        split_ifs with h
        · rw [← h]
          exact Nat.one_le_iff_ne_zero.mpr (hct _)
        · exact Nat.zero_le _
      · intro i _ hi
        rw [Finsupp.single_apply]
        exact ite_eq_right_iff.mpr fun h ↦ absurd (h ▸ ht i).symm hi
      · simp
    have hw' : Finsupp.weight (multiWeight b) c' = 1 := weight_sum_single_one ht
    have hsplit : c = c' + (c - c') := (add_tsub_cancel_of_le hc'le).symm
    have hw : ∀ i, n ≤ Finsupp.weight (multiWeight b) (c - c') i := by
      intro i
      have h := congrFun (congrArg (Finsupp.weight (multiWeight b)) hsplit) i
      rw [map_add, hw'] at h
      simp only [Pi.add_apply, Pi.one_apply] at h
      have := hc i
      omega
    rw [hsplit, ← mul_one (1 : R), ← monomial_mul_monomial, pow_succ']
    exact Ideal.mul_mem_mul (Ideal.subset_span ⟨c', mem_blockMonomials.mpr hw', rfl⟩) (ih hw)

variable (R b) in
/-- A monomial of multidegree `(n, …, n)` lies in `𝔪_ε ^ n`. -/
theorem monomial_mem_irrelevantIdeal_pow (n : ℕ) {c : σ →₀ ℕ}
    (hc : Finsupp.weight (multiWeight b) c = fun _ ↦ n) :
    monomial c (1 : R) ∈ irrelevantIdeal R b ^ n :=
  monomial_mem_irrelevantIdeal_pow_of_le R b n fun i ↦ (congrFun hc i).ge

variable (R b) in
/-- `𝔪_ε ^ n` is contained in the ideal generated by the monomials of multidegree
`(n, …, n)`. -/
theorem irrelevantIdeal_pow_le (n : ℕ) :
    irrelevantIdeal R b ^ n ≤ Ideal.span ((fun c ↦ monomial c (1 : R)) ''
      {c | Finsupp.weight (multiWeight b) c = fun _ ↦ n}) := by
  induction n with
  | zero =>
    rw [pow_zero, Ideal.one_eq_top, top_le_iff, Ideal.eq_top_iff_one]
    exact Ideal.subset_span ⟨0, by simp; rfl, rfl⟩
  | succ n ih =>
    rw [pow_succ, irrelevantIdeal]
    refine (Ideal.mul_mono_left ih).trans ?_
    rw [Ideal.span_mul_span]
    refine Ideal.span_mono ?_
    rintro _ ⟨_, ⟨a, ha, rfl⟩, _, ⟨c, hc, rfl⟩, rfl⟩
    refine ⟨a + c, ?_, by simp [monomial_mul_monomial]⟩
    simp only [Set.mem_ofPred_eq] at ha
    rw [Set.mem_ofPred_eq, map_add, ha, mem_blockMonomials.mp hc]
    rfl

/-- **The elimination theorem**, easy half (LNM 1752, Ch. 5, Thm 2.2, `2 ⟹ 1`): if the
specialization `ρ(I[d])` has a zero `z` with a nonzero coordinate in every block, then `ρ`
kills the eliminant ideal. -/
theorem elimIdeal_le_ker_of_eval_eq_zero {L : Type*} [CommRing L] [IsDomain L]
    {I : Ideal (MvPolynomial σ R)} (ρ : MvPolynomial (GenericVar b d) R →+* L) (z : σ → L)
    (hz : ∀ i, ∃ s, b s = i ∧ z s ≠ 0) (h : ∀ P ∈ genericIdeal R b d I, eval₂ ρ z P = 0) :
    elimIdeal R b d I ≤ RingHom.ker ρ := by
  intro f hf
  obtain ⟨n, hn⟩ := mem_elimIdeal.mp hf
  choose t ht hzt using hz
  have hmem : monomial (∑ i, Finsupp.single (t i) 1) 1 ∈
      irrelevantIdeal (MvPolynomial (GenericVar b d) R) b :=
    Ideal.subset_span ⟨_, mem_blockMonomials.mpr (weight_sum_single_one ht), rfl⟩
  have h0 := h _ (hn _ (Ideal.pow_mem_pow hmem n))
  rw [eval₂_mul, eval₂_pow, eval₂_C, monomial_sum_one] at h0
  have hprod : eval₂ ρ z (∏ i, monomial (Finsupp.single (t i) 1) 1) ≠ 0 := by
    rw [eval₂_prod]
    exact Finset.prod_ne_zero_iff.mpr fun i _ ↦ by simpa using hzt i
  exact (mul_eq_zero.mp h0).resolve_left (pow_ne_zero n hprod)

/-- **The elimination theorem** (LNM 1752, Ch. 5, Thm 2.2, `1 ⟹ 2`): if `ρ` into an
algebraically closed field kills the eliminant ideal of a multihomogeneous ideal `I`, then
`ρ(I[d])` has a zero with a nonzero coordinate in every block. The proof: otherwise the
Nullstellensatz puts a power of the irrelevant ideal into `ρ(I[d]) L[X]`, and the determinant
trick, in the multidegree of that power, gives an element of `𝔈_d(I)` not killed by `ρ`. -/
theorem exists_eval_eq_zero_of_elimIdeal_le_ker {L : Type*} [Field L] [IsAlgClosed L]
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsWeightedHomogeneous (multiWeight b))
    (ρ : MvPolynomial (GenericVar b d) R →+* L) (h : elimIdeal R b d I ≤ RingHom.ker ρ) :
    ∃ z : σ → L, (∀ i, ∃ s, b s = i ∧ z s ≠ 0) ∧
      ∀ P ∈ genericIdeal R b d I, eval₂ ρ z P = 0 := by
  classical
  by_contra hcon
  push Not at hcon
  set A := MvPolynomial (GenericVar b d) R
  set J : Ideal (MvPolynomial σ L) := (genericIdeal R b d I).map (MvPolynomial.map ρ) with hJ
  -- The Nullstellensatz: the irrelevant ideal is in the radical of `J`.
  have hrad : irrelevantIdeal L b ≤ J.radical := by
    rw [← vanishingIdeal_zeroLocus_eq_radical (K := L), irrelevantIdeal, Ideal.span_le]
    rintro _ ⟨c, hc, rfl⟩
    rw [SetLike.mem_coe, mem_vanishingIdeal_iff]
    intro x hx
    by_contra hne
    obtain ⟨P, hP, hPz⟩ := hcon x fun i ↦ by
      have h1 := congrFun (mem_blockMonomials.mp hc) i
      rw [weight_multiWeight_apply] at h1
      obtain ⟨s, hs, hcs⟩ := Finset.exists_ne_zero_of_sum_ne_zero (h1.trans_ne one_ne_zero)
      refine ⟨s, (Finset.mem_filter.mp hs).2, fun hxs ↦ hne ?_⟩
      rw [aeval_monomial, map_one, one_mul]
      exact Finset.prod_eq_zero (Finsupp.mem_support_iff.mpr hcs) (by simp [hxs, hcs])
    have := hx _ (Ideal.mem_map_of_mem (MvPolynomial.map ρ) hP)
    rw [aeval_def, eval₂_map, Algebra.algebraMap_self, RingHom.id_comp] at this
    exact hPz this
  obtain ⟨n, hn⟩ := Ideal.exists_pow_le_of_le_radical_of_fg hrad
    (⟨(blockMonomials b 1).image fun c ↦ monomial c 1, by simp [irrelevantIdeal]⟩)
  -- The multidegree `k = (n, …, n)` and the monomials of that multidegree.
  set k : ι → ℕ := fun _ ↦ n with hk
  set T := blockMonomials b k
  have hmonJ : ∀ c ∈ T, (monomial c 1 : MvPolynomial σ L) ∈ J := fun c hc ↦
    hn (monomial_mem_irrelevantIdeal_pow L b n (mem_blockMonomials.mp hc))
  -- Coefficient vectors.
  let cv : MvPolynomial σ A →ₗ[A] (T → A) := LinearMap.pi fun c ↦ lcoeff A (c : σ →₀ ℕ)
  let cvL : MvPolynomial σ L →ₗ[L] (T → L) := LinearMap.pi fun c ↦ lcoeff L (c : σ →₀ ℕ)
  let H : Submodule A (MvPolynomial σ A) :=
    (genericIdeal R b d I).restrictScalars A ⊓ weightedHomogeneousSubmodule A (multiWeight b) k
  have hspan : Submodule.span L ((fun v ↦ ρ ∘ v) '' (H.map cv : Set (T → A))) = ⊤ := by
    rw [eq_top_iff]
    rintro v -
    rw [pi_eq_sum_univ v]
    refine Submodule.sum_mem _ fun c _ ↦ Submodule.smul_mem _ _ ?_
    have hc : cvL (monomial c 1) = fun c' ↦ if c = c' then 1 else 0 := by
      funext c'
      change (monomial (c : σ →₀ ℕ) (1 : L)).coeff (c' : σ →₀ ℕ) = _
      rw [coeff_monomial]
      by_cases hcc : c = c'
      · simp [hcc]
      · simp [hcc, Subtype.coe_injective.ne hcc]
    rw [← hc]
    have hcomp := weightedHomogeneousComponent_mem_span_homogImage ρ _
      (isWeightedHomogeneous_genericIdeal hI) (hmonJ c c.2) k
    have hmh := isWeightedHomogeneous_monomial (multiWeight b) (c : σ →₀ ℕ) (1 : L)
      (mem_blockMonomials.mp c.2)
    rw [hmh.weightedHomogeneousComponent_same] at hcomp
    have := Submodule.mem_map_of_mem (f := cvL) hcomp
    rw [Submodule.map_span] at this
    refine Submodule.span_mono ?_ this
    rintro _ ⟨_, ⟨Q, ⟨hQ, hQk⟩, rfl⟩, rfl⟩
    refine ⟨cv Q, ⟨Q, ⟨hQ, hQk⟩, rfl⟩, ?_⟩
    funext c'
    simp [cv, cvL, coeff_map]
  obtain ⟨Δ, hΔ, hΔN⟩ := Submodule.exists_smul_single_mem_of_span_eq_top ρ _ hspan
  -- `Δ` times every monomial of multidegree `k` is in `I[d]`, so `Δ ∈ 𝔈_d(I)`.
  have hΔmon : ∀ c ∈ T, monomial c Δ ∈ genericIdeal R b d I := by
    intro c hc
    obtain ⟨Q, ⟨hQ, hQk⟩, hQc⟩ := hΔN ⟨c, hc⟩
    have hQhom : IsWeightedHomogeneous (multiWeight b) Q k := hQk
    have hQ' : Q ∈ genericIdeal R b d I := hQ
    have hQeq : Q = monomial c Δ := by
      refine MvPolynomial.ext _ _ fun c' ↦ ?_
      rw [coeff_monomial]
      by_cases hc' : Finsupp.weight (multiWeight b) c' = k
      · have := congrFun hQc ⟨c', mem_blockMonomials.mpr hc'⟩
        simp only [cv, LinearMap.pi_apply, lcoeff_apply, Pi.smul_apply, smul_eq_mul] at this
        rw [this]
        by_cases hcc : c = c'
        · subst hcc
          simp
        · simp [Subtype.ext_iff, hcc, Ne.symm hcc]
      · rw [hQhom.coeff_eq_zero c' hc']
        exact (ite_eq_right_iff.mpr fun (h : c = c') ↦
          absurd (h ▸ mem_blockMonomials.mp hc) hc').symm
    rwa [← hQeq]
  refine hΔ (h (mem_elimIdeal.mpr ⟨n, fun g hg ↦ ?_⟩))
  have hle := irrelevantIdeal_pow_le A b n hg
  refine (Ideal.span_le (I := (genericIdeal R b d I).colon {C Δ})).mpr ?_ hle |>
    Submodule.mem_colon_singleton.mp
  rintro _ ⟨c, hc, rfl⟩
  rw [SetLike.mem_coe, Submodule.mem_colon_singleton, smul_eq_mul, mul_comm, C_mul_monomial,
    mul_one]
  exact hΔmon c (mem_blockMonomials.mpr hc)

/-- **The elimination theorem** (LNM 1752, Ch. 5, Thm 2.2) over an algebraically closed field:
`ρ` kills `𝔈_d(I)` if and only if `ρ(I[d])` has a zero with a nonzero coordinate in every
block. -/
theorem elimIdeal_le_ker_iff {L : Type*} [Field L] [IsAlgClosed L]
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsWeightedHomogeneous (multiWeight b))
    (ρ : MvPolynomial (GenericVar b d) R →+* L) :
    elimIdeal R b d I ≤ RingHom.ker ρ ↔ ∃ z : σ → L, (∀ i, ∃ s, b s = i ∧ z s ≠ 0) ∧
      ∀ P ∈ genericIdeal R b d I, eval₂ ρ z P = 0 :=
  ⟨exists_eval_eq_zero_of_elimIdeal_le_ker hI ρ,
    fun ⟨z, hz, h⟩ ↦ elimIdeal_le_ker_of_eval_eq_zero ρ z hz h⟩

end Generic

section Subst

variable {σ ι : Type*} [Fintype σ] [Fintype ι] [DecidableEq ι]
variable {R : Type*} [CommRing R] {b : σ → ι} {κ : Type*} {d : κ → ι → ℕ}

variable (R b d) in
/-- The variables `s^{(l)}_{m, m'}` of Rémond's substitution. -/
abbrev PairVar : Type _ := Σ l : κ, blockMonomials b (d l) × blockMonomials b (d l)

variable (R b d) in
/-- Rémond's substitution on the coefficients: `u^{(l)}_m ↦ ∑_{m'} (s_{m,m'} - s_{m',m}) X^{m'}`,
the general form of multidegree `d l` vanishing at `X` (LNM 1752, Ch. 5, before Lemma 2.3). -/
noncomputable def substCoeff :
    MvPolynomial (GenericVar b d) R →+* MvPolynomial σ (MvPolynomial (PairVar b d) R) :=
  eval₂Hom (C.comp C) fun v ↦ ∑ m' : blockMonomials b (d v.1),
    monomial (m' : σ →₀ ℕ) (X ⟨v.1, v.2, m'⟩ - X ⟨v.1, m', v.2⟩)

variable (R b d) in
/-- Rémond's substitution `δ : B[d] → 𝔖B[d]`, the identity on `X`. -/
noncomputable def subst :
    MvPolynomial σ (MvPolynomial (GenericVar b d) R) →+*
      MvPolynomial σ (MvPolynomial (PairVar b d) R) :=
  eval₂Hom (substCoeff R b d) X

theorem subst_map_C (p : MvPolynomial σ R) :
    subst R b d (map C p) = map C p := by
  induction p using MvPolynomial.induction_on with
  | C a => simp [subst, substCoeff]
  | add p q hp hq => rw [map_add, map_add, hp, hq, map_add]
  | mul_X p s hp =>
    rw [map_mul (map C) p (X s), map_X, map_mul, hp, subst, eval₂Hom_X', map_mul, map_X]

theorem subst_genericForm (l : κ) : subst R b d (genericForm R b d l) = 0 := by
  simp only [subst, genericForm, map_sum, coe_eval₂Hom, eval₂_monomial, substCoeff,
    eval₂Hom_X', Finsupp.prod_pow]
  have : ∀ m : blockMonomials b (d l), (∏ s, (X s : MvPolynomial σ
      (MvPolynomial (PairVar b d) R)) ^ (m : σ →₀ ℕ) s) = monomial (m : σ →₀ ℕ) 1 := by
    intro m
    rw [monomial_eq, C_1, one_mul, Finsupp.prod_pow]
  simp only [this, Finset.sum_mul, monomial_mul_monomial, mul_one]
  simp only [map_sub, Finset.sum_sub_distrib]
  rw [sub_eq_zero]
  rw [Finset.sum_comm' (t' := Finset.univ) (s' := fun _ ↦ Finset.univ) (by simp)]
  exact Finset.sum_congr rfl fun _ _ ↦ Finset.sum_congr rfl fun _ _ ↦ by rw [add_comm]

theorem subst_monomial_one (c : σ →₀ ℕ) :
    subst R b d (monomial c 1) = monomial c 1 := by
  have : (monomial c 1 : MvPolynomial σ (MvPolynomial (GenericVar b d) R)) =
      map C (monomial c 1) := by
    rw [map_monomial, C_1]
  rw [this, subst_map_C, map_monomial, C_1]

theorem map_subst_genericIdeal_le (I : Ideal (MvPolynomial σ R)) :
    (genericIdeal R b d I).map (subst R b d) ≤ I.map (map C) := by
  rw [genericIdeal, Ideal.map_sup, sup_le_iff]
  constructor
  · rw [Ideal.map_map, show (subst R b d).comp (map C) = map C from RingHom.ext subst_map_C]
  · rw [Ideal.map_span, Ideal.span_le]
    rintro _ ⟨_, ⟨l, rfl⟩, rfl⟩
    rw [SetLike.mem_coe, subst_genericForm]
    exact Ideal.zero_mem _

omit [Fintype σ] in
/-- A monomial of multidegree `(1, …, 1)` is a product of one variable from each block. -/
theorem exists_eq_sum_single_of_weight_eq_one [Finite σ] {c : σ →₀ ℕ}
    (hc : Finsupp.weight (multiWeight b) c = 1) :
    ∃ t : ι → σ, (∀ i, b (t i) = i) ∧ c = ∑ i, Finsupp.single (t i) 1 := by
  classical
  have := Fintype.ofFinite σ
  have hblock : ∀ i, ∃ s, b s = i ∧ c s = 1 ∧ ∀ s', b s' = i → s' ≠ s → c s' = 0 := by
    intro i
    have h := congrFun hc i
    rw [weight_multiWeight_apply, Pi.one_apply] at h
    obtain ⟨s, hs, hcs⟩ := Finset.exists_ne_zero_of_sum_ne_zero (h.trans_ne one_ne_zero)
    have hs' := (Finset.mem_filter.mp hs).2
    have hle : ∀ s' ∈ ({t | b t = i} : Finset σ), c s' ≤ 1 := fun s' hs' ↦
      h ▸ Finset.single_le_sum (fun _ _ ↦ Nat.zero_le _) hs'
    refine ⟨s, hs', le_antisymm (hle s hs) (Nat.one_le_iff_ne_zero.mpr hcs), fun s' hbs' hne ↦ ?_⟩
    have h2 : c s + c s' ≤ ∑ t with b t = i, c t := by
      rw [← Finset.sum_pair (f := c) (Ne.symm hne)]
      exact Finset.sum_le_sum_of_subset (by
        intro x hx
        simp only [Finset.mem_insert, Finset.mem_singleton] at hx
        rcases hx with rfl | rfl <;> simp [hs', hbs'])
    omega
  choose t ht hct hzero using hblock
  refine ⟨t, ht, ?_⟩
  ext s
  rw [Finsupp.coe_finsetSum, Finset.sum_apply, Finset.sum_eq_single (b s)]
  · rw [Finsupp.single_apply]
    split_ifs with h
    · rw [← h, hct]
    · exact hzero _ s rfl (Ne.symm h)
  · intro i _ hi
    rw [Finsupp.single_apply]
    exact ite_eq_right_iff.mpr fun h ↦ absurd (h ▸ ht i).symm hi
  · simp

omit [Fintype σ] [DecidableEq ι] in
theorem monomial_sum_single_eq_prod {S : Type*} [CommSemiring S] (t : ι → σ) (e : ι → ℕ) :
    (monomial (∑ i, Finsupp.single (t i) (e i)) 1 : MvPolynomial σ S) = ∏ i, X (t i) ^ e i := by
  rw [monomial_sum_one]
  exact Finset.prod_congr rfl fun i _ ↦ (X_pow_eq_monomial).symm

/-- The key step of Lemma 2.3 (`2 ⟹ 1`): after inverting `x = ∏_i X_{t_i}`, Rémond's
substitution followed by `s^{(l)}_{m,m'} ↦ [m' = m₀] u_m / X^{m₀}` is the identity modulo
`I[d]`, so `x` is in the radical of `I[d] : f`. -/
private theorem prod_X_mem_radical_colon {I : Ideal (MvPolynomial σ R)}
    {f : MvPolynomial σ (MvPolynomial (GenericVar b d) R)} {n : ℕ}
    (hn : ∀ g ∈ irrelevantIdeal (MvPolynomial (PairVar b d) R) b ^ n,
      g * subst R b d f ∈ I.map (map C))
    {t : ι → σ} (ht : ∀ i, b (t i) = i) :
    (∏ i, X (t i) : MvPolynomial σ (MvPolynomial (GenericVar b d) R)) ∈
      ((genericIdeal R b d I).colon {f}).radical := by
  classical
  set x : MvPolynomial σ (MvPolynomial (GenericVar b d) R) := ∏ i, X (t i) with hx
  let Loc := Localization.Away x
  let φ := algebraMap (MvPolynomial σ (MvPolynomial (GenericVar b d) R)) Loc
  have hunit : ∀ i, IsUnit (φ (X (t i))) := by
    intro i
    have h : φ (X (t i) * ∏ j ∈ Finset.univ.erase i, X (t j)) = φ x :=
      congrArg φ (Finset.mul_prod_erase _ (fun j ↦ X (t j)) (Finset.mem_univ i))
    have hxu : IsUnit (φ (X (t i) * ∏ j ∈ Finset.univ.erase i, X (t j))) := by
      rw [h]
      exact IsLocalization.Away.algebraMap_isUnit x
    rw [map_mul] at hxu
    exact isUnit_of_mul_isUnit_left hxu
  let m₀ : κ → σ →₀ ℕ := fun l ↦ ∑ i, Finsupp.single (t i) (d l i)
  have hm₀ : ∀ l, m₀ l ∈ blockMonomials b (d l) := by
    intro l
    rw [mem_blockMonomials]
    change Finsupp.weight (multiWeight b) (∑ i, Finsupp.single (t i) (d l i)) = d l
    simp only [map_sum, Finsupp.weight_single, multiWeight, ht]
    funext j
    simp [Finset.sum_apply, Pi.single_apply]
  have hm₀unit : ∀ l, IsUnit (φ (monomial (m₀ l) 1)) := by
    intro l
    rw [monomial_sum_single_eq_prod, map_prod]
    exact IsUnit.prod_univ_iff.mpr fun i ↦ by rw [map_pow]; exact (hunit i).pow _
  let inv : κ → Loc := fun l ↦ ↑(hm₀unit l).unit⁻¹
  have hinv : ∀ l, inv l * φ (monomial (m₀ l) 1) = 1 := fun l ↦ (hm₀unit l).val_inv_mul
  let τ : MvPolynomial (PairVar b d) R →+* Loc := eval₂Hom (φ.comp (C.comp C)) fun v ↦
    if (v.2.2 : σ →₀ ℕ) = m₀ v.1 then φ (C (X ⟨v.1, v.2.1⟩)) * inv v.1 else 0
  let σt : MvPolynomial σ (MvPolynomial (PairVar b d) R) →+* Loc := eval₂Hom τ fun s ↦ φ (X s)
  let 𝔟 : Ideal Loc := (genericIdeal R b d I).map φ
  have hσX : ∀ s, σt (X s) = φ (X s) := fun s ↦ eval₂Hom_X' _ _ _
  have hσmon : ∀ c : σ →₀ ℕ, σt (monomial c 1) = φ (monomial c 1) := by
    intro c
    rw [monomial_eq, C_1, one_mul, monomial_eq, C_1, one_mul, Finsupp.prod, Finsupp.prod, map_prod,
      map_prod]
    exact Finset.prod_congr rfl fun s _ ↦ by rw [map_pow, map_pow, hσX]
  have hσC : ∀ p : MvPolynomial σ R, σt (map C p) = φ (map C p) := by
    intro p
    induction p using MvPolynomial.induction_on with
    | C a => simp [σt, τ, φ]
    | add p q hp hq => simp only [map_add, hp, hq]
    | mul_X p s hp => simp only [map_mul, hp, map_X, hσX]
  have hU : ∀ l, φ (genericForm R b d l) ∈ 𝔟 := fun l ↦
    Ideal.mem_map_of_mem _ (Ideal.mem_sup_right (Ideal.subset_span ⟨l, rfl⟩))
  -- On the generic coefficients the composite is the identity modulo `U_l`.
  have hcoeff : ∀ v : GenericVar b d, σt (substCoeff R b d (X v)) =
      φ (C (X v)) - if (v.2 : σ →₀ ℕ) = m₀ v.1 then inv v.1 * φ (genericForm R b d v.1)
        else 0 := by
    rintro ⟨l, m⟩
    simp only [substCoeff, eval₂Hom_X', map_sum]
    have hmon : ∀ (m' : blockMonomials b (d l)) (a : MvPolynomial (PairVar b d) R),
        σt (monomial (m' : σ →₀ ℕ) a) = τ a * φ (monomial (m' : σ →₀ ℕ) 1) := by
      intro m' a
      rw [← mul_one a, ← C_mul_monomial, map_mul, hσmon, mul_one]
      simp [σt]
    simp only [hmon, map_sub, Finset.sum_sub_distrib]
    simp only [τ, eval₂Hom_X']
    congr 1
    · rw [Finset.sum_eq_single ⟨m₀ l, hm₀ l⟩]
      · simp only [↓reduceIte]
        rw [mul_assoc, hinv, mul_one]
      · intro m' _ hm'
        simp only [show ¬((m' : σ →₀ ℕ) = m₀ l) from fun h ↦ hm' (Subtype.ext h), ↓reduceIte,
          zero_mul]
      · simp
    · split_ifs with hm
      · simp only [genericForm, map_sum, Finset.mul_sum]
        refine Finset.sum_congr rfl fun m' _ ↦ ?_
        rw [← mul_one (X _), ← C_mul_monomial, map_mul, C_1, mul_one, map_mul]
        ring
      · simp
  have key : ∀ g, σt (subst R b d g) - φ g ∈ 𝔟 := by
    intro g
    rw [← Ideal.Quotient.eq]
    change ((Ideal.Quotient.mk 𝔟).comp (σt.comp (subst R b d))) g =
      ((Ideal.Quotient.mk 𝔟).comp φ) g
    congr 1
    refine MvPolynomial.ringHom_ext (fun a ↦ ?_) fun s ↦ ?_
    · change ((Ideal.Quotient.mk 𝔟).comp ((σt.comp (subst R b d)).comp C)) a =
        ((Ideal.Quotient.mk 𝔟).comp (φ.comp C)) a
      congr 1
      refine MvPolynomial.ringHom_ext (fun c ↦ ?_) fun v ↦ ?_
      · simp [subst, substCoeff, σt, τ, φ]
      · simp only [RingHom.comp_apply, subst, eval₂Hom_C]
        rw [Ideal.Quotient.eq, hcoeff]
        split_ifs
        · rw [sub_sub_cancel_left]
          exact 𝔟.neg_mem (𝔟.mul_mem_left _ (hU _))
        · simp
    · simp [subst, hσX]
  have hxs : (∏ i, X (t i) : MvPolynomial σ (MvPolynomial (PairVar b d) R)) ^ n ∈
      irrelevantIdeal (MvPolynomial (PairVar b d) R) b ^ n :=
    by
    have hmem := monomial_mem_irrelevantIdeal (S := MvPolynomial (PairVar b d) R)
      (mem_blockMonomials.mpr (weight_sum_single_one ht))
    rw [monomial_sum_single_eq_prod t fun _ ↦ 1] at hmem
    simp only [pow_one] at hmem
    exact Ideal.pow_mem_pow hmem n
  have h2 : σt ((∏ i, X (t i)) ^ n * subst R b d f) ∈ 𝔟 := by
    have hle : (I.map (map C)).map σt ≤ 𝔟 := by
      rw [Ideal.map_le_iff_le_comap, Ideal.map_le_iff_le_comap]
      intro p hp
      rw [Ideal.mem_comap, Ideal.mem_comap, hσC]
      exact Ideal.mem_map_of_mem _ (Ideal.mem_sup_left (Ideal.mem_map_of_mem _ hp))
    exact hle (Ideal.mem_map_of_mem _ (hn _ hxs))
  rw [map_mul, map_pow, map_prod] at h2
  simp only [hσX] at h2
  have h3 : φ (x ^ n * f) ∈ 𝔟 := by
    have hx' : φ x = ∏ i, φ (X (t i)) := map_prod _ _ _
    have : φ (x ^ n * f) = (∏ i, φ (X (t i))) ^ n * σt (subst R b d f) -
        φ x ^ n * (σt (subst R b d f) - φ f) := by
      rw [map_mul, map_pow, hx']
      ring
    rw [this]
    exact 𝔟.sub_mem h2 (𝔟.mul_mem_left _ (key f))
  obtain ⟨m, ⟨k, rfl⟩, hmI⟩ :=
    (IsLocalization.algebraMap_mem_map_algebraMap_iff (Submonoid.powers x) Loc _ _).mp h3
  refine ⟨k + n, ?_⟩
  rw [Submodule.mem_colon_singleton, smul_eq_mul, pow_add, mul_assoc]
  exact hmI

/-- **Rémond's Lemma 2.3** (LNM 1752, Ch. 5): `f ∈ 𝔄_d(I)` if and only if `δ(f)` is in the
saturation of `I 𝔖B[d]` by the irrelevant ideal. -/
theorem mem_charIdeal_iff_subst {I : Ideal (MvPolynomial σ R)}
    {f : MvPolynomial σ (MvPolynomial (GenericVar b d) R)} :
    f ∈ charIdeal R b d I ↔ ∃ n, ∀ g ∈ irrelevantIdeal (MvPolynomial (PairVar b d) R) b ^ n,
      g * subst R b d f ∈ I.map (map C) := by
  constructor
  · rintro hf
    obtain ⟨n, hn⟩ := mem_charIdeal.mp hf
    refine ⟨n, fun g hg ↦ ?_⟩
    have hle := irrelevantIdeal_pow_le (MvPolynomial (PairVar b d) R) b n hg
    refine (Ideal.span_le (I := (I.map (map C)).colon {subst R b d f})).mpr ?_ hle |>
      Submodule.mem_colon_singleton.mp
    rintro _ ⟨c, hc, rfl⟩
    dsimp only
    rw [SetLike.mem_coe, Submodule.mem_colon_singleton, smul_eq_mul, ← subst_monomial_one,
      ← map_mul]
    exact map_subst_genericIdeal_le I (Ideal.mem_map_of_mem _
      (hn _ (monomial_mem_irrelevantIdeal_pow _ b n hc)))
  · rintro ⟨n, hn⟩
    have hrad : irrelevantIdeal (MvPolynomial (GenericVar b d) R) b ≤
        ((genericIdeal R b d I).colon {f}).radical := by
      rw [irrelevantIdeal, Ideal.span_le]
      rintro _ ⟨c, hc, rfl⟩
      obtain ⟨t, ht, rfl⟩ := exists_eq_sum_single_of_weight_eq_one (mem_blockMonomials.mp hc)
      dsimp only
      rw [SetLike.mem_coe, monomial_sum_single_eq_prod t fun _ ↦ 1]
      simp only [pow_one]
      exact prod_X_mem_radical_colon hn ht
    obtain ⟨N, hN⟩ := Ideal.exists_pow_le_of_le_radical_of_fg hrad (irrelevantIdeal_fg _)
    exact mem_charIdeal.mpr ⟨N, fun g hg ↦ by
      simpa [Submodule.mem_colon_singleton] using hN hg⟩

/-- **Rémond's Lemma 2.4 (2)** (LNM 1752, Ch. 5): for a prime `𝔭` not containing the irrelevant
ideal, `𝔄_d(𝔭)` is the prime `δ⁻¹(𝔭 𝔖B[d])`. -/
theorem charIdeal_eq_comap_subst {I : Ideal (MvPolynomial σ R)} [I.IsPrime]
    (hI : ¬irrelevantIdeal R b ≤ I) :
    charIdeal R b d I = (I.map (map C)).comap (subst R b d) := by
  have hP : (I.map (map (C : R →+* MvPolynomial (PairVar b d) R))).IsPrime := isPrime_map_map_C
  have hirr : ¬irrelevantIdeal (MvPolynomial (PairVar b d) R) b ≤ I.map (map C) := by
    intro h
    refine hI (Ideal.span_le.mpr ?_)
    rintro _ ⟨c, hc, rfl⟩
    have := h (monomial_mem_irrelevantIdeal hc)
    rw [← comap_map_C_map_map_C (P := PairVar b d) (I := I)]
    dsimp only
    rw [SetLike.mem_coe, Ideal.mem_comap, map_monomial, C_1]
    exact this
  ext f
  rw [mem_charIdeal_iff_subst, Ideal.mem_comap]
  constructor
  · rintro ⟨n, hn⟩
    have : ¬irrelevantIdeal (MvPolynomial (PairVar b d) R) b ^ n ≤ I.map (map C) :=
      fun h ↦ hirr (hP.le_of_pow_le h)
    obtain ⟨g, hg, hgI⟩ := Set.not_subset.mp this
    exact (hP.mem_or_mem (hn g hg)).resolve_left hgI
  · exact fun h ↦ ⟨0, fun g _ ↦ Ideal.mul_mem_left _ g h⟩

/-- **Rémond's Lemma 2.4 (2)**: `𝔄_d(𝔭)` is prime. -/
theorem isPrime_charIdeal {I : Ideal (MvPolynomial σ R)} [I.IsPrime]
    (hI : ¬irrelevantIdeal R b ≤ I) : (charIdeal R b d I).IsPrime := by
  have : (I.map (map (C : R →+* MvPolynomial (PairVar b d) R))).IsPrime := isPrime_map_map_C
  rw [charIdeal_eq_comap_subst hI]
  exact Ideal.comap_isPrime _ _

/-- **Rémond's Lemma 2.4 (2)**: `𝔈_d(𝔭)` is prime. -/
theorem isPrime_elimIdeal {I : Ideal (MvPolynomial σ R)} [I.IsPrime]
    (hI : ¬irrelevantIdeal R b ≤ I) : (elimIdeal R b d I).IsPrime := by
  have := isPrime_charIdeal (d := d) hI
  exact Ideal.comap_isPrime _ _

/-- **Rémond's Lemma 2.4 (2)**: `𝔄_d(𝔭) ∩ B = 𝔭`. -/
theorem comap_map_C_charIdeal {I : Ideal (MvPolynomial σ R)} [I.IsPrime]
    (hI : ¬irrelevantIdeal R b ≤ I) : (charIdeal R b d I).comap (map C) = I := by
  rw [charIdeal_eq_comap_subst hI, Ideal.comap_comap,
    show (subst R b d).comp (map C) = map C from RingHom.ext subst_map_C,
    comap_map_C_map_map_C]

/-- **Rémond's Lemma 2.4 (3)**: characteristic ideals commute with intersections. -/
theorem charIdeal_inf (I J : Ideal (MvPolynomial σ R)) :
    charIdeal R b d (I ⊓ J) = charIdeal R b d I ⊓ charIdeal R b d J := by
  ext f
  simp only [Submodule.mem_inf, mem_charIdeal_iff_subst, map_map_C_inf, Submodule.mem_inf]
  constructor
  · rintro ⟨n, hn⟩
    exact ⟨⟨n, fun g hg ↦ (hn g hg).1⟩, ⟨n, fun g hg ↦ (hn g hg).2⟩⟩
  · rintro ⟨⟨m, hm⟩, ⟨n, hn⟩⟩
    refine ⟨max m n, fun g hg ↦ ⟨hm g ?_, hn g ?_⟩⟩
    · exact Ideal.pow_le_pow_right (le_max_left m n) hg
    · exact Ideal.pow_le_pow_right (le_max_right m n) hg

/-- **Rémond's Lemma 2.4 (3)**: eliminant ideals commute with intersections. -/
theorem elimIdeal_inf (I J : Ideal (MvPolynomial σ R)) :
    elimIdeal R b d (I ⊓ J) = elimIdeal R b d I ⊓ elimIdeal R b d J := by
  rw [elimIdeal, charIdeal_inf, Ideal.comap_inf]
  rfl

end Subst

end MvPolynomial

end
