/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ForMathlib.RingTheory.MvPolynomial.Bezout
public import Mathlib.RingTheory.Ideal.AssociatedPrime.Basic
public import Mathlib.RingTheory.Ideal.Height

-- Used only inside proofs.
import Mathlib.GroupTheory.CosetCover
import Mathlib.RingTheory.Ideal.AssociatedPrime.Finiteness
import Mathlib.RingTheory.Ideal.AssociatedPrime.Localization
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.RegularLocalRing.Polynomial
import ForMathlib.RingTheory.RegularLocalRing.RegularSequence

/-!
# The excess Bézout inequality

Let `I ⊆ K[X]` be generated by multihomogeneous polynomials of one multidegree `e`, and let `𝔭` be
a multihomogeneous prime minimal over `I`, of height `t`. Then
`ℓ(K[X]_𝔭 / I_𝔭) · d_β(𝔭) ≤ ∑_{f : β + ∑ j, ε_{f j} = n} ∏ j, e (f j)` for `|β| ≥ |n| - t`: the
Bézout bound holds at each component of the expected codimension, however many equations cut out
`V(I)`. This is the degree part of G. Rémond, *Sur le théorème du produit*, J. Théor. Nombres
Bordeaux **13** (2001), Prop. 3.2, and Evertse's Lemma 4 at one component (J.-H. Evertse, Acta
Arith. **73** (1995), Lemmas 4 and 5).

With lengths as multiplicities the inequality needs `K[X]_𝔭` to be Cohen–Macaulay: in general,
`J = (x², xy)` and `g = y` give `ℓ = 2 > 1`. `K[X]_𝔭` is a regular local ring (Mathlib), so its
maximal ideal contains a regular sequence of length `ht 𝔭`
(`IsRegularLocalRing.exists_isRegular`), and this depth is what the proof uses.

The proof follows Philippon's scheme (see also LNM 1752, Ch. 11, Prop. 2.2):
* Choose `P_1, …, P_t` in the `K`-span of the generators so that `P_{k+1}` avoids the associated
  primes of `(P_1, …, P_k)_𝔭`; over an infinite field this is prime avoidance in a vector space
  (`MvPolynomial.exists_mem_span_forall_notMem`). Then `P_{k+1}` is a nonzerodivisor modulo
  `(P_1, …, P_k)_𝔭`, so `K[X]_𝔭/(P_1, …, P_k)_𝔭` keeps a regular sequence of length `t - k`
  (`IsLocalRing.exists_isRegular_quotient_sup`, by the Rees theorem). For `k < t` its maximal
  ideal is therefore not associated, so the associated primes do not contain `I`, and
  `(P_1, …, P_{k+1})_𝔭` has height `k + 1`.
* The contraction `J_k` of `(P_1, …, P_k)_𝔭` is multihomogeneous
  (`MvPolynomial.isWeightedHomogeneous_comap_map`, because associated primes of multihomogeneous
  quotients are multihomogeneous), `P_{k+1}` is a nonzerodivisor modulo `J_k`, and
  `J_{k+1} ⊇ J_k + (P_{k+1})`. Hence `d_β(J_{k+1}) ≤ ∑ i, e i · d_{β + ε_i}(J_k)`
  (`MvPolynomial.multidegree_le_of_le`), and the Bézout bound for `J_t` follows.
* `J_t` is `𝔭`-primary, so `d_β(J_t) = ℓ(K[X]_𝔭/(P)_𝔭) · d_β(𝔭)` by the associativity formula.
  Finally `(P) ⊆ I` makes `ℓ(K[X]_𝔭/I_𝔭)` smaller.

## Main statements

* `MvPolynomial.isWeightedHomogeneous_of_mem_associatedPrimes`: associated primes of multigraded
  quotients are multihomogeneous.
* `MvPolynomial.isWeightedHomogeneous_comap_map`: contractions of localized multihomogeneous ideals
  are multihomogeneous.
* `MvPolynomial.exists_localLength_mul_multidegree_le`: the Bézout bound for
  `ℓ(K[X]_𝔭/(P_1, …, P_t)_𝔭) · d_β(𝔭)`, with `P_j` in the span of the generators.
* `MvPolynomial.exists_localLength_span_mul_multidegree_le`: **the excess Bézout inequality**,
  for `ℓ(K[X]_𝔭/I_𝔭) · d_β(𝔭)`.
-/

@[expose] public section

open Finset

variable {σ ι K : Type*}

namespace MvPolynomial

variable [Field K] [DecidableEq ι] {b : σ → ι}

section Saturation

variable [Finite σ] [Finite ι]

/-- **Associated primes of multigraded quotients are multihomogeneous.** -/
theorem isWeightedHomogeneous_of_mem_associatedPrimes {J : Ideal (MvPolynomial σ K)}
    (hJ : J.IsWeightedHomogeneous (multiWeight b)) {Q : Ideal (MvPolynomial σ K)}
    (hQ : Q ∈ associatedPrimes (MvPolynomial σ K) (MvPolynomial σ K ⧸ J)) :
    Q.IsWeightedHomogeneous (multiWeight b) := by
  induction J using IsNoetherian.induction with
  | hgt J IH =>
  by_cases htop : J = ⊤
  · subst htop
    rw [associatedPrimes.eq_empty_of_subsingleton] at hQ
    exact hQ.elim
  obtain ⟨f, e, hf, -, hfJ, hprime⟩ :=
    exists_isPrime_colon hJ (isWeightedHomogeneous_top _) fun h ↦ htop (top_le_iff.mp h)
  rcases associatedPrimes.subset_union_of_exact (Ideal.colonMulMap_injective J f)
    (Ideal.exact_colonMulMap J f) hQ with h | h
  · rw [associatedPrimes.eq_singleton_of_isPrimary hprime.isPrimary, hprime.radical,
      Set.mem_singleton_iff] at h
    subst h
    exact hJ.colon hf
  · have hlt : J < J ⊔ Ideal.span {f} := lt_of_le_of_ne le_sup_left fun h ↦
      hfJ (h ▸ Ideal.mem_sup_right (Ideal.mem_span_singleton_self f))
    exact IH _ hlt
      (hJ.sup (isWeightedHomogeneous_span fun x hx ↦ ⟨e, (Set.mem_singleton_iff.mp hx) ▸ hf⟩)) h

variable (b) in
/-- The saturation of `L` by the multihomogeneous elements outside `𝔭`. -/
private def homSat (𝔭 : Ideal (MvPolynomial σ K)) [𝔭.IsPrime] (L : Ideal (MvPolynomial σ K)) :
    Ideal (MvPolynomial σ K) where
  carrier := {x | ∃ s e, IsWeightedHomogeneous (multiWeight b) s e ∧ s ∉ 𝔭 ∧ s * x ∈ L}
  add_mem' := by
    rintro x y ⟨s, e, hs, hs𝔭, hx⟩ ⟨s', e', hs', hs'𝔭, hy⟩
    refine ⟨s * s', e + e', hs.mul hs', fun h ↦ ?_, ?_⟩
    · rcases Ideal.IsPrime.mem_or_mem inferInstance h with h | h
      exacts [hs𝔭 h, hs'𝔭 h]
    · have : s * s' * (x + y) = s' * (s * x) + s * (s' * y) := by ring
      rw [this]
      exact L.add_mem (L.mul_mem_left _ hx) (L.mul_mem_left _ hy)
  zero_mem' := ⟨1, 0, isWeightedHomogeneous_one _ _, fun h ↦
    Ideal.IsPrime.ne_top inferInstance ((Ideal.eq_top_iff_one _).mpr h), by simp⟩
  smul_mem' := by
    rintro c x ⟨s, e, hs, hs𝔭, hx⟩
    refine ⟨s, e, hs, hs𝔭, ?_⟩
    rw [smul_eq_mul, mul_left_comm]
    exact L.mul_mem_left c hx

omit [Finite σ] [Finite ι] in
private theorem mem_homSat {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]
    {L : Ideal (MvPolynomial σ K)} {x : MvPolynomial σ K} :
    x ∈ homSat b 𝔭 L ↔
      ∃ s e, IsWeightedHomogeneous (multiWeight b) s e ∧ s ∉ 𝔭 ∧ s * x ∈ L :=
  Iff.rfl

/-- **Localized ideals of multihomogeneous ideals are multihomogeneous.** For a multihomogeneous
`L` and any prime `𝔭`, the contraction of `L K[X]_𝔭` to `K[X]` is multihomogeneous: it is the
saturation of `L` by the multihomogeneous elements outside `𝔭`, since the associated primes of a
multihomogeneous quotient are multihomogeneous. -/
theorem isWeightedHomogeneous_comap_map {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]
    {L : Ideal (MvPolynomial σ K)}
    (hL : L.IsWeightedHomogeneous (multiWeight b)) :
    ((L.map (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).comap
      (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).IsWeightedHomogeneous
        (multiWeight b) := by
  set J := homSat b 𝔭 L
  have hJ : J.IsWeightedHomogeneous (multiWeight b) := by
    rintro x ⟨s, e, hs, hs𝔭, hx⟩ d
    refine ⟨s, e, hs, hs𝔭, ?_⟩
    rw [mul_comm, ← hs.weightedHomogeneousComponent_add_mul]
    rw [mul_comm] at hx
    exact hL hx _
  have hsat : ∀ q e z, IsWeightedHomogeneous (multiWeight b) q e → q ∉ 𝔭 → q * z ∈ J →
      z ∈ J := by
    rintro q e z hq hq𝔭 ⟨s, e', hs, hs𝔭, hz⟩
    refine ⟨s * q, e' + e, hs.mul hq, fun h ↦ ?_, by rwa [mul_assoc]⟩
    rcases Ideal.IsPrime.mem_or_mem inferInstance h with h | h
    exacts [hs𝔭 h, hq𝔭 h]
  have hLJ : L ≤ J := fun x hx ↦ ⟨1, 0, isWeightedHomogeneous_one _ _, fun h ↦
    Ideal.IsPrime.ne_top inferInstance ((Ideal.eq_top_iff_one _).mpr h), by rwa [one_mul]⟩
  suffices h : (L.map (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).comap
      (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭)) = J by
    rw [h]
    exact hJ
  apply le_antisymm
  · intro x hx
    rw [Ideal.mem_comap, IsLocalization.algebraMap_mem_map_algebraMap_iff 𝔭.primeCompl] at hx
    obtain ⟨s, hs, hsx⟩ := hx
    by_contra hxJ
    have hx0 : (Submodule.Quotient.mk x : MvPolynomial σ K ⧸ J) ≠ 0 := by
      rwa [Ne, Submodule.Quotient.mk_eq_zero]
    obtain ⟨P, hP, hle⟩ := exists_le_isAssociatedPrime_of_isNoetherianRing (MvPolynomial σ K) _ hx0
    have hsP : s ∈ P := hle (by
      rw [Submodule.mem_colon_singleton, Submodule.mem_bot, ← Submodule.Quotient.mk_smul,
        Submodule.Quotient.mk_eq_zero, smul_eq_mul]
      exact hLJ hsx)
    obtain ⟨q, e, hq, hqP, hq𝔭⟩ := exists_isWeightedHomogeneous_mem_notMem (J := 𝔭)
      (isWeightedHomogeneous_of_mem_associatedPrimes hJ hP) fun h ↦ hs (h hsP)
    obtain ⟨hPprime, y, rfl⟩ := (isAssociatedPrime_iff (R := MvPolynomial σ K)).mp hP
    obtain ⟨z, rfl⟩ := Submodule.mkQ_surjective _ y
    rw [Submodule.mem_colon_singleton, Submodule.mem_bot, Submodule.mkQ_apply,
      ← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero, smul_eq_mul] at hqP
    have hz := hsat q e z hq hq𝔭 hqP
    apply hPprime.ne_top
    rw [Submodule.mkQ_apply, (Submodule.Quotient.mk_eq_zero _).mpr hz]
    exact Submodule.eq_top_iff'.mpr fun r ↦ by
      rw [Submodule.mem_colon_singleton, smul_zero]
      exact Submodule.zero_mem _
  · rintro x ⟨s, e, hs, hs𝔭, hx⟩
    rw [Ideal.mem_comap, IsLocalization.algebraMap_mem_map_algebraMap_iff 𝔭.primeCompl]
    exact ⟨s, hs𝔭, hx⟩

end Saturation

section Excess

/-- **Prime avoidance in a vector space.** Over an infinite field, if no ideal of a finite family
contains `R`, some element of the `K`-span of `R` lies in none of them. -/
theorem exists_mem_span_forall_notMem [Infinite K] {R : Set (MvPolynomial σ K)}
    {S : Set (Ideal (MvPolynomial σ K))} (hS : S.Finite) (h : ∀ Q ∈ S, ¬ R ⊆ Q) :
    ∃ v ∈ Submodule.span K R, ∀ Q ∈ S, v ∉ Q := by
  by_contra! H
  set V := Submodule.span K R
  have := hS.to_subtype
  let p : S → Subspace K V := fun Q ↦ (Q.1.restrictScalars K).comap V.subtype
  obtain ⟨Q, hQ⟩ := Subspace.exists_eq_top_of_iUnion_eq_univ (p := p) (by
    refine Set.eq_univ_of_forall fun v ↦ ?_
    obtain ⟨Q, hQS, hvQ⟩ := H v v.2
    exact Set.mem_iUnion.mpr ⟨⟨Q, hQS⟩, hvQ⟩)
  refine h Q.1 Q.2 fun r hr ↦ ?_
  have : (⟨r, Submodule.subset_span hr⟩ : V) ∈ p Q := hQ ▸ Submodule.mem_top
  exact this

variable [Finite σ] [Fintype ι] {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]

/-- The sequence of Evertse's Lemma 5: `P_1, …, P_k` in the `K`-span of the generators, of height
`k` at `𝔭`, whose localized ideals `J_k` satisfy the Bézout bound in dimension `|n| - k`. -/
private theorem exists_seq [Infinite K] (hb : Function.Surjective b)
    {e : ι → ℕ} {R : Set (MvPolynomial σ K)}
    (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r e)
    (h𝔭R : 𝔭 ∈ (Ideal.span R).minimalPrimes) {t : ℕ} (ht : 𝔭.height = t) :
    ∀ k ≤ t, ∃ P : Fin k → MvPolynomial σ K, (∀ j, P j ∈ Submodule.span K R) ∧
      ((Ideal.span (Set.range P)).map
        (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).height = k ∧
      (∃ rs : List (Localization.AtPrime 𝔭), rs.length + k = t ∧
        (∀ r ∈ rs, r ∈ IsLocalRing.maximalIdeal (Localization.AtPrime 𝔭)) ∧
        RingTheory.Sequence.IsRegular (Localization.AtPrime 𝔭 ⧸ (Ideal.span (Set.range P)).map
          (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))) rs) ∧
      (hilbertPoly b (((Ideal.span (Set.range P)).map
        (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).comap
          (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭)))).totalDegree ≤
        (bottomType b).degree - k ∧
      ∀ β : ι →₀ ℕ, (bottomType b).degree - k ≤ β.degree →
        multidegree b (((Ideal.span (Set.range P)).map
          (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).comap
            (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))) β ≤
          ∑ f : Fin k → ι, (∏ j, (e (f j) : ℚ)) *
            multidegree b (⊥ : Ideal (MvPolynomial σ K)) (β + ∑ j, Finsupp.single (f j) 1) := by
  set A := Localization.AtPrime 𝔭
  set φ := algebraMap (MvPolynomial σ K) A
  have hinj : Function.Injective φ :=
    IsLocalization.injective A 𝔭.primeCompl_le_nonZeroDivisors
  have hVhom : ∀ v ∈ Submodule.span K R, IsWeightedHomogeneous (multiWeight b) v e := by
    intro v hv
    have : Submodule.span K R ≤ weightedHomogeneousSubmodule K (multiWeight b) e :=
      Submodule.span_le.mpr fun r hr ↦ (mem_weightedHomogeneousSubmodule _ _ _ _).mpr (hR r hr)
    exact (mem_weightedHomogeneousSubmodule _ _ _ _).mp (this hv)
  have hVI : ∀ v ∈ Submodule.span K R, v ∈ Ideal.span R := by
    intro v hv
    have : Submodule.span K R ≤ (Ideal.span R).restrictScalars K :=
      Submodule.span_le.mpr fun r hr ↦ Ideal.subset_span hr
    exact this hv
  have hI𝔭 : Ideal.span R ≤ 𝔭 := h𝔭R.1.2
  have hmax : 𝔭.map φ = IsLocalRing.maximalIdeal A := Localization.AtPrime.map_eq_maximalIdeal
  have hcomax : (IsLocalRing.maximalIdeal A).comap φ = 𝔭 := Localization.AtPrime.under_maximalIdeal
  intro k
  induction k with
  | zero =>
    intro _
    refine ⟨Fin.elim0, fun j ↦ j.elim0, ?_, ?_, ?_, fun β _ ↦ ?_⟩
    · simp [Ideal.height_bot]
    · obtain ⟨rs, hlen, hmem, hrs⟩ := IsRegularLocalRing.exists_isRegular (R := A)
      refine ⟨rs, ?_, hmem, ?_⟩
      · have h1 := (isRegularLocalRing_iff A).mp inferInstance
        rw [IsLocalization.AtPrime.ringKrullDim_eq_height 𝔭 A, ht] at h1
        rw [hlen, add_zero]
        exact_mod_cast h1
      · rw [show (Ideal.span (Set.range (Fin.elim0 : Fin 0 → MvPolynomial σ K))).map φ = ⊥ by
          simp]
        exact (Submodule.quotEquivOfEqBot ⊥ rfl).isRegular_congr rs |>.mpr hrs
    · simp only [Set.range_eq_empty, Ideal.span_empty, Ideal.map_bot,
        Ideal.comap_bot_of_injective _ hinj, totalDegree_hilbertPoly_bot hb]
      omega
    · simp [Ideal.comap_bot_of_injective _ hinj]
  | succ k IH =>
  intro hk
  obtain ⟨P, hPV, hht, ⟨rs, hrslen, hrsmem, hrs⟩, hdeg, hbound⟩ := IH (by omega)
  set L := Ideal.span (Set.range P)
  set 𝔞 := L.map φ
  set J := 𝔞.comap φ
  have hL : L.IsWeightedHomogeneous (multiWeight b) :=
    isWeightedHomogeneous_span fun _ ⟨j, hj⟩ ↦ ⟨e, hj ▸ hVhom _ (hPV j)⟩
  have hJ : J.IsWeightedHomogeneous (multiWeight b) := isWeightedHomogeneous_comap_map hL
  have hL𝔭 : L ≤ 𝔭 :=
    (Ideal.span_le.mpr (Set.range_subset_iff.mpr fun j ↦ hVI _ (hPV j))).trans hI𝔭
  have h𝔞m : 𝔞 ≤ IsLocalRing.maximalIdeal A := hmax ▸ Ideal.map_mono hL𝔭
  have hJ𝔭 : J ≤ 𝔭 := hcomax ▸ Ideal.comap_mono h𝔞m
  have h𝔞span : 𝔞 = Ideal.span (Set.range (φ ∘ P)) := by
    rw [Set.range_comp, ← Ideal.map_span]
  set S := associatedPrimes A (A ⧸ 𝔞)
  have hzd : ∀ y : A, y ∉ ⋃ Q ∈ S, (Q : Set A) → IsSMulRegular (A ⧸ 𝔞) y := by
    intro y hy v w hvw
    rw [← sub_eq_zero]
    by_contra hne
    refine hy ?_
    rw [biUnion_associatedPrimes_eq_zero_divisors]
    exact ⟨v - w, hne, by simp only [smul_sub, hvw, sub_self]⟩
  -- The depth of `A / 𝔞` is positive, so the maximal ideal is not associated.
  have hmS : IsLocalRing.maximalIdeal A ∉ S := by
    intro hm
    obtain ⟨y, ys, rfl⟩ : ∃ y ys, rs = y :: ys :=
      List.exists_cons_of_length_pos (by omega)
    have hy := ((RingTheory.Sequence.isRegular_cons_iff _ _ _).mp hrs).1
    obtain ⟨v, hv, hyv⟩ : y ∈ {r : A | ∃ v : A ⧸ 𝔞, v ≠ 0 ∧ r • v = 0} := by
      rw [← biUnion_associatedPrimes_eq_zero_divisors]
      exact Set.mem_biUnion hm (hrsmem y List.mem_cons_self)
    exact hv (hy (show y • v = y • 0 by rw [hyv, smul_zero]))
  have havoid : ∀ Q ∈ (fun Q : Ideal A ↦ Q.comap φ) '' S, ¬ R ⊆ (Q : Set (MvPolynomial σ K)) := by
    rintro _ ⟨Q, hQ, rfl⟩ hRQ
    have := hQ.isPrime
    have hQ𝔭 : Q.comap φ ≤ 𝔭 :=
      (Ideal.comap_mono (IsLocalRing.le_maximalIdeal this.ne_top)).trans hcomax.le
    have heq : Q.comap φ = 𝔭 := le_antisymm hQ𝔭 (h𝔭R.2 ⟨inferInstance,
      Ideal.span_le.mpr hRQ⟩ hQ𝔭)
    have hQm : Q = IsLocalRing.maximalIdeal A := by
      rw [← IsLocalization.map_under 𝔭.primeCompl A Q]
      change (Q.comap φ).map φ = _
      rw [heq, hmax]
    exact hmS (hQm ▸ hQ)
  obtain ⟨p, hpV, hpQ⟩ := exists_mem_span_forall_notMem
    ((associatedPrimes.finite A (A ⧸ 𝔞)).image _) havoid
  have hpS : ∀ Q ∈ S, φ p ∉ Q := fun Q hQ h ↦ hpQ _ ⟨Q, hQ, rfl⟩ h
  have hp : IsWeightedHomogeneous (multiWeight b) p e := hVhom p hpV
  have hcol : J.colon {p} = J := by
    refine le_antisymm (fun y hy ↦ ?_) (le_colon_singleton J p)
    rw [Submodule.mem_colon_singleton, smul_eq_mul, Ideal.mem_comap, map_mul] at hy
    rw [Ideal.mem_comap]
    by_contra hy'
    have hx : (Submodule.Quotient.mk (φ y) : A ⧸ 𝔞) ≠ 0 := by
      rwa [Ne, Submodule.Quotient.mk_eq_zero]
    have hmem : φ p ∈ ⋃ Q ∈ S, (Q : Set A) := by
      rw [biUnion_associatedPrimes_eq_zero_divisors]
      refine ⟨_, hx, ?_⟩
      rw [← Submodule.Quotient.mk_smul, smul_eq_mul, mul_comm, Submodule.Quotient.mk_eq_zero]
      exact hy
    obtain ⟨Q, hQ, hpQ'⟩ := Set.mem_iUnion₂.mp hmem
    exact hpS Q hQ hpQ'
  have hp0 : p ≠ 0 := by
    rintro rfl
    apply Ideal.IsPrime.ne_top (inferInstance : 𝔭.IsPrime)
    rw [eq_top_iff]
    refine le_trans ?_ hJ𝔭
    rw [← hcol]
    intro x _
    rw [Submodule.mem_colon_singleton, smul_zero]
    exact J.zero_mem
  set P' : Fin (k + 1) → MvPolynomial σ K := Fin.cons p P
  set L' := Ideal.span (Set.range P')
  set 𝔞' := L'.map φ
  set J' := 𝔞'.comap φ
  have hLL' : L' = Ideal.span {p} ⊔ L := by
    rw [← Ideal.span_insert]
    exact congrArg Ideal.span (Fin.range_cons p P)
  have hpL' : p ∈ L' := by
    rw [hLL']
    exact Ideal.mem_sup_left (Ideal.mem_span_singleton_self p)
  have hLL'le : L ≤ L' := by
    rw [hLL']
    exact le_sup_right
  have hL' : L'.IsWeightedHomogeneous (multiWeight b) :=
    isWeightedHomogeneous_span fun _ ⟨j, hj⟩ ↦ ⟨e, hj ▸ hVhom _ (by
      refine Fin.cases hpV (fun j ↦ ?_) j
      exact hPV j)⟩
  have hJ' : J'.IsWeightedHomogeneous (multiWeight b) := isWeightedHomogeneous_comap_map hL'
  have hJp : (J ⊔ Ideal.span {p}).IsWeightedHomogeneous (multiWeight b) :=
    hJ.sup (isWeightedHomogeneous_span fun x hx ↦ ⟨e, (Set.mem_singleton_iff.mp hx) ▸ hp⟩)
  have hJJ' : J ⊔ Ideal.span {p} ≤ J' := by
    refine sup_le (Ideal.comap_mono (Ideal.map_mono hLL'le)) ?_
    rw [Ideal.span_le, Set.singleton_subset_iff]
    exact Ideal.le_comap_map hpL'
  have h1 := totalDegree_hilbertPoly_sup_span_singleton_le_of_colon_eq hb hJ hp hp0 hcol
  have h2 := totalDegree_hilbertPoly_le_of_le hb hJp hJ' hJJ'
  have hPV' : ∀ j, P' j ∈ Submodule.span K R := fun j ↦ Fin.cases hpV (fun j ↦ hPV j) j
  refine ⟨P', hPV', ?_, ?_, h2.trans (h1.trans (by omega)), fun β hβ ↦ ?_⟩
  · have h𝔞'span : 𝔞' = Ideal.span (Set.range (φ ∘ P')) := by
      rw [Set.range_comp, ← Ideal.map_span]
    have hL'𝔭 : L' ≤ 𝔭 :=
      (Ideal.span_le.mpr (Set.range_subset_iff.mpr fun j ↦ hVI _ (hPV' j))).trans hI𝔭
    have h𝔞'm : 𝔞' ≤ IsLocalRing.maximalIdeal A := hmax ▸ Ideal.map_mono hL'𝔭
    have h𝔞'top : 𝔞' ≠ ⊤ := ne_top_of_le_ne_top (IsLocalRing.maximalIdeal.isMaximal A).ne_top h𝔞'm
    refine le_antisymm ?_ ?_
    · classical
      have hs : ((univ.image (φ ∘ P') : Finset A) : Set A) = Set.range (φ ∘ P') := by
        rw [coe_image, coe_univ, Set.image_univ]
      have := Ideal.height_span_le_card_of_span_ne_top (s := univ.image (φ ∘ P'))
        (by rw [hs, ← h𝔞'span]; exact h𝔞'top)
      rw [hs, ← h𝔞'span] at this
      refine this.trans ?_
      have hc : (univ.image (φ ∘ P')).card ≤ k + 1 :=
        card_image_le.trans (by simp)
      exact_mod_cast hc
    · rw [Ideal.height_eq_inf_minimalPrimes]
      refine le_iInf₂ fun Q' hQ' ↦ ?_
      have := hQ'.1.1
      have h𝔞Q' : 𝔞 ≤ Q' :=
        (Ideal.map_mono hLL'le).trans hQ'.1.2
      obtain ⟨Q, hQ, hQQ'⟩ := Ideal.exists_minimalPrimes_le h𝔞Q'
      have := hQ.1.1
      have hQS : Q ∈ S :=
        Module.associatedPrimes.minimalPrimes_annihilator_subset_associatedPrimes A (A ⧸ 𝔞)
        (by rwa [Ideal.annihilator_quotient])
      have hpQ' : φ p ∈ Q' := hQ'.1.2 (Ideal.mem_map_of_mem φ hpL')
      have hlt : Q < Q' := lt_of_le_of_ne hQQ' fun h ↦ hpS Q hQS (h ▸ hpQ')
      have := Ideal.height_add_one_le_of_lt_of_isPrime hlt
      have hQk : (k : ℕ∞) ≤ Q.height := hht ▸ Ideal.height_mono hQ.1.2
      exact_mod_cast (by gcongr : (k : ℕ∞) + 1 ≤ Q.height + 1).trans this
  · have h𝔞' : 𝔞' = 𝔞 ⊔ Ideal.span {φ p} := by
      change L'.map φ = _
      rw [hLL', Ideal.map_sup, Ideal.map_span, Set.image_singleton, sup_comm]
    have hpm : φ p ∈ IsLocalRing.maximalIdeal A :=
      hmax ▸ Ideal.mem_map_of_mem φ (hI𝔭 (hVI p hpV))
    have hpreg : IsSMulRegular (A ⧸ 𝔞) (φ p) := hzd _ fun h ↦ by
      obtain ⟨Q, hQ, hpQ⟩ := Set.mem_iUnion₂.mp h
      exact hpS Q hQ hpQ
    obtain ⟨rs', hlen', hmem', hrs'⟩ := IsLocalRing.exists_isRegular_quotient_sup 𝔞
      (n := rs.length - 1) (by omega) hrsmem hrs hpm hpreg
    refine ⟨rs', by omega, hmem', ?_⟩
    change RingTheory.Sequence.IsRegular (A ⧸ 𝔞') rs'
    rw [h𝔞']
    exact hrs'
  · calc multidegree b J' β ≤ multidegree b (J ⊔ Ideal.span {p}) β :=
          multidegree_le_of_le hb hJp hJ' hJJ' (by omega)
      _ = ∑ i, (e i : ℚ) * multidegree b J (β + Finsupp.single i 1) :=
          multidegree_sup_span_singleton_of_colon_eq hb hJ hp hp0 hcol (by omega)
      _ ≤ ∑ i, (e i : ℚ) * ∑ f : Fin k → ι, (∏ j, (e (f j) : ℚ)) *
            multidegree b ⊥ (β + Finsupp.single i 1 + ∑ j, Finsupp.single (f j) 1) := by
          refine sum_le_sum fun i _ ↦ mul_le_mul_of_nonneg_left (hbound _ ?_) (Nat.cast_nonneg _)
          rw [map_add, Finsupp.degree_single]
          omega
      _ = ∑ f : Fin (k + 1) → ι, (∏ j, (e (f j) : ℚ)) *
            multidegree b ⊥ (β + ∑ j, Finsupp.single (f j) 1) := by
          simp_rw [Finset.mul_sum]
          rw [← (Fin.consEquiv fun _ : Fin (k + 1) ↦ ι).sum_comp, Fintype.sum_prod_type]
          refine sum_congr rfl fun i _ ↦ sum_congr rfl fun f _ ↦ ?_
          simp only [Fin.consEquiv_apply, Fin.prod_univ_succ, Fin.sum_univ_succ, Fin.cons_zero,
            Fin.cons_succ]
          rw [add_assoc β]
          ring

/-- **The excess Bézout inequality** (Rémond 2001, Prop. 3.2, degree part; Evertse 1995, Lemmas 4
and 5). Let `I` be generated by a set `R` of multihomogeneous polynomials of multidegree `e`, and
let `𝔭` be a multihomogeneous prime of positive-dimensional type (`H_𝔭 ≠ 0`), minimal over `I`,
of height `t`. Then there are `P_1, …, P_t` in the `K`-span of `R` such that `dim 𝔭 ≤ |n| - t`
and, in every degree `|β| ≥ |n| - t`,
`ℓ(K[X]_𝔭/(P_1, …, P_t)_𝔭) · d_β(𝔭) ≤ ∑_{f : β + ∑ j, ε_{f j} = n} ∏ j, e (f j)`.

The proof follows Philippon's scheme: `P_{k+1}` avoids the associated primes of
`(P_1, …, P_k)_𝔭`, none of which is maximal for `k < t` because `K[X]_𝔭` has depth `t` (it is
regular local), so it is a nonzerodivisor on the contraction `J_k` of `(P_1, …, P_k)_𝔭`, and
`J_{k+1} ⊇ J_k + (P_{k+1})`. The degrees along the chain obey the Bézout bound, and `J_t` is
`𝔭`-primary, so its degree is `ℓ_𝔭 · d_β(𝔭)` by the associativity formula. -/
theorem exists_localLength_mul_multidegree_le [Infinite K] (hb : Function.Surjective b)
    {e : ι → ℕ} {R : Set (MvPolynomial σ K)}
    (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r e)
    (h𝔭R : 𝔭 ∈ (Ideal.span R).minimalPrimes) (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} (ht : 𝔭.height = t) :
    ∃ P : Fin t → MvPolynomial σ K, (∀ j, P j ∈ Submodule.span K R) ∧
      ∃ ℓ : ℕ, Ideal.localLength 𝔭 (Ideal.span (Set.range P)) = ℓ ∧
        (hilbertPoly b 𝔭).totalDegree ≤ (bottomType b).degree - t ∧
        ∀ β : ι →₀ ℕ, (bottomType b).degree - t ≤ β.degree →
          ℓ * multidegree b 𝔭 β ≤
            ∑ f : Fin t → ι with β + ∑ j, Finsupp.single (f j) 1 = bottomType b,
              ∏ j, (e (f j) : ℚ) := by
  classical
  obtain ⟨P, hPV, hht, -, hdeg, hbound⟩ := exists_seq hb hR h𝔭R ht t le_rfl
  set A := Localization.AtPrime 𝔭
  set φ := algebraMap (MvPolynomial σ K) A
  set L := Ideal.span (Set.range P)
  set 𝔞 := L.map φ
  set J := 𝔞.comap φ
  have hVhom : ∀ v ∈ Submodule.span K R, IsWeightedHomogeneous (multiWeight b) v e := by
    intro v hv
    have : Submodule.span K R ≤ weightedHomogeneousSubmodule K (multiWeight b) e :=
      Submodule.span_le.mpr fun r hr ↦ (mem_weightedHomogeneousSubmodule _ _ _ _).mpr (hR r hr)
    exact (mem_weightedHomogeneousSubmodule _ _ _ _).mp (this hv)
  have hVI : ∀ v ∈ Submodule.span K R, v ∈ Ideal.span R := by
    intro v hv
    have : Submodule.span K R ≤ (Ideal.span R).restrictScalars K :=
      Submodule.span_le.mpr fun r hr ↦ Ideal.subset_span hr
    exact this hv
  have hcomax : (IsLocalRing.maximalIdeal A).comap φ = 𝔭 := Localization.AtPrime.under_maximalIdeal
  have hmax : 𝔭.map φ = IsLocalRing.maximalIdeal A := Localization.AtPrime.map_eq_maximalIdeal
  have hL : L.IsWeightedHomogeneous (multiWeight b) :=
    isWeightedHomogeneous_span fun _ ⟨j, hj⟩ ↦ ⟨e, hj ▸ hVhom _ (hPV j)⟩
  have hJ : J.IsWeightedHomogeneous (multiWeight b) := isWeightedHomogeneous_comap_map hL
  have hL𝔭 : L ≤ 𝔭 :=
    (Ideal.span_le.mpr (Set.range_subset_iff.mpr fun j ↦ hVI _ (hPV j))).trans h𝔭R.1.2
  have hJ𝔭 : J ≤ 𝔭 := (Ideal.comap_mono (hmax ▸ Ideal.map_mono hL𝔭)).trans hcomax.le
  -- `J` is `𝔭`-primary: every minimal prime of `𝔞` lies over `𝔭`.
  have hmin : ∀ Q' ∈ 𝔞.minimalPrimes, Q'.comap φ = 𝔭 := by
    intro Q' hQ'
    have := hQ'.1.1
    have hle : Q'.comap φ ≤ 𝔭 :=
      (Ideal.comap_mono (IsLocalRing.le_maximalIdeal this.ne_top)).trans hcomax.le
    refine (Ideal.comap φ Q').eq_of_le_of_height_le hle ?_
    have h1 := IsLocalization.height_under 𝔭.primeCompl Q'
    rw [Ideal.under] at h1
    rw [h1, ht, ← hht, Ideal.height_eq_inf_minimalPrimes 𝔞]
    exact iInf₂_le Q' hQ'
  have hrad : ∀ x ∈ 𝔭, ∃ n : ℕ, x ^ n ∈ J := by
    intro x hx
    have : φ x ∈ 𝔞.radical := by
      rw [← Ideal.sInf_minimalPrimes, Submodule.mem_sInf]
      intro Q' hQ'
      have : x ∈ Ideal.comap φ Q' := (hmin Q' hQ').symm ▸ hx
      exact this
    obtain ⟨n, hn⟩ := (Ideal.mem_radical_iff).mp this
    exact ⟨n, by rw [Ideal.mem_comap, map_pow]; exact hn⟩
  have hprimes : ∀ 𝔮 : Ideal (MvPolynomial σ K), 𝔮.IsPrime → J ≤ 𝔮 → 𝔭 ≤ 𝔮 := by
    intro 𝔮 h𝔮 hJ𝔮 x hx
    obtain ⟨n, hn⟩ := hrad x hx
    exact h𝔮.mem_of_pow_mem n (hJ𝔮 hn)
  have hD := totalDegree_hilbertPoly_le_of_le hb hJ h𝔭 hJ𝔭
  obtain ⟨Pr, ℓ, hPr, hℓ, hsum⟩ := multidegree_eq_sum_localLength hb hJ
  have hPr𝔭 : ∀ 𝔮 ∈ Pr, 𝔮 = 𝔭 := by
    intro 𝔮 h𝔮
    obtain ⟨h𝔮p, h𝔮h, hJ𝔮, h𝔮0, h𝔮d⟩ := (hPr 𝔮).mp h𝔮
    have h𝔭𝔮 := hprimes 𝔮 h𝔮p hJ𝔮
    by_contra hne𝔮
    have := totalDegree_hilbertPoly_lt_of_lt hb h𝔭 h𝔮h (lt_of_le_of_ne h𝔭𝔮 (Ne.symm hne𝔮)) h𝔮0
    omega
  have hmem : 𝔭 ∈ Pr := by
    refine (hPr 𝔭).mpr ⟨inferInstance, h𝔭, hJ𝔭, hne, le_antisymm hD ?_⟩
    by_contra hlt
    have hempty : Pr = ∅ := Finset.eq_empty_of_forall_notMem fun 𝔮 h𝔮 ↦ by
      obtain ⟨-, -, -, -, h𝔮d⟩ := (hPr 𝔮).mp h𝔮
      rw [hPr𝔭 𝔮 h𝔮] at h𝔮d
      omega
    obtain ⟨α, hα, hαdeg⟩ :=
      exists_coeff_ne_zero_degree_eq (hilbertPoly_ne_zero_of_le hb hJ h𝔭 hJ𝔭 hne)
    have := hsum α hαdeg.ge
    rw [hempty, sum_empty, multidegree] at this
    exact hα ((mul_eq_zero.mp this).resolve_left
      (Finset.prod_ne_zero_iff.mpr fun i _ ↦ Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero _)))
  have hPr1 : Pr = {𝔭} := Finset.eq_singleton_iff_unique_mem.mpr ⟨hmem, hPr𝔭⟩
  have hlen : Ideal.localLength 𝔭 L = ℓ 𝔭 := by
    rw [← hℓ 𝔭 hmem]
    unfold Ideal.localLength
    rw [IsLocalization.map_under 𝔭.primeCompl]
  refine ⟨P, hPV, ℓ 𝔭, hlen, hD.trans hdeg, fun β hβ ↦ ?_⟩
  have h1 := hsum β (by omega)
  rw [hPr1, sum_singleton] at h1
  rw [← h1]
  refine (hbound β hβ).trans_eq ?_
  rw [Finset.sum_filter]
  refine sum_congr rfl fun f _ ↦ ?_
  have hdeg' : (bottomType b).degree ≤ (β + ∑ j, Finsupp.single (f j) 1).degree := by
    rw [map_add, map_sum]
    simp only [Finsupp.degree_single, sum_const, card_univ, Fintype.card_fin, smul_eq_mul,
      mul_one]
    omega
  rw [multidegree_bot hb hdeg']
  split_ifs <;> simp

/-- **Evertse's Lemma 4 at one component.** Under the hypotheses of
`MvPolynomial.exists_localLength_mul_multidegree_le`, the length `ℓ(K[X]_𝔭/I_𝔭)` itself is finite
and `ℓ(K[X]_𝔭/I_𝔭) · d_β(𝔭)` is at most the Bézout number, for every `|β| ≥ |n| - t`. -/
theorem exists_localLength_span_mul_multidegree_le [Infinite K] (hb : Function.Surjective b)
    {e : ι → ℕ} {R : Set (MvPolynomial σ K)}
    (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r e)
    (h𝔭R : 𝔭 ∈ (Ideal.span R).minimalPrimes) (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} (ht : 𝔭.height = t) :
    ∃ m : ℕ, Ideal.localLength 𝔭 (Ideal.span R) = m ∧
      (hilbertPoly b 𝔭).totalDegree ≤ (bottomType b).degree - t ∧
      ∀ β : ι →₀ ℕ, (bottomType b).degree - t ≤ β.degree →
        m * multidegree b 𝔭 β ≤
          ∑ f : Fin t → ι with β + ∑ j, Finsupp.single (f j) 1 = bottomType b,
            ∏ j, (e (f j) : ℚ) := by
  obtain ⟨P, hPV, ℓ, hℓ, hdeg, h⟩ := exists_localLength_mul_multidegree_le hb hR h𝔭R h𝔭 hne ht
  have hle : Ideal.localLength 𝔭 (Ideal.span R) ≤ ℓ := by
    rw [← hℓ]
    refine Ideal.localLength_le_of_le (Ideal.span_le.mpr (Set.range_subset_iff.mpr fun j ↦ ?_))
    have : Submodule.span K R ≤ (Ideal.span R).restrictScalars K :=
      Submodule.span_le.mpr fun r hr ↦ Ideal.subset_span hr
    exact this (hPV j)
  obtain ⟨m, hm⟩ := ENat.ne_top_iff_exists.mp (ne_top_of_le_ne_top (ENat.natCast_ne_top ℓ) hle)
  refine ⟨m, hm.symm, hdeg, fun β hβ ↦ (mul_le_mul_of_nonneg_right ?_ ?_).trans (h β hβ)⟩
  · rw [← hm] at hle
    exact_mod_cast hle
  · exact mul_nonneg (Finset.prod_nonneg fun _ _ ↦ Nat.cast_nonneg _)
      (coeff_hilbertPoly_nonneg hb h𝔭 (hdeg.trans hβ))

end Excess

end MvPolynomial
