/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ForMathlib.RingTheory.MvPolynomial.Multigraded
public import Mathlib.RingTheory.Polynomial.Pochhammer
public import Mathlib.Algebra.MvPolynomial.Polynomial

-- Used only inside proofs.
import Mathlib.Algebra.Order.Sub.Prod
import Mathlib.Combinatorics.Nullstellensatz
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.Data.Finsupp.MonomialOrder
import Mathlib.Order.WellQuasiOrder
import Mathlib.Data.Finsupp.PWO

/-!
# The multigraded Hilbert–Samuel theorem

Let `K[X]` be graded by blocks of variables `b : σ → ι`, every block nonempty, as the coordinate
ring of a product of projective spaces. For every multihomogeneous ideal `I` the Hilbert function
`d ↦ dim_K (K[X]/I)_d` agrees with a polynomial in `d` for `d` large in every coordinate
(`MvPolynomial.exists_hilbertPolynomial`). This is van der Waerden's theorem (1928), the
foundation of the theory of multiprojective degrees; see G. Rémond, *Élimination multihomogène*,
Chapter 5 of Nesterenko–Philippon (eds.), *Introduction to algebraic independence theory*,
LNM 1752 (2001), Theorem 2.10.

The proof here is combinatorial rather than Rémond's induction over prime filtrations. By
`MvPolynomial.hilbertFunction_eq_card_filter` the Hilbert function counts the monomials of
multidegree `d` outside the upper set of leading monomials of `I`. By Dickson's lemma that upper
set is generated by finitely many monomials `G`. Removing one generator `g` changes the count by
the count for the translate `(G - g)` in multidegree `d - deg g`, which gives polynomiality by
induction on `#G`. The monomials themselves are counted by
`∏ i, C(d i + N_i - 1, N_i - 1)`, a polynomial in `d`.

## Main statements

* `MvPolynomial.eval_blockCountPoly`: the number of monomials of multidegree `d` is a polynomial
  in `d`.
* `MvPolynomial.exists_card_filter_forall_not_le`: the number of monomials of multidegree `d`
  above none of the finitely many monomials `G` is a polynomial in `d`, for `d` large.
* `MvPolynomial.exists_hilbertPolynomial`: the multigraded Hilbert function of a multihomogeneous
  ideal is a polynomial for `d` large.
* `MvPolynomial.hilbertPoly_eq_of_forall_le`: that polynomial, `MvPolynomial.hilbertPoly`, is
  unique.
* `MvPolynomial.hilbertPoly_bot`: the Hilbert polynomial of the whole space is
  `∏ i, C(T_i + n_i, n_i)`.
* `MvPolynomial.hilbertPoly_sup_span_singleton`: `H_{J + (g)}(T) = H_J(T) - H_{(J : g)}(T - e)`,
  `MvPolynomial.hilbertPoly_sup_span_singleton_of_colon_eq` its case `(J : g) = J`, and
  `MvPolynomial.hilbertPoly_sup_span_singleton_of_isPrime` its case `J` prime, `g ∉ J`.
-/

@[expose] public section

open Finset

variable {σ ι K : Type*}

namespace MvPolynomial

section Shift

/-- The translate `P(T - a)` of a polynomial in the variables `T_i`. -/
noncomputable def shiftPoly (a : ι → ℕ) (P : MvPolynomial ι ℚ) : MvPolynomial ι ℚ :=
  aeval (fun i ↦ X i - C (a i : ℚ)) P

theorem eval_shiftPoly (a : ι → ℕ) (P : MvPolynomial ι ℚ) (x : ι → ℚ) :
    eval x (shiftPoly a P) = eval (fun i ↦ x i - a i) P := by
  have := congrArg (fun φ ↦ φ P) (comp_aeval (R := ℚ) (fun i ↦ X i - C (a i : ℚ)) (aeval x))
  simp only [AlgHom.comp_apply] at this
  simpa [shiftPoly] using this

end Shift

theorem weight_mono {M : Type*} {w : σ → M → ℕ} {g c : σ →₀ ℕ} (h : g ≤ c) :
    Finsupp.weight w g ≤ Finsupp.weight w c := by
  obtain ⟨k, rfl⟩ := le_iff_exists_add.mp h
  rw [map_add]
  exact le_self_add

section Count

/-- The polynomial `C(T_i + n, n) = (T_i + 1) ⋯ (T_i + n) / n!` in the variable `T_i`. -/
noncomputable def binomPoly (n : ℕ) (i : ι) : MvPolynomial ι ℚ :=
  C ((n.factorial : ℚ)⁻¹) * Polynomial.aeval (X i + 1) (ascPochhammer ℚ n)

theorem eval_binomPoly (n : ℕ) (i : ι) (d : ι → ℕ) :
    eval (fun i ↦ (d i : ℚ)) (binomPoly n i) = (d i + n).choose n := by
  have hev : ∀ q : Polynomial ℚ,
      eval (fun i ↦ (d i : ℚ)) (Polynomial.aeval (X i + 1) q) = q.eval ((d i : ℚ) + 1) := by
    intro q
    induction q using Polynomial.induction_on' with
    | add p q hp hq => simp [hp, hq]
    | monomial n a => simp
  rw [binomPoly, map_mul, eval_C, hev]
  have hcast : ((d i : ℚ) + 1) = ((d i + 1 : ℕ) : ℚ) := by push_cast; ring
  rw [hcast, ← ascPochhammer_eval_cast, ascPochhammer_nat_eq_ascFactorial,
    Nat.ascFactorial_eq_factorial_mul_choose]
  push_cast
  field_simp

variable [DecidableEq ι] [Fintype σ] [Fintype ι]

/-- The polynomial `∏ i, C(T_i + N_i - 1, N_i - 1)`, with `N_i` the size of the `i`-th block. -/
noncomputable def blockCountPoly (b : σ → ι) : MvPolynomial ι ℚ :=
  ∏ i, binomPoly (#({s | b s = i} : Finset σ) - 1) i

/-- With every block nonempty, the number of monomials of multidegree `d` is the value at `d` of
`blockCountPoly`. -/
theorem eval_blockCountPoly {b : σ → ι} (hb : Function.Surjective b) (d : ι → ℕ) :
    eval (fun i ↦ (d i : ℚ)) (blockCountPoly b) = #(blockMonomials b d) := by
  rw [card_blockMonomials, blockCountPoly, map_prod, Nat.cast_prod]
  refine Finset.prod_congr rfl fun i _ ↦ ?_
  rw [eval_binomPoly]
  obtain ⟨s, hs⟩ := hb i
  have : 0 < #({s | b s = i} : Finset σ) := Finset.card_pos.mpr ⟨s, by simp [hs]⟩
  rw [show #({s | b s = i} : Finset σ) + d i - 1 = d i + (#({s | b s = i} : Finset σ) - 1) by
    omega, Nat.choose_symm_add]

/-- The monomials of multidegree `d` above `g` and above none of `G` correspond, by translation
by `g`, to the monomials of multidegree `d - deg g` above none of `G - g`. -/
theorem card_filter_le_forall_not_le [DecidableEq σ] (b : σ → ι) (g : σ →₀ ℕ)
    (G : Finset (σ →₀ ℕ)) (d : ι → ℕ) (hd : Finsupp.weight (multiWeight b) g ≤ d) :
    #((blockMonomials b d).filter fun c ↦ g ≤ c ∧ ∀ g' ∈ G, ¬g' ≤ c) =
      #((blockMonomials b (d - Finsupp.weight (multiWeight b) g)).filter
        fun c ↦ ∀ g' ∈ G.image (· - g), ¬g' ≤ c) := by
  classical
  set e := Finsupp.weight (multiWeight b) g
  symm
  refine Finset.card_nbij' (g + ·) (· - g) ?_ ?_ ?_ ?_
  · intro c hc
    rw [Finset.mem_coe, Finset.mem_filter, mem_blockMonomials] at hc ⊢
    refine ⟨?_, le_self_add, fun g' hg' hle ↦ ?_⟩
    · rw [map_add, hc.1, add_tsub_cancel_of_le hd]
    · exact hc.2 (g' - g) (Finset.mem_image_of_mem _ hg') (tsub_le_iff_left.mpr hle)
  · intro c hc
    rw [Finset.mem_coe, Finset.mem_filter, mem_blockMonomials] at hc ⊢
    obtain ⟨hcw, hgc, hG⟩ := hc
    refine ⟨?_, fun g' hg' hle ↦ ?_⟩
    · have hsum :
          Finsupp.weight (multiWeight b) c = e + Finsupp.weight (multiWeight b) (c - g) := by
        rw [← map_add, add_tsub_cancel_of_le hgc]
      rw [← hcw, hsum, add_tsub_cancel_left]
    · obtain ⟨g'', hg'', rfl⟩ := Finset.mem_image.mp hg'
      refine hG g'' hg'' ?_
      have := tsub_le_iff_left.mp hle
      rwa [add_tsub_cancel_of_le hgc] at this
  · intro c _
    simp
  · intro c hc
    rw [Finset.mem_coe, Finset.mem_filter] at hc
    exact add_tsub_cancel_of_le hc.2.1

theorem card_filter_le_forall_not_le_eq_zero (b : σ → ι) (g : σ →₀ ℕ) (G : Finset (σ →₀ ℕ))
    (d : ι → ℕ) (hd : ¬Finsupp.weight (multiWeight b) g ≤ d) :
    #((blockMonomials b d).filter fun c ↦ g ≤ c ∧ ∀ g' ∈ G, ¬g' ≤ c) = 0 := by
  rw [Finset.card_eq_zero, Finset.filter_eq_empty_iff]
  intro c hc h
  rw [mem_blockMonomials] at hc
  exact hd (hc ▸ weight_mono h.1)

/-- **Polynomiality of the count of standard monomials.** For finitely many monomials `G`, the
number of monomials of multidegree `d` above none of them is a polynomial in `d` for `d` large in
every coordinate. -/
theorem exists_card_filter_forall_not_le {b : σ → ι} (hb : Function.Surjective b)
    (G : Finset (σ →₀ ℕ)) :
    ∃ (P : MvPolynomial ι ℚ) (d₀ : ι → ℕ), ∀ d, d₀ ≤ d →
      (#((blockMonomials b d).filter fun c ↦ ∀ g ∈ G, ¬g ≤ c) : ℚ) =
        eval (fun i ↦ (d i : ℚ)) P := by
  classical
  suffices h : ∀ n, ∀ G : Finset (σ →₀ ℕ), #G ≤ n → ∃ (P : MvPolynomial ι ℚ) (d₀ : ι → ℕ),
      ∀ d, d₀ ≤ d → (#((blockMonomials b d).filter fun c ↦ ∀ g ∈ G, ¬g ≤ c) : ℚ) =
        eval (fun i ↦ (d i : ℚ)) P from h _ G le_rfl
  intro n
  induction n with
  | zero =>
    intro G hG
    rw [Nat.le_zero, Finset.card_eq_zero] at hG
    subst hG
    exact ⟨blockCountPoly b, 0, fun d _ ↦ by simp [eval_blockCountPoly hb]⟩
  | succ n ih =>
    intro G hG
    rcases G.eq_empty_or_nonempty with rfl | ⟨g, hg⟩
    · exact ih ∅ (by simp)
    set G₀ := G.erase g
    have hG₀ : #G₀ ≤ n := by
      simp only [G₀, Finset.card_erase_of_mem hg]
      omega
    obtain ⟨P₀, d₀, hP₀⟩ := ih G₀ hG₀
    obtain ⟨P₁, d₁, hP₁⟩ := ih (G₀.image (· - g)) (Finset.card_image_le.trans hG₀)
    set e := Finsupp.weight (multiWeight b) g
    refine ⟨P₀ - shiftPoly e P₁, d₀ ⊔ (d₁ + e), fun d hd ↦ ?_⟩
    have hd₀ : d₀ ≤ d := le_sup_left.trans hd
    have hde : d₁ + e ≤ d := le_sup_right.trans hd
    have he : e ≤ d := le_add_self.trans hde
    have hd₁ : d₁ ≤ d - e := le_tsub_of_add_le_right hde
    have hcongr : ((blockMonomials b d).filter fun c ↦ (∀ g' ∈ G₀, ¬g' ≤ c) ∧ g ≤ c) =
        (blockMonomials b d).filter fun c ↦ g ≤ c ∧ ∀ g' ∈ G₀, ¬g' ≤ c :=
      Finset.filter_congr fun c _ ↦ and_comm
    have hsplit := Finset.card_filter_add_card_filter_not
      (s := (blockMonomials b d).filter fun c ↦ ∀ g' ∈ G₀, ¬g' ≤ c) (p := fun c ↦ g ≤ c)
    rw [Finset.filter_filter, Finset.filter_filter, hcongr,
      card_filter_le_forall_not_le b g G₀ d he] at hsplit
    have hG : G = insert g G₀ := (Finset.insert_erase hg).symm
    have hfilter : ((blockMonomials b d).filter fun c ↦ ∀ g' ∈ G, ¬g' ≤ c) =
        (blockMonomials b d).filter fun c ↦ (∀ g' ∈ G₀, ¬g' ≤ c) ∧ ¬g ≤ c := by
      refine Finset.filter_congr fun c _ ↦ ?_
      rw [hG, Finset.forall_mem_insert]
      tauto
    rw [hfilter, map_sub, eval_shiftPoly, ← hP₀ d hd₀]
    have hsub : (fun i ↦ (d i : ℚ) - (e i : ℚ)) = fun i ↦ ((d - e) i : ℚ) := by
      funext i
      rw [Pi.sub_apply, Nat.cast_sub (he i)]
    rw [hsub, ← hP₁ (d - e) hd₁]
    have := congrArg (Nat.cast (R := ℚ)) hsplit
    push_cast at this
    linarith

end Count

section HilbertPolynomial

variable [Field K]

/-- The upper set of leading monomials is generated by finitely many monomials (Dickson). -/
theorem exists_finset_leadingMonomials [Finite σ] (m : MonomialOrder σ)
    (I : Ideal (MvPolynomial σ K)) :
    ∃ G : Finset (σ →₀ ℕ), ∀ c, c ∈ leadingMonomials m I ↔ ∃ g ∈ G, g ≤ c := by
  set U := leadingMonomials m I
  have hfin : {x | Minimal (· ∈ U) x}.Finite :=
    (setOfPred_minimal_antichain _).finite_of_partiallyWellOrderedOn
      (Set.isPWO_of_wellQuasiOrderedLE _)
  refine ⟨hfin.toFinset, fun c ↦ ⟨fun hc ↦ ?_, ?_⟩⟩
  · obtain ⟨g, hgc, hg⟩ := exists_minimal_le_of_wellFoundedLT (· ∈ U) c hc
    exact ⟨g, by simpa using hg, hgc⟩
  · rintro ⟨g, hg, hgc⟩
    rw [Set.Finite.mem_toFinset] at hg
    exact isUpperSet_leadingMonomials I hgc hg.1

/-- **The multigraded Hilbert–Samuel theorem** (van der Waerden). With every block nonempty, the
Hilbert function of a multihomogeneous ideal agrees with a polynomial for `d` large in every
coordinate. -/
theorem exists_hilbertPolynomial [DecidableEq ι] [Finite σ] [Finite ι] {b : σ → ι}
    (hb : Function.Surjective b) {I : Ideal (MvPolynomial σ K)}
    (hI : I.IsWeightedHomogeneous (multiWeight b)) :
    ∃ (P : MvPolynomial ι ℚ) (d₀ : ι → ℕ), ∀ d, d₀ ≤ d →
      (hilbertFunction b I d : ℚ) = eval (fun i ↦ (d i : ℚ)) P := by
  classical
  have := Fintype.ofFinite σ
  have := Fintype.ofFinite ι
  let : LinearOrder σ := LinearOrder.lift' (Fintype.equivFin σ) (Fintype.equivFin σ).injective
  set m : MonomialOrder σ := MonomialOrder.lex
  obtain ⟨G, hG⟩ := exists_finset_leadingMonomials m I
  obtain ⟨P, d₀, hP⟩ := exists_card_filter_forall_not_le hb G
  refine ⟨P, d₀, fun d hd ↦ ?_⟩
  rw [hilbertFunction_eq_card_filter m b hI, ← hP d hd]
  congr 2
  refine Finset.filter_congr fun c _ ↦ ?_
  rw [hG]
  push Not
  rfl

/-- A polynomial vanishing at every `d ≥ d₀` of `ℕ^ι` is zero. -/
theorem eq_zero_of_forall_le_eval_eq_zero [Finite ι] {P : MvPolynomial ι ℚ} (d₀ : ι → ℕ)
    (h : ∀ d, d₀ ≤ d → eval (fun i ↦ (d i : ℚ)) P = 0) : P = 0 := by
  classical
  refine eq_zero_of_eval_zero_at_prod_finset P
    (fun i ↦ (Finset.range (P.degreeOf i + 1)).image fun n ↦ ((d₀ i + n : ℕ) : ℚ))
    (fun i ↦ ?_) fun x hx ↦ ?_
  · rw [Finset.card_image_of_injective _ fun a c hac ↦ by simpa using hac]
    simp
  · choose n _ hxn using fun i ↦ Finset.mem_image.mp (hx i)
    have := h (fun i ↦ d₀ i + n i) fun i ↦ Nat.le_add_right _ _
    rwa [show x = fun i ↦ ((d₀ i + n i : ℕ) : ℚ) from funext fun i ↦ (hxn i).symm]

/-- Two polynomials agreeing at every `d ≥ d₀` of `ℕ^ι` are equal. -/
theorem eq_of_forall_le_eval_eq [Finite ι] {P Q : MvPolynomial ι ℚ} (d₀ : ι → ℕ)
    (h : ∀ d, d₀ ≤ d → eval (fun i ↦ (d i : ℚ)) P = eval (fun i ↦ (d i : ℚ)) Q) : P = Q :=
  sub_eq_zero.mp <| eq_zero_of_forall_le_eval_eq_zero d₀ fun d hd ↦ by
    rw [map_sub, h d hd, sub_self]

variable [DecidableEq ι]

open Classical in
/-- The *Hilbert polynomial* of an ideal: the polynomial that agrees with the Hilbert function for
`d` large in every coordinate. It exists for multihomogeneous ideals when every block is nonempty
(`MvPolynomial.exists_hilbertPolynomial`); it is `0` by convention otherwise. -/
noncomputable def hilbertPoly (b : σ → ι) (I : Ideal (MvPolynomial σ K)) : MvPolynomial ι ℚ :=
  if h : ∃ (P : MvPolynomial ι ℚ) (d₀ : ι → ℕ), ∀ d, d₀ ≤ d →
      (hilbertFunction b I d : ℚ) = eval (fun i ↦ (d i : ℚ)) P then h.choose else 0

theorem exists_forall_le_hilbertFunction_eq_hilbertPoly [Finite σ] [Finite ι] {b : σ → ι}
    (hb : Function.Surjective b) {I : Ideal (MvPolynomial σ K)}
    (hI : I.IsWeightedHomogeneous (multiWeight b)) :
    ∃ d₀ : ι → ℕ, ∀ d, d₀ ≤ d → (hilbertFunction b I d : ℚ) = eval (fun i ↦ (d i : ℚ))
      (hilbertPoly b I) := by
  have h := exists_hilbertPolynomial (K := K) hb hI
  rw [hilbertPoly]
  split_ifs
  exact h.choose_spec

/-- The Hilbert polynomial is the unique polynomial that agrees with the Hilbert function for
`d` large. -/
theorem hilbertPoly_eq_of_forall_le [Finite σ] [Finite ι] {b : σ → ι}
    (hb : Function.Surjective b) {I : Ideal (MvPolynomial σ K)}
    (hI : I.IsWeightedHomogeneous (multiWeight b)) {P : MvPolynomial ι ℚ} {d₀ : ι → ℕ}
    (hP : ∀ d, d₀ ≤ d → (hilbertFunction b I d : ℚ) = eval (fun i ↦ (d i : ℚ)) P) :
    hilbertPoly b I = P := by
  obtain ⟨d₁, hd₁⟩ := exists_forall_le_hilbertFunction_eq_hilbertPoly hb hI
  exact eq_of_forall_le_eval_eq (d₀ ⊔ d₁) fun d hd ↦ by
    rw [← hd₁ d (le_sup_right.trans hd), hP d (le_sup_left.trans hd)]

theorem hilbertFunction_cast [Finite σ] [Finite ι] (b : σ → ι) (I : Ideal (MvPolynomial σ K))
    (d : ι → ℕ) :
    (hilbertFunction b I d : ℚ) =
      (Module.finrank K (weightedHomogeneousSubmodule K (multiWeight b) d) : ℚ) -
        Module.finrank K ↥(I.restrictScalars K ⊓ weightedHomogeneousSubmodule K (multiWeight b) d)
    := by
  rw [hilbertFunction, Nat.cast_sub (Submodule.finrank_mono inf_le_right)]

/-- **The Hilbert polynomial of `J + (g)`.** For a multihomogeneous ideal `J` and a nonzero
multihomogeneous `g` of multidegree `e`, `H_{J + (g)}(T) = H_J(T) - H_{(J : g)}(T - e)`. When `J`
is prime and `g ∉ J` the colon ideal is `J` itself, and this computes the Hilbert polynomial of the
hypersurface section `V(J) ∩ {g = 0}`. -/
theorem hilbertPoly_sup_span_singleton [Finite σ] [Finite ι] {b : σ → ι}
    (hb : Function.Surjective b) {J : Ideal (MvPolynomial σ K)}
    (hJ : J.IsWeightedHomogeneous (multiWeight b)) {g : MvPolynomial σ K} {e : ι → ℕ}
    (hg : IsWeightedHomogeneous (multiWeight b) g e) (hg0 : g ≠ 0) :
    hilbertPoly b (J ⊔ Ideal.span {g}) =
      hilbertPoly b J - shiftPoly e (hilbertPoly b (J.colon {g})) := by
  have hJg : (J ⊔ Ideal.span {g}).IsWeightedHomogeneous (multiWeight b) :=
    hJ.sup (isWeightedHomogeneous_span fun x hx ↦ ⟨e, (Set.mem_singleton_iff.mp hx) ▸ hg⟩)
  have hcol : (J.colon {g}).IsWeightedHomogeneous (multiWeight b) := hJ.colon hg
  obtain ⟨d₁, hd₁⟩ := exists_forall_le_hilbertFunction_eq_hilbertPoly hb hJ
  obtain ⟨d₂, hd₂⟩ := exists_forall_le_hilbertFunction_eq_hilbertPoly hb hcol
  refine hilbertPoly_eq_of_forall_le hb hJg (d₀ := d₁ ⊔ (d₂ + e)) fun D hD ↦ ?_
  have he : e ≤ D := le_add_self.trans (le_sup_right.trans hD)
  have hd₂' : d₂ ≤ D - e := le_tsub_of_add_le_right (le_sup_right.trans hD)
  obtain ⟨d, rfl⟩ : ∃ d, D = d + e := ⟨D - e, (tsub_add_cancel_of_le he).symm⟩
  rw [add_tsub_cancel_right] at hd₂'
  have key := finrank_sup_span_singleton_add_finrank_colon b hJ hg hg0 d
  have hsub : (fun i ↦ (((d + e) i : ℕ) : ℚ) - (e i : ℚ)) = fun i ↦ ((d i : ℕ) : ℚ) := by
    funext i
    simp
  rw [map_sub, eval_shiftPoly, hsub, ← hd₁ _ (le_sup_left.trans hD), ← hd₂ d hd₂',
    hilbertFunction_cast, hilbertFunction_cast, hilbertFunction_cast]
  have := congrArg (Nat.cast (R := ℚ)) key
  push_cast at this
  linarith

/-- The Hilbert polynomial of the whole multiprojective space is `∏ i, C(T_i + n_i, n_i)`, with
`n_i + 1` variables in the `i`-th block. -/
theorem hilbertPoly_bot [Fintype σ] [Fintype ι] {b : σ → ι} (hb : Function.Surjective b) :
    hilbertPoly (K := K) b ⊥ = blockCountPoly b := by
  refine hilbertPoly_eq_of_forall_le hb (isWeightedHomogeneous_bot _) (d₀ := 0) fun d _ ↦ ?_
  rw [eval_blockCountPoly hb, hilbertFunction, finrank_multiWeight,
    Submodule.restrictScalars_bot, bot_inf_eq, finrank_bot]
  simp

/-- **The Hilbert polynomial of a section by a nonzerodivisor.** For a multihomogeneous ideal `J`
and a nonzero multihomogeneous `g` of multidegree `e` with `(J : g) = J`,
`H_{J + (g)}(T) = H_J(T) - H_J(T - e)`. -/
theorem hilbertPoly_sup_span_singleton_of_colon_eq [Finite σ] [Finite ι] {b : σ → ι}
    (hb : Function.Surjective b) {J : Ideal (MvPolynomial σ K)}
    (hJ : J.IsWeightedHomogeneous (multiWeight b)) {g : MvPolynomial σ K} {e : ι → ℕ}
    (hg : IsWeightedHomogeneous (multiWeight b) g e) (hg0 : g ≠ 0) (hcol : J.colon {g} = J) :
    hilbertPoly b (J ⊔ Ideal.span {g}) = hilbertPoly b J - shiftPoly e (hilbertPoly b J) := by
  rw [hilbertPoly_sup_span_singleton hb hJ hg hg0, hcol]

omit [DecidableEq ι] in
/-- For a prime `𝔭` and `g ∉ 𝔭`, `(𝔭 : g) = 𝔭`. -/
theorem _root_.Ideal.colon_singleton_eq_of_isPrime {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]
    {g : MvPolynomial σ K} (hg𝔭 : g ∉ 𝔭) : 𝔭.colon {g} = 𝔭 := by
  ext x
  rw [Submodule.mem_colon_singleton, smul_eq_mul]
  exact ⟨fun h ↦ (Ideal.IsPrime.mem_or_mem ‹_› h).resolve_right hg𝔭,
    fun h ↦ 𝔭.mul_mem_right g h⟩

/-- **The Hilbert polynomial of a hypersurface section.** For a multihomogeneous prime `𝔭` and a
multihomogeneous `g ∉ 𝔭` of multidegree `e`, `H_{𝔭 + (g)}(T) = H_𝔭(T) - H_𝔭(T - e)`. -/
theorem hilbertPoly_sup_span_singleton_of_isPrime [Finite σ] [Finite ι] {b : σ → ι}
    (hb : Function.Surjective b) {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]
    (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b)) {g : MvPolynomial σ K} {e : ι → ℕ}
    (hg : IsWeightedHomogeneous (multiWeight b) g e) (hg𝔭 : g ∉ 𝔭) :
    hilbertPoly b (𝔭 ⊔ Ideal.span {g}) = hilbertPoly b 𝔭 - shiftPoly e (hilbertPoly b 𝔭) :=
  hilbertPoly_sup_span_singleton_of_colon_eq hb h𝔭 hg (fun h ↦ hg𝔭 (h ▸ 𝔭.zero_mem))
    (Ideal.colon_singleton_eq_of_isPrime hg𝔭)

end HilbertPolynomial

end MvPolynomial
