/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ForMathlib.RingTheory.MvPolynomial.StandardMonomials
public import Mathlib.Algebra.Order.Antidiag.Finsupp
public import Mathlib.Data.Fintype.BigOperators
public import Mathlib.RingTheory.Ideal.Colon

-- Used only inside proofs.
import Mathlib.Algebra.Order.Antidiag.FinsuppEquiv
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# Multihomogeneous polynomials and multigraded Hilbert functions

The coordinate ring of a product of projective spaces `ℙ^{n₁} × ⋯ × ℙ^{n_q}` is `K[X]`, with the
variables split into blocks, one block of `n_i + 1` variables for each factor. A polynomial is
*multihomogeneous* of multidegree `d : ι → ℕ` if it is homogeneous of degree `d i` in the `i`-th
block for every `i`. We encode the blocks by a map `b : σ → ι` and use Mathlib's weighted
homogeneity, with the weight `multiWeight b` that sends the variable `X s` to the `b s`-th unit
vector of `ι → ℕ`.

The *Hilbert function* of an ideal `I` is `d ↦ dim_K (K[X]/I)_d`. For a multihomogeneous ideal it
counts the standard monomials of multidegree `d` for any monomial order
(`hilbertFunction_eq_card_filter`). This is the input to the multigraded Hilbert–Samuel theorem in
`ForMathlib.RingTheory.MvPolynomial.HilbertPolynomial`.

The file also proves the exact-sequence identity behind Bézout's theorem
(`finrank_sup_span_singleton_add_finrank_colon`). For `g` multihomogeneous of multidegree `e`, the
sequence `0 → (K[X]/(J : g))(−e) → K[X]/J → K[X]/(J + (g)) → 0` gives, in multidegree `d + e`,
`h_{J + (g)}(d + e) = h_J(d + e) − h_{(J : g)}(d)`. See G. Rémond, *Élimination multihomogène*,
Chapter 5 of Nesterenko–Philippon (eds.), *Introduction to algebraic independence theory*, LNM
1752 (2001), §2.2.

## Main definitions

* `MvPolynomial.multiWeight b`: the multigrading of `K[X]` by the blocks `b : σ → ι`.
* `MvPolynomial.blockMonomials b d`: the monomials of multidegree `d`.
* `MvPolynomial.hilbertFunction b I d`: `dim_K (K[X]/I)_d`.

## Main statements

* `MvPolynomial.card_blockMonomials`: there are `∏ i, C(N_i + d i - 1, d i)` monomials of
  multidegree `d`, where `N_i` is the size of the `i`-th block.
* `MvPolynomial.hilbertFunction_eq_card_filter`: the Hilbert function counts standard monomials.
* `Ideal.IsWeightedHomogeneous.colon`, `MvPolynomial.isWeightedHomogeneous_span`: colon
  ideals and ideals generated by homogeneous elements are homogeneous.
* `MvPolynomial.finrank_sup_span_singleton_add_finrank_colon`: the exact-sequence identity.
-/

@[expose] public section

open Module Finset

variable {σ ι M R K : Type*}

namespace MvPolynomial

section Homogeneous

variable [AddCommMonoid M] [CommSemiring R]

theorem IsWeightedHomogeneous.weightedHomogeneousComponent_add_mul [IsCancelAdd M]
    {w : σ → M} {g : MvPolynomial σ R} {e : M} (hg : IsWeightedHomogeneous w g e)
    (p : MvPolynomial σ R) (d : M) :
    weightedHomogeneousComponent w (d + e) (p * g) = weightedHomogeneousComponent w d p * g := by
  classical
  induction p using MvPolynomial.induction_on' with
  | monomial u a =>
    have hmul : IsWeightedHomogeneous w (monomial u a * g) (Finsupp.weight w u + e) :=
      (isWeightedHomogeneous_monomial w u a rfl).mul hg
    by_cases hu : Finsupp.weight w u = d
    · subst hu
      rw [hmul.weightedHomogeneousComponent_same,
        (isWeightedHomogeneous_monomial w u a rfl).weightedHomogeneousComponent_same]
    · rw [hmul.weightedHomogeneousComponent_ne _ (fun h ↦ hu (add_right_cancel h.symm)),
        (isWeightedHomogeneous_monomial w u a rfl).weightedHomogeneousComponent_ne _
          (Ne.symm hu), zero_mul]
  | add p q hp hq => rw [add_mul, map_add, map_add, hp, hq, add_mul]

/-- The colon ideal of a homogeneous ideal by a homogeneous element is homogeneous. -/
theorem _root_.Ideal.IsWeightedHomogeneous.colon [IsCancelAdd M] {w : σ → M}
    {J : Ideal (MvPolynomial σ R)}
    (hJ : J.IsWeightedHomogeneous w) {g : MvPolynomial σ R} {e : M}
    (hg : IsWeightedHomogeneous w g e) :
    (J.colon {g}).IsWeightedHomogeneous w := by
  intro p hp d
  rw [Submodule.mem_colon_singleton, smul_eq_mul] at hp ⊢
  rw [← hg.weightedHomogeneousComponent_add_mul]
  exact hJ hp _

/-- The sum of two homogeneous ideals is homogeneous. -/
theorem _root_.Ideal.IsWeightedHomogeneous.sup {w : σ → M} {I J : Ideal (MvPolynomial σ R)}
    (hI : I.IsWeightedHomogeneous w) (hJ : J.IsWeightedHomogeneous w) :
    (I ⊔ J).IsWeightedHomogeneous w := by
  intro p hp d
  obtain ⟨x, hx, y, hy, rfl⟩ := Submodule.mem_sup.mp hp
  rw [map_add]
  exact Submodule.add_mem_sup (hI hx d) (hJ hy d)

attribute [local instance] weightedGradedAlgebra in
/-- For a decidable weight monoid, `w`-homogeneity is Mathlib's homogeneity for the weighted
grading. -/
theorem isWeightedHomogeneous_iff_isHomogeneous [DecidableEq M] {w : σ → M}
    {I : Ideal (MvPolynomial σ R)} :
    I.IsWeightedHomogeneous w ↔ I.IsHomogeneous (weightedHomogeneousSubmodule R w) := by
  refine ⟨fun h i r hr ↦ ?_, fun h p hp d ↦ weightedHomogeneousComponent_mem_of_mem R w h hp d⟩
  have := h hr i
  rwa [← weightedDecomposition.decompose'_apply] at this

attribute [local instance] weightedGradedAlgebra in
/-- An ideal generated by homogeneous elements is homogeneous. -/
theorem isWeightedHomogeneous_span {w : σ → M} {s : Set (MvPolynomial σ R)}
    (hs : ∀ g ∈ s, ∃ e, IsWeightedHomogeneous w g e) :
    (Ideal.span s).IsWeightedHomogeneous w := by
  classical
  rw [isWeightedHomogeneous_iff_isHomogeneous]
  refine Ideal.homogeneous_span _ s fun g hg ↦ ?_
  obtain ⟨e, he⟩ := hs g hg
  exact ⟨e, he⟩

end Homogeneous

section Blocks

variable [DecidableEq ι]

/-- The multigrading of `R[X]` by blocks of variables: `X s` gets the `b s`-th unit vector. -/
def multiWeight (b : σ → ι) : σ → ι → ℕ := fun s ↦ Pi.single (b s) 1

theorem weight_multiWeight_apply [Fintype σ] (b : σ → ι) (c : σ →₀ ℕ) (i : ι) :
    Finsupp.weight (multiWeight b) c i = ∑ s with b s = i, c s := by
  classical
  rw [Finsupp.weight_apply, Finsupp.sum, Finset.sum_apply]
  simp only [multiWeight, Pi.smul_apply, Pi.single_apply, smul_eq_mul, mul_ite, mul_one,
    mul_zero]
  rw [Finset.sum_ite, Finset.sum_const_zero, add_zero]
  refine Finset.sum_subset (fun s hs ↦ ?_) (fun s hs hs' ↦ ?_)
  · simp only [Finset.mem_filter, Finsupp.mem_support_iff] at hs
    simp [hs.2.symm]
  · simp only [Finset.mem_filter, Finsupp.mem_support_iff, not_and] at hs'
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hs
    by_contra h
    exact hs' h hs.symm

variable [Fintype σ] [Fintype ι]

/-- The monomials of multidegree `d` for the blocks `b`. -/
noncomputable def blockMonomials (b : σ → ι) (d : ι → ℕ) : Finset (σ →₀ ℕ) := by
  classical
  exact (Fintype.piFinset fun i ↦ ({s | b s = i} : Finset σ).finsuppAntidiag (d i)).image
    fun f ↦ ∑ i, f i

/-- The block of a finsupp supported in block `j`, filtered to block `i`. -/
private theorem filter_sum_blocks (b : σ → ι) {f : ι → σ →₀ ℕ}
    (hf : ∀ j, (f j).support ⊆ ({s | b s = j} : Finset σ)) (i : ι) :
    Finsupp.filter (b · = i) (∑ j, f j) = f i := by
  classical
  rw [Finsupp.filter_sum, Finset.sum_eq_single i]
  · rw [Finsupp.filter_eq_self_iff]
    intro s hs
    have := hf i (Finsupp.mem_support_iff.mpr hs)
    simpa using this
  · intro j _ hji
    ext s
    rw [Finsupp.filter_apply]
    split_ifs with hs
    · by_contra h
      have := hf j (Finsupp.mem_support_iff.mpr (by simpa using h))
      simp only [Finset.mem_filter, Finset.mem_univ, true_and] at this
      exact hji (this.symm.trans hs)
    · rfl
  · simp

theorem mem_blockMonomials {b : σ → ι} {d : ι → ℕ} {c : σ →₀ ℕ} :
    c ∈ blockMonomials b d ↔ Finsupp.weight (multiWeight b) c = d := by
  classical
  unfold blockMonomials
  rw [Finset.mem_image]
  constructor
  · rintro ⟨f, hf, rfl⟩
    rw [Fintype.mem_piFinset] at hf
    have hsupp : ∀ j, (f j).support ⊆ ({s | b s = j} : Finset σ) :=
      fun j ↦ (Finset.mem_finsuppAntidiag.mp (hf j)).2
    funext i
    rw [weight_multiWeight_apply]
    have : ∀ s ∈ ({s | b s = i} : Finset σ), (∑ j, f j) s = f i s := by
      intro s hs
      rw [← filter_sum_blocks b hsupp i, Finsupp.filter_apply]
      simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hs
      simp [hs]
    rw [Finset.sum_congr rfl this]
    exact (Finset.mem_finsuppAntidiag.mp (hf i)).1
  · intro hc
    refine ⟨fun i ↦ Finsupp.filter (b · = i) c, ?_, ?_⟩
    · rw [Fintype.mem_piFinset]
      intro i
      rw [Finset.mem_finsuppAntidiag]
      refine ⟨?_, fun s hs ↦ ?_⟩
      · rw [← congrFun hc i, weight_multiWeight_apply]
        refine Finset.sum_congr rfl fun s hs ↦ ?_
        simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hs
        simp [hs]
      · rw [Finsupp.mem_support_iff, Finsupp.filter_apply] at hs
        split_ifs at hs with h
        · simpa using h
        · exact absurd rfl hs
    · ext s
      rw [Finsupp.coe_finsetSum, Finset.sum_apply, Finset.sum_eq_single (b s)]
      · simp
      · intro j _ hj
        simp [Ne.symm hj]
      · simp

/-- A sum of block-supported finsupps, evaluated at `s`, is the block of `s` evaluated at `s`. -/
theorem sum_apply_of_support_subset (b : σ → ι) {f : ι → σ →₀ ℕ}
    (hf : ∀ j, (f j).support ⊆ ({s | b s = j} : Finset σ)) (s : σ) :
    (∑ j, f j) s = f (b s) s := by
  rw [← filter_sum_blocks b hf (b s), Finsupp.filter_apply]
  simp

private theorem injOn_sum_blocks [DecidableEq σ] (b : σ → ι) (d : ι → ℕ) :
    Set.InjOn (fun f : ι → σ →₀ ℕ ↦ ∑ i, f i)
      (Fintype.piFinset fun i ↦ ({s | b s = i} : Finset σ).finsuppAntidiag (d i)) := by
  intro f hf g hg hfg
  simp only [Fintype.coe_piFinset, Set.mem_pi, Set.mem_univ, Finset.mem_coe,
    forall_const] at hf hg
  have hsf : ∀ j, (f j).support ⊆ ({s | b s = j} : Finset σ) :=
    fun j ↦ (Finset.mem_finsuppAntidiag.mp (hf j)).2
  have hsg : ∀ j, (g j).support ⊆ ({s | b s = j} : Finset σ) :=
    fun j ↦ (Finset.mem_finsuppAntidiag.mp (hg j)).2
  funext i
  rw [← filter_sum_blocks b hsf i, ← filter_sum_blocks b hsg i]
  exact congrArg _ hfg

theorem card_blockMonomials (b : σ → ι) (d : ι → ℕ) :
    #(blockMonomials b d) = ∏ i, (#({s | b s = i} : Finset σ) + d i - 1).choose (d i) := by
  classical
  unfold blockMonomials
  rw [Finset.card_image_of_injOn (injOn_sum_blocks b d), Fintype.card_piFinset]
  simp_rw [Finset.card_finsuppAntidiag_nat_eq_choose]

open Classical in
/-- A sum over the monomials of multidegree `d` is a sum over one monomial of degree `d i` in
each block `i`. -/
theorem sum_blockMonomials {M : Type*} [AddCommMonoid M] (b : σ → ι) (d : ι → ℕ)
    (F : (σ →₀ ℕ) → M) :
    ∑ c ∈ blockMonomials b d, F c =
      ∑ f ∈ Fintype.piFinset fun i ↦ ({s | b s = i} : Finset σ).finsuppAntidiag (d i),
        F (∑ i, f i) := by
  unfold blockMonomials
  exact Finset.sum_image (injOn_sum_blocks b d)

variable [Field K]

/-- The multidegree-`d` part of `K[X]` has dimension the number of monomials of multidegree `d`. -/
theorem finrank_multiWeight (b : σ → ι) (d : ι → ℕ) :
    finrank K (weightedHomogeneousSubmodule K (multiWeight b) d) = #(blockMonomials b d) :=
  finrank_weightedHomogeneousSubmodule fun _ ↦ mem_blockMonomials

omit [Fintype σ] [Fintype ι] in
instance [Finite σ] [Finite ι] (b : σ → ι) (d : ι → ℕ) :
    FiniteDimensional K (weightedHomogeneousSubmodule K (multiWeight b) d) := by
  have := Fintype.ofFinite σ
  have := Fintype.ofFinite ι
  exact finiteDimensional_weightedHomogeneousSubmodule fun _ ↦ mem_blockMonomials

/-- The *Hilbert function* `d ↦ dim_K (K[X]/I)_d` of an ideal for the multigrading by blocks. -/
noncomputable def hilbertFunction (b : σ → ι) (I : Ideal (MvPolynomial σ K)) (d : ι → ℕ) : ℕ :=
  finrank K (weightedHomogeneousSubmodule K (multiWeight b) d) -
    finrank K ↥(I.restrictScalars K ⊓ weightedHomogeneousSubmodule K (multiWeight b) d)

/-- **The Hilbert function counts standard monomials.** For a multihomogeneous ideal and any
monomial order, `dim_K (K[X]/I)_d` is the number of monomials of multidegree `d` that are not
leading monomials of `I`. -/
theorem hilbertFunction_eq_card_filter (m : MonomialOrder σ) (b : σ → ι)
    {I : Ideal (MvPolynomial σ K)} (hI : I.IsWeightedHomogeneous (multiWeight b)) (d : ι → ℕ)
    [DecidablePred (· ∈ leadingMonomials m I)] :
    hilbertFunction b I d = #((blockMonomials b d).filter (· ∉ leadingMonomials m I)) := by
  rw [hilbertFunction, finrank_multiWeight,
    finrank_inf_weightedHomogeneousSubmodule m hI fun _ ↦ mem_blockMonomials,
    ← Finset.card_filter_add_card_filter_not (s := blockMonomials b d)
      (p := (· ∈ leadingMonomials m I))]
  omega

omit [Fintype σ] [Fintype ι] in
/-- **The exact-sequence identity.** For a homogeneous ideal `J` and a nonzero homogeneous `g` of
multidegree `e`, in multidegree `d + e`:
`dim (J + (g))_{d+e} + dim (J : g)_d = dim J_{d+e} + dim K[X]_d`. -/
theorem finrank_sup_span_singleton_add_finrank_colon [Finite σ] [Finite ι] (b : σ → ι)
    {J : Ideal (MvPolynomial σ K)} (hJ : J.IsWeightedHomogeneous (multiWeight b))
    {g : MvPolynomial σ K} {e : ι → ℕ} (hg : IsWeightedHomogeneous (multiWeight b) g e)
    (hg0 : g ≠ 0) (d : ι → ℕ) :
    finrank K ↥((J ⊔ Ideal.span {g}).restrictScalars K ⊓
        weightedHomogeneousSubmodule K (multiWeight b) (d + e)) +
      finrank K ↥((J.colon {g}).restrictScalars K ⊓
        weightedHomogeneousSubmodule K (multiWeight b) d) =
      finrank K ↥(J.restrictScalars K ⊓ weightedHomogeneousSubmodule K (multiWeight b) (d + e)) +
        finrank K (weightedHomogeneousSubmodule K (multiWeight b) d) := by
  set w := multiWeight b
  set φ : MvPolynomial σ K →ₗ[K] MvPolynomial σ K := LinearMap.mulRight K g
  have hφ : Function.Injective φ := fun p q h ↦ mul_right_cancel₀ hg0 h
  set A := J.restrictScalars K ⊓ weightedHomogeneousSubmodule K w (d + e)
  set B := (weightedHomogeneousSubmodule K w d).map φ
  have hsup : (J ⊔ Ideal.span {g}).restrictScalars K ⊓
      weightedHomogeneousSubmodule K w (d + e) = A ⊔ B := by
    apply le_antisymm
    · rintro x ⟨hxJ, hxΓ⟩
      obtain ⟨j, hj, y, hy, rfl⟩ := Submodule.mem_sup.mp hxJ
      obtain ⟨a, rfl⟩ := Ideal.mem_span_singleton'.mp hy
      have hx : j + a * g = weightedHomogeneousComponent w (d + e) (j + a * g) :=
        ((mem_weightedHomogeneousSubmodule K w _ _).mp hxΓ).weightedHomogeneousComponent_same.symm
      rw [hx, map_add, hg.weightedHomogeneousComponent_add_mul]
      refine Submodule.add_mem_sup ⟨hJ hj _, weightedHomogeneousComponent_mem w _ _⟩ ?_
      exact ⟨_, weightedHomogeneousComponent_mem w _ _, rfl⟩
    · refine sup_le (inf_le_inf_right _ ?_) ?_
      · exact Submodule.restrictScalars_mono K le_sup_left
      · rintro x ⟨p, hp, rfl⟩
        refine ⟨?_, ?_⟩
        · exact (le_sup_right : Ideal.span {g} ≤ J ⊔ Ideal.span {g})
            (Ideal.mem_span_singleton'.mpr ⟨p, rfl⟩)
        · exact ((mem_weightedHomogeneousSubmodule K w _ _).mp hp).mul hg
  have hinf : A ⊓ B = ((J.colon {g}).restrictScalars K ⊓
      weightedHomogeneousSubmodule K w d).map φ := by
    ext x
    constructor
    · rintro ⟨⟨hxJ, _⟩, p, hp, rfl⟩
      refine ⟨p, ⟨?_, hp⟩, rfl⟩
      change p ∈ J.colon {g}
      rw [Submodule.mem_colon_singleton, smul_eq_mul]
      exact hxJ
    · rintro ⟨p, ⟨hpJ, hp⟩, rfl⟩
      change p ∈ J.colon {g} at hpJ
      rw [Submodule.mem_colon_singleton, smul_eq_mul] at hpJ
      exact ⟨⟨hpJ, ((mem_weightedHomogeneousSubmodule K w _ _).mp hp).mul hg⟩, p, hp, rfl⟩
  have hdim := Submodule.finrank_sup_add_finrank_inf_eq A B
  rw [← hsup, hinf, ← (Submodule.equivMapOfInjective φ hφ _).finrank_eq,
    ← (Submodule.equivMapOfInjective φ hφ _).finrank_eq] at hdim
  exact hdim

end Blocks

end MvPolynomial
