/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ForMathlib.RingTheory.MvPolynomial.ExcessBezout
public import ForMathlib.RingTheory.MvPolynomial.Multiplicity

/-!
# Multiplicity against degree

The degree inequality at the heart of the product theorem (G. Rémond, *Sur le théorème du
produit*, J. Théor. Nombres Bordeaux **13** (2001), the chain of Prop. 3.1, Lemma 3.1 and
Prop. 3.2 in the proof of Prop. 2.1, degree part). Let `I` be generated by multihomogeneous
polynomials of multidegree `e`, and `𝔭` a multihomogeneous prime of height `t`, minimal over `I`.
Suppose `Q_1, …, Q_t ∈ 𝔭` and directions `v_1, …, v_t` with `∂Q_β/∂X_{v_α} ∈ 𝔭` exactly when
`α ≠ β`, and that every element of `I` vanishes at the generic point of `𝔭` to weighted order
`> ε`, the direction `v_α` having weight `1/δ_α`. Then for `|β| ≥ |n| - t`
`ε^t (∏_α δ_α) d_β(𝔭) ≤ ∑_{f : β + ∑ ε_{f j} = n} ∏ j, e (f j)`.

The two sides meet in a length: the excess Bézout inequality bounds `ℓ(B_𝔭/(P)B_𝔭) d_β(𝔭)` from
above for suitable `P_1, …, P_t ∈ I` (`MvPolynomial.exists_localLength_mul_multidegree_le`), and
the multiplicity estimate bounds `ℓ(B_𝔭/(P)B_𝔭)` from below by `ε^t ∏ δ_α`
(`MvPolynomial.prod_mul_pow_le_localLength`).

One input remains a hypothesis: the existence of the `Q_α` and `v_α`, which Rémond derives from
exact sequences of Kähler differentials (Rémond 2001, §4), with
`#{α : v_α in the i-th factor} = ht 𝔭_i - ht 𝔭_{i+1}` for the traces `𝔭_i` of `𝔭`.

## Main statements

* `MvPolynomial.prod_mul_pow_mul_multidegree_le`: `ε^t (∏ δ_α) d_β(𝔭) ≤` the Bézout number.
-/

@[expose] public section

open Finset

namespace MvPolynomial

variable {σ ι K : Type*} [Field K] [DecidableEq ι] {b : σ → ι} [Finite σ] [DecidableEq σ]
  [Fintype ι] {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]

/-- **Multiplicity against degree** (Rémond 2001, proof of Prop. 2.1, degree part). If `I` is
generated by multihomogeneous polynomials of multidegree `e` and vanishes at the generic point of
the multihomogeneous minimal prime `𝔭` of height `t` to weighted order `> ε` along `t` transversal
directions of weights `1/δ_α`, then `ε^t (∏ δ_α) d_β(𝔭)` is at most the Bézout number. -/
theorem prod_mul_pow_mul_multidegree_le [Infinite K] (hb : Function.Surjective b)
    {e : ι → ℕ} {R : Set (MvPolynomial σ K)}
    (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r e)
    (h𝔭R : 𝔭 ∈ (Ideal.span R).minimalPrimes) (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} (ht : 𝔭.height = t) {v : Fin t → σ}
    {Q : Fin t → MvPolynomial σ K} (hQ : ∀ α, Q α ∈ 𝔭)
    (hoff : ∀ α β, α ≠ β → pderiv (v α) (Q β) ∈ 𝔭) (hdiag : ∀ α, pderiv (v α) (Q α) ∉ 𝔭)
    {δ : Fin t → ℕ} (hδ : ∀ α, 0 < δ α) {ε : ℝ} (hε : 0 < ε)
    (hI : Ideal.span R ≤ (weightIdeal (fun α ↦ ((δ α : ℝ))⁻¹) ε).comap (taylorAtPrime 𝔭 v))
    (β : ι →₀ ℕ) (hβ : (bottomType b).degree - t ≤ β.degree) :
    (∏ α, (δ α : ℝ)) * ε ^ t * multidegree b 𝔭 β ≤
      ∑ f : Fin t → ι with β + ∑ j, Finsupp.single (f j) 1 = bottomType b,
        ∏ j, (e (f j) : ℝ) := by
  obtain ⟨P, hP, ℓ, hℓ, hdim, hbound⟩ :=
    exists_localLength_mul_multidegree_le hb hR h𝔭R h𝔭 hne ht
  have hx : ∀ j, P j ∈ Ideal.span R := fun j ↦
    Submodule.span_le_restrictScalars K (MvPolynomial σ K) R (hP j)
  have hmult := prod_mul_pow_le_localLength hQ hoff hdiag hδ hε hI hx hℓ
  obtain ⟨m, hm⟩ := exists_multidegree_eq_natCast hb h𝔭 (hdim.trans hβ)
  have hb' := hbound β hβ
  rw [hm] at hb' ⊢
  have hb'' : ((ℓ * m : ℚ) : ℝ) ≤
      ((∑ f : Fin t → ι with β + ∑ j, Finsupp.single (f j) 1 = bottomType b,
        ∏ j, (e (f j) : ℚ) : ℚ) : ℝ) := Rat.cast_le.mpr hb'
  push_cast at hb'' ⊢
  exact (mul_le_mul_of_nonneg_right hmult (Nat.cast_nonneg _)).trans hb''

end MvPolynomial
