/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ForMathlib.RingTheory.MvPolynomial.Transversal
public import Mathlib.Combinatorics.Matroid.Map
public import Mathlib.Combinatorics.Matroid.Rank.ENat

/-!
# When a prime is a component of a product

Let `𝔭` be a prime of `B = K[X_s : s ∈ σ]` and `x_s = X_s mod 𝔭`. The sets of variables whose
classes are algebraically independent over `K` form a matroid on `σ` (`MvPolynomial.varMatroid`,
pulled back from Mathlib's algebraic matroid of `B/𝔭`); its rank function `r(S)` is the
transcendence degree of `K[x_S]`.

With the variables in blocks `b : σ → ι`, `𝔭` is a minimal prime of the ideal generated by its
traces `𝔭 ∩ K[X_s : b s = i]` on the blocks as soon as `∑_i r(block i) ≤ r(σ)`
(`MvPolynomial.mem_minimalPrimes_span_of_sum_eRk_le`): geometrically, the subvariety is a
component of the product of its projections. A transcendence basis of each block then makes a
transcendence basis of `B/𝔭`, and every `x_s` satisfies, over the basis of its block, a relation
lying in the trace of `𝔭` on that block, which persists modulo every prime between the traces and
`𝔭`.

For blocks indexed by `Fin m`, the inequality `∑_i r(block i) ≤ r(σ)` follows from
`r(P_k) + r(σ \ P_k) ≤ r(σ)` at every cut `P_k = {s | b s < k}`, by submodularity
(`MvPolynomial.sum_eRk_le_of_forall_cut`). This is how Rémond concludes the product theorem
(G. Rémond, *Sur le théorème du produit*, J. Théor. Nombres Bordeaux **13** (2001), proof of
Prop. 2.1), with heights of primes in place of ranks.

## Main definitions

* `MvPolynomial.varMatroid 𝔭`: the algebraic matroid of the variables modulo `𝔭`.

## Main statements

* `MvPolynomial.varMatroid_indep_iff`, `MvPolynomial.varMatroid_isBasis`,
  `MvPolynomial.eRk_varMatroid_eq`: independence, bases and ranks in terms of algebraic
  independence and algebraicity.
* `MvPolynomial.mem_minimalPrimes_span_of_sum_eRk_le`: `𝔭` is minimal over its block traces.
* `MvPolynomial.sum_eRk_le_of_forall_cut`: the block ranks from the cuts.
-/

@[expose] public section

open Finset

namespace MvPolynomial

variable {σ K : Type*} [Field K]

section Matroid

section Domain

variable {A : Type*} [CommRing A] [IsDomain A] [Algebra K A] (x : σ → A)

theorem comap_matroid_indep_iff {I : Set σ} :
    ((AlgebraicIndependent.matroid K A).comap x).Indep I ↔ AlgebraicIndepOn K x I := by
  rw [Matroid.comap_indep_iff, AlgebraicIndependent.matroid_indep_iff]
  refine ⟨fun h ↦ ?_, fun h ↦ ⟨h.image, Set.injOn_iff_injective.mpr h.injective⟩⟩
  exact (algebraicIndependent_equiv' (Equiv.Set.imageOfInjOn _ I h.2)
    (f := fun y : x '' I ↦ (y : A)) (funext fun t ↦ rfl)).mpr h.1

theorem comap_matroid_isBasis {W S : Set σ} (hWS : W ⊆ S) (hW : AlgebraicIndepOn K x W)
    (hS : ∀ s ∈ S, IsAlgebraic (Algebra.adjoin K (x '' W)) (x s)) :
    ((AlgebraicIndependent.matroid K A).comap x).IsBasis W S := by
  have hI := (comap_matroid_indep_iff x).mpr hW
  rw [Matroid.comap_indep_iff] at hI
  rw [Matroid.comap_isBasis_iff, AlgebraicIndependent.matroid_isBasis_iff]
  refine ⟨⟨(AlgebraicIndependent.matroid_indep_iff).mp hI.1, Set.image_mono hWS, ?_⟩, hI.2, hWS⟩
  rintro _ ⟨s, hs, rfl⟩
  exact hS s hs

theorem mem_closure_comap_matroid {U : Set σ} {s : σ}
    (h : IsAlgebraic (Algebra.adjoin K (x '' U)) (x s)) :
    s ∈ ((AlgebraicIndependent.matroid K A).comap x).closure U := by
  rw [Matroid.comap_closure_eq, Set.mem_preimage, AlgebraicIndependent.matroid_closure_eq,
    SetLike.mem_coe, Subalgebra.mem_algebraicClosure]
  exact h

end Domain

variable (𝔭 : Ideal (MvPolynomial σ K)) [𝔭.IsPrime]

/-- The algebraic matroid of the variables modulo `𝔭`: a set of variables is independent when
their classes in `B/𝔭` are algebraically independent over `K`. -/
noncomputable def varMatroid : Matroid σ :=
  (AlgebraicIndependent.matroid K (MvPolynomial σ K ⧸ 𝔭)).comap
    fun s ↦ Ideal.Quotient.mk 𝔭 (X s)

variable {𝔭}

theorem varMatroid_indep_iff {I : Set σ} :
    (varMatroid 𝔭).Indep I ↔ AlgebraicIndepOn K (fun s ↦ Ideal.Quotient.mk 𝔭 (X s)) I :=
  comap_matroid_indep_iff _

/-- A basis of `S`: independent variables `W ⊆ S` over which every `x_s`, `s ∈ S`, is
algebraic. -/
theorem varMatroid_isBasis {W S : Set σ} (hWS : W ⊆ S)
    (hW : AlgebraicIndepOn K (fun s ↦ Ideal.Quotient.mk 𝔭 (X s)) W)
    (hS : ∀ s ∈ S, IsAlgebraic (Algebra.adjoin K ((fun t ↦ Ideal.Quotient.mk 𝔭 (X t)) '' W))
      (Ideal.Quotient.mk 𝔭 (X s))) :
    (varMatroid 𝔭).IsBasis W S :=
  comap_matroid_isBasis _ hWS hW hS

theorem eRk_varMatroid_eq [Finite σ] {W S : Set σ} (hWS : W ⊆ S)
    (hW : AlgebraicIndepOn K (fun s ↦ Ideal.Quotient.mk 𝔭 (X s)) W)
    (hS : ∀ s ∈ S, IsAlgebraic (Algebra.adjoin K ((fun t ↦ Ideal.Quotient.mk 𝔭 (X t)) '' W))
      (Ideal.Quotient.mk 𝔭 (X s))) :
    (varMatroid 𝔭).eRk S = W.ncard := by
  rw [(varMatroid_isBasis hWS hW hS).eRk_eq_encard, (Set.toFinite W).cast_ncard_eq]

/-- Every variable algebraic over `K[x_U]` lies in the closure of `U`. -/
theorem mem_closure_varMatroid {U : Set σ} {s : σ}
    (h : IsAlgebraic (Algebra.adjoin K ((fun t ↦ Ideal.Quotient.mk 𝔭 (X t)) '' U))
      (Ideal.Quotient.mk 𝔭 (X s))) :
    s ∈ (varMatroid 𝔭).closure U :=
  mem_closure_comap_matroid _ h

end Matroid

section Blocks

variable {ι : Type*} [Fintype ι] (b : σ → ι) (𝔭 : Ideal (MvPolynomial σ K)) [𝔭.IsPrime]

/-- **`𝔭` is minimal over its traces on the blocks** when the ranks of the blocks add up to at
most the rank of `σ`: geometrically, `V(𝔭)` is a component of the product of its projections to
the factors. -/
theorem mem_minimalPrimes_span_of_sum_eRk_le [CharZero K] [Finite σ]
    (h : ∑ i, (varMatroid 𝔭).eRk {s | b s = i} ≤ (varMatroid 𝔭).eRk Set.univ) :
    𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes := by
  classical
  have := Fintype.ofFinite σ
  set x : σ → MvPolynomial σ K ⧸ 𝔭 := fun t ↦ Ideal.Quotient.mk 𝔭 (X t) with hx
  -- A transcendence basis `W i` of each block.
  have hW : ∀ i, ∃ W : Finset σ, (W : Set σ) ⊆ {s | b s = i} ∧ AlgebraicIndepOn K x W ∧
      ∀ s, b s = i → s ∉ W → IsAlgebraic (Algebra.adjoin K (x '' W)) (x s) := by
    intro i
    obtain ⟨W, hWS, hW, halg⟩ := exists_algebraicIndepOn_isAlgebraic (K := K) x
      (fun _ ↦ (0 : ℕ)) (univ.filter (b · = i))
    refine ⟨W, fun s hs ↦ by simpa using hWS hs, hW, fun s hs hsW ↦ ?_⟩
    have : {t | t ∈ W ∧ (0 : ℕ) ≤ 0} = (W : Set σ) := Set.ext fun t ↦ by simp
    rw [← this]
    exact halg s (by simp [hs]) hsW
  choose W hWb hWi hWa using hW
  have hWalg : ∀ i, ∀ s, b s = i →
      IsAlgebraic (Algebra.adjoin K (x '' (W i : Set σ))) (x s) := by
    intro i s hs
    by_cases hsW : s ∈ W i
    · exact isAlgebraic_algebraMap (⟨_, Algebra.subset_adjoin ⟨s, hsW, rfl⟩⟩ :
        Algebra.adjoin K (x '' (W i : Set σ)))
    · exact hWa i s hs hsW
  set U := univ.biUnion W
  have hWU : ∀ i, (W i : Set σ) ⊆ U := fun i s hs ↦ by
    simp only [U, coe_biUnion, coe_univ, Set.mem_univ, Set.iUnion_true, Set.mem_iUnion]
    exact ⟨i, hs⟩
  have hspan : ∀ s, IsAlgebraic (Algebra.adjoin K (x '' (U : Set σ))) (x s) := fun s ↦
    (hWalg (b s) s rfl).tower_top_of_subalgebra_le
      (Algebra.adjoin_mono (Set.image_mono (hWU (b s))))
  have hrk : ∀ i, (varMatroid 𝔭).eRk {s | b s = i} = #(W i) := by
    intro i
    rw [eRk_varMatroid_eq (hWb i) (hWi i) fun s hs ↦ hWalg i s hs, Set.ncard_coe_finset]
  -- `U` is independent: it spans, and it is no larger than the rank.
  have hU : (varMatroid 𝔭).Indep (U : Set σ) := by
    rw [Matroid.indep_iff_eRk_eq_encard_of_finite (Set.toFinite _)]
    refine le_antisymm (Matroid.eRk_le_encard _ _) ?_
    have hcl : Set.univ ⊆ (varMatroid 𝔭).closure (U : Set σ) := fun s _ ↦
      mem_closure_varMatroid (hspan s)
    calc (U : Set σ).encard = (#U : ℕ∞) := Set.encard_coe_eq_coe_finsetCard U
      _ ≤ ∑ i, (#(W i) : ℕ∞) := by exact_mod_cast card_biUnion_le
      _ = ∑ i, (varMatroid 𝔭).eRk {s | b s = i} := by simp only [hrk]
      _ ≤ (varMatroid 𝔭).eRk Set.univ := h
      _ ≤ (varMatroid 𝔭).eRk ((varMatroid 𝔭).closure (U : Set σ)) := Matroid.eRk_mono _ hcl
      _ = (varMatroid 𝔭).eRk (U : Set σ) := Matroid.eRk_closure_eq _ _
  rw [varMatroid_indep_iff] at hU
  set J := Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}
  have hJ : J ≤ 𝔭 := Ideal.span_le.mpr fun f hf ↦ hf.1
  refine mem_minimalPrimes_of_forall_isAlgebraic 𝔭 hU hJ fun 𝔮 _ hJ𝔮 h𝔮𝔭 s ↦ ?_
  by_cases hs : s ∈ W (b s)
  · exact isAlgebraic_algebraMap (⟨_, Algebra.subset_adjoin ⟨s, hWU (b s) hs, rfl⟩⟩ :
      Algebra.adjoin K ((fun t ↦ Ideal.Quotient.mk 𝔮 (X t)) '' (U : Set σ)))
  obtain ⟨Q, hQ, -, -, h𝔮, hQs⟩ := exists_mem_pderiv_notMem_of_isAlgebraic 𝔭
    (W := (W (b s) : Set σ)) hs (hWa (b s) s rfl hs)
  have hsub : insert s (W (b s) : Set σ) ⊆ {t | b t = b s} :=
    Set.insert_subset_iff.mpr ⟨(rfl : b s = b s), hWb (b s)⟩
  have hQJ : Q ∈ J := by
    refine Ideal.subset_span ?_
    rw [Set.mem_ofPred_eq]
    exact ⟨hQ, b s, supported_mono hsub hQs⟩
  exact (h𝔮 𝔮 h𝔮𝔭 (hJ𝔮 hQJ)).tower_top_of_subalgebra_le
    (Algebra.adjoin_mono (Set.image_mono (hWU (b s))))

end Blocks

section Cuts

variable {m : ℕ} (b : σ → Fin m) (M : Matroid σ)

/-- **Block ranks from the cuts.** If `r(P_k) + r(σ \ P_k) ≤ r(σ)` for the cuts
`P_k = {s | b s < k}`, then `∑_i r(block i) ≤ r(σ)`: by submodularity
`r(block k) + r(σ) ≤ r(P_{k+1}) + r(σ \ P_k)`, so `r(block k) + r(σ \ P_{k+1}) ≤ r(σ \ P_k)`. -/
theorem sum_eRk_le_of_forall_cut (hfin : M.eRk Set.univ ≠ ⊤)
    (h : ∀ k : ℕ, M.eRk {s | (b s : ℕ) < k} + M.eRk {s | k ≤ (b s : ℕ)} ≤ M.eRk Set.univ) :
    ∑ i, M.eRk {s | b s = i} ≤ M.eRk Set.univ := by
  classical
  have hstep : ∀ k : ℕ, M.eRk {s | (b s : ℕ) = k} + M.eRk {s | k + 1 ≤ (b s : ℕ)} ≤
      M.eRk {s | k ≤ (b s : ℕ)} := by
    intro k
    have hsub := M.eRk_inter_add_eRk_union_le {s | (b s : ℕ) < k + 1} {s | k ≤ (b s : ℕ)}
    have hinter : {s | (b s : ℕ) < k + 1} ∩ {s | k ≤ (b s : ℕ)} = {s | (b s : ℕ) = k} := by
      ext s
      simp only [Set.mem_inter_iff, Set.mem_ofPred_eq]
      omega
    have hunion : {s | (b s : ℕ) < k + 1} ∪ {s | k ≤ (b s : ℕ)} = Set.univ := by
      ext s
      simp only [Set.mem_union, Set.mem_ofPred_eq, Set.mem_univ, iff_true]
      omega
    rw [hinter, hunion] at hsub
    have hcut := h (k + 1)
    have : M.eRk {s | (b s : ℕ) = k} + M.eRk {s | k + 1 ≤ (b s : ℕ)} + M.eRk Set.univ ≤
        M.eRk {s | k ≤ (b s : ℕ)} + M.eRk Set.univ :=
      calc M.eRk {s | (b s : ℕ) = k} + M.eRk {s | k + 1 ≤ (b s : ℕ)} + M.eRk Set.univ
          = (M.eRk {s | (b s : ℕ) = k} + M.eRk Set.univ) + M.eRk {s | k + 1 ≤ (b s : ℕ)} := by
            ring
        _ ≤ (M.eRk {s | (b s : ℕ) < k + 1} + M.eRk {s | k ≤ (b s : ℕ)}) +
            M.eRk {s | k + 1 ≤ (b s : ℕ)} := add_le_add hsub le_rfl
        _ = (M.eRk {s | (b s : ℕ) < k + 1} + M.eRk {s | k + 1 ≤ (b s : ℕ)}) +
            M.eRk {s | k ≤ (b s : ℕ)} := by ring
        _ ≤ M.eRk Set.univ + M.eRk {s | k ≤ (b s : ℕ)} := add_le_add hcut le_rfl
        _ = M.eRk {s | k ≤ (b s : ℕ)} + M.eRk Set.univ := add_comm _ _
    exact (ENat.add_le_add_iff_right hfin).mp this
  -- Induction along the cuts.
  have hind : ∀ k : ℕ, ∑ i ∈ univ.filter (fun i : Fin m ↦ (i : ℕ) < k), M.eRk {s | b s = i} +
      M.eRk {s | k ≤ (b s : ℕ)} ≤ M.eRk Set.univ := by
    intro k
    induction k with
    | zero =>
      simp
    | succ k ih =>
      by_cases hk : k < m
      · have hfilter : univ.filter (fun i : Fin m ↦ (i : ℕ) < k + 1) =
            insert ⟨k, hk⟩ (univ.filter fun i : Fin m ↦ (i : ℕ) < k) := by
          ext i
          simp only [mem_filter, mem_univ, true_and, mem_insert, Fin.ext_iff]
          omega
        rw [hfilter, sum_insert (by simp)]
        have hblock : {s | b s = (⟨k, hk⟩ : Fin m)} = {s | (b s : ℕ) = k} := by
          ext s
          simp [Fin.ext_iff]
        rw [hblock, add_comm (M.eRk _), add_assoc]
        exact (add_le_add le_rfl (hstep k)).trans ih
      · have hfilter : univ.filter (fun i : Fin m ↦ (i : ℕ) < k + 1) =
            univ.filter fun i : Fin m ↦ (i : ℕ) < k := by
          ext i
          simp only [mem_filter, mem_univ, true_and]
          omega
        have hempty : {s | k + 1 ≤ (b s : ℕ)} = (∅ : Set σ) := by
          ext s
          simp only [Set.mem_ofPred_eq, Set.mem_empty_iff_false, iff_false, not_le]
          omega
        rw [hfilter, hempty, Matroid.eRk_empty, add_zero]
        exact le_self_add.trans ih
  have := hind m
  have hfilter : univ.filter (fun i : Fin m ↦ (i : ℕ) < m) = univ := by
    ext i
    simp
  rw [hfilter] at this
  exact le_self_add.trans this

end Cuts

end MvPolynomial
