/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ForMathlib.RingTheory.MvPolynomial.Elimination

-- Used only inside proofs.
import Mathlib.Algebra.Order.Sub.Prod
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.MvPolynomial.Localization

/-!
# Saturation by the irrelevant ideal

The saturation `J : 𝔪^∞ = ⋃_n (J : 𝔪^n)` of an ideal `J` of `R[X]` by the irrelevant ideal `𝔪` of
`ℙ^{n_1} × ⋯ × ℙ^{n_q}`. The characteristic ideal `𝔄_d(I)` of `MvPolynomial.charIdeal` is the
saturation of `I[d]`.

For a multihomogeneous `J` over a Noetherian ring, `J : 𝔪^∞` and `J` agree in all multidegrees
`d ≥ d₀` (`MvPolynomial.exists_forall_le_mem_of_mem_saturation`): the saturation is `J : 𝔪^k` for
one `k`, it is generated by finitely many homogeneous elements, and a homogeneous polynomial of
multidegree `≥ (k, …, k)` lies in `𝔪^k`. Over a field, `J` and `J : 𝔪^∞` therefore have the same
Hilbert polynomial (`MvPolynomial.hilbertPoly_saturation`). This is the step "`N` is killed by
a power of `𝔪`, so `H_{L[X]/(𝔭'', U_1)} = H_{L[X]/𝔮}`" of the proof of Rémond's Lemma 2.12
(G. Rémond, *Élimination multihomogène*, Chapter 5 of Nesterenko–Philippon (eds.), *Introduction
to algebraic independence theory*, LNM 1752 (2001)).

## Main statements

* `MvPolynomial.saturation`: `J : 𝔪^∞`.
* `MvPolynomial.mem_irrelevantIdeal_pow`: a homogeneous polynomial of multidegree `≥ (k, …, k)`
  lies in `𝔪^k`.
* `MvPolynomial.isWeightedHomogeneous_saturation`: the saturation of a multihomogeneous ideal is
  multihomogeneous.
* `MvPolynomial.exists_forall_le_mem_of_mem_saturation`: `J : 𝔪^∞` and `J` agree in large
  multidegrees.
* `MvPolynomial.hilbertPoly_saturation`: `H_{J : 𝔪^∞} = H_J`.
* `MvPolynomial.map_saturation`: saturation commutes with localization of the coefficients.
-/

@[expose] public section

open Finset Module

namespace MvPolynomial

variable {σ ι : Type*} [Fintype σ] [Fintype ι] [DecidableEq ι] {b : σ → ι}

section Ring

variable {R : Type*} [CommRing R]

variable (b) in
/-- The saturation `J : 𝔪^∞` of an ideal by the irrelevant ideal. -/
noncomputable def saturation (J : Ideal (MvPolynomial σ R)) : Ideal (MvPolynomial σ R) :=
  ⨆ n : ℕ, J.colon (irrelevantIdeal R b ^ n : Set _)

theorem charIdeal_eq_saturation {κ : Type*} (d : κ → ι → ℕ) (I : Ideal (MvPolynomial σ R)) :
    charIdeal R b d I = saturation b (genericIdeal R b d I) :=
  rfl

theorem mem_saturation {J : Ideal (MvPolynomial σ R)} {f : MvPolynomial σ R} :
    f ∈ saturation b J ↔ ∃ n, ∀ g ∈ irrelevantIdeal R b ^ n, g * f ∈ J := by
  rw [saturation, Submodule.mem_iSup_of_directed]
  · simp [Submodule.mem_colon, mul_comm]
  · refine Monotone.directed_le fun m n hmn ↦ Submodule.colon_mono le_rfl ?_
    exact Ideal.pow_le_pow_right hmn

theorem colon_le_saturation (J : Ideal (MvPolynomial σ R)) (n : ℕ) :
    J.colon (irrelevantIdeal R b ^ n : Set _) ≤ saturation b J :=
  le_iSup (fun n : ℕ ↦ J.colon (irrelevantIdeal R b ^ n : Set _)) n

theorem le_saturation (J : Ideal (MvPolynomial σ R)) : J ≤ saturation b J :=
  fun _ hf ↦ mem_saturation.mpr ⟨0, fun g _ ↦ J.mul_mem_left g hf⟩

/-- A homogeneous polynomial of multidegree `≥ (k, …, k)` lies in `𝔪^k`. -/
theorem mem_irrelevantIdeal_pow {k : ℕ} {e : ι → ℕ} (he : ∀ i, k ≤ e i)
    {p : MvPolynomial σ R} (hp : IsWeightedHomogeneous (multiWeight b) p e) :
    p ∈ irrelevantIdeal R b ^ k := by
  rw [p.as_sum]
  refine Ideal.sum_mem _ fun c hc ↦ ?_
  rw [← mul_one (p.coeff c), ← smul_eq_mul, ← smul_monomial, smul_eq_C_mul]
  refine Ideal.mul_mem_left _ _ (monomial_mem_irrelevantIdeal_pow_of_le R b k fun i ↦ ?_)
  rw [hp (mem_support_iff.mp hc)]
  exact he i

/-- `f ∈ J : 𝔪^k` if and only if `X^c f ∈ J` for every monomial `X^c` of multidegree
`(k, …, k)`. -/
theorem mem_colon_irrelevantIdeal_pow_iff {J : Ideal (MvPolynomial σ R)} {k : ℕ}
    {f : MvPolynomial σ R} :
    f ∈ J.colon (irrelevantIdeal R b ^ k : Set _) ↔
      ∀ c, Finsupp.weight (multiWeight b) c = (fun _ ↦ k) → monomial c 1 * f ∈ J := by
  rw [Submodule.mem_colon]
  refine ⟨fun h c hc ↦ ?_, fun h g hg ↦ ?_⟩
  · rw [mul_comm, ← smul_eq_mul]
    exact h _ (monomial_mem_irrelevantIdeal_pow R b k hc)
  · have hle : Ideal.span ((fun c ↦ monomial c (1 : R)) ''
        {c | Finsupp.weight (multiWeight b) c = fun _ ↦ k}) ≤ J.colon {f} := by
      refine Ideal.span_le.mpr ?_
      rintro _ ⟨c, hc, rfl⟩
      rw [SetLike.mem_coe, Submodule.mem_colon_singleton, smul_eq_mul]
      exact h c hc
    have := hle (irrelevantIdeal_pow_le R b k hg)
    rw [Submodule.mem_colon_singleton, smul_eq_mul, mul_comm] at this
    rwa [smul_eq_mul]

/-- The colon ideal `J : 𝔪^k` of a multihomogeneous ideal is multihomogeneous. -/
theorem isWeightedHomogeneous_colon_irrelevantIdeal_pow {J : Ideal (MvPolynomial σ R)}
    (hJ : J.IsWeightedHomogeneous (multiWeight b)) (k : ℕ) :
    (J.colon (irrelevantIdeal R b ^ k : Set _)).IsWeightedHomogeneous (multiWeight b) := by
  intro f hf d
  rw [mem_colon_irrelevantIdeal_pow_iff] at hf ⊢
  intro c hc
  have h := hJ (hf c hc) (d + Finsupp.weight (multiWeight b) c)
  rwa [mul_comm, (isWeightedHomogeneous_monomial (multiWeight b) c (1 : R)
    rfl).weightedHomogeneousComponent_add_mul, mul_comm] at h

variable [IsNoetherianRing R]

/-- Over a Noetherian ring, the saturation is `J : 𝔪^k` for some `k`. -/
theorem exists_saturation_eq_colon (J : Ideal (MvPolynomial σ R)) :
    ∃ k : ℕ, saturation b J = J.colon (irrelevantIdeal R b ^ k : Set _) := by
  have hmono : Monotone fun n : ℕ ↦
      J.colon ((irrelevantIdeal R b ^ n : Ideal (MvPolynomial σ R)) : Set (MvPolynomial σ R)) :=
    fun m n hmn ↦ Submodule.colon_mono le_rfl (Ideal.pow_le_pow_right hmn)
  obtain ⟨k, hk⟩ := monotone_stabilizes_iff_noetherian.mpr inferInstance ⟨_, hmono⟩
  refine ⟨k, le_antisymm (iSup_le fun n ↦ ?_) (le_iSup (fun n : ℕ ↦
    J.colon ((irrelevantIdeal R b ^ n : Ideal (MvPolynomial σ R)) : Set (MvPolynomial σ R))) k)⟩
  rcases le_total n k with h | h
  · exact hmono h
  · exact (hk n h).symm.le

/-- The saturation of a multihomogeneous ideal is multihomogeneous. -/
theorem isWeightedHomogeneous_saturation {J : Ideal (MvPolynomial σ R)}
    (hJ : J.IsWeightedHomogeneous (multiWeight b)) :
    (saturation b J).IsWeightedHomogeneous (multiWeight b) := by
  obtain ⟨k, hk⟩ := exists_saturation_eq_colon (b := b) J
  rw [hk]
  exact isWeightedHomogeneous_colon_irrelevantIdeal_pow hJ k

/-- **`J : 𝔪^∞` and `J` agree in large multidegrees.** -/
theorem exists_forall_le_mem_of_mem_saturation {J : Ideal (MvPolynomial σ R)}
    (hJ : J.IsWeightedHomogeneous (multiWeight b)) :
    ∃ d₀ : ι → ℕ, ∀ d, d₀ ≤ d → ∀ f ∈ saturation b J,
      IsWeightedHomogeneous (multiWeight b) f d → f ∈ J := by
  classical
  obtain ⟨k, hk⟩ := exists_saturation_eq_colon (b := b) J
  have hsat := isWeightedHomogeneous_saturation hJ
  obtain ⟨G, hG⟩ := (IsNoetherian.noetherian (saturation b J) :
    (saturation b J).FG)
  set E := G.biUnion fun g ↦ g.support.image (Finsupp.weight (multiWeight b))
  refine ⟨fun i ↦ k + E.sup fun e ↦ e i, fun d hd f hf hfd ↦ ?_⟩
  rw [← hG, Submodule.mem_span_finset] at hf
  obtain ⟨a, -, rfl⟩ := hf
  rw [← hfd.weightedHomogeneousComponent_same, map_sum]
  refine J.sum_mem fun g hg ↦ ?_
  have hgsat : g ∈ saturation b J := hG ▸ Ideal.subset_span hg
  generalize a g = A
  rw [smul_eq_mul, ← sum_weightedHomogeneousComponent_image (w := multiWeight b) g,
    Finset.mul_sum, map_sum]
  refine J.sum_mem fun e he ↦ ?_
  have heE : e ∈ E := Finset.mem_biUnion.mpr ⟨g, hg, he⟩
  have hed : e ≤ d := fun i ↦ (Finset.le_sup (f := fun e ↦ e i) heE).trans
    ((Nat.le_add_left _ _).trans (hd i))
  rw [← tsub_add_cancel_of_le hed,
    (weightedHomogeneousComponent_isWeightedHomogeneous e g).weightedHomogeneousComponent_add_mul,
    mul_comm]
  have hcomp : weightedHomogeneousComponent (multiWeight b) e g ∈
      J.colon (irrelevantIdeal R b ^ k : Set _) := hk ▸ hsat hgsat e
  rw [Submodule.mem_colon] at hcomp
  rw [← smul_eq_mul]
  refine hcomp _ (mem_irrelevantIdeal_pow (fun i ↦ ?_)
    (weightedHomogeneousComponent_isWeightedHomogeneous _ _))
  have h1 : k + E.sup (fun e ↦ e i) ≤ d i := hd i
  have h2 : e i ≤ E.sup (fun e ↦ e i) := Finset.le_sup (f := fun e ↦ e i) heE
  change k ≤ d i - e i
  omega

end Ring

section Localization

variable {R S : Type*} [CommRing R] [CommRing S]

/-- The irrelevant ideal is extended from the coefficients. -/
theorem map_irrelevantIdeal (f : R →+* S) :
    (irrelevantIdeal R b).map (MvPolynomial.map f : MvPolynomial σ R →+* MvPolynomial σ S) =
      irrelevantIdeal S b := by
  rw [irrelevantIdeal, irrelevantIdeal, Ideal.map_span, Set.image_image]
  simp [map_monomial]

variable [Algebra R S] (M : Submonoid R) [IsLocalization M S]

include M in
attribute [local instance] algebraMvPolynomial in
/-- **Saturation commutes with localization of the coefficients.** -/
theorem map_saturation (I : Ideal (MvPolynomial σ R)) :
    (saturation b I).map (MvPolynomial.map (algebraMap R S)) =
      saturation b (I.map (MvPolynomial.map (algebraMap R S))) := by
  classical
  have e : (MvPolynomial.map (algebraMap R S) : MvPolynomial σ R →+* MvPolynomial σ S) =
      algebraMap (MvPolynomial σ R) (MvPolynomial σ S) := rfl
  have hm : ∀ n, (irrelevantIdeal R b ^ n).map (algebraMap (MvPolynomial σ R)
      (MvPolynomial σ S)) = irrelevantIdeal S b ^ n := fun n ↦ by
    rw [Ideal.map_pow, ← e, map_irrelevantIdeal]
  rw [e]
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    intro f hf
    obtain ⟨n, hn⟩ := mem_saturation.mp hf
    refine mem_saturation.mpr ⟨n, fun g hg ↦ ?_⟩
    have hle : (irrelevantIdeal R b ^ n).map (algebraMap (MvPolynomial σ R)
        (MvPolynomial σ S)) ≤ (I.map (algebraMap (MvPolynomial σ R) (MvPolynomial σ S))).colon
          {algebraMap (MvPolynomial σ R) (MvPolynomial σ S) f} := by
      rw [Ideal.map_le_iff_le_comap]
      intro g hg
      rw [Ideal.mem_comap, Submodule.mem_colon_singleton, smul_eq_mul, ← map_mul]
      exact Ideal.mem_map_of_mem _ (hn g hg)
    have := hle (hm n ▸ hg)
    rwa [Submodule.mem_colon_singleton, smul_eq_mul] at this
  · intro f hf
    obtain ⟨n, hn⟩ := mem_saturation.mp hf
    obtain ⟨⟨f₀, m⟩, rfl⟩ := IsLocalization.mk'_surjective (M.map (C (σ := σ))) f
    have hc : ∀ c ∈ blockMonomials b (fun _ ↦ n),
        ∃ s ∈ M.map (C (σ := σ)), s * (monomial c 1 * f₀) ∈ I := by
      intro c hc
      rw [← IsLocalization.mk'_mem_map_algebraMap_iff (M.map (C (σ := σ))) (MvPolynomial σ S)
        I _ m, ← IsLocalization.mul_mk'_eq_mk'_of_mul]
      have := hn (monomial c 1) (monomial_mem_irrelevantIdeal_pow S b n
        (mem_blockMonomials.mp hc))
      rwa [← e, map_monomial, map_one]
    choose s hsM hs using hc
    set t := ∏ c ∈ (blockMonomials b (fun _ ↦ n)).attach, s c.1 c.2
    have htM : t ∈ M.map (C (σ := σ)) := Submonoid.prod_mem _ fun c _ ↦ hsM c.1 c.2
    refine (IsLocalization.mk'_mem_map_algebraMap_iff (M.map (C (σ := σ))) (MvPolynomial σ S)
      _ f₀ m).mpr ⟨t, htM, ?_⟩
    refine colon_le_saturation I n (mem_colon_irrelevantIdeal_pow_iff.mpr fun c hc ↦ ?_)
    have hcb : c ∈ blockMonomials b (fun _ ↦ n) := mem_blockMonomials.mpr hc
    have := I.mul_mem_left (∏ x ∈ (blockMonomials b (fun _ ↦ n)).attach.erase ⟨c, hcb⟩,
      s x.1 x.2) (hs c hcb)
    convert this using 1
    simp only [t]
    rw [← Finset.mul_prod_erase _ (fun x : blockMonomials b (fun _ ↦ n) ↦ s x.1 x.2)
      (Finset.mem_attach _ ⟨c, hcb⟩)]
    ring

end Localization

section Field

variable {K : Type*} [Field K]

/-- `J : 𝔪^∞` and `J` have the same Hilbert function in large multidegrees. -/
theorem exists_forall_le_hilbertFunction_saturation {J : Ideal (MvPolynomial σ K)}
    (hJ : J.IsWeightedHomogeneous (multiWeight b)) :
    ∃ d₀ : ι → ℕ, ∀ d, d₀ ≤ d → hilbertFunction b (saturation b J) d = hilbertFunction b J d := by
  obtain ⟨d₀, hd₀⟩ := exists_forall_le_mem_of_mem_saturation hJ
  refine ⟨d₀, fun d hd ↦ ?_⟩
  have : (saturation b J).restrictScalars K ⊓ weightedHomogeneousSubmodule K (multiWeight b) d =
      J.restrictScalars K ⊓ weightedHomogeneousSubmodule K (multiWeight b) d :=
    le_antisymm (fun f ⟨hf, hfd⟩ ↦ ⟨hd₀ d hd f hf hfd, hfd⟩)
      (inf_le_inf_right _ (Submodule.restrictScalars_mono K (le_saturation J)))
  rw [hilbertFunction, hilbertFunction, this]

/-- **Saturation by the irrelevant ideal keeps the Hilbert polynomial.** -/
theorem hilbertPoly_saturation (hb : Function.Surjective b) {J : Ideal (MvPolynomial σ K)}
    (hJ : J.IsWeightedHomogeneous (multiWeight b)) :
    hilbertPoly b (saturation b J) = hilbertPoly b J := by
  obtain ⟨d₀, hd₀⟩ := exists_forall_le_hilbertFunction_saturation hJ
  obtain ⟨d₁, hd₁⟩ := exists_forall_le_hilbertFunction_eq_hilbertPoly hb hJ
  refine hilbertPoly_eq_of_forall_le hb (isWeightedHomogeneous_saturation hJ)
    (d₀ := d₀ ⊔ d₁) fun d hd ↦ ?_
  rw [hd₀ d (le_sup_left.trans hd), hd₁ d (le_sup_right.trans hd)]

end Field

end MvPolynomial

end
