/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import AdamczewskiBugeaud2007.AutomaticSequence
public import Bugeaud2013.Theorem11
public import Mathlib.FieldTheory.Minpoly.Basic

-- Used only inside proofs.
import AdamczewskiBugeaud2007.AutomaticComplexity
import Mathlib.Algebra.Polynomial.Degree.SmallDegree
import Mathlib.FieldTheory.Minpoly.Field

/-!
# Theorem 1.2 (Bugeaud 2013, §1)

**Theorem 1.2**: the continued fraction expansion of an algebraic number of degree at least
three cannot be generated by a finite automaton.

The paper deduces it from Theorem 1.1 and Cobham's bound `p(n, a) = O(n)` for automatic
sequences, which here is `Function.IsAutomatic.exists_complexity_le` from the
Adamczewski–Bugeaud 2007 library (automaticity is defined there by a finite `k`-kernel).

## Main results

* `Nat.isEventuallyPeriodic_of_isAutomatic`: if `[0; a₁, a₂, …]` is algebraic and `a₁ a₂ …` is
  automatic, then `a₁ a₂ …` is eventually periodic.
* `Nat.not_isAutomatic_of_three_le_natDegree`: **Theorem 1.2**.

## Implementation notes

⚠ **"Degree at least three" is `3 ≤ (minpoly ℚ α).natDegree`.** It implies that `α` is
algebraic: otherwise `minpoly ℚ α = 0`. A degree `≤ 2` is excluded by Euler's theorem
(`Nat.exists_quadratic_of_isEventuallyPeriodic`), since `α` is a root of the quadratic it gives.

⚠ **This file imports another paper library.** Cobham's bound lives in
`AdamczewskiBugeaud2007/AutomaticComplexity.lean`; only this file depends on it.
-/

@[expose] public section

open Filter Polynomial

namespace Nat

variable {a : ℕ → ℕ}

section Positive

variable (ha : ∀ n, 1 ≤ a (n + 1))
include ha

/-- **Algebraic automatic continued fractions are eventually periodic**: if `[0; a₁, a₂, …]` is
algebraic and `a₁ a₂ …` is automatic, then `a₁ a₂ …` is eventually periodic. -/
theorem isEventuallyPeriodic_of_isAutomatic (halg : IsAlgebraic ℚ (contFrac a))
    (haut : Function.IsAutomatic fun k ↦ a (k + 1)) :
    Function.IsEventuallyPeriodic fun k ↦ a (k + 1) := by
  by_contra hp
  obtain ⟨C, hC⟩ := haut.exists_complexity_le
  obtain ⟨n, hn, hn1⟩ := ((tendsto_complexity_div_atTop ha haut.finite_range hp halg).eventually
    (eventually_gt_atTop (C : ℝ))).and (eventually_ge_atTop 1) |>.exists
  have hn0 : (0 : ℝ) < n := by exact_mod_cast hn1
  rw [lt_div_iff₀ hn0] at hn
  have : (Function.complexity (fun k ↦ a (k + 1)) n : ℝ) ≤ C * n := by exact_mod_cast hC n hn1
  linarith

/-- **Theorem 1.2 (Bugeaud 2013).** The continued fraction expansion of an algebraic number of
degree at least three cannot be generated by a finite automaton. -/
theorem not_isAutomatic_of_three_le_natDegree
    (hdeg : 3 ≤ (minpoly ℚ (contFrac a)).natDegree) :
    ¬ Function.IsAutomatic fun k ↦ a (k + 1) := by
  intro haut
  have halg : IsAlgebraic ℚ (contFrac a) := by
    by_contra hn
    rw [minpoly.eq_zero fun hi ↦ hn hi.isAlgebraic, natDegree_zero] at hdeg
    omega
  obtain ⟨A, B, C, hA, h⟩ :=
    exists_quadratic_of_isEventuallyPeriodic ha (isEventuallyPeriodic_of_isAutomatic ha halg haut)
  set p : ℚ[X] := Polynomial.C (A : ℚ) * X ^ 2 + Polynomial.C (B : ℚ) * X + Polynomial.C (C : ℚ)
  have hp2 : p.natDegree = 2 := natDegree_quadratic (by exact_mod_cast hA)
  have hp0 : p ≠ 0 := by
    intro h0
    rw [h0, natDegree_zero] at hp2
    omega
  have hroot : aeval (contFrac a) p = 0 := by
    simp only [p, map_add, map_mul, aeval_C, aeval_X, map_pow, eq_ratCast, Rat.cast_intCast]
    exact h
  have := natDegree_le_natDegree (minpoly.degree_le_of_ne_zero ℚ (contFrac a) hp0 hroot)
  omega

end Positive

end Nat
