/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ForMathlib.RingTheory.MvPolynomial.ExcessBezout
public import QuantitativeSubspace.MultiprojectiveHeight

-- Used only inside proofs.
import ForMathlib.LinearAlgebra.SmallCombination
import ForMathlib.RingTheory.Ideal.LengthPow
import ForMathlib.RingTheory.MvPolynomial.Projection
import ForMathlib.RingTheory.RegularLocalRing.RegularSequence
import Mathlib.RingTheory.Ideal.AssociatedPrime.Finiteness
import Mathlib.RingTheory.Ideal.AssociatedPrime.Localization
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.RegularLocalRing.Polynomial

/-!
# The arithmetic excess Bézout inequality

Let `𝔭` be a multihomogeneous prime of height `t`, minimal over the ideal generated by a finite
family `R` of multihomogeneous polynomials of multidegree `e`, and let `H` be a multiprojective
height theory (`MvPolynomial.MultiprojectiveHeight`). Then there are `P_1, …, P_t`, natural
combinations `P_{j+1} = ∑_r a_r r` of `R` with `∑_r a_r ≤ |e|^j`, such that
`ℓ(K[X]_𝔭/(P)_𝔭) · d_β(𝔭)` obeys the Bézout bound (as in
`MvPolynomial.exists_localLength_mul_multidegree_le`) and
`ℓ(K[X]_𝔭/(P)_𝔭) · h_β(𝔭) ≤ ∑_f ∏_j e_{f j} h_{β + ∑ ε_{f j}}(ℙ) + (∑_j h_m(P_j)) ∑_g ∏_j e_{g j}`
for `|β| = dim 𝔭 + 1`, the sums over the `f : Fin t → ι` and the `g : Fin (t - 1) → ι` that sum
`β` up to the type of `ℙ`. This is the height part of G. Rémond, *Sur le théorème du produit*,
J. Théor. Nombres Bordeaux **13** (2001), Prop. 3.2, before the heights `h_m(P_j)` are estimated.

The proof is Rémond's (§5): the chain `J_k = (P_1, …, P_k) K[X]_𝔭 ∩ K[X]` of
`MvPolynomial.exists_localLength_mul_multidegree_le`, with `P_{k+1}` chosen by
`Submodule.exists_sum_nsmul_forall_notMem` (Rémond's Lemma 5.1) to avoid the `s` associated
primes of `J_k`. These are minimal primes of `J_k` of dimension `|n| - k`, each of positive degree,
so `s ≤ ∑_β d_β(J_k) ≤ |e|^k`. The heights along the chain obey
`h_β(J_{k+1}) ≤ h_β(J_k + (P_{k+1})) ≤ ∑_i e_i h_{β + ε_i}(J_k) + d_β(J_k) h_m(P_{k+1})`, by
`MvPolynomial.cycleHeight_le_of_le` and the intersection inequality of the height theory.

## Main definitions

* `MvPolynomial.bezoutSum`: `∑_{f : Fin k → ι} ∏_j e_{f j} · g(β + ∑_j ε_{f j})`.

## Main statements

* `MvPolynomial.exists_localLength_mul_height_le`: the arithmetic excess Bézout inequality.
-/

@[expose] public section

open Finset

variable {σ ι K : Type*}

namespace MvPolynomial

/-- The Bézout sum `∑_{f : Fin k → ι} ∏_j e_{f j} · g(β + ∑_j ε_{f j})`. -/
noncomputable def bezoutSum [Fintype ι] (e : ι → ℕ) (k : ℕ)
    (g : (ι →₀ ℕ) → ℝ) (β : ι →₀ ℕ) : ℝ :=
  ∑ f : Fin k → ι, (∏ j, (e (f j) : ℝ)) * g (β + ∑ j, Finsupp.single (f j) 1)

theorem bezoutSum_zero [Fintype ι] (e : ι → ℕ) (g : (ι →₀ ℕ) → ℝ)
    (β : ι →₀ ℕ) : bezoutSum e 0 g β = g β := by
  simp [bezoutSum]

/-- One step of the Bézout sum: `S_{k+1}(β) = ∑_i e_i S_k(β + ε_i)`. -/
theorem bezoutSum_succ [Fintype ι] (e : ι → ℕ) (k : ℕ) (g : (ι →₀ ℕ) → ℝ)
    (β : ι →₀ ℕ) :
    bezoutSum e (k + 1) g β = ∑ i, (e i : ℝ) * bezoutSum e k g (β + Finsupp.single i 1) := by
  simp_rw [bezoutSum, Finset.mul_sum]
  rw [← (Fin.consEquiv fun _ : Fin (k + 1) ↦ ι).sum_comp, Fintype.sum_prod_type]
  refine sum_congr rfl fun i _ ↦ sum_congr rfl fun f _ ↦ ?_
  simp only [Fin.consEquiv_apply, Fin.prod_univ_succ, Fin.sum_univ_succ, Fin.cons_zero,
    Fin.cons_succ]
  rw [add_assoc β]
  ring

/-- The Bézout sum against a nonnegative function is monotone in it. -/
theorem bezoutSum_mono [Fintype ι] (e : ι → ℕ) (k : ℕ)
    {g g' : (ι →₀ ℕ) → ℝ} (h : ∀ γ, g γ ≤ g' γ) (β : ι →₀ ℕ) :
    bezoutSum e k g β ≤ bezoutSum e k g' β :=
  sum_le_sum fun _ _ ↦ mul_le_mul_of_nonneg_left (h _)
    (prod_nonneg fun _ _ ↦ Nat.cast_nonneg _)


section Count

variable [Field K] [Finite σ] [Fintype ι] [DecidableEq ι] {b : σ → ι}

omit [DecidableEq ι] in
/-- `|n| + |ι| = |σ|`: the dimension of `ℙ^{n_1} × ⋯ × ℙ^{n_m}`. -/
theorem degree_bottomType_add_card (hb : Function.Surjective b) :
    (bottomType b).degree + Fintype.card ι = Nat.card σ := by
  classical
  have := Fintype.ofFinite σ
  rw [Nat.card_eq_fintype_card]
  have h := degree_coneType_add_card b (V := univ) fun i ↦ by
    obtain ⟨s, hs⟩ := hb i
    exact ⟨s, mem_univ s, hs⟩
  rwa [← bottomType_eq_coneType, card_univ] at h

omit [Finite σ] [DecidableEq ι] in
/-- `∑_{f : Fin k → ι} ∏_j e_{f j} = |e|^k`. -/
theorem sum_prod_eq_pow (e : ι → ℕ) (k : ℕ) :
    ∑ f : Fin k → ι, ∏ j, (e (f j) : ℚ) = ((∑ i, e i : ℕ) : ℚ) ^ k := by
  rw [← Fintype.prod_sum (fun (_ : Fin k) i ↦ (e i : ℚ)), prod_const, card_univ, Fintype.card_fin,
    Nat.cast_sum]

/-- **Counting components** (Rémond 2001, §5). If the degrees of `J` obey the Bézout bound in
dimension `|n| - k`, then `J` has at most `|e|^k` minimal primes of height `k` with `H_𝔮 ≠ 0`:
each of them has dimension `|n| - k` and a positive degree in that dimension. -/
theorem card_le_pow_of_multidegree_le [CharZero K] (hb : Function.Surjective b)
    {J : Ideal (MvPolynomial σ K)} (hJ : J.IsWeightedHomogeneous (multiWeight b)) {k : ℕ}
    (e : ι → ℕ) (hJdeg : (hilbertPoly b J).totalDegree = (bottomType b).degree - k)
    (hbound : ∀ β : ι →₀ ℕ, (bottomType b).degree - k ≤ β.degree →
      multidegree b J β ≤ ∑ f : Fin k → ι, (∏ j, (e (f j) : ℚ)) *
        multidegree b (⊥ : Ideal (MvPolynomial σ K)) (β + ∑ j, Finsupp.single (f j) 1))
    (F : Finset (Ideal (MvPolynomial σ K)))
    (hF : ∀ 𝔮 ∈ F, 𝔮 ∈ J.minimalPrimes ∧ hilbertPoly b 𝔮 ≠ 0 ∧ 𝔮.height = k) :
    #F ≤ (∑ i, e i) ^ k := by
  classical
  have hn := degree_bottomType_add_card hb
  -- Every `𝔮 ∈ F` has dimension `|n| - k` and a positive degree there.
  have hβ : ∀ 𝔮, ∃ β : ι →₀ ℕ, 𝔮 ∈ F →
      β.degree = (bottomType b).degree - k ∧ 1 ≤ multidegree b 𝔮 β := by
    intro 𝔮
    by_cases h𝔮 : 𝔮 ∈ F
    · obtain ⟨hmin, hne, hht⟩ := hF 𝔮 h𝔮
      have := hmin.1.1
      obtain ⟨hdim, β, hβdeg, hβ1⟩ :=
        totalDegree_hilbertPoly_add_height hb 𝔮 (hJ.of_mem_minimalPrimes hmin) hne hht
      exact ⟨β, fun _ ↦ ⟨by omega, hβ1⟩⟩
    · exact ⟨0, fun h ↦ absurd h h𝔮⟩
  choose β hβ using hβ
  obtain ⟨Pr, ℓ, hPr, hℓ, hsum⟩ := multidegree_eq_sum_localLength hb hJ
  have hFPr : F ⊆ Pr := by
    intro 𝔮 h𝔮
    obtain ⟨hmin, hne, -⟩ := hF 𝔮 h𝔮
    have := hmin.1.1
    have hdim := (hβ 𝔮 h𝔮).1
    refine (hPr 𝔮).mpr ⟨inferInstance, hJ.of_mem_minimalPrimes hmin, hmin.1.2, hne, ?_⟩
    obtain ⟨hd, -⟩ := totalDegree_hilbertPoly_add_height hb 𝔮 (hJ.of_mem_minimalPrimes hmin) hne
      (hF 𝔮 h𝔮).2.2
    omega
  have hℓ1 : ∀ 𝔮 ∈ Pr, (1 : ℚ) ≤ ℓ 𝔮 := by
    intro 𝔮 h𝔮
    obtain ⟨hp, -, hJ𝔮, -, -⟩ := (hPr 𝔮).mp h𝔮
    have h0 := Ideal.localLength_ne_zero (𝔭 := 𝔮) hJ𝔮
    rw [hℓ 𝔮 h𝔮] at h0
    exact_mod_cast Nat.one_le_iff_ne_zero.mpr (by exact_mod_cast h0)
  have hnn : ∀ 𝔮 ∈ Pr, ∀ γ : ι →₀ ℕ, (bottomType b).degree - k ≤ γ.degree →
      0 ≤ multidegree b 𝔮 γ := by
    intro 𝔮 h𝔮 γ hγ
    obtain ⟨-, h𝔮h, -, -, hd⟩ := (hPr 𝔮).mp h𝔮
    exact mul_nonneg (prod_nonneg fun _ _ ↦ Nat.cast_nonneg _)
      (coeff_hilbertPoly_nonneg hb h𝔮h (by omega))
  -- Each fiber of `β` is bounded by a degree of `J`.
  have hfib : ∀ γ ∈ F.image β, ((#(F.filter fun 𝔮 ↦ β 𝔮 = γ) : ℕ) : ℚ) ≤ multidegree b J γ := by
    intro γ hγ
    obtain ⟨𝔮₀, h𝔮₀, rfl⟩ := mem_image.mp hγ
    have hγdeg := (hβ 𝔮₀ h𝔮₀).1
    rw [hsum _ (by omega), card_eq_sum_ones, Nat.cast_sum]
    refine le_trans ?_ (sum_le_sum_of_subset_of_nonneg
      ((filter_subset (fun 𝔮 ↦ β 𝔮 = β 𝔮₀) F).trans hFPr) fun 𝔮 h𝔮 _ ↦
        mul_nonneg (Nat.cast_nonneg _) (hnn 𝔮 h𝔮 _ hγdeg.ge))
    refine sum_le_sum fun 𝔮 h𝔮 ↦ ?_
    obtain ⟨h𝔮F, h𝔮γ⟩ := mem_filter.mp h𝔮
    rw [Nat.cast_one, ← one_mul (1 : ℚ), ← h𝔮γ]
    exact mul_le_mul (hℓ1 𝔮 (hFPr h𝔮F)) (hβ 𝔮 h𝔮F).2 zero_le_one (by positivity)
  -- Each `f` contributes to at most one `γ`.
  have hone : ∀ f : Fin k → ι, ∑ γ ∈ F.image β,
      multidegree b (⊥ : Ideal (MvPolynomial σ K)) (γ + ∑ j, Finsupp.single (f j) 1) ≤ 1 := by
    intro f
    have hbot : ∀ γ ∈ F.image β, multidegree b (⊥ : Ideal (MvPolynomial σ K))
        (γ + ∑ j, Finsupp.single (f j) 1) =
          if γ + ∑ j, Finsupp.single (f j) 1 = bottomType b then 1 else 0 := by
      intro γ hγ
      obtain ⟨𝔮, h𝔮, rfl⟩ := mem_image.mp hγ
      refine multidegree_bot hb ?_
      rw [map_add, map_sum, (hβ 𝔮 h𝔮).1]
      simp only [Finsupp.degree_single, sum_const, card_univ, Fintype.card_fin, smul_eq_mul,
        mul_one]
      omega
    have hcard : #((F.image β).filter fun γ ↦
        γ + ∑ j, Finsupp.single (f j) 1 = bottomType b) ≤ 1 :=
      card_le_one.mpr fun γ₁ h₁ γ₂ h₂ ↦
        add_right_cancel ((mem_filter.mp h₁).2.trans (mem_filter.mp h₂).2.symm)
    rw [sum_congr rfl hbot, sum_boole]
    exact_mod_cast hcard
  have hmain : ((#F : ℕ) : ℚ) ≤ ((∑ i, e i : ℕ) : ℚ) ^ k := by
    rw [card_eq_sum_card_image β F, Nat.cast_sum, ← sum_prod_eq_pow]
    calc ∑ γ ∈ F.image β, ((#(F.filter fun 𝔮 ↦ β 𝔮 = γ) : ℕ) : ℚ)
        ≤ ∑ γ ∈ F.image β, multidegree b J γ := sum_le_sum hfib
      _ ≤ ∑ γ ∈ F.image β, ∑ f : Fin k → ι, (∏ j, (e (f j) : ℚ)) *
            multidegree b (⊥ : Ideal (MvPolynomial σ K)) (γ + ∑ j, Finsupp.single (f j) 1) := by
          refine sum_le_sum fun γ hγ ↦ hbound γ ?_
          obtain ⟨𝔮, h𝔮, rfl⟩ := mem_image.mp hγ
          exact (hβ 𝔮 h𝔮).1.ge
      _ = ∑ f : Fin k → ι, (∏ j, (e (f j) : ℚ)) * ∑ γ ∈ F.image β,
            multidegree b (⊥ : Ideal (MvPolynomial σ K)) (γ + ∑ j, Finsupp.single (f j) 1) := by
          rw [sum_comm]
          simp_rw [Finset.mul_sum]
      _ ≤ ∑ f : Fin k → ι, ∏ j, (e (f j) : ℚ) := by
          refine sum_le_sum fun f _ ↦ ?_
          calc (∏ j, (e (f j) : ℚ)) * _ ≤ (∏ j, (e (f j) : ℚ)) * 1 :=
                mul_le_mul_of_nonneg_left (hone f) (prod_nonneg fun _ _ ↦ Nat.cast_nonneg _)
            _ = _ := mul_one _
  exact_mod_cast hmain

end Count

section Localization

variable {A : Type*} [CommRing A] [IsNoetherianRing A] {𝔭 : Ideal A} [𝔭.IsPrime]

/-- In the localization `A_𝔭`, if the associated primes of `A_𝔭/𝔞` all have height `k`, each of
them contracts to a minimal prime of `𝔞 ∩ A` of height `k`. -/
theorem mem_minimalPrimes_comap_of_mem_associatedPrimes
    {𝔞 : Ideal (Localization.AtPrime 𝔭)} {k : ℕ}
    (hS : ∀ Q ∈ associatedPrimes (Localization.AtPrime 𝔭) (Localization.AtPrime 𝔭 ⧸ 𝔞),
      Q.height = k)
    {Q : Ideal (Localization.AtPrime 𝔭)}
    (hQ : Q ∈ associatedPrimes (Localization.AtPrime 𝔭) (Localization.AtPrime 𝔭 ⧸ 𝔞)) :
    Q.comap (algebraMap A (Localization.AtPrime 𝔭)) ∈
        (𝔞.comap (algebraMap A (Localization.AtPrime 𝔭))).minimalPrimes ∧
      (Q.comap (algebraMap A (Localization.AtPrime 𝔭))).height = k := by
  set B := Localization.AtPrime 𝔭
  set φ := algebraMap A B
  have hQp : Q.IsPrime := hQ.isPrime
  have h𝔞Q : 𝔞 ≤ Q := by
    have := hQ.annihilator_le
    rwa [Submodule.annihilator_top, Ideal.annihilator_quotient] at this
  have hht : (Q.comap φ).height = k := by
    have h1 := IsLocalization.height_under 𝔭.primeCompl Q
    rw [Ideal.under] at h1
    rw [h1, hS Q hQ]
  have hQ𝔭 : Q.comap φ ≤ 𝔭 :=
    (Ideal.comap_mono (IsLocalRing.le_maximalIdeal hQp.ne_top)).trans
      Localization.AtPrime.under_maximalIdeal.le
  refine ⟨⟨⟨Ideal.comap_isPrime φ Q, Ideal.comap_mono h𝔞Q⟩, fun 𝔮' h𝔮' hle ↦ ?_⟩, hht⟩
  have := h𝔮'.1
  have hdisj : Disjoint (𝔭.primeCompl : Set A) 𝔮' :=
    Set.disjoint_left.mpr fun x hx hx' ↦ hx (hle.trans hQ𝔭 hx')
  have hQ'p : (𝔮'.map φ).IsPrime :=
    IsLocalization.isPrime_of_isPrime_disjoint 𝔭.primeCompl B 𝔮' h𝔮'.1 hdisj
  have hcomap : (𝔮'.map φ).comap φ = 𝔮' :=
    IsLocalization.under_map_of_isPrime_disjoint 𝔭.primeCompl B h𝔮'.1 hdisj
  have h𝔞Q' : 𝔞 ≤ 𝔮'.map φ := by
    rw [← IsLocalization.map_under 𝔭.primeCompl B 𝔞]
    exact Ideal.map_mono h𝔮'.2
  have hQ'Q : 𝔮'.map φ ≤ Q := by
    rw [← IsLocalization.map_under 𝔭.primeCompl B Q]
    exact Ideal.map_mono hle
  obtain ⟨Q'', hQ'', hQ''Q'⟩ := Ideal.exists_minimalPrimes_le h𝔞Q'
  have hQ''S : Q'' ∈ associatedPrimes B (B ⧸ 𝔞) :=
    Module.associatedPrimes.minimalPrimes_annihilator_subset_associatedPrimes B (B ⧸ 𝔞)
      (by rwa [Ideal.annihilator_quotient])
  have := hQ''.1.1
  have : Q''.FiniteHeight := ⟨Or.inr (by rw [hS Q'' hQ''S]; exact ENat.natCast_ne_top k)⟩
  have heq : Q'' = Q := Q''.eq_of_le_of_height_le (hQ''Q'.trans hQ'Q)
    (by rw [hS Q hQ, hS Q'' hQ''S])
  rw [← hcomap]
  exact Ideal.comap_mono (heq ▸ hQ''Q')

end Localization

section Chain

variable [Field K] [CharZero K] [Height.AdmissibleAbsValues K] [Fintype σ] [Fintype ι]
  [DecidableEq ι] {b : σ → ι} {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]

/-- Rémond's chain (2001, §5): `P_1, …, P_k`, natural combinations of the generators with
`∑ a_r ≤ |e|^j`, of height `k` at `𝔭`, whose localized ideals `J_k` have dimension `|n| - k`, obey
the Bézout bound for degrees, and the Bézout bound for heights with the error term
`(∑_j h_m(P_j)) · ∑_g ∏ e_{g j} d(ℙ)`. -/
private theorem exists_chain (hb : Function.Surjective b) (H : MultiprojectiveHeight b)
    (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {e : ι → ℕ} {R : Finset (MvPolynomial σ K)}
    (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r e)
    (h𝔭R : 𝔭 ∈ (Ideal.span (R : Set (MvPolynomial σ K))).minimalPrimes) {t : ℕ}
    (ht : 𝔭.height = t) :
    ∀ k ≤ t, ∃ P : Fin k → MvPolynomial σ K,
      (∀ j : Fin k, ∃ a : MvPolynomial σ K → ℕ, ∑ r ∈ R, a r ≤ (∑ i, e i) ^ (j : ℕ) ∧
        P j = ∑ r ∈ R, a r • r) ∧
      ((Ideal.span (Set.range P)).map
        (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).height = k ∧
      (∃ rs : List (Localization.AtPrime 𝔭), rs.length + k = t ∧
        (∀ r ∈ rs, r ∈ IsLocalRing.maximalIdeal (Localization.AtPrime 𝔭)) ∧
        RingTheory.Sequence.IsRegular (Localization.AtPrime 𝔭 ⧸ (Ideal.span (Set.range P)).map
          (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))) rs) ∧
      (hilbertPoly b (((Ideal.span (Set.range P)).map
        (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).comap
          (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭)))).totalDegree =
        (bottomType b).degree - k ∧
      (∀ β : ι →₀ ℕ, (bottomType b).degree - k ≤ β.degree →
        multidegree b (((Ideal.span (Set.range P)).map
          (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).comap
            (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))) β ≤
          ∑ f : Fin k → ι, (∏ j, (e (f j) : ℚ)) *
            multidegree b (⊥ : Ideal (MvPolynomial σ K)) (β + ∑ j, Finsupp.single (f j) 1)) ∧
      ∀ β : ι →₀ ℕ, β.degree = (bottomType b).degree - k + 1 →
        cycleHeight b H.height (((Ideal.span (Set.range P)).map
          (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))).comap
            (algebraMap (MvPolynomial σ K) (Localization.AtPrime 𝔭))) β ≤
          bezoutSum e k (H.height ⊥) β +
            (∑ j, max (bombieriLogHeight b (P j)) 0) *
              bezoutSum e (k - 1) (fun γ ↦ (multidegree b (⊥ : Ideal (MvPolynomial σ K)) γ : ℝ))
                β := by
  classical
  set A := Localization.AtPrime 𝔭
  set φ := algebraMap (MvPolynomial σ K) A
  have hinj : Function.Injective φ :=
    IsLocalization.injective A 𝔭.primeCompl_le_nonZeroDivisors
  have hVhom : ∀ v ∈ Submodule.span K (R : Set (MvPolynomial σ K)),
      IsWeightedHomogeneous (multiWeight b) v e := by
    intro v hv
    have : Submodule.span K (R : Set (MvPolynomial σ K)) ≤
        weightedHomogeneousSubmodule K (multiWeight b) e :=
      Submodule.span_le.mpr fun r hr ↦ (mem_weightedHomogeneousSubmodule _ _ _ _).mpr (hR r hr)
    exact (mem_weightedHomogeneousSubmodule _ _ _ _).mp (this hv)
  have hVI : ∀ v ∈ Submodule.span K (R : Set (MvPolynomial σ K)),
      v ∈ Ideal.span (R : Set (MvPolynomial σ K)) := by
    intro v hv
    have : Submodule.span K (R : Set (MvPolynomial σ K)) ≤
        (Ideal.span (R : Set (MvPolynomial σ K))).restrictScalars K :=
      Submodule.span_le.mpr fun r hr ↦ Ideal.subset_span hr
    exact this hv
  have hI𝔭 : Ideal.span (R : Set (MvPolynomial σ K)) ≤ 𝔭 := h𝔭R.1.2
  have hmax : 𝔭.map φ = IsLocalRing.maximalIdeal A := Localization.AtPrime.map_eq_maximalIdeal
  have hcomax : (IsLocalRing.maximalIdeal A).comap φ = 𝔭 := Localization.AtPrime.under_maximalIdeal
  have hdimA : ringKrullDim A = t := by
    rw [IsLocalization.AtPrime.ringKrullDim_eq_height 𝔭 A, ht]
    rfl
  have hn := degree_bottomType_add_card hb (σ := σ)
  have htn : t ≤ (bottomType b).degree := by
    obtain ⟨hd, -⟩ := totalDegree_hilbertPoly_add_height hb 𝔭 h𝔭 hne ht
    omega
  intro k
  induction k with
  | zero =>
    intro _
    have hJ0 : ((Ideal.span (Set.range (Fin.elim0 : Fin 0 → MvPolynomial σ K))).map φ).comap φ =
        ⊥ := by
      simp only [Set.range_eq_empty, Ideal.span_empty, Ideal.map_bot,
        Ideal.comap_bot_of_injective _ hinj]
    refine ⟨Fin.elim0, fun j ↦ j.elim0, ?_, ?_, ?_, fun β _ ↦ ?_, fun β hβ ↦ ?_⟩
    · simp [Ideal.height_bot]
    · obtain ⟨rs, hlen, hmem, hrs⟩ := IsRegularLocalRing.exists_isRegular (R := A)
      refine ⟨rs, ?_, hmem, ?_⟩
      · have h1 := (isRegularLocalRing_iff A).mp inferInstance
        rw [hdimA] at h1
        rw [hlen, add_zero]
        exact_mod_cast h1
      · rw [show (Ideal.span (Set.range (Fin.elim0 : Fin 0 → MvPolynomial σ K))).map φ = ⊥ by
          simp]
        exact (Submodule.quotEquivOfEqBot ⊥ rfl).isRegular_congr rs |>.mpr hrs
    · rw [hJ0, totalDegree_hilbertPoly_bot hb, Nat.sub_zero]
    · rw [hJ0]
      simp
    · rw [hJ0, cycleHeight_bot hb _ (by omega), bezoutSum_zero]
      simp
  | succ k IH =>
  intro hk
  obtain ⟨P, hPa, hht, ⟨rs, hrslen, hrsmem, hrs⟩, hdeg, hbound, hheight⟩ := IH (by omega)
  clear IH
  have hPV : ∀ j, P j ∈ Submodule.span K (R : Set (MvPolynomial σ K)) := by
    intro j
    obtain ⟨a, -, ha⟩ := hPa j
    rw [ha]
    exact Submodule.sum_mem _ fun r hr ↦ Submodule.smul_of_tower_mem _ _
      (Submodule.subset_span hr)
  set L := Ideal.span (Set.range P)
  set 𝔞 := L.map φ
  set J := 𝔞.comap φ
  have hL : L.IsWeightedHomogeneous (multiWeight b) :=
    isWeightedHomogeneous_span fun _ ⟨j, hj⟩ ↦ ⟨e, hj ▸ hVhom _ (hPV j)⟩
  have hJ : J.IsWeightedHomogeneous (multiWeight b) := isWeightedHomogeneous_comap_map hL
  have hL𝔭 : L ≤ 𝔭 :=
    (Ideal.span_le.mpr (Set.range_subset_iff.mpr fun j ↦ hVI _ (hPV j))).trans hI𝔭
  have h𝔞m : 𝔞 ≤ IsLocalRing.maximalIdeal A := hmax ▸ Ideal.map_mono hL𝔭
  have h𝔞span : 𝔞 = Ideal.span (Set.range (φ ∘ P)) := by
    rw [Set.range_comp, ← Ideal.map_span]
  set S := associatedPrimes A (A ⧸ 𝔞)
  have hSht : ∀ Q ∈ S, Q.height = k := fun Q hQ ↦
    IsLocalRing.height_eq_of_mem_associatedPrimes hdimA hht hrslen hrsmem hrs hQ
  have havoid : ∀ Q ∈ S,
      ¬ (R : Set (MvPolynomial σ K)) ⊆ (Q.comap φ : Set (MvPolynomial σ K)) := by
    intro Q hQ hRQ
    have := hQ.isPrime
    have hQ𝔭 : Q.comap φ ≤ 𝔭 :=
      (Ideal.comap_mono (IsLocalRing.le_maximalIdeal this.ne_top)).trans hcomax.le
    have heq : Q.comap φ = 𝔭 := le_antisymm hQ𝔭 (h𝔭R.2 ⟨inferInstance,
      Ideal.span_le.mpr hRQ⟩ hQ𝔭)
    have h1 := IsLocalization.height_under 𝔭.primeCompl Q
    rw [Ideal.under, heq, ht, hSht Q hQ] at h1
    norm_cast at h1
    omega
  -- The contracted associated primes: at most `|e|^k` of them (Rémond's `s`).
  set S' : Finset (Ideal (MvPolynomial σ K)) :=
    (associatedPrimes.finite A (A ⧸ 𝔞)).toFinset.image (·.comap φ)
  have hS' : ∀ 𝔮 ∈ S', 𝔮 ∈ J.minimalPrimes ∧ hilbertPoly b 𝔮 ≠ 0 ∧ 𝔮.height = k := by
    intro 𝔮 h𝔮
    obtain ⟨Q, hQ, rfl⟩ := mem_image.mp h𝔮
    rw [Set.Finite.mem_toFinset] at hQ
    obtain ⟨hmin, hQht⟩ := mem_minimalPrimes_comap_of_mem_associatedPrimes hSht hQ
    have := hQ.isPrime
    have hQ𝔭 : Q.comap φ ≤ 𝔭 :=
      (Ideal.comap_mono (IsLocalRing.le_maximalIdeal this.ne_top)).trans hcomax.le
    exact ⟨hmin, hilbertPoly_ne_zero_of_le hb (hJ.of_mem_minimalPrimes hmin) h𝔭 hQ𝔭 hne, hQht⟩
  have hcardS' : #S' ≤ (∑ i, e i) ^ k := card_le_pow_of_multidegree_le hb hJ e hdeg hbound S' hS'
  -- Rémond's Lemma 5.1: a small natural combination avoiding them.
  obtain ⟨a, ha, hpS'⟩ := Submodule.exists_sum_nsmul_forall_notMem
    (fun r : R ↦ (r : MvPolynomial σ K))
    (fun 𝔮 : S' ↦ (𝔮 : Ideal (MvPolynomial σ K)).restrictScalars K) (fun 𝔮 ↦ by
      obtain ⟨Q, hQ, hQ𝔮⟩ := mem_image.mp 𝔮.2
      rw [Set.Finite.mem_toFinset] at hQ
      obtain ⟨r, hr, hrQ⟩ := Set.not_subset.mp (havoid Q hQ)
      exact ⟨⟨r, hr⟩, by rw [← hQ𝔮] at *; exact hrQ⟩)
  set p : MvPolynomial σ K := ∑ r : R, a r • (r : MvPolynomial σ K)
  set a' : MvPolynomial σ K → ℕ := fun r ↦ if h : r ∈ R then a ⟨r, h⟩ else 0
  have ha'sum : ∑ r ∈ R, a' r = ∑ r : R, a r := by
    rw [← sum_coe_sort R]
    exact sum_congr rfl fun r _ ↦ by simp [a']
  have hpa' : p = ∑ r ∈ R, a' r • r := by
    rw [← sum_coe_sort R]
    exact sum_congr rfl fun r _ ↦ by simp [a']
  have hpV : p ∈ Submodule.span K (R : Set (MvPolynomial σ K)) :=
    Submodule.sum_mem _ fun r _ ↦ Submodule.smul_of_tower_mem _ _ (Submodule.subset_span r.2)
  have hpS : ∀ Q ∈ S, φ p ∉ Q := by
    intro Q hQ hpQ
    have h𝔮 : Q.comap φ ∈ S' := mem_image.mpr ⟨Q, (Set.Finite.mem_toFinset _).mpr hQ, rfl⟩
    exact hpS' ⟨_, h𝔮⟩ hpQ
  have hp : IsWeightedHomogeneous (multiWeight b) p e := hVhom p hpV
  have hcol : J.colon {p} = J := by
    refine le_antisymm (fun y hy ↦ ?_) (le_colon_singleton J p)
    rw [Submodule.mem_colon_singleton, smul_eq_mul, Ideal.mem_comap, map_mul] at hy
    rw [Ideal.mem_comap]
    by_contra hy'
    have hx : (Submodule.Quotient.mk (φ y) : A ⧸ 𝔞) ≠ 0 := by
      rwa [Ne, Submodule.Quotient.mk_eq_zero]
    have hmem : φ p ∈ ⋃ Q ∈ S, (Q : Set A) := by
      rw [biUnion_associatedPrimes_eq_zero_divisors]
      refine ⟨_, hx, ?_⟩
      rw [← Submodule.Quotient.mk_smul, smul_eq_mul, mul_comm, Submodule.Quotient.mk_eq_zero]
      exact hy
    obtain ⟨Q, hQ, hpQ'⟩ := Set.mem_iUnion₂.mp hmem
    exact hpS Q hQ hpQ'
  have hJ𝔭 : J ≤ 𝔭 := hcomax ▸ Ideal.comap_mono h𝔞m
  have hp0 : p ≠ 0 := by
    intro h0
    apply Ideal.IsPrime.ne_top (inferInstance : 𝔭.IsPrime)
    rw [eq_top_iff]
    refine le_trans ?_ hJ𝔭
    rw [← hcol, h0]
    intro x _
    rw [Submodule.mem_colon_singleton, smul_zero]
    exact J.zero_mem
  set P' : Fin (k + 1) → MvPolynomial σ K := Fin.snoc P p
  set L' := Ideal.span (Set.range P')
  set 𝔞' := L'.map φ
  set J' := 𝔞'.comap φ
  have hLL' : L' = Ideal.span {p} ⊔ L := by
    rw [← Ideal.span_insert]
    exact congrArg Ideal.span (Fin.range_snoc P p)
  have hpL' : p ∈ L' := by
    rw [hLL']
    exact Ideal.mem_sup_left (Ideal.mem_span_singleton_self p)
  have hLL'le : L ≤ L' := by
    rw [hLL']
    exact le_sup_right
  have hPV' : ∀ j, P' j ∈ Submodule.span K (R : Set (MvPolynomial σ K)) := by
    intro j
    refine Fin.lastCases ?_ (fun i ↦ ?_) j
    · simpa [P'] using hpV
    · simpa [P'] using hPV i
  have hL' : L'.IsWeightedHomogeneous (multiWeight b) :=
    isWeightedHomogeneous_span fun _ ⟨j, hj⟩ ↦ ⟨e, hj ▸ hVhom _ (hPV' j)⟩
  have hJ' : J'.IsWeightedHomogeneous (multiWeight b) := isWeightedHomogeneous_comap_map hL'
  have hJp : (J ⊔ Ideal.span {p}).IsWeightedHomogeneous (multiWeight b) :=
    hJ.sup (isWeightedHomogeneous_span fun x hx ↦ ⟨e, (Set.mem_singleton_iff.mp hx) ▸ hp⟩)
  have hJJ' : J ⊔ Ideal.span {p} ≤ J' := by
    refine sup_le (Ideal.comap_mono (Ideal.map_mono hLL'le)) ?_
    rw [Ideal.span_le, Set.singleton_subset_iff]
    exact Ideal.le_comap_map hpL'
  have h1 := totalDegree_hilbertPoly_sup_span_singleton_le_of_colon_eq hb hJ hp hp0 hcol
  have h2 := totalDegree_hilbertPoly_le_of_le hb hJp hJ' hJJ'
  have hL'𝔭 : L' ≤ 𝔭 :=
    (Ideal.span_le.mpr (Set.range_subset_iff.mpr fun j ↦ hVI _ (hPV' j))).trans hI𝔭
  have h𝔞'm : 𝔞' ≤ IsLocalRing.maximalIdeal A := hmax ▸ Ideal.map_mono hL'𝔭
  have h𝔞'top : 𝔞' ≠ ⊤ := ne_top_of_le_ne_top (IsLocalRing.maximalIdeal.isMaximal A).ne_top h𝔞'm
  have h𝔞'span : 𝔞' = Ideal.span (Set.range (φ ∘ P')) := by
    rw [Set.range_comp, ← Ideal.map_span]
  have hht' : 𝔞'.height = (k + 1 : ℕ) := by
    refine le_antisymm ?_ ?_
    · have hs : ((univ.image (φ ∘ P') : Finset A) : Set A) = Set.range (φ ∘ P') := by
        rw [coe_image, coe_univ, Set.image_univ]
      have := Ideal.height_span_le_card_of_span_ne_top (s := univ.image (φ ∘ P'))
        (by rw [hs, ← h𝔞'span]; exact h𝔞'top)
      rw [hs, ← h𝔞'span] at this
      refine this.trans ?_
      have hc : (univ.image (φ ∘ P')).card ≤ k + 1 :=
        card_image_le.trans (by simp)
      exact_mod_cast hc
    · rw [Ideal.height_eq_inf_minimalPrimes]
      refine le_iInf₂ fun Q' hQ' ↦ ?_
      have := hQ'.1.1
      have h𝔞Q' : 𝔞 ≤ Q' :=
        (Ideal.map_mono hLL'le).trans hQ'.1.2
      obtain ⟨Q, hQ, hQQ'⟩ := Ideal.exists_minimalPrimes_le h𝔞Q'
      have := hQ.1.1
      have hQS : Q ∈ S :=
        Module.associatedPrimes.minimalPrimes_annihilator_subset_associatedPrimes A (A ⧸ 𝔞)
        (by rwa [Ideal.annihilator_quotient])
      have hpQ' : φ p ∈ Q' := hQ'.1.2 (Ideal.mem_map_of_mem φ hpL')
      have hlt : Q < Q' := lt_of_le_of_ne hQQ' fun h ↦ hpS Q hQS (h ▸ hpQ')
      have := Ideal.height_add_one_le_of_lt_of_isPrime hlt
      rw [hSht Q hQS] at this
      exact_mod_cast this
  -- The depth of `A / 𝔞'` is one less.
  obtain ⟨rs', hlen', hmem', hrs'⟩ : ∃ rs' : List A, rs'.length + (k + 1) = t ∧
      (∀ r ∈ rs', r ∈ IsLocalRing.maximalIdeal A) ∧ RingTheory.Sequence.IsRegular (A ⧸ 𝔞') rs' := by
    have h𝔞' : 𝔞' = 𝔞 ⊔ Ideal.span {φ p} := by
      change L'.map φ = _
      rw [hLL', Ideal.map_sup, Ideal.map_span, Set.image_singleton, sup_comm]
    have hpm : φ p ∈ IsLocalRing.maximalIdeal A :=
      hmax ▸ Ideal.mem_map_of_mem φ (hI𝔭 (hVI p hpV))
    have hpreg : IsSMulRegular (A ⧸ 𝔞) (φ p) := by
      intro v w hvw
      rw [← sub_eq_zero]
      by_contra hne
      have hmem : φ p ∈ ⋃ Q ∈ S, (Q : Set A) := by
        rw [biUnion_associatedPrimes_eq_zero_divisors]
        exact ⟨v - w, hne, by simp only [smul_sub, hvw, sub_self]⟩
      obtain ⟨Q, hQ, hpQ⟩ := Set.mem_iUnion₂.mp hmem
      exact hpS Q hQ hpQ
    obtain ⟨rs', hlen', hmem', hrs'⟩ := IsLocalRing.exists_isRegular_quotient_sup 𝔞
      (n := rs.length - 1) (by omega) hrsmem hrs hpm hpreg
    exact ⟨rs', by omega, hmem', h𝔞' ▸ hrs'⟩
  -- The exact dimension of `J_{k+1}`, from a component of height `k + 1`.
  have hdeg' : (hilbertPoly b J').totalDegree = (bottomType b).degree - (k + 1) := by
    refine le_antisymm (h2.trans (h1.trans (by omega))) ?_
    have hSht' : ∀ Q ∈ associatedPrimes A (A ⧸ 𝔞'), Q.height = (k + 1 : ℕ) := fun Q hQ ↦
      IsLocalRing.height_eq_of_mem_associatedPrimes hdimA hht' hlen' hmem' hrs' hQ
    have : Nontrivial (A ⧸ 𝔞') := Ideal.Quotient.nontrivial_iff.mpr h𝔞'top
    obtain ⟨Q, hQ⟩ := associatedPrimes.nonempty A (A ⧸ 𝔞')
    obtain ⟨hmin, hQht⟩ := mem_minimalPrimes_comap_of_mem_associatedPrimes hSht' hQ
    have := hQ.isPrime
    have hQ𝔭 : Q.comap φ ≤ 𝔭 :=
      (Ideal.comap_mono (IsLocalRing.le_maximalIdeal this.ne_top)).trans hcomax.le
    have h𝔮h := hJ'.of_mem_minimalPrimes hmin
    have h𝔮ne := hilbertPoly_ne_zero_of_le hb h𝔮h h𝔭 hQ𝔭 hne
    obtain ⟨hd, -⟩ := totalDegree_hilbertPoly_add_height hb (Q.comap φ) h𝔮h h𝔮ne hQht
    have := totalDegree_hilbertPoly_le_of_le (L := Q.comap φ) hb hJ' h𝔮h hmin.1.2
    omega
  refine ⟨P', fun j ↦ ?_, hht', ⟨rs', hlen', hmem', hrs'⟩, hdeg', fun β hβ ↦ ?_, fun β hβ ↦ ?_⟩
  · refine Fin.lastCases ?_ (fun i ↦ ?_) j
    · refine ⟨a', ?_, by simpa [P'] using hpa'⟩
      rw [ha'sum, Fin.val_last]
      exact ha.trans ((Fintype.card_coe S').trans_le hcardS')
    · obtain ⟨c, hc, hcP⟩ := hPa i
      exact ⟨c, by simpa using hc, by simpa [P'] using hcP⟩
  · calc multidegree b J' β ≤ multidegree b (J ⊔ Ideal.span {p}) β :=
          multidegree_le_of_le hb hJp hJ' hJJ' (by omega)
      _ = ∑ i, (e i : ℚ) * multidegree b J (β + Finsupp.single i 1) :=
          multidegree_sup_span_singleton_of_colon_eq hb hJ hp hp0 hcol (by omega)
      _ ≤ ∑ i, (e i : ℚ) * ∑ f : Fin k → ι, (∏ j, (e (f j) : ℚ)) *
            multidegree b ⊥ (β + Finsupp.single i 1 + ∑ j, Finsupp.single (f j) 1) := by
          refine sum_le_sum fun i _ ↦ mul_le_mul_of_nonneg_left (hbound _ ?_) (Nat.cast_nonneg _)
          rw [map_add, Finsupp.degree_single]
          omega
      _ = ∑ f : Fin (k + 1) → ι, (∏ j, (e (f j) : ℚ)) *
            multidegree b ⊥ (β + ∑ j, Finsupp.single (f j) 1) := by
          simp_rw [Finset.mul_sum]
          rw [← (Fin.consEquiv fun _ : Fin (k + 1) ↦ ι).sum_comp, Fintype.sum_prod_type]
          refine sum_congr rfl fun i _ ↦ sum_congr rfl fun f _ ↦ ?_
          simp only [Fin.consEquiv_apply, Fin.prod_univ_succ, Fin.sum_univ_succ, Fin.cons_zero,
            Fin.cons_succ]
          rw [add_assoc β]
          ring
  · -- The heights along the chain.
    set D : (ι →₀ ℕ) → ℝ := fun γ ↦ (multidegree b (⊥ : Ideal (MvPolynomial σ K)) γ : ℝ)
    set Sk := ∑ j, max (bombieriLogHeight b (P j)) 0
    have hSk : 0 ≤ Sk := sum_nonneg fun _ _ ↦ le_max_right _ _
    have hβk : β.degree = (bottomType b).degree - k := by omega
    have hdJ : (multidegree b J β : ℝ) ≤ bezoutSum e k D β := by
      have := hbound β hβk.ge
      simp only [bezoutSum, D]
      exact_mod_cast this
    have hdJ0 : (0 : ℝ) ≤ multidegree b J β := by
      have : (0 : ℚ) ≤ multidegree b J β :=
        mul_nonneg (prod_nonneg fun _ _ ↦ Nat.cast_nonneg _)
          (coeff_hilbertPoly_nonneg hb hJ (α := β) (by omega))
      exact_mod_cast this
    have hstep : ∑ i, (e i : ℝ) * (Sk * bezoutSum e (k - 1) D (β + Finsupp.single i 1)) =
        Sk * bezoutSum e k D β := by
      rcases Nat.eq_zero_or_pos k with rfl | hk0
      · simp [Sk]
      · obtain ⟨k', rfl⟩ : ∃ k', k = k' + 1 := ⟨k - 1, by omega⟩
        rw [Nat.add_sub_cancel, bezoutSum_succ, Finset.mul_sum]
        exact sum_congr rfl fun i _ ↦ by ring
    have hS' : ∑ j, max (bombieriLogHeight b (P' j)) 0 = Sk + max (bombieriLogHeight b p) 0 := by
      rw [Fin.sum_univ_castSucc]
      simp [P', Sk]
    calc cycleHeight b H.height J' β ≤ cycleHeight b H.height (J ⊔ Ideal.span {p}) β :=
          cycleHeight_le_of_le hb H.height_nonneg hJp hJ' hJJ' (by omega)
      _ ≤ ∑ i, (e i : ℝ) * cycleHeight b H.height J (β + Finsupp.single i 1) +
            (multidegree b J β : ℝ) * bombieriLogHeight b p :=
          H.cycleHeight_sup_le J p e hJ hp hcol β (by omega) (by omega)
      _ ≤ ∑ i, (e i : ℝ) * (bezoutSum e k (H.height ⊥) (β + Finsupp.single i 1) +
            Sk * bezoutSum e (k - 1) D (β + Finsupp.single i 1)) +
            bezoutSum e k D β * max (bombieriLogHeight b p) 0 := by
          refine add_le_add (sum_le_sum fun i _ ↦ mul_le_mul_of_nonneg_left
            (hheight _ ?_) (Nat.cast_nonneg _)) ?_
          · rw [map_add, Finsupp.degree_single]
            omega
          · exact (mul_le_mul_of_nonneg_left (le_max_left _ _) hdJ0).trans
              (mul_le_mul_of_nonneg_right hdJ (le_max_right _ _))
      _ = bezoutSum e (k + 1) (H.height ⊥) β +
            (Sk + max (bombieriLogHeight b p) 0) * bezoutSum e k D β := by
          rw [bezoutSum_succ, add_mul, ← hstep]
          simp only [mul_add, Finset.sum_add_distrib]
          ring
      _ = _ := by rw [hS', Nat.add_sub_cancel]

/-- **The arithmetic excess Bézout inequality** (Rémond 2001, Prop. 3.2, height part, before the
heights `h_m(P_j)` are estimated). Let `R` be a finite family of multihomogeneous polynomials of
multidegree `e`, `𝔭` a multihomogeneous prime of positive-dimensional type, minimal over `(R)`,
of height `t`, and `H` a multiprojective height theory. Then there are
`P_1, …, P_t`, natural combinations `P_{j+1} = ∑_r a_r r` with `∑_r a_r ≤ |e|^j`, such that
`dim 𝔭 = |n| - t` and, for `|β| = dim 𝔭 + 1`,
`ℓ(K[X]_𝔭/(P)_𝔭) · h_β(𝔭) ≤ ∑_f ∏_j e_{f j} h_{β + ∑ ε_{f j}}(ℙ)
  + (∑_j max(h_m(P_j), 0)) ∑_g ∏_j e_{g j} d_{β + ∑ ε_{g j}}(ℙ)`,
with `f : Fin t → ι` and `g : Fin (t - 1) → ι`. -/
theorem exists_localLength_mul_height_le (hb : Function.Surjective b)
    (H : MultiprojectiveHeight b)
    (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b)) (hne : hilbertPoly b 𝔭 ≠ 0) {e : ι → ℕ}
    {R : Finset (MvPolynomial σ K)} (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r e)
    (h𝔭R : 𝔭 ∈ (Ideal.span (R : Set (MvPolynomial σ K))).minimalPrimes) {t : ℕ}
    (ht : 𝔭.height = t) :
    ∃ P : Fin t → MvPolynomial σ K,
      (∀ j : Fin t, ∃ a : MvPolynomial σ K → ℕ, ∑ r ∈ R, a r ≤ (∑ i, e i) ^ (j : ℕ) ∧
        P j = ∑ r ∈ R, a r • r) ∧
      ∃ ℓ : ℕ, Ideal.localLength 𝔭 (Ideal.span (Set.range P)) = ℓ ∧
        (hilbertPoly b 𝔭).totalDegree + t = (bottomType b).degree ∧
        ∀ β : ι →₀ ℕ, β.degree = (bottomType b).degree - t + 1 →
          (ℓ : ℝ) * H.height 𝔭 β ≤ bezoutSum e t (H.height ⊥) β +
            (∑ j, max (bombieriLogHeight b (P j)) 0) *
              bezoutSum e (t - 1) (fun γ ↦ (multidegree b (⊥ : Ideal (MvPolynomial σ K)) γ : ℝ))
                β := by
  classical
  obtain ⟨P, hPa, hht, -, -, -, hheight⟩ := exists_chain hb H h𝔭 hne hR h𝔭R ht t le_rfl
  set A := Localization.AtPrime 𝔭
  set φ := algebraMap (MvPolynomial σ K) A
  set L := Ideal.span (Set.range P)
  set 𝔞 := L.map φ
  set J := 𝔞.comap φ
  have hPV : ∀ j, P j ∈ Ideal.span (R : Set (MvPolynomial σ K)) := by
    intro j
    obtain ⟨a, -, ha⟩ := hPa j
    rw [ha]
    exact Ideal.sum_mem _ fun r hr ↦ Submodule.smul_of_tower_mem _ _ (Ideal.subset_span hr)
  have hcomax : (IsLocalRing.maximalIdeal A).comap φ = 𝔭 := Localization.AtPrime.under_maximalIdeal
  have hmax : 𝔭.map φ = IsLocalRing.maximalIdeal A := Localization.AtPrime.map_eq_maximalIdeal
  have hL𝔭 : L ≤ 𝔭 :=
    (Ideal.span_le.mpr (Set.range_subset_iff.mpr hPV)).trans h𝔭R.1.2
  have hJ𝔭 : J ≤ 𝔭 := (Ideal.comap_mono (hmax ▸ Ideal.map_mono hL𝔭)).trans hcomax.le
  -- `J` is `𝔭`-primary: every minimal prime of `𝔞` lies over `𝔭`.
  have hmin : ∀ Q' ∈ 𝔞.minimalPrimes, Q'.comap φ = 𝔭 := by
    intro Q' hQ'
    have := hQ'.1.1
    have hle : Q'.comap φ ≤ 𝔭 :=
      (Ideal.comap_mono (IsLocalRing.le_maximalIdeal this.ne_top)).trans hcomax.le
    refine (Ideal.comap φ Q').eq_of_le_of_height_le hle ?_
    have h1 := IsLocalization.height_under 𝔭.primeCompl Q'
    rw [Ideal.under] at h1
    rw [h1, ht, ← hht, Ideal.height_eq_inf_minimalPrimes 𝔞]
    exact iInf₂_le Q' hQ'
  have hprimes : ∀ 𝔮 : Ideal (MvPolynomial σ K), 𝔮.IsPrime → J ≤ 𝔮 → 𝔭 ≤ 𝔮 := by
    intro 𝔮 h𝔮 hJ𝔮 x hx
    have : φ x ∈ 𝔞.radical := by
      rw [← Ideal.sInf_minimalPrimes, Submodule.mem_sInf]
      intro Q' hQ'
      have : x ∈ Ideal.comap φ Q' := (hmin Q' hQ').symm ▸ hx
      exact this
    obtain ⟨n, hn⟩ := (Ideal.mem_radical_iff).mp this
    exact h𝔮.mem_of_pow_mem n (hJ𝔮 (by rw [Ideal.mem_comap, map_pow]; exact hn))
  have h𝔭J : 𝔭 ∈ J.minimalPrimes :=
    ⟨⟨inferInstance, hJ𝔭⟩, fun 𝔮 h𝔮 _ ↦ hprimes 𝔮 h𝔮.1 h𝔮.2⟩
  have hlen : Ideal.localLength 𝔭 J = Ideal.localLength 𝔭 L := by
    unfold Ideal.localLength
    rw [IsLocalization.map_under 𝔭.primeCompl]
  have hfin : Ideal.localLength 𝔭 L ≠ ⊤ := hlen ▸ Ideal.localLength_ne_top_of_mem_minimalPrimes h𝔭J
  obtain ⟨hdim, -⟩ := totalDegree_hilbertPoly_add_height hb 𝔭 h𝔭 hne ht
  have hn := degree_bottomType_add_card hb (σ := σ)
  refine ⟨P, hPa, (Ideal.localLength 𝔭 L).toNat, ENat.natCast_toNat hfin |>.symm, by omega,
    fun β hβ ↦ ?_⟩
  have hcyc := cycleHeight_eq_of_forall_le H.height hJ𝔭 hprimes hne (β := β) (by omega)
  rw [primeMult_eq, hlen] at hcyc
  rw [← hcyc]
  exact hheight β hβ

end Chain

end MvPolynomial
