/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import DiophantineApproximation.TaylorAtPrimeHasse
public import ForMathlib.RingTheory.MvPolynomial.ProductStructure

-- Used only inside proofs.
import Mathlib.Algebra.BigOperators.Module
import Mathlib.Algebra.Order.BigOperators.Ring.Finset
import Mathlib.Analysis.SpecialFunctions.Log.Basic

/-!
# The product theorem, geometric part (Rémond 2001, Prop. 2.1)

Let `𝔭` be a multihomogeneous prime of `B = K[X]`, `K` of characteristic `0`, with the variables in
blocks `b : σ → Fin m`, minimal over an ideal generated by polynomials `R` of multidegree `δ`, and
suppose every `P ∈ R` has `∂_κ P ∈ 𝔭` whenever `∑_s κ_s / δ_{b s} ≤ ε` (Rémond's hypothesis: `𝔭` is
a component of the zeros of index `σ` and of index `σ + ε` of a polynomial of multidegree `δ`). If
`δ` is decreasing and `δ_i / δ_{i+1} > (m/ε)^t` with `t = ht 𝔭`, then `𝔭` is a minimal prime of
the ideal generated by its traces on the blocks: the subvariety is a component of the product of its
projections to the factors. Moreover, with `β_i` the dimension of the projection to factor `i`,
`ε^t d_β(𝔭) ≤ t!/∏_i c_i! ≤ m^t`, `c_i` the codimensions of the projections
(`MvPolynomial.productTheorem`; the product part alone is
`MvPolynomial.mem_minimalPrimes_span_of_productTheorem`). This is
G. Rémond, *Sur le théorème du produit*, J. Théor. Nombres Bordeaux **13** (2001), Prop. 2.1 and
Thm. 1.1, with `m^t` in place of Rémond's sharper `ψ(t)`.

The proof is Rémond's, with ranks of the algebraic matroid of the variables in place of heights of
primes. Take a transcendence basis `T` adapted to the last blocks, giving the transversal
equations and the exponents `c_i = |block i \ T|`, and a transcendence basis `T'` adapted to the
first blocks, giving the type `β'` with `d_{β'}(𝔭) ≥ 1`. The degree inequality
`ε^t ∏_i δ_i^{c_i} d_{β'}(𝔭) ≤ #F · ∏_i δ_i^{c'_i}`
(`MvPolynomial.prod_pow_mul_pow_mul_multidegree_le`) compares the two. Abel summation over the cuts
`P_k = {s | b s < k}` writes
`∑_i (c_i - c'_i) log δ_i = ∑_k E_k (log δ_{k-1} - log δ_k)` with
`E_k = r(P_k) + r(σ \ P_k) - r(σ) ≥ 0`, so the ratio condition forces every `E_k = 0`, and
`MvPolynomial.sum_eRk_le_of_forall_cut` with `MvPolynomial.mem_minimalPrimes_span_of_sum_eRk_le`
concludes.

Tight cuts also force the adapted basis `T` to meet each block in a basis of it, so its type
`β = coneType b T` is the type `(dim Z_i)_i` of the factors, and the degree inequality at `β`
is Rémond's `d(Z) ≤ ρ(ε, Z)`. `MvPolynomial.productTheorem_of_basis` states the theorem for a
given adapted basis `T`, so that the height part (`QuantitativeSubspace.ProductTheoremHeight`) can
use the same `T`.

The degree part needs no ratio condition: for the type `β` of the adapted basis,
`ε^t d_β(𝔭) ≤ #{f : Fin t → Fin m | β + ∑_j ε_{f j} = n}`, a multinomial coefficient
(`MvPolynomial.mul_multidegree_le_card`).

The form with the zeros of index `σ` of one polynomial, and Rémond's Cor. 1.1, are in
`QuantitativeSubspace.ZerosOfIndex`.

This is part of Layer Q1.2 of the `QuantitativeSubspace` roadmap.
-/

@[expose] public section

open Finset

namespace MvPolynomial

/-- **Abel summation against nonnegative partial sums.** If the partial sums `G_k = ∑_{j<k} a_j`
are nonnegative integers with `G_m = 0`, `L` is decreasing on `[0, m)`, and `∑_{j<m} a_j L_j ≤ C`
while every gap `L_k - L_{k+1}` exceeds `C`, then every `G_k`, `k ≤ m`, vanishes:
`∑_{j<m} a_j L_j = ∑_{k<m-1} (L_k - L_{k+1}) G_{k+1}`. -/
theorem sum_range_eq_zero_of_sum_mul_le {m : ℕ} {a : ℕ → ℤ} {L : ℕ → ℝ} {C : ℝ}
    (hnn : ∀ k ≤ m, 0 ≤ ∑ j ∈ range k, a j) (htot : ∑ j ∈ range m, a j = 0)
    (hL : ∀ k, k + 1 < m → L (k + 1) ≤ L k)
    (hsum : ∑ j ∈ range m, (a j : ℝ) * L j ≤ C) (hgap : ∀ k, k + 1 < m → C < L k - L (k + 1))
    {k : ℕ} (hk : k ≤ m) : ∑ j ∈ range k, a j = 0 := by
  by_contra hne
  have hpos : 1 ≤ ∑ j ∈ range k, a j := by
    have := hnn k hk
    omega
  have hk0 : k ≠ 0 := by
    rintro rfl
    simp at hne
  have hkm : k ≠ m := by
    rintro rfl
    exact hne htot
  have habel := Finset.sum_range_by_parts L (fun j ↦ (a j : ℝ)) m
  have hG : ∀ n, ∑ i ∈ range n, (a i : ℝ) = ((∑ i ∈ range n, a i : ℤ) : ℝ) := fun n ↦ by
    push_cast
    rfl
  simp only [smul_eq_mul] at habel
  rw [hG m, htot, Int.cast_zero, mul_zero, zero_sub] at habel
  have hterm : ∀ i ∈ range (m - 1),
      0 ≤ -((L (i + 1) - L i) * ∑ j ∈ range (i + 1), (a j : ℝ)) := by
    intro i hi
    rw [mem_range] at hi
    rw [hG, neg_mul_eq_neg_mul, neg_sub]
    exact mul_nonneg (sub_nonneg.mpr (hL i (by omega)))
      (by exact_mod_cast hnn (i + 1) (by omega))
  have hsingle := Finset.single_le_sum hterm (mem_range.mpr (show k - 1 < m - 1 by omega))
  rw [Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr hk0), hG, neg_mul_eq_neg_mul, neg_sub]
    at hsingle
  have hgapk := hgap (k - 1) (by omega)
  rw [Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr hk0)] at hgapk
  have hGk : (1 : ℝ) ≤ ((∑ j ∈ range k, a j : ℤ) : ℝ) := by exact_mod_cast hpos
  have hLk : 0 ≤ L (k - 1) - L k := by
    have := hL (k - 1) (by omega)
    rw [Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr hk0)] at this
    linarith
  have : C < ∑ j ∈ range m, (a j : ℝ) * L j := by
    have h1 : (L (k - 1) - L k) ≤ (L (k - 1) - L k) * ((∑ j ∈ range k, a j : ℤ) : ℝ) :=
      le_mul_of_one_le_right hLk hGk
    have h2 : ∑ j ∈ range m, (a j : ℝ) * L j =
        ∑ i ∈ range (m - 1), -((L (i + 1) - L i) * ∑ j ∈ range (i + 1), (a j : ℝ)) := by
      rw [← Finset.sum_neg_distrib] at habel
      simpa only [mul_comm] using habel
    rw [h2]
    linarith
  linarith

/-- **The cuts are tight under the ratio condition.** If `∏_i δ_i^{c_i} ε^t ≤ F ∏_i δ_i^{c'_i}`
with `F ≤ m^t`, `δ` decreasing with `δ_i / δ_{i+1} > (m/ε)^t`, and the differences
`a_i = c_i - c'_i` have nonnegative partial sums summing to `0`, then every partial sum vanishes.
This is `MvPolynomial.sum_range_eq_zero_of_sum_mul_le` after taking logarithms. -/
theorem sum_range_eq_zero_of_prod_pow_le {m t : ℕ} {δ : Fin m → ℕ} (hδ : ∀ i, 0 < δ i)
    (hanti : Antitone δ) {ε : ℝ} (hε : 0 < ε) {F : ℕ} (hF : F ≤ m ^ t)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → (m : ℝ) ^ t < ε ^ t * (δ i / δ j))
    {c c' : Fin m → ℕ} (h : (∏ i, (δ i : ℝ) ^ c i) * ε ^ t ≤ F * ∏ i, (δ i : ℝ) ^ c' i)
    {a : ℕ → ℤ} (ha : ∀ i : Fin m, a i = (c i : ℤ) - c' i)
    (hnn : ∀ k ≤ m, 0 ≤ ∑ j ∈ range k, a j) (htot : ∑ j ∈ range m, a j = 0)
    {k : ℕ} (hk : k ≤ m) : ∑ j ∈ range k, a j = 0 := by
  have hδR : ∀ i, (0 : ℝ) < δ i := fun i ↦ Nat.cast_pos.mpr (hδ i)
  have hP : ∀ c : Fin m → ℕ, 0 < ∏ i, (δ i : ℝ) ^ c i :=
    fun c ↦ Finset.prod_pos fun i _ ↦ pow_pos (hδR i) _
  have hF0 : (0 : ℝ) < F := by
    by_contra h0
    have : (F : ℝ) = 0 := le_antisymm (not_lt.mp h0) (Nat.cast_nonneg F)
    rw [this, zero_mul] at h
    exact (mul_pos (hP c) (pow_pos hε t)).not_ge h
  have hlogP : ∀ c : Fin m → ℕ,
      Real.log (∏ i, (δ i : ℝ) ^ c i) = ∑ i, (c i : ℝ) * Real.log (δ i) := by
    intro c
    rw [Real.log_prod fun i _ ↦ (pow_pos (hδR i) _).ne']
    simp only [Real.log_pow]
  have hlog := Real.log_le_log (mul_pos (hP c) (pow_pos hε t)) h
  rw [Real.log_mul (hP c).ne' (pow_pos hε t).ne', Real.log_mul hF0.ne' (hP c').ne', hlogP,
    hlogP, Real.log_pow] at hlog
  set L : ℕ → ℝ := fun j ↦ if h : j < m then Real.log (δ ⟨j, h⟩) else 0
  have hLi : ∀ i : Fin m, L i = Real.log (δ i) := fun i ↦ by simp [L, i.2]
  refine sum_range_eq_zero_of_sum_mul_le (L := L) (C := Real.log F - t * Real.log ε) hnn htot
    ?_ ?_ ?_ hk
  · intro j hj
    have hj' : j < m := by omega
    simp only [L, hj, hj', ↓reduceDIte]
    exact Real.log_le_log (hδR _) (by exact_mod_cast hanti (Fin.mk_le_mk.mpr (Nat.le_succ j)))
  · rw [← Fin.sum_univ_eq_sum_range (fun j ↦ (a j : ℝ) * L j)]
    simp only [hLi, ha]
    push_cast
    simp only [sub_mul, Finset.sum_sub_distrib]
    linarith
  · intro j hj
    have hj' : j < m := by omega
    have hr := hratio ⟨j, hj'⟩ ⟨j + 1, hj⟩ rfl
    simp only [L, hj, hj', ↓reduceDIte]
    rw [← Real.log_div (hδR _).ne' (hδR _).ne']
    have hFm : (F : ℝ) < ε ^ t * (δ ⟨j, hj'⟩ / δ ⟨j + 1, hj⟩) :=
      lt_of_le_of_lt (by exact_mod_cast hF) hr
    have := Real.log_lt_log hF0 hFm
    rw [Real.log_mul (pow_pos hε t).ne' (div_pos (hδR _) (hδR _)).ne', Real.log_pow] at this
    linarith

section Count

variable {σ ι : Type*} [Fintype σ] [Fintype ι] [DecidableEq ι] (b : σ → ι)

omit [Fintype ι] in
/-- The variables of block `i` outside `T`, and those in `T`, make up the block. -/
theorem ncard_notMem_add_card_filter (T : Finset σ) (i : ι) :
    {s | s ∉ T ∧ b s = i}.ncard + #(T.filter (b · = i)) = #(univ.filter (b · = i)) := by
  classical
  have h1 : {s | s ∉ T ∧ b s = i} = ((univ.filter (b · = i)).filter (· ∉ T) : Set σ) := by
    ext s
    simp [and_comm]
  have h2 : T.filter (b · = i) = (univ.filter (b · = i)).filter (· ∈ T) := by
    ext s
    simp [and_comm]
  rw [h1, Set.ncard_coe_finset, h2, add_comm]
  exact Finset.card_filter_add_card_filter_not _

omit [Fintype σ] in
/-- **The Bézout sum in the type of a basis.** For `T` meeting every block and `β` its type, every
`f` with `β + ∑_j ε_{f j} = n` takes the value `i` exactly `c_i = |block i \ T|` times, so the
Bézout sum is `#F · ∏_i δ_i^{c_i}`. -/
theorem sum_prod_eq_card_mul_prod_pow [Finite σ] {T : Finset σ} (hTb : ∀ i, ∃ s ∈ T, b s = i)
    {t : ℕ} (δ : ι → ℕ) :
    ∑ f : Fin t → ι with coneType b T + ∑ j, Finsupp.single (f j) 1 = bottomType b,
        ∏ j, (δ (f j) : ℝ) =
      #(univ.filter fun f : Fin t → ι ↦
          coneType b T + ∑ j, Finsupp.single (f j) 1 = bottomType b) *
        ∏ i, (δ i : ℝ) ^ {s | s ∉ T ∧ b s = i}.ncard := by
  classical
  have := Fintype.ofFinite σ
  rw [← nsmul_eq_mul, ← Finset.sum_const]
  refine Finset.sum_congr rfl fun f hf ↦ ?_
  have hf := (Finset.mem_filter.mp hf).2
  rw [← Finset.prod_fiberwise' Finset.univ f (fun i ↦ (δ i : ℝ))]
  refine Finset.prod_congr rfl fun i _ ↦ ?_
  rw [Finset.prod_const]
  congr 1
  have hi := congrArg (· i) hf
  simp only [Finsupp.coe_add, Pi.add_apply, Finsupp.coe_finsetSum, Finset.sum_apply,
    Finsupp.single_apply] at hi
  rw [Finset.sum_boole] at hi
  have hcount := ncard_notMem_add_card_filter b T i
  obtain ⟨s, hs, hsi⟩ := hTb i
  have hpos : 0 < #(T.filter (b · = i)) := Finset.card_pos.mpr ⟨s, by simp [hs, hsi]⟩
  have hct : coneType b T i = #(T.filter (b · = i)) - 1 := by
    simp [coneType]
  have hbt : bottomType b i = #(univ.filter (b · = i)) - 1 := by
    rw [bottomType_eq_coneType]
    simp [coneType]
  have hcnt : #(univ.filter fun j ↦ f j = i) = #(univ.filter fun j ↦ i = f j) := by
    congr 1
    ext j
    simp [eq_comm]
  rw [hct, hbt] at hi
  simp only [Nat.cast_id] at hi
  rw [hcnt]
  omega

end Count

section Product

variable {σ K : Type*} [Field K] [Finite σ] {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]

/-- **The degree part of Rémond's estimate.** Under the hypotheses of
`MvPolynomial.prod_pow_mul_pow_mul_multidegree_le` with generators of multidegree `δ`, the type
`β` of the adapted transcendence basis has `ε^t d_β(𝔭) ≤ #{f : Fin t → ι | β + ∑_j ε_{f j} = n}`,
the multinomial coefficient `t! / ∏_i c_i!`. -/
theorem mul_multidegree_le_card {ι : Type*} [Fintype ι] [DecidableEq ι] [LinearOrder ι]
    [CharZero K] {b : σ → ι}
    (hb : Function.Surjective b) (hU : IsUnmixedRing (Localization.AtPrime 𝔭)) {δ : ι → ℕ}
    {R : Set (MvPolynomial σ K)} (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r δ)
    (h𝔭R : 𝔭 ∈ (Ideal.span R).minimalPrimes) (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} (ht : 𝔭.height = t) (hδ : ∀ i, 0 < δ i) {ε : ℝ}
    (hε : 0 < ε) {R' : Set (MvPolynomial σ K)} (hRR' : Ideal.span R ≤ Ideal.span R')
    (hI : ∀ P ∈ R', ∀ κ : σ →₀ ℕ, Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ ε →
      hasseDeriv κ P ∈ 𝔭) :
    ∃ T : Finset σ,
      IsTranscendenceBasis K (fun t : (T : Set σ) ↦ Ideal.Quotient.mk 𝔭 (X (t : σ))) ∧
      (∀ i, ∃ s ∈ T, b s = i) ∧ 1 ≤ multidegree b 𝔭 (coneType b T) ∧
      ε ^ t * multidegree b 𝔭 (coneType b T) ≤
        #(univ.filter fun f : Fin t → ι ↦
          coneType b T + ∑ j, Finsupp.single (f j) 1 = bottomType b) := by
  have := Fintype.ofFinite σ
  obtain ⟨T, hB, -, hTb, hcard, h⟩ :=
    prod_pow_mul_pow_mul_multidegree_le hb hU hR h𝔭R h𝔭 hne ht hδ hε hRR' hI
  obtain ⟨-, hpos⟩ := totalDegree_hilbertPoly_eq_and_one_le_multidegree hb h𝔭 hB hTb
  refine ⟨T, hB, hTb, hpos, ?_⟩
  have hβ : (bottomType b).degree - t ≤ (coneType b T).degree := by
    have h1 := degree_coneType_add_card b hTb
    have h2 := degree_coneType_add_card b (V := univ) fun i ↦
      (hb i).imp fun s hs ↦ ⟨mem_univ s, hs⟩
    rw [bottomType_eq_coneType]
    rw [Nat.card_eq_fintype_card] at hcard
    rw [Finset.card_univ] at h2
    omega
  have h' := h _ hβ
  rw [sum_prod_eq_card_mul_prod_pow b hTb δ] at h'
  have hP : 0 < ∏ i, (δ i : ℝ) ^ {s | s ∉ T ∧ b s = i}.ncard :=
    Finset.prod_pos fun i _ ↦ pow_pos (Nat.cast_pos.mpr (hδ i)) _
  rw [mul_assoc, mul_comm] at h'
  exact le_of_mul_le_mul_right h' hP

/-- **The cuts of two adapted bases.** Let `T` be a transcendence basis of `K[X]/𝔭` made of
variables, adapted to the last blocks. There is a transcendence basis `T'` made of variables,
adapted to the first blocks and meeting every block, with `|T'| = |T| = r(σ)`, such that the cut
`P_k = {s | b s < k}` has rank `|T' ∩ P_k|` and its complement has rank `|T \ P_k|` in the
algebraic matroid of the variables. -/
theorem exists_isTranscendenceBasis_cuts {m : ℕ} {b : σ → Fin m}
    (hb : Function.Surjective b) (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {T : Finset σ}
    (hB : IsTranscendenceBasis K (fun t : (T : Set σ) ↦ Ideal.Quotient.mk 𝔭 (X (t : σ))))
    (hadapt : ∀ s ∉ T, IsAlgebraic (Algebra.adjoin K
      ((fun t ↦ Ideal.Quotient.mk 𝔭 (X t)) '' {t | t ∈ T ∧ b s ≤ b t}))
        (Ideal.Quotient.mk 𝔭 (X s))) :
    ∃ T' : Finset σ,
      IsTranscendenceBasis K (fun t : (T' : Set σ) ↦ Ideal.Quotient.mk 𝔭 (X (t : σ))) ∧
      (∀ i, ∃ s ∈ T', b s = i) ∧ #T' = #T ∧ (varMatroid 𝔭).eRk Set.univ = #T ∧
      (∀ k : ℕ, (varMatroid 𝔭).eRk {s | (b s : ℕ) < k} = #(T'.filter fun s ↦ (b s : ℕ) < k)) ∧
      ∀ k : ℕ, (varMatroid 𝔭).eRk {s | k ≤ (b s : ℕ)} = #(T.filter fun s ↦ k ≤ (b s : ℕ)) := by
  classical
  have := Fintype.ofFinite σ
  set x : σ → MvPolynomial σ K ⧸ 𝔭 := fun s ↦ Ideal.Quotient.mk 𝔭 (X s)
  set N := varMatroid 𝔭
  -- The basis adapted to the first blocks.
  obtain ⟨T', hB', hadapt', hTb'⟩ :=
    exists_isTranscendenceBasis_adapted (fun s ↦ OrderDual.toDual (b s)) hb 𝔭 h𝔭 hne
  -- Ranks of the cuts.
  have hrank : ∀ (S : Finset σ), IsTranscendenceBasis K (fun t : (S : Set σ) ↦ x t) →
      (∀ s, IsAlgebraic (Algebra.adjoin K (x '' S)) (x s)) → N.eRk Set.univ = #S := by
    intro S hS hSa
    rw [eRk_varMatroid_eq (Set.subset_univ _) hS.1 fun s _ ↦ hSa s, Set.ncard_coe_finset]
  have hrT : N.eRk Set.univ = #T := hrank T hB fun s ↦ by
    by_cases hs : s ∈ T
    · exact isAlgebraic_algebraMap (⟨_, Algebra.subset_adjoin ⟨s, hs, rfl⟩⟩ :
        Algebra.adjoin K (x '' (T : Set σ)))
    · exact (hadapt s hs).tower_top_of_subalgebra_le
        (Algebra.adjoin_mono (Set.image_mono fun t ht ↦ ht.1))
  have hrT' : N.eRk Set.univ = #T' := hrank T' hB' fun s ↦ by
    by_cases hs : s ∈ T'
    · exact isAlgebraic_algebraMap (⟨_, Algebra.subset_adjoin ⟨s, hs, rfl⟩⟩ :
        Algebra.adjoin K (x '' (T' : Set σ)))
    · exact (hadapt' s hs).tower_top_of_subalgebra_le
        (Algebra.adjoin_mono (Set.image_mono fun t ht ↦ ht.1))
  have hTT' : #T' = #T := by
    have := hrT'.symm.trans hrT
    exact_mod_cast this
  have hP : ∀ k : ℕ, N.eRk {s | (b s : ℕ) < k} = #(T'.filter fun s ↦ (b s : ℕ) < k) := by
    intro k
    rw [← Set.ncard_coe_finset]
    refine eRk_varMatroid_eq (fun s hs ↦ (mem_filter.mp hs).2)
      (AlgebraicIndepOn.mono hB'.1 fun s hs ↦ (mem_filter.mp hs).1) fun s hs ↦ ?_
    by_cases hsT : s ∈ T'
    · exact isAlgebraic_algebraMap (⟨_, Algebra.subset_adjoin ⟨s, mem_filter.mpr ⟨hsT, hs⟩,
        rfl⟩⟩ : Algebra.adjoin K (x '' (T'.filter fun s ↦ (b s : ℕ) < k : Set σ)))
    · refine (hadapt' s hsT).tower_top_of_subalgebra_le
        (Algebra.adjoin_mono (Set.image_mono fun u hu ↦ mem_filter.mpr ⟨hu.1, ?_⟩))
      have : b u ≤ b s := OrderDual.toDual_le_toDual.mp hu.2
      exact lt_of_le_of_lt (Fin.le_iff_val_le_val.mp this) hs
  have hQ : ∀ k : ℕ, N.eRk {s | k ≤ (b s : ℕ)} = #(T.filter fun s ↦ k ≤ (b s : ℕ)) := by
    intro k
    rw [← Set.ncard_coe_finset]
    refine eRk_varMatroid_eq (fun s hs ↦ (mem_filter.mp hs).2)
      (AlgebraicIndepOn.mono hB.1 fun s hs ↦ (mem_filter.mp hs).1) fun s hs ↦ ?_
    by_cases hsT : s ∈ T
    · exact isAlgebraic_algebraMap (⟨_, Algebra.subset_adjoin ⟨s, mem_filter.mpr ⟨hsT, hs⟩,
        rfl⟩⟩ : Algebra.adjoin K (x '' (T.filter fun s ↦ k ≤ (b s : ℕ) : Set σ)))
    · refine (hadapt s hsT).tower_top_of_subalgebra_le
        (Algebra.adjoin_mono (Set.image_mono fun u hu ↦ mem_filter.mpr ⟨hu.1, ?_⟩))
      exact le_trans (Set.mem_ofPred_eq.mp hs) (Fin.le_iff_val_le_val.mp hu.2)
  exact ⟨T', hB', hTb', hTT', hrT, hP, hQ⟩

/-- **The product theorem from an adapted basis** (Rémond 2001, Prop. 2.1 and Thm. 1.1, geometric
part). Let `T` be a transcendence basis of `K[X]/𝔭` made of variables, adapted to the last blocks
(each `x_s`, `s ∉ T`, algebraic over the `x_t`, `t ∈ T`, with `b t ≥ b s`), meeting every block,
with `t + |T| = |σ|`, for which the degree inequality
`ε^t ∏_i δ_i^{c_i} d_β(𝔭) ≤ ∑_{f : β + ∑ ε_{f j} = n} ∏ δ_{f j}` holds (`c_i = |block i \ T|`).
If `δ` is decreasing and `δ_i / δ_{i+1} > (m/ε)^t`, then `V(𝔭)` is a component of the product of
its projections, `T` meets every block in a basis of it, and the type `β = coneType b T` of `T`
satisfies `ε^t d_β(𝔭) ≤ #{f : Fin t → Fin m | β + ∑_j ε_{f j} = n} ≤ m^t`. -/
theorem productTheorem_of_basis [CharZero K] {m : ℕ} {b : σ → Fin m}
    (hb : Function.Surjective b) (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} {δ : Fin m → ℕ} (hδ : ∀ i, 0 < δ i) {ε : ℝ}
    (hε : 0 < ε) (hanti : Antitone δ)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → (m : ℝ) ^ t < ε ^ t * (δ i / δ j))
    {T : Finset σ}
    (hB : IsTranscendenceBasis K (fun t : (T : Set σ) ↦ Ideal.Quotient.mk 𝔭 (X (t : σ))))
    (hadapt : ∀ s ∉ T, IsAlgebraic (Algebra.adjoin K
      ((fun t ↦ Ideal.Quotient.mk 𝔭 (X t)) '' {t | t ∈ T ∧ b s ≤ b t}))
        (Ideal.Quotient.mk 𝔭 (X s)))
    (hTb : ∀ i, ∃ s ∈ T, b s = i) (hcard : t + #T = Nat.card σ)
    (hineq : ∀ β : Fin m →₀ ℕ, (bottomType b).degree - t ≤ β.degree →
      (∏ i, (δ i : ℝ) ^ {s | s ∉ T ∧ b s = i}.ncard) * ε ^ t * multidegree b 𝔭 β ≤
        ∑ f : Fin t → Fin m with β + ∑ j, Finsupp.single (f j) 1 = bottomType b,
          ∏ j, (δ (f j) : ℝ)) :
    𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes ∧
      (∀ i, (coneType b T i : ℕ∞) + 1 = (varMatroid 𝔭).eRk {s | b s = i}) ∧
      1 ≤ multidegree b 𝔭 (coneType b T) ∧
      ε ^ t * multidegree b 𝔭 (coneType b T) ≤
        #(univ.filter fun f : Fin t → Fin m ↦
          coneType b T + ∑ j, Finsupp.single (f j) 1 = bottomType b) ∧
      #(univ.filter fun f : Fin t → Fin m ↦
        coneType b T + ∑ j, Finsupp.single (f j) 1 = bottomType b) ≤ m ^ t := by
  classical
  have := Fintype.ofFinite σ
  set N := varMatroid 𝔭
  obtain ⟨T', hB', hTb', hTT', hrT, hP, hQ⟩ := exists_isTranscendenceBasis_cuts hb h𝔭 hne hB hadapt
  have hsplit : ∀ (S : Finset σ) (k : ℕ),
      #(S.filter fun s ↦ k ≤ (b s : ℕ)) + #(S.filter fun s ↦ (b s : ℕ) < k) = #S := by
    intro S k
    rw [add_comm]
    have := Finset.card_filter_add_card_filter_not (s := S) (fun s ↦ (b s : ℕ) < k)
    simpa only [not_lt] using this
  -- `E_k ≥ 0`: the cut ranks are subadditive.
  have hsub : ∀ k : ℕ, #(T.filter fun s ↦ (b s : ℕ) < k) ≤
      #(T'.filter fun s ↦ (b s : ℕ) < k) := by
    intro k
    have h := N.eRk_union_le_eRk_add_eRk {s | (b s : ℕ) < k} {s | k ≤ (b s : ℕ)}
    have hU' : {s | (b s : ℕ) < k} ∪ {s | k ≤ (b s : ℕ)} = Set.univ := by
      ext s
      simp only [Set.mem_union, Set.mem_ofPred_eq, Set.mem_univ, iff_true]
      omega
    rw [hU', hrT, hP, hQ] at h
    have h' : #T ≤ #(T'.filter fun s ↦ (b s : ℕ) < k) + #(T.filter fun s ↦ k ≤ (b s : ℕ)) := by
      exact_mod_cast h
    have := hsplit T k
    omega
  -- The partial sums.
  set a : ℕ → ℤ := fun j ↦ (#(T'.filter fun s ↦ (b s : ℕ) = j) : ℤ) -
    #(T.filter fun s ↦ (b s : ℕ) = j)
  have hfib : ∀ (S : Finset σ) (k : ℕ),
      ∑ j ∈ range k, #(S.filter fun s ↦ (b s : ℕ) = j) = #(S.filter fun s ↦ (b s : ℕ) < k) := by
    intro S k
    rw [Finset.card_eq_sum_card_fiberwise (f := fun s ↦ (b s : ℕ)) (t := range k)
      fun s hs ↦ mem_range.mpr (mem_filter.mp hs).2]
    refine Finset.sum_congr rfl fun j hj ↦ ?_
    congr 1
    ext s
    simp only [mem_filter]
    constructor
    · intro h
      exact ⟨⟨h.1, h.2 ▸ mem_range.mp hj⟩, h.2⟩
    · intro h
      exact ⟨h.1.1, h.2⟩
  have hG : ∀ k, ∑ j ∈ range k, a j =
      (#(T'.filter fun s ↦ (b s : ℕ) < k) : ℤ) - #(T.filter fun s ↦ (b s : ℕ) < k) := by
    intro k
    simp only [a, Finset.sum_sub_distrib]
    rw [← Nat.cast_sum, ← Nat.cast_sum, hfib, hfib]
  have hall : ∀ (S : Finset σ), S.filter (fun s ↦ (b s : ℕ) < m) = S := fun S ↦
    Finset.filter_true_of_mem fun s _ ↦ (b s).2
  -- The degree inequality between the two bases forces every `E_k = 0`.
  have hEk : ∀ k ≤ m, ∑ j ∈ range k, a j = 0 := by
    intro k hk
    have hβ' : (bottomType b).degree - t ≤ (coneType b T').degree := by
      have h1 := degree_coneType_add_card b hTb'
      have h2 := degree_coneType_add_card b (V := univ) fun i ↦
        (hb i).imp fun s hs ↦ ⟨mem_univ s, hs⟩
      rw [bottomType_eq_coneType]
      rw [Nat.card_eq_fintype_card] at hcard
      rw [Finset.card_univ] at h2
      omega
    have h' := hineq _ hβ'
    rw [sum_prod_eq_card_mul_prod_pow b hTb' δ] at h'
    obtain ⟨-, hpos⟩ := totalDegree_hilbertPoly_eq_and_one_le_multidegree hb h𝔭 hB' hTb'
    have hpos' : (1 : ℝ) ≤ multidegree b 𝔭 (coneType b T') := by exact_mod_cast hpos
    have hδR : 0 ≤ (∏ i, (δ i : ℝ) ^ {s | s ∉ T ∧ b s = i}.ncard) * ε ^ t :=
      mul_nonneg (Finset.prod_nonneg fun i _ ↦ pow_nonneg (Nat.cast_nonneg _) _)
        (pow_nonneg hε.le t)
    refine sum_range_eq_zero_of_prod_pow_le hδ hanti hε ?_ hratio
      ((le_mul_of_one_le_right hδR hpos').trans h') (fun i ↦ ?_)
      (fun k _ ↦ ?_) ?_ hk
    · refine (Finset.card_filter_le _ _).trans ?_
      simp
    · have h1 := ncard_notMem_add_card_filter b T i
      have h2 := ncard_notMem_add_card_filter b T' i
      have hc : ∀ S : Finset σ,
          S.filter (fun s ↦ (b s : ℕ) = (i : ℕ)) = S.filter (b · = i) :=
        fun S ↦ Finset.filter_congr fun s _ ↦ Fin.val_inj
      simp only [a, hc]
      omega
    · rw [hG]
      have := hsub k
      omega
    · rw [hG, hall, hall, hTT', sub_self]
  -- The cuts are tight, so `𝔭` is minimal over its block traces.
  have hblocks : ∑ i, N.eRk {s | b s = i} ≤ N.eRk Set.univ := by
    refine sum_eRk_le_of_forall_cut b N ?_ fun k ↦ ?_
    · rw [hrT]
      exact ENat.natCast_ne_top _
    · rw [hP, hQ, hrT]
      by_cases hk : k ≤ m
      · have h := hEk k hk
        rw [hG] at h
        have := hsplit T k
        have h' : #(T'.filter fun s ↦ (b s : ℕ) < k) = #(T.filter fun s ↦ (b s : ℕ) < k) := by
          omega
        rw [h']
        have h2 := hsplit T k
        exact_mod_cast (show #(T.filter fun s ↦ (b s : ℕ) < k) +
          #(T.filter fun s ↦ k ≤ (b s : ℕ)) ≤ #T by omega)
      · have hempty : T.filter (fun s ↦ k ≤ (b s : ℕ)) = ∅ :=
          Finset.filter_false_of_mem fun s _ ↦ by have := (b s).2; omega
        have hT'k : T'.filter (fun s ↦ (b s : ℕ) < k) = T' :=
          Finset.filter_true_of_mem fun s _ ↦ by have := (b s).2; omega
        rw [hempty, hT'k, Finset.card_empty, Nat.cast_zero, add_zero, hTT']
  -- Hence `T` meets each block in a basis of it, and `coneType b T` is the type of the factors.
  have hle : ∀ i, (#(T.filter (b · = i)) : ℕ∞) ≤ N.eRk {s | b s = i} := fun i ↦ by
    have hind : N.Indep (T.filter (b · = i) : Set σ) :=
      varMatroid_indep_iff.mpr (AlgebraicIndepOn.mono hB.1 fun s hs ↦ (mem_filter.mp hs).1)
    rw [← Set.encard_coe_eq_coe_finsetCard]
    exact hind.encard_le_eRk_of_subset fun s hs ↦ (mem_filter.mp hs).2
  have hfinR : ∀ i, N.eRk {s | b s = i} = ((N.eRk {s | b s = i}).toNat : ℕ∞) := fun i ↦
    (ENat.natCast_toNat (ne_top_of_le_ne_top (ENat.natCast_ne_top #T)
      ((N.eRk_mono (Set.subset_univ _)).trans hrT.le))).symm
  have hsumT : ∑ i, #(T.filter (b · = i)) = #T :=
    (Finset.card_eq_sum_card_fiberwise fun s _ ↦ mem_univ (b s)).symm
  have hblk : ∀ i, (#(T.filter (b · = i)) : ℕ∞) = N.eRk {s | b s = i} := by
    have hle' : ∀ i ∈ (univ : Finset (Fin m)),
        #(T.filter (b · = i)) ≤ (N.eRk {s | b s = i}).toNat := fun i _ ↦ by
      have := hle i
      rw [hfinR i] at this
      exact_mod_cast this
    have hge : ∑ i, (N.eRk {s | b s = i}).toNat ≤ ∑ i, #(T.filter (b · = i)) := by
      have := hblocks
      rw [hrT, ← hsumT] at this
      rw [Finset.sum_congr rfl fun i _ ↦ hfinR i] at this
      exact_mod_cast this
    have heq := (Finset.sum_eq_sum_iff_of_le hle').mp (le_antisymm (Finset.sum_le_sum hle') hge)
    intro i
    rw [hfinR i, heq i (mem_univ i)]
  have hβT : (bottomType b).degree - t ≤ (coneType b T).degree := by
    have h1 := degree_coneType_add_card b hTb
    have h2 := degree_coneType_add_card b (V := univ) fun i ↦
      (hb i).imp fun s hs ↦ ⟨mem_univ s, hs⟩
    rw [bottomType_eq_coneType]
    rw [Nat.card_eq_fintype_card] at hcard
    rw [Finset.card_univ] at h2
    omega
  obtain ⟨-, hpos⟩ := totalDegree_hilbertPoly_eq_and_one_le_multidegree hb h𝔭 hB hTb
  refine ⟨mem_minimalPrimes_span_of_sum_eRk_le b 𝔭 hblocks, fun i ↦ ?_, hpos, ?_, ?_⟩
  · rw [← hblk i]
    obtain ⟨s, hs, hsi⟩ := hTb i
    have hc : 0 < #(T.filter (b · = i)) := Finset.card_pos.mpr ⟨s, mem_filter.mpr ⟨hs, hsi⟩⟩
    have : coneType b T i = #(T.filter (b · = i)) - 1 := by
      simp [coneType]
    rw [this]
    exact_mod_cast Nat.sub_add_cancel hc
  · have h' := hineq _ hβT
    rw [sum_prod_eq_card_mul_prod_pow b hTb δ] at h'
    have hP0 : 0 < ∏ i, (δ i : ℝ) ^ {s | s ∉ T ∧ b s = i}.ncard :=
      Finset.prod_pos fun i _ ↦ pow_pos (Nat.cast_pos.mpr (hδ i)) _
    rw [mul_assoc, mul_comm] at h'
    exact le_of_mul_le_mul_right h' hP0
  · refine (Finset.card_filter_le _ _).trans ?_
    simp

/-- **Rémond's product theorem, geometric part** (Rémond 2001, Prop. 2.1 and Thm. 1.1). Let `𝔭` be
a multihomogeneous prime of `K[X]`, `K` of characteristic `0`, with the variables in blocks
`b : σ → Fin m`, minimal over an ideal generated by polynomials `R` of multidegree `δ`, and suppose
that ideal lies in the one generated by a set `R'` (for instance `R' = R`) every element of which
has `∂_κ P ∈ 𝔭` whenever `∑_s κ_s / δ_{b s} ≤ ε`. If `δ` is decreasing and
`δ_i / δ_{i+1} > (m/ε)^t`, `t = ht 𝔭`, then:
* `𝔭` is a minimal prime of the ideal generated by its traces on the blocks: `V(𝔭)` is a
  component of the product `Z_1 × ⋯ × Z_m` of its projections;
* with `β_i = dim Z_i`, i.e. `β_i + 1` the transcendence degree of the variables of block `i`
  modulo `𝔭`, the degree `d_β(𝔭)` is a positive integer with
  `ε^t d_β(𝔭) ≤ #{f : Fin t → Fin m | β + ∑_j ε_{f j} = n} ≤ m^t`. The count is the multinomial
  coefficient `t! / ∏_i (codim Z_i)!`, so this is Rémond's `d(Z) ≤ ρ(ε, Z) ≤ (m/ε)^{codim Z}`. -/
theorem productTheorem [CharZero K] {m : ℕ} {b : σ → Fin m}
    (hb : Function.Surjective b) (hU : IsUnmixedRing (Localization.AtPrime 𝔭)) {δ : Fin m → ℕ}
    {R : Set (MvPolynomial σ K)} (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r δ)
    (h𝔭R : 𝔭 ∈ (Ideal.span R).minimalPrimes) (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} (ht : 𝔭.height = t) (hδ : ∀ i, 0 < δ i) {ε : ℝ}
    (hε : 0 < ε) {R' : Set (MvPolynomial σ K)} (hRR' : Ideal.span R ≤ Ideal.span R')
    (hI : ∀ P ∈ R', ∀ κ : σ →₀ ℕ, Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ ε →
      hasseDeriv κ P ∈ 𝔭)
    (hanti : Antitone δ)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → (m : ℝ) ^ t < ε ^ t * (δ i / δ j)) :
    𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes ∧
      ∃ β : Fin m →₀ ℕ, (∀ i, (β i : ℕ∞) + 1 = (varMatroid 𝔭).eRk {s | b s = i}) ∧
        1 ≤ multidegree b 𝔭 β ∧
        ε ^ t * multidegree b 𝔭 β ≤
          #(univ.filter fun f : Fin t → Fin m ↦
            β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ∧
        #(univ.filter fun f : Fin t → Fin m ↦
          β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ≤ m ^ t := by
  obtain ⟨T, hB, hadapt, hTb, hcard, hineq⟩ :=
    prod_pow_mul_pow_mul_multidegree_le hb hU hR h𝔭R h𝔭 hne ht hδ hε hRR' hI
  obtain ⟨hmin, hrk, hpos, hle, hcount⟩ :=
    productTheorem_of_basis hb h𝔭 hne hδ hε hanti hratio hB hadapt hTb hcard hineq
  exact ⟨hmin, coneType b T, hrk, hpos, hle, hcount⟩

/-- **Rémond's product theorem, the product structure** (Rémond 2001, Thm. 1.1): under the
hypotheses of `MvPolynomial.productTheorem`, `V(𝔭)` is a component of the product of its
projections. -/
theorem mem_minimalPrimes_span_of_productTheorem [CharZero K] {m : ℕ} {b : σ → Fin m}
    (hb : Function.Surjective b) (hU : IsUnmixedRing (Localization.AtPrime 𝔭)) {δ : Fin m → ℕ}
    {R : Set (MvPolynomial σ K)} (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r δ)
    (h𝔭R : 𝔭 ∈ (Ideal.span R).minimalPrimes) (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} (ht : 𝔭.height = t) (hδ : ∀ i, 0 < δ i) {ε : ℝ}
    (hε : 0 < ε)
    (hI : ∀ P ∈ R, ∀ κ : σ →₀ ℕ, Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ ε →
      hasseDeriv κ P ∈ 𝔭)
    (hanti : Antitone δ)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → (m : ℝ) ^ t < ε ^ t * (δ i / δ j)) :
    𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes :=
  (productTheorem hb hU hR h𝔭R h𝔭 hne ht hδ hε le_rfl hI hanti hratio).1

end Product

end MvPolynomial
