/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import QuantitativeSubspace.ArithmeticBezout
public import QuantitativeSubspace.PolynomialHeight
public import QuantitativeSubspace.ProductTheorem

-- Used only inside proofs.
import ForMathlib.RingTheory.MvPolynomial.Product
import Mathlib.Algebra.Order.BigOperators.Ring.Finset

/-!
# The product theorem, height part (Rémond 2001, Thm 1.1)

Under the hypotheses of `MvPolynomial.productTheorem`, with the ideal generated by a finite family
`R` of polynomials of multidegree `δ`, let `H` be a multiprojective height theory
(`MvPolynomial.MultiprojectiveHeight`) and suppose the polynomial heights of the natural
combinations of `R` are bounded by a monotone function of the size of the coefficients:
`h_m(∑_r a_r r) ≤ B(∑_r a_r)`. Then `V(𝔭)` is a component of the product `Z_1 × ⋯ × Z_m` of its
projections, of type `β = (dim Z_i)_i`, and for every `k` with `Z_k ≠ ℙ^{n_k}`,
`ε^t δ_k h_{β + ε_k}(𝔭) ≤ ∑_l h(ℙ^{n_l}) δ_l #F_l + S · #G_k`, where
`S = ∑_{j < t} max(B(|δ|^j), 0)`,
`F_l = {f : Fin t → Fin m | β + ε_k + ∑_j ε_{f j} = n + ε_l}` and
`G_k = {g : Fin (t - 1) → Fin m | β + ε_k + ∑_j ε_{g j} = n}`
(`MvPolynomial.productTheorem_height`).

This is the height part of G. Rémond, *Sur le théorème du produit*, J. Théor. Nombres Bordeaux
**13** (2001), Thm 1.1, for `h(𝔭)` in place of Rémond's `N⁻¹ ∏_{j ≠ k} d(Z_j) h(Z_k)`. The counts
are multinomial coefficients: `#F_l = c! / (α' + ε_l)!` and `#G_k = (c - 1)! / α'!` for
`α' = c - ε_k`, `c = n - β` the codimensions, and with Rémond's bound `B(s) ≤ h(R) + log s + |√n|`
(relative to `K`, see `QuantitativeSubspace.MultiprojectiveHeight`) the error term is his
`c!/α'! · h_0`. `MvPolynomial.productTheorem_height_coeff` takes
`B(s) = h(R) + [K : ℚ] (log s + log (∑_{μ ∈ M} 1/C(δ, μ))^{1/2})`, with `h(R)` the height of the
coefficients of `R` (`MvPolynomial.bombieriLogHeight_sum_nsmul_le`); Rémond's Lemma 5.2 bounds the
last term by `|√n|` (`MvPolynomial.log_sqrt_sum_inv_blockMultinomial_le`).

The proof combines the arithmetic excess Bézout inequality
(`MvPolynomial.exists_localLength_mul_height_le`) with the multiplicity estimate
`ε^t ∏_i δ_i^{c_i} ≤ ℓ(K[X]_𝔭/(P)_𝔭)` (`MvPolynomial.prod_mul_pow_le_localLength`), for the
same adapted transcendence basis `T` that gives the product structure
(`MvPolynomial.productTheorem_of_basis`). In the type `β + ε_k`, each term of the Bézout sums is
`∏_i δ_i^{c_i}` times `δ_l / δ_k` or `1 / δ_k`.

This is part of Layer Q1.3 of the `QuantitativeSubspace` roadmap.
-/

@[expose] public section

open Finset

namespace MvPolynomial

section Count

variable {ι : Type*} [Fintype ι]

/-- `∏_j δ_{f j} = ∏_i δ_i^{x_i}` for `x = ∑_j ε_{f j}`. -/
theorem prod_comp_eq_prod_pow_sum {t : ℕ} (f : Fin t → ι) (δ : ι → ℝ) :
    ∏ j, δ (f j) = ∏ i, δ i ^ ((∑ j, Finsupp.single (f j) 1 : ι →₀ ℕ) i) := by
  classical
  rw [← Finset.prod_fiberwise' Finset.univ f δ]
  refine Finset.prod_congr rfl fun i _ ↦ ?_
  rw [Finset.prod_const]
  congr 1
  simp only [Finsupp.coe_finsetSum, Finset.sum_apply, Finsupp.single_apply, Finset.sum_boole,
    Nat.cast_id]

theorem prod_pow_add (δ : ι → ℝ) (x y : ι →₀ ℕ) :
    ∏ i, δ i ^ ((x + y) i) = (∏ i, δ i ^ x i) * ∏ i, δ i ^ y i := by
  simp [pow_add, prod_mul_distrib]

theorem prod_pow_single (δ : ι → ℝ) (k : ι) :
    ∏ i, δ i ^ ((Finsupp.single k 1 : ι →₀ ℕ) i) = δ k := by
  classical
  simp [Finsupp.single_apply, pow_ite]

end Count

section Height

variable {σ K : Type*} [Field K] [Fintype σ] {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime]

/-- **The multiplicity estimate against heights** (Rémond 2001, proof of Thm 1.1, height part).
Under the hypotheses of `MvPolynomial.prod_pow_mul_pow_mul_multidegree_le`, with `R` finite, there
is an adapted transcendence basis `T` with the degree inequality of that theorem and, for a
multiprojective height theory `H`, natural combinations `P_1, …, P_t` of `R` with
`∑ a_r ≤ |e|^j` and
`ε^t ∏_i δ_i^{c_i} h_β(𝔭) ≤ ∑_f ∏ e_{f j} h_{β + ∑ ε_{f j}}(ℙ)
  + (∑_j max(h_m(P_j), 0)) ∑_g ∏ e_{g j} d_{β + ∑ ε_{g j}}(ℙ)` for `|β| = |n| - t + 1`. -/
theorem prod_pow_mul_pow_mul_height_le [CharZero K] [Height.AdmissibleAbsValues K] {ι : Type*}
    [Fintype ι] [DecidableEq ι] [LinearOrder ι] {b : σ → ι}
    (hb : Function.Surjective b) (H : MultiprojectiveHeight b)
    (hU : IsUnmixedRing (Localization.AtPrime 𝔭)) {e : ι → ℕ}
    {R : Finset (MvPolynomial σ K)} (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r e)
    (h𝔭R : 𝔭 ∈ (Ideal.span (R : Set (MvPolynomial σ K))).minimalPrimes)
    (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} (ht : 𝔭.height = t)
    {δ : ι → ℕ} (hδ : ∀ i, 0 < δ i) {ε : ℝ} (hε : 0 < ε) {R' : Set (MvPolynomial σ K)}
    (hRR' : Ideal.span (R : Set (MvPolynomial σ K)) ≤ Ideal.span R')
    (hI : ∀ P ∈ R', ∀ κ : σ →₀ ℕ, Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ ε →
      hasseDeriv κ P ∈ 𝔭) :
    ∃ T : Finset σ,
      IsTranscendenceBasis K (fun t : (T : Set σ) ↦ Ideal.Quotient.mk 𝔭 (X (t : σ))) ∧
      (∀ s ∉ T, IsAlgebraic (Algebra.adjoin K
        ((fun t ↦ Ideal.Quotient.mk 𝔭 (X t)) '' {t | t ∈ T ∧ b s ≤ b t}))
          (Ideal.Quotient.mk 𝔭 (X s))) ∧
      (∀ i, ∃ s ∈ T, b s = i) ∧ t + #T = Nat.card σ ∧
      (∀ β : ι →₀ ℕ, (bottomType b).degree - t ≤ β.degree →
        (∏ i, (δ i : ℝ) ^ {s | s ∉ T ∧ b s = i}.ncard) * ε ^ t * multidegree b 𝔭 β ≤
          ∑ f : Fin t → ι with β + ∑ j, Finsupp.single (f j) 1 = bottomType b,
            ∏ j, (e (f j) : ℝ)) ∧
      ∃ P : Fin t → MvPolynomial σ K,
        (∀ j : Fin t, ∃ a : MvPolynomial σ K → ℕ, ∑ r ∈ R, a r ≤ (∑ i, e i) ^ (j : ℕ) ∧
          P j = ∑ r ∈ R, a r • r) ∧
        ∀ β : ι →₀ ℕ, β.degree = (bottomType b).degree - t + 1 →
          (∏ i, (δ i : ℝ) ^ {s | s ∉ T ∧ b s = i}.ncard) * ε ^ t * H.height 𝔭 β ≤
            bezoutSum e t (H.height ⊥) β +
              (∑ j, max (bombieriLogHeight b (P j)) 0) *
                bezoutSum e (t - 1)
                  (fun γ ↦ (multidegree b (⊥ : Ideal (MvPolynomial σ K)) γ : ℝ)) β := by
  classical
  have : Infinite K := Infinite.of_injective _ Nat.cast_injective
  obtain ⟨T, hB, hadapt, hTb, hcard, v, hv, hrange, Q, hQ, hoff, hdiag⟩ :=
    exists_transversal_fin_of_hilbertPoly_ne_zero hb 𝔭 h𝔭 hne ht
  have hI' : Ideal.span (R : Set (MvPolynomial σ K)) ≤
      (weightIdeal (fun α ↦ ((δ (b (v α)) : ℝ))⁻¹) ε).comap (taylorAtPrime 𝔭 v) := by
    refine hRR'.trans (Ideal.span_le.mpr fun P hP ↦ ?_)
    refine (taylorAtPrime_mem_weightIdeal_iff 𝔭 hv
      (fun α ↦ inv_nonneg.mpr (Nat.cast_nonneg _)) P).mpr fun γ hγ ↦ hI P hP _ ?_
    rwa [weight_mapDomain (w := fun α ↦ ((δ (b (v α)) : ℝ))⁻¹)
      (w' := fun s ↦ ((δ (b s) : ℝ))⁻¹) (AddMonoidHom.id ℝ) (f := v) (fun _ ↦ rfl)]
  refine ⟨T, hB, hadapt, hTb, hcard, fun β hβ ↦ ?_, ?_⟩
  · rw [← prod_comp_eq_prod_pow hv hrange δ]
    exact prod_mul_pow_mul_multidegree_le hb hU hR h𝔭R h𝔭 hne ht hQ hoff hdiag
      (fun α ↦ hδ _) hε hI' β hβ
  obtain ⟨P, hPa, ℓ, hℓ, -, hh⟩ := exists_localLength_mul_height_le hb H hU h𝔭 hne hR h𝔭R ht
  have hx : ∀ j, P j ∈ Ideal.span (R : Set (MvPolynomial σ K)) := by
    intro j
    obtain ⟨a, -, ha⟩ := hPa j
    rw [ha]
    exact Ideal.sum_mem _ fun r hr ↦ Submodule.smul_of_tower_mem _ _ (Ideal.subset_span hr)
  have hmult := prod_mul_pow_le_localLength hQ hoff hdiag (fun α ↦ hδ (b (v α))) hε hI' hx hℓ
  rw [prod_comp_eq_prod_pow hv hrange δ] at hmult
  refine ⟨P, hPa, fun β hβ ↦ (mul_le_mul_of_nonneg_right hmult ?_).trans (hh β hβ)⟩
  exact H.height_nonneg 𝔭 inferInstance h𝔭 hne β

/-- **Rémond's product theorem with heights** (Rémond 2001, Thm 1.1). Under the hypotheses of
`MvPolynomial.productTheorem`, with `R` finite, let `H` be a multiprojective height theory and `B`
a monotone bound for the polynomial heights of the nonzero natural combinations of `R`:
`h_m(∑_r a_r r) ≤ B(∑_r a_r)`. Then `V(𝔭)` is a component of the product of its projections, with
type `β` as in `MvPolynomial.productTheorem`, and for every `k` with `β_k < n_k`
`ε^t δ_k h_{β + ε_k}(𝔭) ≤ ∑_l h(ℙ^{n_l}) δ_l #F_l + (∑_{j < t} max(B(|δ|^j), 0)) #G_k`,
`F_l = {f : Fin t → Fin m | β + ε_k + ∑_j ε_{f j} = n + ε_l}`,
`G_k = {g : Fin (t - 1) → Fin m | β + ε_k + ∑_j ε_{g j} = n}`. -/
theorem productTheorem_height [CharZero K] [Height.AdmissibleAbsValues K] {m : ℕ}
    {b : σ → Fin m} (hb : Function.Surjective b) (H : MultiprojectiveHeight b)
    (hU : IsUnmixedRing (Localization.AtPrime 𝔭)) {δ : Fin m → ℕ}
    {R : Finset (MvPolynomial σ K)} (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r δ)
    (h𝔭R : 𝔭 ∈ (Ideal.span (R : Set (MvPolynomial σ K))).minimalPrimes)
    (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b)) (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ}
    (ht : 𝔭.height = t) (hδ : ∀ i, 0 < δ i) {ε : ℝ} (hε : 0 < ε)
    {R' : Set (MvPolynomial σ K)} (hRR' : Ideal.span (R : Set (MvPolynomial σ K)) ≤ Ideal.span R')
    (hI : ∀ P ∈ R', ∀ κ : σ →₀ ℕ, Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ ε →
      hasseDeriv κ P ∈ 𝔭)
    (hanti : Antitone δ)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → (m : ℝ) ^ t < ε ^ t * (δ i / δ j))
    {B : ℕ → ℝ} (hBmono : Monotone B)
    (hRB : ∀ a : MvPolynomial σ K → ℕ, ∑ r ∈ R, a r • r ≠ 0 →
      bombieriLogHeight b (∑ r ∈ R, a r • r) ≤ B (∑ r ∈ R, a r)) :
    𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes ∧
      ∃ β : Fin m →₀ ℕ, (∀ i, (β i : ℕ∞) + 1 = (varMatroid 𝔭).eRk {s | b s = i}) ∧
        1 ≤ multidegree b 𝔭 β ∧
        ε ^ t * multidegree b 𝔭 β ≤
          #(univ.filter fun f : Fin t → Fin m ↦
            β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ∧
        #(univ.filter fun f : Fin t → Fin m ↦
          β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ≤ m ^ t ∧
        ∀ k, β k < bottomType b k →
          ε ^ t * δ k * H.height 𝔭 (β + Finsupp.single k 1) ≤
            ∑ l, Height.totalWeight K * H.botBound (bottomType b l) * δ l *
                #(univ.filter fun f : Fin t → Fin m ↦ β + Finsupp.single k 1 +
                  ∑ j, Finsupp.single (f j) 1 = bottomType b + Finsupp.single l 1) +
              (∑ j ∈ range t, max (B ((∑ i, δ i) ^ j)) 0) *
                #(univ.filter fun g : Fin (t - 1) → Fin m ↦ β + Finsupp.single k 1 +
                  ∑ j, Finsupp.single (g j) 1 = bottomType b) := by
  classical
  obtain ⟨T, hB, hadapt, hTb, hcard, hineq, P, hPa, hh⟩ :=
    prod_pow_mul_pow_mul_height_le hb H hU hR h𝔭R h𝔭 hne ht hδ hε hRR' hI
  obtain ⟨hmin, hrk, hpos, hle, hcount⟩ :=
    productTheorem_of_basis hb h𝔭 hne hδ hε hanti hratio hB hadapt hTb hcard hineq
  refine ⟨hmin, coneType b T, hrk, hpos, hle, hcount, fun k hk ↦ ?_⟩
  set β := coneType b T
  -- The codimensions `c = bottomType b - β`.
  have hcβ : ∀ i, {s | s ∉ T ∧ b s = i}.ncard + β i = bottomType b i := by
    intro i
    have h1 := ncard_notMem_add_card_filter b T i
    obtain ⟨s, hs, hsi⟩ := hTb i
    have hpos : 0 < #(T.filter (b · = i)) := Finset.card_pos.mpr ⟨s, by simp [hs, hsi]⟩
    have hct : β i = #(T.filter (b · = i)) - 1 := by simp [β, coneType]
    have hbt : bottomType b i = #(univ.filter (b · = i)) - 1 := by
      rw [bottomType_eq_coneType]
      simp [coneType]
    omega
  set c : Fin m →₀ ℕ := bottomType b - β
  have hc : ∀ i, {s | s ∉ T ∧ b s = i}.ncard = c i := by
    intro i
    have := hcβ i
    simp only [c, Finsupp.coe_tsub, Pi.sub_apply]
    omega
  have hβc : β + c = bottomType b := by
    ext i
    simp only [c, Finsupp.coe_add, Finsupp.coe_tsub, Pi.add_apply, Pi.sub_apply]
    have := hcβ i
    omega
  have hd1 : β.degree + Fintype.card (Fin m) = #T := degree_coneType_add_card b hTb
  have hd2 := degree_bottomType_add_card hb (σ := σ)
  have hβdeg : β.degree = (bottomType b).degree - t := by omega
  have htn : t ≤ (bottomType b).degree := by omega
  set Pc := ∏ i, (δ i : ℝ) ^ c i
  have hPc : 0 < Pc := Finset.prod_pos fun i _ ↦ pow_pos (Nat.cast_pos.mpr (hδ i)) _
  have hPc' : ∏ i, (δ i : ℝ) ^ {s | s ∉ T ∧ b s = i}.ncard = Pc :=
    Finset.prod_congr rfl fun i _ ↦ by rw [hc i]
  set γ := β + Finsupp.single k 1
  have hγdeg : γ.degree = (bottomType b).degree - t + 1 := by
    simp only [γ, map_add, Finsupp.degree_single, hβdeg]
  -- `δ_k ∏_j δ_{f j} = Pc δ_l` when `γ + ∑ ε_{f j} = bottomType b + ε_l`.
  have hprod : ∀ {u : ℕ} (f : Fin u → Fin m) (y : Fin m →₀ ℕ),
      γ + ∑ j, Finsupp.single (f j) 1 = bottomType b + y →
        (δ k : ℝ) * ∏ j, (δ (f j) : ℝ) = Pc * ∏ i, (δ i : ℝ) ^ y i := by
    intro u f y hf
    have hx : (∑ j, Finsupp.single (f j) 1) + Finsupp.single k 1 = c + y := by
      apply add_left_cancel (a := β)
      rw [← add_assoc, ← add_assoc, hβc, ← hf]
      simp only [γ]
      abel
    rw [prod_comp_eq_prod_pow_sum f (fun i ↦ (δ i : ℝ)), mul_comm,
      ← prod_pow_single (fun i ↦ (δ i : ℝ)) k, ← prod_pow_add, hx, prod_pow_add]
  have hdeg_f : ∀ {u : ℕ} (f : Fin u → Fin m),
      (γ + ∑ j, Finsupp.single (f j) 1).degree = (bottomType b).degree - t + 1 + u := by
    intro u f
    rw [map_add, map_sum, hγdeg]
    simp
  -- The term `∑_f ∏ δ_{f j} h(ℙ, γ + ∑ ε_{f j})`.
  have h1 : (δ k : ℝ) * bezoutSum δ t (H.height ⊥) γ ≤
      Pc * ∑ l, Height.totalWeight K * H.botBound (bottomType b l) * δ l *
        #(univ.filter fun f : Fin t → Fin m ↦
          γ + ∑ j, Finsupp.single (f j) 1 = bottomType b + Finsupp.single l 1) := by
    rw [bezoutSum, Finset.mul_sum, Finset.mul_sum]
    have hterm : ∀ f : Fin t → Fin m, (δ k : ℝ) * ((∏ j, (δ (f j) : ℝ)) *
        H.height ⊥ (γ + ∑ j, Finsupp.single (f j) 1)) ≤
          ∑ l, if γ + ∑ j, Finsupp.single (f j) 1 = bottomType b + Finsupp.single l 1 then
            Pc * (Height.totalWeight K * H.botBound (bottomType b l) * δ l) else 0 := by
      intro f
      by_cases hex : ∃ l, γ + ∑ j, Finsupp.single (f j) 1 = bottomType b + Finsupp.single l 1
      · obtain ⟨l, hl⟩ := hex
        have hiff : ∀ l', γ + ∑ j, Finsupp.single (f j) 1 = bottomType b + Finsupp.single l' 1 ↔
            l' = l := by
          intro l'
          rw [hl]
          constructor
          · intro h
            exact (Finsupp.single_left_injective one_ne_zero (add_left_cancel h)).symm
          · rintro rfl
            rfl
        simp only [hiff, Finset.sum_ite_eq', Finset.mem_univ, ↓reduceIte]
        rw [← mul_assoc, hprod f _ hl, hl, prod_pow_single]
        have := mul_le_mul_of_nonneg_left (H.height_bot_single_le l)
          (mul_nonneg hPc.le (Nat.cast_nonneg (δ l)))
        calc Pc * (δ l : ℝ) * H.height ⊥ (bottomType b + Finsupp.single l 1)
            ≤ Pc * δ l * (Height.totalWeight K * H.botBound (bottomType b l)) := this
          _ = _ := by ring
      · push Not at hex
        rw [H.height_bot_of_ne _ (by rw [hdeg_f]; omega) hex]
        simp [hex]
    refine (Finset.sum_le_sum fun f _ ↦ hterm f).trans (le_of_eq ?_)
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun l _ ↦ ?_
    rw [Finset.sum_ite, Finset.sum_const_zero, add_zero, Finset.sum_const, nsmul_eq_mul]
    ring
  -- The term `∑_g ∏ δ_{g j} d(ℙ, γ + ∑ ε_{g j})`.
  have h2 : (δ k : ℝ) * bezoutSum δ (t - 1)
      (fun γ' ↦ (multidegree b (⊥ : Ideal (MvPolynomial σ K)) γ' : ℝ)) γ =
      Pc * #(univ.filter fun g : Fin (t - 1) → Fin m ↦
        γ + ∑ j, Finsupp.single (g j) 1 = bottomType b) := by
    rw [bezoutSum, Finset.mul_sum, Finset.card_eq_sum_ones, Nat.cast_sum, Finset.mul_sum,
      Finset.sum_filter]
    refine Finset.sum_congr rfl fun g _ ↦ ?_
    rw [multidegree_bot hb (by rw [hdeg_f]; omega)]
    split_ifs with hg
    · have := hprod g 0 (by rw [hg, add_zero])
      simp only [Finsupp.coe_zero, Pi.zero_apply, pow_zero, prod_const_one, mul_one] at this
      rw [← mul_assoc, this]
      simp
    · simp
  -- Combine and divide by `Pc`.
  have hS : ∑ j, max (bombieriLogHeight b (P j)) 0 ≤
      ∑ j ∈ range t, max (B ((∑ i, δ i) ^ j)) 0 := by
    rw [← Fin.sum_univ_eq_sum_range]
    refine Finset.sum_le_sum fun j _ ↦ ?_
    obtain ⟨a, ha, hPj⟩ := hPa j
    rw [hPj]
    by_cases h0 : ∑ r ∈ R, a r • r = 0
    · rw [h0, bombieriLogHeight_zero, max_self]
      exact le_max_right _ _
    exact max_le_max ((hRB a h0).trans (hBmono ha)) le_rfl
  have hmain := hh γ hγdeg
  rw [hPc'] at hmain
  have hk0 : (0 : ℝ) < δ k := Nat.cast_pos.mpr (hδ k)
  have hS0 : 0 ≤ ∑ j, max (bombieriLogHeight b (P j)) 0 :=
    Finset.sum_nonneg fun _ _ ↦ le_max_right _ _
  have hmul := mul_le_mul_of_nonneg_left hmain hk0.le
  set X := ∑ l, Height.totalWeight K * H.botBound (bottomType b l) * δ l *
    #(univ.filter fun f : Fin t → Fin m ↦
      γ + ∑ j, Finsupp.single (f j) 1 = bottomType b + Finsupp.single l 1)
  set G := #(univ.filter fun g : Fin (t - 1) → Fin m ↦
    γ + ∑ j, Finsupp.single (g j) 1 = bottomType b)
  set S := ∑ j, max (bombieriLogHeight b (P j)) 0
  have hR : (δ k : ℝ) * (bezoutSum δ t (H.height ⊥) γ + S * bezoutSum δ (t - 1)
      (fun γ' ↦ (multidegree b (⊥ : Ideal (MvPolynomial σ K)) γ' : ℝ)) γ) ≤
        Pc * X + S * (Pc * G) := by
    rw [← h2, mul_add, mul_left_comm _ S]
    exact add_le_add h1 le_rfl
  replace hmul := hmul.trans hR
  refine le_of_mul_le_mul_left ?_ hPc
  calc Pc * (ε ^ t * δ k * H.height 𝔭 γ) = δ k * (Pc * ε ^ t * H.height 𝔭 γ) := by ring
    _ ≤ Pc * X + S * (Pc * G) := hmul
    _ ≤ Pc * X + (∑ j ∈ range t, max (B ((∑ i, δ i) ^ j)) 0) * (Pc * G) :=
      add_le_add le_rfl (mul_le_mul_of_nonneg_right hS (by positivity))
    _ = _ := by ring

/-- **Rémond's product theorem with heights**, with the height of the family of coefficients
(Rémond 2001, Thm 1.1). As `MvPolynomial.productTheorem_height`, with the bound
`h_m(∑_r a_r r) ≤ h(R) + [K : ℚ] (log ∑_r a_r + log c^{1/2})` of
`MvPolynomial.bombieriLogHeight_sum_nsmul_le` for `B`, where `h(R)` is the height of the tuple of
coefficients of `R` indexed by `R × M`, `M` contains the supports of the `r ∈ R`, and
`c = ∑_{μ ∈ M} 1/C(δ, μ)`. -/
theorem productTheorem_height_coeff [CharZero K] [Height.AdmissibleAbsValues K] {m : ℕ}
    {b : σ → Fin m} (hb : Function.Surjective b) (H : MultiprojectiveHeight b)
    (hU : IsUnmixedRing (Localization.AtPrime 𝔭)) {δ : Fin m → ℕ}
    {R : Finset (MvPolynomial σ K)} (hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r δ)
    (h𝔭R : 𝔭 ∈ (Ideal.span (R : Set (MvPolynomial σ K))).minimalPrimes)
    (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b)) (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ}
    (ht : 𝔭.height = t) (hδ : ∀ i, 0 < δ i) {ε : ℝ} (hε : 0 < ε)
    {R' : Set (MvPolynomial σ K)} (hRR' : Ideal.span (R : Set (MvPolynomial σ K)) ≤ Ideal.span R')
    (hI : ∀ P ∈ R', ∀ κ : σ →₀ ℕ, Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ ε →
      hasseDeriv κ P ∈ 𝔭)
    (hanti : Antitone δ)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → (m : ℝ) ^ t < ε ^ t * (δ i / δ j))
    {M : Finset (σ →₀ ℕ)} (hM : ∀ r ∈ R, r.support ⊆ M) :
    𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes ∧
      ∃ β : Fin m →₀ ℕ, (∀ i, (β i : ℕ∞) + 1 = (varMatroid 𝔭).eRk {s | b s = i}) ∧
        1 ≤ multidegree b 𝔭 β ∧
        ε ^ t * multidegree b 𝔭 β ≤
          #(univ.filter fun f : Fin t → Fin m ↦
            β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ∧
        #(univ.filter fun f : Fin t → Fin m ↦
          β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ≤ m ^ t ∧
        ∀ k, β k < bottomType b k →
          ε ^ t * δ k * H.height 𝔭 (β + Finsupp.single k 1) ≤
            ∑ l, Height.totalWeight K * H.botBound (bottomType b l) * δ l *
                #(univ.filter fun f : Fin t → Fin m ↦ β + Finsupp.single k 1 +
                  ∑ j, Finsupp.single (f j) 1 = bottomType b + Finsupp.single l 1) +
              (∑ j ∈ range t, max (Height.logHeight (coeffTuple R M) +
                Height.totalWeight K * (j * Real.log (∑ i, δ i : ℕ) +
                  Real.log √(∑ μ ∈ M, 1 / (blockMultinomial b μ : ℝ)))) 0) *
                #(univ.filter fun g : Fin (t - 1) → Fin m ↦ β + Finsupp.single k 1 +
                  ∑ j, Finsupp.single (g j) 1 = bottomType b) := by
  have hmono : Monotone fun n : ℕ ↦ Height.logHeight (coeffTuple R M) +
      Height.totalWeight K *
        (Real.log n + Real.log √(∑ μ ∈ M, 1 / (blockMultinomial b μ : ℝ))) := by
    intro n n' hn
    have hlog : Real.log n ≤ Real.log n' := by
      rcases n.eq_zero_or_pos with rfl | hn0
      · simpa using Real.log_natCast_nonneg n'
      · exact Real.log_le_log (Nat.cast_pos.mpr hn0) (Nat.cast_le.mpr hn)
    dsimp only
    gcongr
  simpa only [Nat.cast_pow, Real.log_pow] using productTheorem_height hb H hU hR h𝔭R h𝔭 hne ht hδ
    hε hRR' hI hanti hratio hmono fun a ha ↦ by
      rw [Nat.cast_sum]
      exact bombieriLogHeight_sum_nsmul_le b hM a ha

end Height

end MvPolynomial
