/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import QuantitativeSubspace.TwistedSuccessiveMinima

-- Used only inside proofs.
import Mathlib.LinearAlgebra.LinearIndependent.BaseChange

/-!
# The absolute Minkowski theorem through a finite place

D. Roy and J. L. Thunder, *An absolute Siegel's lemma*, J. reine angew. Math. **476** (1996),
1–26, Theorem 6.3, upper bound, by RT's own route: the auxiliary place `u₀` is **finite**.
`TwistedSuccessiveMinima.lean` proves the same bound through a complex place; this file keeps RT's
route, the one that also works over function fields, which have no infinite place.

1. As in the complex route: a gap `ε₀` below the jumps of the minima, a basis `x₁, …, xₙ` with
   `H_A(x_i) < μ_i + ε₀`, and every point outside `span(x₁, …, x_{i-1})` has height `≥ μ_i`.
2. A finite place `u₀` of `K` and `b₀ ∈ K` with `|b₀|_{u₀} > 1` (`FinitePlace.exists_one_lt`, from
   the product formula at `2`), an `N`-th root `b` of `b₀`, the field `E` generated by `b` and the
   `x_i`, and a place `w'` of `E` above `u₀`. The absolute size `β = |b|_{w'}^{1/[E:ℚ]}` lies in
   `(1, 1 + ε]` once `N` is large: `log β ≤ log |b₀|_{u₀} / (N [K:ℚ])` because the local degree
   of `w'` is at most `[E:K]`. No ramification theory is needed.
3. **The Iwasawa decomposition at `w'`** (`Matrix.exists_integral_mul_isUpperTriangular`): mutually
   inverse `w'`-integral `V`, `W` with `V A_{w'} X` upper triangular, by Gaussian elimination with
   the largest pivot (`X` the matrix of the `x_i`). Mutually inverse integral matrices preserve the
   max norm at every place above `w'` (`Matrix.iSup_mulVec_eq_of_mul_eq_one`).
4. The twist `B` is `A` except at `w'`, where it is `diag(a) V A_{w'}` with `a_i = b^{m_i}`,
   `m_i = ⌈-log μ_i / log β⌉`, so `α_i = β^{m_i} ∈ [μ_i⁻¹, (1 + ε) μ_i⁻¹]` (`Twist.modifyFin`).
   Then `H_B ≥ α_i H_A ≥ 1` outside the `(i-1)`-st flag space, so `μ₁(B) ≥ 1`, and
   `|det B|_𝔸 = ∏ α_i |det A|_𝔸` (`absDet_modifyFin`).
5. RT96 Prop. 6.2 for `B` gives `∏ μ_i ≤ (1 + ε)ⁿ √2^{n(n-1)} |det A|_𝔸`, and `ε → 0`.

## Main definitions

* `NumberField.Twist.modifyFin A w₀ N hN`: the twist `A` with its component at the finite place
  `w₀` replaced by `N`.

## Main results

* `Matrix.exists_integral_mul_isUpperTriangular`: the Iwasawa decomposition at a nonarchimedean
  absolute value.
* `NumberField.Twist.mulHeight_modifyFin_ge`, `NumberField.Twist.le_absMulHeight_modifyFin`,
  `NumberField.Twist.absDet_modifyFin`.
* `NumberField.Twist.prod_absMinimum_le_one_add_pow_mul`: the bound for a given `ε`.
* `NumberField.Twist.prod_absMinimum_le_of_finitePlace`: RT96 Thm 6.3, upper bound,
  `∏ μ_i ≤ √2^{n(n-1)} |det A|_𝔸`.

This is milestone Q2.2e of `QuantitativeSubspace/README.md` (the finite auxiliary place).
-/

@[expose] public section

open Finset Module Matrix IntermediateField

namespace Matrix

variable {L : Type*} [Field L] {v : AbsoluteValue L ℝ}

/-- A product of integral matrices is integral, for a nonarchimedean absolute value. -/
theorem apply_mul_le_one (hv : IsNonarchimedean v) {ι κ μ : Type*} [Fintype κ]
    {M : Matrix ι κ L} {N : Matrix κ μ L} (hM : ∀ i j, v (M i j) ≤ 1)
    (hN : ∀ i j, v (N i j) ≤ 1) (i : ι) (j : μ) : v ((M * N) i j) ≤ 1 := by
  have h := apply_mulVec_le hv M (fun k ↦ N k j) zero_le_one zero_le_one hM (fun k ↦ hN k j) i
  rwa [one_mul] at h

/-- **The Iwasawa decomposition at a nonarchimedean place**, in the form RT96 Lemma 3.3 uses:
for every square matrix `G` there are mutually inverse integral matrices `V`, `W` with `V G`
upper triangular. The proof is Gaussian elimination with the pivot of largest absolute value in
each column, so that every multiplier is integral. -/
theorem exists_integral_mul_isUpperTriangular (hv : IsNonarchimedean v) {n : ℕ}
    (G : Matrix (Fin n) (Fin n) L) :
    ∃ V W : Matrix (Fin n) (Fin n) L, V * W = 1 ∧ (∀ i j, v (V i j) ≤ 1) ∧
      (∀ i j, v (W i j) ≤ 1) ∧ (V * G).IsUpperTriangular := by
  classical
  have hint1 : ∀ i j : Fin n, v ((1 : Matrix (Fin n) (Fin n) L) i j) ≤ 1 := fun i j ↦ by
    rw [one_apply]
    split_ifs <;> simp
  have hadd : ∀ a b : L, v a ≤ 1 → v b ≤ 1 → v (a + b) ≤ 1 := fun a b ha hb ↦
    (hv a b).trans (max_le ha hb)
  suffices h : ∀ k ≤ n, ∃ V W : Matrix (Fin n) (Fin n) L, V * W = 1 ∧ (∀ i j, v (V i j) ≤ 1) ∧
      (∀ i j, v (W i j) ≤ 1) ∧ ∀ i j : Fin n, (j : ℕ) < k → j < i → (V * G) i j = 0 by
    obtain ⟨V, W, hVW, hV, hW, hG⟩ := h n le_rfl
    exact ⟨V, W, hVW, hV, hW, fun i j hji ↦ hG i j j.2 hji⟩
  intro k
  induction k with
  | zero => exact fun _ ↦ ⟨1, 1, Matrix.one_mul 1, hint1, hint1, fun _ _ h ↦ absurd h (by omega)⟩
  | succ k ih =>
    intro hk
    obtain ⟨V, W, hVW, hV, hW, hG⟩ := ih (by omega)
    set kk : Fin n := ⟨k, by omega⟩
    set G' := V * G
    by_cases hz : ∀ i, kk < i → G' i kk = 0
    · refine ⟨V, W, hVW, hV, hW, fun i j hj hji ↦ ?_⟩
      rcases Nat.lt_succ_iff_lt_or_eq.mp hj with hj | hj
      · exact hG i j hj hji
      · obtain rfl : j = kk := Fin.ext hj
        exact hz i hji
    push Not at hz
    obtain ⟨i₀, hi₀, hG'i₀⟩ := hz
    -- The pivot: an entry of largest absolute value in column `k`, at or below the diagonal.
    obtain ⟨r, hr, hrmax⟩ := (univ.filter fun i ↦ kk ≤ i).exists_max_image (fun i ↦ v (G' i kk))
      ⟨kk, by simp⟩
    simp only [mem_filter, mem_univ, true_and] at hr hrmax
    set p := G' r kk
    have hp : p ≠ 0 := by
      intro h0
      have := hrmax i₀ hi₀.le
      rw [show v p = 0 by simp [h0]] at this
      exact hG'i₀ (v.eq_zero.mp (le_antisymm this (v.nonneg _)))
    -- Swap rows `k` and `r`.
    set σ := Equiv.swap kk r
    set S : Matrix (Fin n) (Fin n) L := Matrix.of fun i j ↦ if σ i = j then 1 else 0
    have hS : ∀ (M : Matrix (Fin n) (Fin n) L) i j, (S * M) i j = M (σ i) j := fun M i j ↦ by
      simp [S, mul_apply]
    have hSS : S * S = 1 := by
      ext i j
      rw [hS]
      simp [S, one_apply, σ, Equiv.swap_apply_self]
    have hSint : ∀ i j, v (S i j) ≤ 1 := fun i j ↦ by
      simp only [S, of_apply]
      split_ifs <;> simp
    set G'' := S * G'
    have hG'' : ∀ i j, G'' i j = G' (σ i) j := hS G'
    have hσ : ∀ i, kk ≤ i → kk ≤ σ i := fun i hi ↦ by
      simp only [σ, Equiv.swap_apply_def]
      split_ifs
      exacts [hr, le_rfl, hi]
    -- Eliminate below the pivot.
    set c : Fin n → L := fun i ↦ if kk < i then G'' i kk / p else 0
    set Ne : Matrix (Fin n) (Fin n) L := Matrix.of fun i j ↦ if j = kk then c i else 0
    have hNe : ∀ (M : Matrix (Fin n) (Fin n) L) i j, (Ne * M) i j = c i * M kk j := fun M i j ↦ by
      simp [Ne, mul_apply]
    have hNeNe : Ne * Ne = 0 := by
      ext i j
      rw [hNe]
      simp [Ne, c]
    have hcint : ∀ i, v (c i) ≤ 1 := fun i ↦ by
      simp only [c]
      split_ifs with h
      · rw [map_div₀, div_le_one (v.pos hp), hG'']
        exact hrmax _ (hσ i h.le)
      · simp
    have hNeint : ∀ i j, v (Ne i j) ≤ 1 := fun i j ↦ by
      simp only [Ne, of_apply]
      split_ifs
      exacts [hcint i, by simp]
    have hneg : ∀ (M : Matrix (Fin n) (Fin n) L), (∀ i j, v (M i j) ≤ 1) →
        ∀ i j, v ((-M) i j) ≤ 1 := fun M hM i j ↦ by
      rw [neg_apply, map_neg_eq_map]
      exact hM i j
    refine ⟨(1 - Ne) * S * V, W * S * (1 + Ne), ?_, ?_, ?_, ?_⟩
    · calc (1 - Ne) * S * V * (W * S * (1 + Ne)) = (1 - Ne) * S * (V * W) * S * (1 + Ne) := by
            simp only [Matrix.mul_assoc]
        _ = 1 := by
            rw [hVW, Matrix.mul_one, Matrix.mul_assoc (1 - Ne), hSS, Matrix.mul_one, sub_mul,
              Matrix.one_mul, mul_add, Matrix.mul_one, hNeNe]
            abel
    · refine apply_mul_le_one hv (apply_mul_le_one hv ?_ hSint) hV
      intro i j
      rw [sub_eq_add_neg, add_apply]
      exact hadd _ _ (hint1 i j) (hneg Ne hNeint i j)
    · refine apply_mul_le_one hv (apply_mul_le_one hv hW hSint) ?_
      intro i j
      rw [add_apply]
      exact hadd _ _ (hint1 i j) (hNeint i j)
    · intro i j hj hji
      have hE : ((1 - Ne) * S * V * G) i j = G'' i j - c i * G'' kk j := by
        rw [Matrix.mul_assoc, Matrix.mul_assoc, sub_mul, Matrix.one_mul, sub_apply, hNe]
      rw [hE]
      rcases Nat.lt_succ_iff_lt_or_eq.mp hj with hj | hj
      · -- An earlier column: both entries vanish already.
        have hj' : j < kk := hj
        have h1 : G'' i j = 0 := by
          rw [hG'']
          refine hG _ _ hj ?_
          simp only [σ, Equiv.swap_apply_def]
          split_ifs
          exacts [lt_of_lt_of_le hj' hr, hj', hji]
        have h2 : G'' kk j = 0 := by
          rw [hG'', show σ kk = r from Equiv.swap_apply_left _ _]
          exact hG _ _ hj (lt_of_lt_of_le hj' hr)
        rw [h1, h2, mul_zero, sub_zero]
      · -- Column `k`: the elimination.
        obtain rfl : j = kk := Fin.ext hj
        have hpiv : G'' kk kk = p := by
          rw [hG'', show σ kk = r from Equiv.swap_apply_left _ _]
        simp only [c, hji, ite_true, hpiv, div_mul_cancel₀ _ hp, sub_self]

/-- **Mutually inverse integral matrices preserve the max norm**, over any field `F` with a
nonarchimedean absolute value. -/
theorem iSup_mulVec_eq_of_mul_eq_one {F : Type*} [Field F] {w : AbsoluteValue F ℝ}
    (hw : IsNonarchimedean w) {κ : Type*} [Fintype κ] [DecidableEq κ] {V W : Matrix κ κ F}
    (hWV : W * V = 1) (hV : ∀ i j, w (V i j) ≤ 1) (hW : ∀ i j, w (W i j) ≤ 1) (y : κ → F) :
    ⨆ i, w ((V *ᵥ y) i) = ⨆ i, w (y i) := by
  rcases isEmpty_or_nonempty κ with hκ | hκ
  · simp
  have hle : ∀ (M : Matrix κ κ F) (u : κ → F), (∀ i j, w (M i j) ≤ 1) →
      ⨆ i, w ((M *ᵥ u) i) ≤ ⨆ i, w (u i) := fun M u hM ↦
    ciSup_le fun i ↦ by
      simpa using apply_mulVec_le hw M u zero_le_one (Real.iSup_nonneg fun _ ↦ w.nonneg _) hM
        (fun j ↦ Finite.le_ciSup_of_le j le_rfl) i
  refine le_antisymm (hle V y hV) ?_
  calc ⨆ i, w (y i) = ⨆ i, w ((W *ᵥ (V *ᵥ y)) i) := by rw [mulVec_mulVec, hWV, one_mulVec]
    _ ≤ _ := hle W _ hW

/-- **Mutually inverse integral matrices have unit determinants.** -/
theorem apply_det_eq_one_of_mul_eq_one (hv : IsNonarchimedean v) {κ : Type*} [Fintype κ]
    [DecidableEq κ] {V W : Matrix κ κ L} (hVW : V * W = 1) (hV : ∀ i j, v (V i j) ≤ 1)
    (hW : ∀ i j, v (W i j) ≤ 1) : v V.det = 1 := by
  have h := congrArg (fun M ↦ v M.det) hVW
  simp only [det_mul, map_mul, det_one, map_one] at h
  have h1 := apply_det_le_one hv V hV
  have h2 := apply_det_le_one hv W hW
  nlinarith [v.nonneg V.det, v.nonneg W.det]

/-- `|a_i| ⨆ |u_j| ≤ ⨆ |a_j u_j|` when `u` vanishes beyond `i` and `|a_j| ≥ |a_i|` up to `i`. -/
theorem mul_iSup_le_iSup_diagonal_mulVec {F : Type*} [Field F] {w : AbsoluteValue F ℝ} {n : ℕ}
    {a : Fin n → F} {i : Fin n} (ha : ∀ j ≤ i, w (a i) ≤ w (a j)) {u : Fin n → F}
    (hu : ∀ j, i < j → u j = 0) :
    w (a i) * ⨆ j, w (u j) ≤ ⨆ j, w ((diagonal a *ᵥ u) j) := by
  rw [Real.mul_iSup_of_nonneg (w.nonneg _)]
  refine ciSup_mono (Finite.bddAbove_range _) fun j ↦ ?_
  rw [mulVec_diagonal, map_mul]
  rcases le_or_gt j i with hj | hj
  · exact mul_le_mul_of_nonneg_right (ha j hj) (w.nonneg _)
  · simp [hu j hj]

end Matrix

namespace NumberField.Twist

section ModifyFin

variable {E : Type*} [Field E] [NumberField E] {ι : Type*} [Fintype ι] [DecidableEq ι]
  (A : Twist E ι) (w₀ : FinitePlace E) (N : Matrix ι ι E) (hN : N.det ≠ 0)

open scoped Classical in
/-- **Modifying a twist at a finite place**: the component at `w₀` becomes `N`; everything else
is `A`. -/
noncomputable def modifyFin : Twist E ι where
  arch := A.arch
  arch_det_ne_zero := A.arch_det_ne_zero
  arch_conjugate := A.arch_conjugate
  fin w := if w = w₀ then N else A.fin w
  fin_det_ne_zero w := by
    split_ifs
    exacts [hN, A.fin_det_ne_zero w]
  finite_setOf_fin_ne_one := (A.finite_setOf_fin_ne_one.insert w₀).subset fun w hw ↦ by
    by_cases h : w = w₀
    · exact Or.inl h
    · exact Or.inr (by simpa [h] using hw)

@[simp] theorem modifyFin_arch : (A.modifyFin w₀ N hN).arch = A.arch := rfl

open scoped Classical in
theorem modifyFin_fin (w : FinitePlace E) :
    (A.modifyFin w₀ N hN).fin w = if w = w₀ then N else A.fin w :=
  rfl

/-- **The height for a twist modified at a finite place**, relative to a field `F ⊇ E`: if
`‖N y‖_w ≥ c^{n_w} ‖A_{w₀} y‖_w` at every place `w` of `F` above `w₀` (`n_w` the local degree), then
`H_B(y) ≥ c^{[F:E]} H_A(y)`. -/
theorem mulHeight_modifyFin_ge {F : Type*} [Field F] [NumberField F] [Algebra E F] {y : ι → F}
    (hy : y ≠ 0) {c : ℝ} (hc : 0 ≤ c)
    (h : ∀ w : FinitePlace F, w.under E = w₀ →
      c ^ w.localDegree E * A.finFactor w y ≤ (A.modifyFin w₀ N hN).finFactor w y) :
    c ^ finrank E F * A.mulHeight y ≤ (A.modifyFin w₀ N hN).mulHeight y := by
  classical
  set g : FinitePlace E → ℝ := fun v ↦ if v = w₀ then c else 1
  have hg : g.HasFiniteMulSupport := (Set.finite_singleton w₀).subset fun v hv ↦ by
    by_contra h'
    exact hv (by simp [g, show v ≠ w₀ from h'])
  have hloc : ∀ w : FinitePlace F, g (w.under E) ^ w.localDegree E * A.finFactor w y ≤
      (A.modifyFin w₀ N hN).finFactor w y := by
    intro w
    by_cases hw : w.under E = w₀
    · simpa [g, hw] using h w hw
    · simp only [g, hw, ite_false, one_pow, one_mul, finFactor, modifyFin_fin]
      exact le_rfl
  have hg0 : ∀ v, 0 ≤ g v := fun v ↦ by
    simp only [g]
    split_ifs
    exacts [hc, zero_le_one]
  have hprod : ∏ᶠ v, g v = c := by
    rw [finprod_eq_single g w₀ fun v hv ↦ by simp [g, hv]]
    simp [g]
  have hsupp := FinitePlace.hasFiniteMulSupport_comp_under (F := F) hg (fun w ↦ w.localDegree E)
  rw [mulHeight, mulHeight, ← mul_assoc, mul_comm (c ^ _), mul_assoc]
  refine mul_le_mul_of_nonneg_left ?_ (prod_nonneg fun _ _ ↦ A.archFactor_nonneg _ _)
  calc c ^ finrank E F * ∏ᶠ w : FinitePlace F, A.finFactor w y
      = ∏ᶠ w : FinitePlace F, (g (w.under E) ^ w.localDegree E * A.finFactor w y) := by
        rw [finprod_mul_distrib hsupp (A.hasFiniteMulSupport_finFactor hy),
          FinitePlace.finprod_under_pow_localDegree g hg, hprod]
    _ ≤ _ := finprod_le_finprod_of_nonneg
        (Set.Finite.subset (hsupp.union (A.hasFiniteMulSupport_finFactor hy))
          (Function.mulSupport_mul _ _))
        ((A.modifyFin w₀ N hN).hasFiniteMulSupport_finFactor hy)
        (fun w ↦ mul_nonneg (pow_nonneg (hg0 _) _) (A.finFactor_nonneg _ _)) hloc

variable {Ω : Type*} [Field Ω] [Algebra E Ω] [Algebra.IsAlgebraic E Ω]

/-- **The height for a twist modified at a finite place**, absolute form: under the local
hypothesis of `mulHeight_modifyFin_ge` in every field of definition of `x`,
`H_B(x) ≥ c^{1/[E:ℚ]} H_A(x)`. -/
theorem le_absMulHeight_modifyFin {x : ι → Ω} (hx : x ≠ 0) {c : ℝ} (hc : 0 ≤ c)
    (h : ∀ (F : IntermediateField E Ω) [NumberField F] (y : ι → F), (∀ i, (y i : Ω) = x i) →
      ∀ w : FinitePlace F, w.under E = w₀ →
        c ^ w.localDegree E * A.finFactor w y ≤ (A.modifyFin w₀ N hN).finFactor w y) :
    c ^ ((finrank ℚ E : ℝ))⁻¹ * A.absMulHeight x ≤ (A.modifyFin w₀ N hN).absMulHeight x := by
  have := numberField_adjoin_range (K := E) x
  set F := adjoin E (Set.range x)
  set y : ι → F := fun i ↦ ⟨x i, subset_adjoin E _ ⟨i, rfl⟩⟩
  have hy : y ≠ 0 := fun h0 ↦ hx (funext fun i ↦ congrArg Subtype.val (congrFun h0 i))
  have hrel := A.mulHeight_modifyFin_ge w₀ N hN hy hc (h F y fun _ ↦ rfl)
  have hd := Module.finrank_mul_finrank ℚ E F
  have hE : (finrank ℚ E : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr finrank_pos.ne'
  have hFE : (finrank E F : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr finrank_pos.ne'
  rw [absMulHeight, absMulHeight]
  calc c ^ ((finrank ℚ E : ℝ))⁻¹ * A.mulHeight y ^ ((finrank ℚ F : ℝ))⁻¹
      = (c ^ finrank E F * A.mulHeight y) ^ ((finrank ℚ F : ℝ))⁻¹ := by
        rw [Real.mul_rpow (pow_nonneg hc _) (A.mulHeight_nonneg _), ← Real.rpow_natCast,
          ← Real.rpow_mul hc, ← hd]
        congr 2
        push_cast
        field_simp
    _ ≤ _ := Real.rpow_le_rpow (mul_nonneg (pow_nonneg hc _) (A.mulHeight_nonneg _)) hrel
        (by positivity)

end ModifyFin

section ModifyFinDet

variable {E : Type*} [Field E] [NumberField E] {ι : Type*} [Fintype ι] [LinearOrder ι]
  (A : Twist E ι) (w₀ : FinitePlace E) (N : Matrix ι ι E) (hN : N.det ≠ 0)

/-- **The determinant of a twist modified at a finite place**:
`|det B|_𝔸 = (|det N|_{w₀} / |det A_{w₀}|_{w₀})^{1/[E:ℚ]} |det A|_𝔸`. -/
theorem absDet_modifyFin : (A.modifyFin w₀ N hN).absDet =
    (w₀ N.det / w₀ (A.fin w₀).det) ^ ((finrank ℚ E : ℝ))⁻¹ * A.absDet := by
  classical
  set r := w₀ N.det / w₀ (A.fin w₀).det
  have hA0 : w₀ (A.fin w₀).det ≠ 0 := (map_ne_zero _).mpr (A.fin_det_ne_zero w₀)
  have hr : 0 ≤ r := by positivity
  set f : FinitePlace E → ℝ := fun v ↦ v (A.fin v).det
  have hf : f.HasFiniteMulSupport := A.finite_setOf_fin_ne_one.subset fun v hv ↦ by
    by_contra h'
    exact hv (by simp [f, show A.fin v = 1 by simpa using h'])
  set g : FinitePlace E → ℝ := fun v ↦ if v = w₀ then r else 1
  have hg : g.HasFiniteMulSupport := (Set.finite_singleton w₀).subset fun v hv ↦ by
    by_contra h'
    exact hv (by simp [g, show v ≠ w₀ from h'])
  have hloc : ∀ v, v ((A.modifyFin w₀ N hN).fin v).det = g v * f v := fun v ↦ by
    rw [modifyFin_fin]
    by_cases hv : v = w₀
    · subst hv
      simp [g, f, r, div_mul_cancel₀ _ hA0]
    · simp [g, f, hv]
  have hprod : ∏ᶠ v, g v = r := by
    rw [finprod_eq_single g w₀ fun v hv ↦ by simp [g, hv]]
    simp [g]
  rw [absDet, absDet, modifyFin_arch]
  simp_rw [hloc]
  rw [finprod_mul_distrib hg hf, hprod, mul_left_comm, Real.mul_rpow hr (mul_nonneg
    (prod_nonneg fun _ _ ↦ norm_nonneg _) (finprod_nonneg fun _ ↦ apply_nonneg _ _))]

end ModifyFinDet

end NumberField.Twist

namespace NumberField.FinitePlace

/-- Some finite place is larger than `1` somewhere: by the product formula `∏_v |2|_v = 2^{-d}`,
some finite place has `|2|_v < 1`, and `|1/2|_v > 1`. -/
theorem exists_one_lt (K : Type*) [Field K] [NumberField K] :
    ∃ (u : FinitePlace K) (b : K), 1 < u b := by
  by_contra! hall
  have h2 : ∀ u : FinitePlace K, u 2 = 1 := fun u ↦ by
    have h1 := hall u 2
    have h2 := hall u 2⁻¹
    rw [map_inv₀] at h2
    have hpos : 0 < u 2 :=
      lt_of_le_of_ne (apply_nonneg _ _) (Ne.symm ((map_ne_zero _).mpr two_ne_zero))
    exact le_antisymm h1 (by rwa [inv_le_one₀ hpos] at h2)
  have hprod := FinitePlace.prod_eq_inv_abs_norm (K := K) (two_ne_zero (α := K))
  rw [finprod_eq_one_of_forall_eq_one h2, show (2 : K) = algebraMap ℚ K 2 by simp,
    Algebra.norm_algebraMap] at hprod
  have hd : 0 < finrank ℚ K := finrank_pos
  have : (1 : ℝ) < |((2 : ℚ) ^ finrank ℚ K : ℚ)| := by
    push_cast
    rw [abs_of_pos (by positivity)]
    exact one_lt_pow₀ one_lt_two hd.ne'
  rw [Rat.cast_inv, eq_comm, inv_eq_one] at hprod
  linarith

end NumberField.FinitePlace

namespace NumberField.Twist

section UpperFinite

variable {K : Type*} [Field K] [NumberField K] {Ω : Type*} [Field Ω] [Algebra K Ω]
  [Algebra.IsAlgebraic K Ω] [IsAlgClosed Ω]

/-- **The absolute Minkowski theorem through a finite auxiliary place**, for a given `ε > 0`
(RT96, proof of Thm 6.3): `μ₁(A) ⋯ μₙ(A) ≤ (1 + ε)ⁿ √2^{n(n-1)} |det A|_𝔸`. -/
theorem prod_absMinimum_le_one_add_pow_mul {n : ℕ} (hn : 0 < n) (A : Twist K (Fin n)) {ε : ℝ}
    (hε : 0 < ε) :
    ∏ i : Fin n, A.absMinimum Ω (i + 1) ≤ (1 + ε) ^ n * (√2 ^ (n * (n - 1)) * A.absDet) := by
  classical
  have hcard := Fintype.card_fin n
  have : Nonempty (Fin n) := ⟨⟨0, hn⟩⟩
  set μ : Fin n → ℝ := fun i ↦ A.absMinimum Ω (i + 1)
  have hpos : ∀ i, 0 < μ i := fun i ↦ A.absMinimum_pos (by omega) (by simp)
  obtain ⟨ε₀, hε₀, hgap⟩ := A.exists_absMinimum_gap (Ω := Ω) hcard
  obtain ⟨x, hx, hxε⟩ := A.exists_linearIndependent_absMulHeight_lt_absMinimum_add (Ω := Ω) hcard
    hε₀
  -- The place `u₀` of `K`, an element `b₀` with `|b₀|_{u₀} > 1`, and an `N`-th root `b` of `b₀`
  -- with `N` so large that `|b|` is close to `1`.
  obtain ⟨u₀, b₀, hb₀⟩ := FinitePlace.exists_one_lt K
  set dK := finrank ℚ K
  have hdK : (0 : ℝ) < dK := Nat.cast_pos.mpr finrank_pos
  set ℓ := Real.log (u₀ b₀)
  have hℓ : 0 < ℓ := Real.log_pos hb₀
  have hlε : 0 < Real.log (1 + ε) := Real.log_pos (by linarith)
  obtain ⟨N, hN⟩ := exists_nat_gt (ℓ / (dK * Real.log (1 + ε)))
  have hN0 : 0 < N := by
    have : 0 < ℓ / (dK * Real.log (1 + ε)) := by positivity
    exact_mod_cast this.trans hN
  have hNpos : (0 : ℝ) < N := Nat.cast_pos.mpr hN0
  have hNℓ : ℓ / (N * dK) < Real.log (1 + ε) := by
    rw [div_lt_iff₀ (by positivity)]
    rw [div_lt_iff₀ (by positivity)] at hN
    linarith
  obtain ⟨b, hb⟩ := IsAlgClosed.exists_pow_nat_eq (algebraMap K Ω b₀) hN0
  -- The field `E` of the basis and of `b`, the matrix `X` of the basis over it.
  set g : Option (Fin n × Fin n) → Ω := fun o ↦ o.elim b fun p ↦ x p.2 p.1
  have := numberField_adjoin_range (K := K) g
  set E := adjoin K (Set.range g)
  have : Algebra.IsAlgebraic E Ω := Algebra.IsAlgebraic.tower_top (K := K) E
  set X : Matrix (Fin n) (Fin n) E :=
    Matrix.of fun i k ↦ ⟨x k i, subset_adjoin K _ ⟨some (i, k), rfl⟩⟩
  have hXx : (fun k ↦ algebraMap E Ω ∘ X.col k) = x := rfl
  have hXdet : X.det ≠ 0 := by
    have hXli : LinearIndependent E X.col :=
      linearIndependent_algebraMap_comp_iff.mp (hXx ▸ hx)
    exact ((Matrix.isUnit_iff_isUnit_det X).mp (linearIndependent_cols_iff_isUnit.mp hXli)).ne_zero
  set bE : E := ⟨b, subset_adjoin K _ ⟨none, rfl⟩⟩
  have hbE : bE ^ N = algebraMap K E b₀ := Subtype.ext (by simpa [bE] using hb)
  -- A place `w'` of `E` above `u₀`, and the absolute size `β` of `b` there.
  obtain ⟨w', hw'⟩ := FinitePlace.nonempty_placesOver E u₀
  have : w'.LiesOver u₀ := FinitePlace.mem_placesOver.mp hw'
  set deg := w'.localDegree K
  have hdeg : deg ≤ finrank K E := by
    rw [← FinitePlace.sum_localDegree (F := E) u₀]
    exact Finset.single_le_sum (f := fun w : FinitePlace E ↦ w.localDegree K)
      (fun _ _ ↦ Nat.zero_le _) (FinitePlace.mem_placesOverFinset.mpr this)
  have hdeg0 : 0 < deg := FinitePlace.localDegree_pos w'
  have hwb : w' bE ^ N = u₀ b₀ ^ deg := by
    rw [← map_pow, hbE, FinitePlace.apply_algebraMap w' u₀]
  set dE := finrank ℚ E
  have hdE : dE = finrank K E * dK := (Module.finrank_mul_finrank ℚ K E).symm.trans (mul_comm _ _)
  have hwb1 : 1 < w' bE := by
    by_contra! h
    have h1 : w' bE ^ N ≤ 1 := pow_le_one₀ (apply_nonneg _ _) h
    rw [hwb] at h1
    exact absurd h1 (not_le.mpr (one_lt_pow₀ hb₀ hdeg0.ne'))
  have hdE0 : (0 : ℝ) < dE := Nat.cast_pos.mpr finrank_pos
  set β := w' bE ^ ((dE : ℝ))⁻¹
  have hβ1 : 1 < β := Real.one_lt_rpow hwb1 (inv_pos.mpr hdE0)
  have hβε : β ≤ 1 + ε := by
    have hlog : Real.log β = deg * ℓ / (N * dE) := by
      rw [Real.log_rpow (by linarith), show Real.log (w' bE) = deg * ℓ / N by
        rw [eq_div_iff hNpos.ne', mul_comm, ← Real.log_pow, hwb, Real.log_pow]]
      field_simp
    have h : Real.log β ≤ ℓ / (N * dK) := by
      rw [hlog, div_le_div_iff₀ (mul_pos hNpos hdE0) (mul_pos hNpos hdK), hdE]
      push_cast
      have : (deg : ℝ) ≤ finrank K E := by exact_mod_cast hdeg
      have := mul_le_mul_of_nonneg_right this (by positivity : (0 : ℝ) ≤ ℓ * (N * dK))
      nlinarith
    rw [← Real.exp_log (by linarith : 0 < β), ← Real.exp_log (by linarith : 0 < 1 + ε)]
    exact Real.exp_le_exp.mpr (h.trans hNℓ.le)
  -- The weights `a_k = b^{m_k}`, with absolute size `α_k = β^{m_k} ∈ [μ_k⁻¹, (1 + ε) μ_k⁻¹]`.
  have hβ0 : 0 < β := by linarith
  have hlβ : 0 < Real.log β := Real.log_pos hβ1
  set m : Fin n → ℤ := fun k ↦ ⌈-Real.log (μ k) / Real.log β⌉
  set a : Fin n → E := fun k ↦ bE ^ m k
  have hbE0 : bE ≠ 0 := fun h ↦ by
    rw [h, map_zero] at hwb1
    linarith
  have ha0 : ∀ k, a k ≠ 0 := fun k ↦ zpow_ne_zero _ hbE0
  set α : Fin n → ℝ := fun k ↦ β ^ (m k : ℝ)
  have hα : ∀ k, w' (a k) ^ ((dE : ℝ))⁻¹ = α k := fun k ↦ by
    rw [map_zpow₀, ← Real.rpow_intCast, ← Real.rpow_mul (apply_nonneg _ _), mul_comm,
      Real.rpow_mul (apply_nonneg _ _)]
  have hαlow : ∀ k, (μ k)⁻¹ ≤ α k := fun k ↦ by
    have h := Int.le_ceil (-Real.log (μ k) / Real.log β)
    rw [div_le_iff₀ hlβ] at h
    simp only [α]
    rw [Real.rpow_def_of_pos hβ0, ← Real.exp_log (inv_pos.mpr (hpos k)), Real.log_inv]
    exact Real.exp_le_exp.mpr (by rw [mul_comm]; exact h)
  have hαup : ∀ k, α k ≤ (1 + ε) * (μ k)⁻¹ := fun k ↦ by
    have h := Int.ceil_lt_add_one (-Real.log (μ k) / Real.log β)
    rw [← sub_lt_iff_lt_add, lt_div_iff₀ hlβ] at h
    calc α k = Real.exp (Real.log β * m k) := Real.rpow_def_of_pos hβ0 _
      _ ≤ Real.exp (Real.log β + -Real.log (μ k)) := Real.exp_le_exp.mpr (by
          rw [sub_mul, one_mul] at h
          linarith)
      _ = β * (μ k)⁻¹ := by rw [Real.exp_add, Real.exp_log hβ0, ← Real.log_inv, Real.exp_log
          (inv_pos.mpr (hpos k))]
      _ ≤ (1 + ε) * (μ k)⁻¹ := mul_le_mul_of_nonneg_right hβε (inv_pos.mpr (hpos k)).le
  have hmono : ∀ k l, k ≤ l → w' (a l) ≤ w' (a k) := fun k l hkl ↦ by
    simp only [a, map_zpow₀]
    refine zpow_le_zpow_right₀ hwb1.le (Int.ceil_mono ?_)
    have hμ : μ k ≤ μ l := A.absMinimum_mono (by simpa using hkl) (by simp)
    exact div_le_div_of_nonneg_right (neg_le_neg (Real.log_le_log (hpos k) hμ)) hlβ.le
  -- The Iwasawa decomposition of `G = A_{w'} X` at `w'`, and the new component
  -- `N = diag(a) V A_{w'}`.
  set AE := A.baseChange E
  set Aw := AE.fin w'
  have hv : IsNonarchimedean w'.1 := fun a b ↦ FinitePlace.add_le w' a b
  obtain ⟨V, W, hVW, hV, hW, hT⟩ := (Aw * X).exists_integral_mul_isUpperTriangular hv
  have hVdet : w' V.det = 1 := apply_det_eq_one_of_mul_eq_one hv hVW hV hW
  set Nm := diagonal a * V * Aw
  have hNm : Nm.det ≠ 0 := by
    have hV0 : V.det ≠ 0 := fun h ↦ by simp [h] at hVdet
    simp only [Nm, det_mul, det_diagonal]
    exact mul_ne_zero (mul_ne_zero (prod_ne_zero_iff.mpr fun k _ ↦ ha0 k) hV0)
      (AE.fin_det_ne_zero w')
  set B := AE.modifyFin w' Nm hNm
  have hdetB : B.absDet = (∏ k, α k) * A.absDet := by
    have hAw0 : w' Aw.det ≠ 0 := (map_ne_zero _).mpr (AE.fin_det_ne_zero w')
    rw [absDet_modifyFin, absDet_baseChange]
    congr 1
    simp only [Nm, det_mul, det_diagonal, map_mul, map_prod, hVdet, mul_one]
    rw [show (AE.fin w').det = Aw.det from rfl, mul_div_cancel_right₀ _ hAw0,
      ← Real.finsetProd_rpow _ _ fun k _ ↦ apply_nonneg _ _]
    exact prod_congr rfl fun k _ ↦ hα k
  -- Every nonzero point has `H_B ≥ 1`.
  have hXΩ : (X.map (algebraMap E Ω)).det ≠ 0 := by
    rw [← RingHom.mapMatrix_apply, ← RingHom.map_det]
    exact (map_ne_zero _).mpr hXdet
  have hB : ∀ z : Fin n → Ω, z ≠ 0 → 1 ≤ B.absMulHeight z := by
    intro z hz
    set bs := basisOfLinearIndependentOfCardEqFinrank hx (by simp)
    have hbs : ⇑bs = x := coe_basisOfLinearIndependentOfCardEqFinrank _ _
    set y := bs.equivFun z
    have hzy : z = ∑ k, y k • x k := by
      rw [← hbs]
      exact (bs.sum_equivFun z).symm
    have hzX : X.map (algebraMap E Ω) *ᵥ y = z := by
      rw [hzy]
      funext j
      simp only [mulVec, dotProduct, Matrix.map_apply, Finset.sum_apply, Pi.smul_apply,
        smul_eq_mul]
      exact sum_congr rfl fun k _ ↦ mul_comm _ _
    have hy : y ≠ 0 := fun h ↦ hz (by rw [hzy, h]; simp)
    have hne : (univ.filter fun k ↦ y k ≠ 0).Nonempty := by
      obtain ⟨k, hk⟩ := Function.ne_iff.mp hy
      exact ⟨k, by simpa using hk⟩
    set i := (univ.filter fun k ↦ y k ≠ 0).max' hne
    have hi : y i ≠ 0 := (mem_filter.mp (max'_mem _ hne)).2
    have hgt : ∀ k, i < k → y k = 0 := fun k hk ↦ by
      by_contra h
      exact absurd (le_max' _ k (by simpa using h)) (not_le.mpr hk)
    have hzspan : z ∉ Submodule.span Ω (x '' {k | k < i}) := by
      rw [← hbs, Basis.mem_span_image]
      intro h
      have hmem : i ∈ (bs.repr z).support := by
        rw [Finsupp.mem_support_iff, ← Basis.equivFun_apply]
        exact hi
      exact lt_irrefl i (by simpa using h hmem)
    have hHA : μ i ≤ A.absMulHeight z :=
      A.absMinimum_le_absMulHeight_of_notMem_span hcard hgap hx hxε hzspan
    have hmod := AE.le_absMulHeight_modifyFin w' Nm hNm hz (apply_nonneg w' (a i)) ?_
    · rw [absMulHeight_baseChange, hα i] at hmod
      calc (1 : ℝ) = (μ i)⁻¹ * μ i := (inv_mul_cancel₀ (hpos i).ne').symm
        _ ≤ α i * A.absMulHeight z :=
          mul_le_mul (hαlow i) hHA (hpos i).le (Real.rpow_nonneg hβ0.le _)
        _ ≤ B.absMulHeight z := hmod
    -- The local estimate at a place `w` above `w'`, in a field of definition `F` of `z`.
    intro F _ yF hyF w hw
    have : w.LiesOver w' := FinitePlace.liesOver_iff_eq_under.mpr hw.symm
    set e := algebraMap E F
    have hwe : ∀ t : E, w (e t) = w' t ^ w.localDegree E := fun t ↦
      FinitePlace.apply_algebraMap w w' t
    have hwn : IsNonarchimedean w.1 := fun a b ↦ FinitePlace.add_le w a b
    set XF := X.map e
    have hXF : XF.det ≠ 0 := by
      rw [show XF = e.mapMatrix X from rfl, ← RingHom.map_det]
      exact (map_ne_zero _).mpr hXdet
    set cF := XF⁻¹ *ᵥ yF
    have hyc : XF *ᵥ cF = yF := by
      rw [mulVec_mulVec, mul_nonsing_inv _ (isUnit_iff_ne_zero.mpr hXF), one_mulVec]
    have hc0 : ∀ j, i < j → cF j = 0 := by
      have hmap : X.map (algebraMap E Ω) *ᵥ (algebraMap F Ω ∘ cF) = z := by
        have h : algebraMap F Ω ∘ (XF *ᵥ cF) = algebraMap F Ω ∘ yF := by rw [hyc]
        rw [show algebraMap F Ω ∘ yF = z from funext hyF] at h
        rw [← h]
        funext j
        rw [Function.comp_apply, RingHom.map_mulVec, Matrix.map_map]
        rfl
      have hinj : algebraMap F Ω ∘ cF = y := by
        rw [← hzX] at hmap
        have := congrArg ((X.map (algebraMap E Ω))⁻¹ *ᵥ ·) hmap
        simpa [mulVec_mulVec, nonsing_inv_mul _ (isUnit_iff_ne_zero.mpr hXΩ)] using this
      intro j hj
      have h := congrFun hinj j
      rw [Function.comp_apply, hgt j hj] at h
      exact (map_eq_zero_iff _ (algebraMap F Ω).injective).mp h
    -- `N y = diag(a) V (A_{w'} y)` and `V (A_{w'} y) = T c` vanishes beyond `i`.
    have hBfin : (AE.modifyFin w' Nm hNm).fin (w.under E) = Nm := by
      rw [modifyFin_fin]
      simp [hw]
    have hAfin : AE.fin (w.under E) = Aw := by rw [hw]
    rw [finFactor, finFactor, hBfin, hAfin]
    set u := V.map e *ᵥ (Aw.map e *ᵥ yF)
    have hNu : Nm.map e *ᵥ yF = diagonal (e ∘ a) *ᵥ u := by
      simp only [u, Nm, Matrix.map_mul, mulVec_mulVec, diagonal_map (map_zero e)]
      rw [Matrix.mul_assoc]
      rfl
    have hu : ∀ j, i < j → u j = 0 := by
      intro j hj
      have hT' : u = (V * (Aw * X)).map e *ᵥ cF := by
        simp only [u, Matrix.map_mul, mulVec_mulVec, ← hyc, XF, Matrix.mul_assoc]
      rw [hT']
      simp only [mulVec, dotProduct]
      refine sum_eq_zero fun l _ ↦ ?_
      rcases lt_or_ge l j with hlj | hjl
      · rw [Matrix.map_apply, hT hlj, map_zero, zero_mul]
      · rw [hc0 l (lt_of_lt_of_le hj hjl), mul_zero]
    have hVint : ∀ p q, w (V.map e p q) ≤ 1 := fun p q ↦ by
      rw [Matrix.map_apply, hwe]
      exact pow_le_one₀ (apply_nonneg _ _) (hV p q)
    have hWint : ∀ p q, w (W.map e p q) ≤ 1 := fun p q ↦ by
      rw [Matrix.map_apply, hwe]
      exact pow_le_one₀ (apply_nonneg _ _) (hW p q)
    have hWV : W.map e * V.map e = 1 := by
      rw [← Matrix.map_mul, mul_eq_one_comm.mp hVW, Matrix.map_one _ (map_zero e) (map_one e)]
    have hiso : ⨆ j, w ((V.map e *ᵥ (Aw.map e *ᵥ yF)) j) = ⨆ j, w ((Aw.map e *ᵥ yF) j) :=
      iSup_mulVec_eq_of_mul_eq_one hwn hWV hVint hWint (Aw.map e *ᵥ yF)
    rw [hNu, ← hwe, ← hiso]
    refine mul_iSup_le_iSup_diagonal_mulVec (w := w.1) (a := e ∘ a) (u := u) (fun j hj ↦ ?_) hu
    change w (e (a i)) ≤ w (e (a j))
    rw [hwe, hwe]
    exact pow_le_pow_left₀ (apply_nonneg _ _) (hmono j i hj) _
  have hμB : 1 ≤ B.absMinimum Ω 1 :=
    le_csInf (B.absMinimumSet_nonempty (by simp; omega)) fun ν ⟨z, hz, hzν⟩ ↦
      (hB _ (hz.ne_zero 0)).trans (hzν 0)
  -- RT96 Prop. 6.2 for `B`.
  have h62 := B.absMinimum_one_pow_le (Ω := Ω) hn
  rw [hdetB] at h62
  have key := (one_le_pow₀ hμB).trans h62
  have hP : 0 < ∏ k, μ k := prod_pos fun k _ ↦ hpos k
  have hα_le : ∏ k, α k ≤ (1 + ε) ^ n * (∏ k, μ k)⁻¹ := by
    calc ∏ k, α k ≤ ∏ k : Fin n, ((1 + ε) * (μ k)⁻¹) :=
          Finset.prod_le_prod₀ (fun k _ ↦ Real.rpow_nonneg hβ0.le _) fun k _ ↦ hαup k
      _ = (1 + ε) ^ n * (∏ k, μ k)⁻¹ := by
          rw [prod_mul_distrib, prod_const, card_univ, Fintype.card_fin, prod_inv_distrib]
  have key' : 1 ≤ √2 ^ (n * (n - 1)) * ((1 + ε) ^ n * (∏ k, μ k)⁻¹ * A.absDet) :=
    key.trans (mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_right hα_le A.absDet_pos.le)
      (by positivity))
  calc ∏ k, μ k = (∏ k, μ k) * 1 := (mul_one _).symm
    _ ≤ (∏ k, μ k) * (√2 ^ (n * (n - 1)) * ((1 + ε) ^ n * (∏ k, μ k)⁻¹ * A.absDet)) := by
        gcongr
    _ = (1 + ε) ^ n * (√2 ^ (n * (n - 1)) * A.absDet) := by field_simp

/-- **The absolute Minkowski theorem**, upper bound (RT96 Thm 6.3), through RT's finite auxiliary
place: `μ₁(A) ⋯ μₙ(A) ≤ √2^{n(n-1)} |det A|_𝔸`. The same statement as `prod_absMinimum_le`
(complex auxiliary place); here `ε → 0` in `prod_absMinimum_le_one_add_pow_mul`. -/
theorem prod_absMinimum_le_of_finitePlace {n : ℕ} (hn : 0 < n) (A : Twist K (Fin n)) :
    ∏ i : Fin n, A.absMinimum Ω (i + 1) ≤ √2 ^ (n * (n - 1)) * A.absDet := by
  have hc : Continuous fun ε : ℝ ↦ (1 + ε) ^ n * (√2 ^ (n * (n - 1)) * A.absDet) := by fun_prop
  have ht := (hc.tendsto 0).mono_left (nhdsWithin_le_nhds (s := Set.Ioi 0))
  simp only [add_zero, one_pow, one_mul] at ht
  exact ge_of_tendsto ht (eventually_nhdsWithin_of_forall fun ε hε ↦
    prod_absMinimum_le_one_add_pow_mul hn A hε)

end UpperFinite

end NumberField.Twist
