/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import QuantitativeSubspace.TwistedDuality
public import QuantitativeSubspace.TwistedPlane
public import QuantitativeSubspace.TwistedPullback

-- Used only inside proofs.
import Mathlib.LinearAlgebra.LinearIndependent.BaseChange

/-!
# The first absolute minimum of a twist

D. Roy and J. L. Thunder, *An absolute Siegel's lemma*, J. reine angew. Math. **476** (1996),
1–26, Prop. 6.2: for a twist `A` of `Kⁿ`, `n ≥ 2`, over a number field `K`, with the absolute
minima taken over an algebraically closed field,

```text
(i)  μ₁(A*)^{n-1} ≤ 2^{(n-1)(n-2)/2} |det A|_𝔸⁻¹ μ₁(A),
(ii) μ₁(A)^n ≤ 2^{n(n-1)/2} |det A|_𝔸.
```

The proof is by induction on `n`. For (i), take a point `x` of height close to `μ₁(A)` and a
basis `P` of `(Ω x)^⊥` over the field `F` generated by `x`; the pullback `B` of `A*` along `P`
(`TwistedPullback.lean`) is a twist of `F^{n-1}` with `μ₁(A*) ≤ μ₁(B)` and
`|det B|_𝔸 = H_{A*}((Ω x)^⊥) = |det A|_𝔸⁻¹ H_A(x)` (twisted duality, `TwistedDuality.lean`), and
(ii) in dimension `n - 1` applies to `B`. Then (ii) in dimension `n ≥ 3` follows from (i) for
`A` and for `A*`. In dimension `2`, (ii) is RT Prop. 5.3 (`TwistedPlane.lean`).

The induction changes the base field, from `K` to `F`, which lives in the universe of `Ω`; so the
induction runs over number fields in that universe (`absMinimum_one_pow_le_aux`), and the
statement for an arbitrary `K` uses it in dimension `n - 1` only.

## Main results

* `NumberField.Twist.absDet_mul_dual_absMinimum_one_pow_le`: RT96 Prop. 6.2 (i),
  `|det A|_𝔸 μ₁(A*)^{n-1} ≤ √2^{(n-1)(n-2)} μ₁(A)`.
* `NumberField.Twist.absMinimum_one_pow_le`: RT96 Prop. 6.2 (ii),
  `μ₁(A)^n ≤ √2^{n(n-1)} |det A|_𝔸`, for every `n ≥ 1`; `absMinimum_one_le_rpow` is RT's form
  `μ₁(A) ≤ √2^{n-1} |det A|_𝔸^{1/n}`.
* `NumberField.Twist.exists_col_span_eq_dual`: the orthogonal complement of a nonzero point has a
  basis over the field generated by the point.

This is milestone Q2.2d of `QuantitativeSubspace/README.md`.
-/

@[expose] public section

open Finset Module Matrix IntermediateField

universe u v

namespace NumberField.Twist

variable {K : Type u} [Field K] [NumberField K] {Ω : Type v} [Field Ω] [Algebra K Ω]
  [Algebra.IsAlgebraic K Ω]

/-- In dimension `1` the first minimum is at most `|det A|_𝔸`, the height of `1`. -/
theorem absMinimum_one_le_absDet (A : Twist K (Fin 1)) : A.absMinimum Ω 1 ≤ A.absDet := by
  set x : Fin 1 → Ω := fun _ ↦ 1
  have hx : x ≠ 0 := fun h ↦ one_ne_zero (congrFun h 0)
  have hspan : Submodule.span Ω {x} = ⊤ := by
    refine eq_top_iff.mpr fun w _ ↦ Submodule.mem_span_singleton.mpr ⟨w 0, ?_⟩
    ext i
    simp [x, Subsingleton.elim i 0]
  calc A.absMinimum Ω 1 ≤ A.absMulHeight x := A.absMinimum_one_le hx
    _ = A.absDet := by
      rw [← A.absSubspaceHeight_span_singleton hx, hspan, absSubspaceHeight_top]

omit [NumberField K] [Algebra.IsAlgebraic K Ω] in
/-- The orthogonal complement of a nonzero point: a basis over the field of definition, as the
columns of a matrix. -/
theorem exists_col_span_eq_dual {F : IntermediateField K Ω} {m : ℕ} {y : Fin (m + 1) → F}
    (hy : y ≠ 0) : ∃ P : Matrix (Fin (m + 1)) (Fin m) F, LinearIndependent F P.col ∧
      Submodule.span Ω (Set.range fun j ↦ algebraMap F Ω ∘ P.col j) =
        (Submodule.span Ω {algebraMap F Ω ∘ y}).dualAnnihilator.comap
          (Module.piEquiv (Fin (m + 1)) Ω Ω).toLinearMap := by
  set f := Module.piEquiv (Fin (m + 1)) F F y
  obtain ⟨i, hi⟩ : ∃ i, y i ≠ 0 := by
    by_contra! h
    exact hy (funext h)
  have hrange : LinearMap.range f = ⊤ := by
    refine eq_top_iff.mpr fun c _ ↦ ⟨Pi.single i (c / y i), ?_⟩
    simp [f, Module.piEquiv_apply_apply, Pi.single_apply, hi]
  have hker : finrank F (LinearMap.ker f) = m := by
    have h := LinearMap.finrank_range_add_finrank_ker f
    rw [hrange, finrank_top, Module.finrank_self, Module.finrank_fin_fun] at h
    omega
  set b := Module.finBasisOfFinrankEq F (LinearMap.ker f) hker
  set P : Matrix (Fin (m + 1)) (Fin m) F := Matrix.of fun i j ↦ (b j : Fin (m + 1) → F) i
  have hP : LinearIndependent F P.col :=
    b.linearIndependent.map' (LinearMap.ker f).subtype (Submodule.ker_subtype _)
  have hli : LinearIndependent Ω fun j ↦ algebraMap F Ω ∘ P.col j :=
    linearIndependent_algebraMap_comp_iff.mpr hP
  refine ⟨P, hP, Submodule.eq_of_le_of_finrank_eq ?_ ?_⟩
  · refine Submodule.span_le.mpr ?_
    rintro _ ⟨j, rfl⟩
    rw [SetLike.mem_coe, Submodule.mem_comap, Submodule.mem_dualAnnihilator]
    intro w hw
    obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.mp hw
    have hb : f (b j) = 0 := (b j).2
    simp only [f, Module.piEquiv_apply_apply, smul_eq_mul] at hb
    simp only [LinearEquiv.coe_coe, map_smul, Module.piEquiv_apply_apply, smul_eq_mul,
      Function.comp_apply, mul_eq_zero]
    right
    have h := congrArg (algebraMap F Ω) hb
    rw [map_sum, map_zero] at h
    simp only [map_mul, mul_comm] at h ⊢
    exact h
  · rw [finrank_span_eq_card hli, Fintype.card_fin, Submodule.comap_equiv_eq_map_symm,
      LinearEquiv.finrank_map_eq]
    have h := Subspace.finrank_add_finrank_dualAnnihilator_eq
      (Submodule.span Ω {algebraMap F Ω ∘ y})
    have hx : algebraMap F Ω ∘ y ≠ 0 := fun h0 ↦
      hi ((algebraMap F Ω).injective (by simpa using congrFun h0 i))
    rw [finrank_span_singleton hx, Module.finrank_fin_fun] at h
    exact (Nat.add_left_cancel (h.trans (add_comm m 1))).symm

/-- **RT96 Prop. 6.2 (i), from (ii) in dimension `m`.** If every twist of `L^m` over a number
field `L` in the universe of `Ω` satisfies `μ₁^m ≤ √2^{m(m-1)} |det|_𝔸`, then every twist `A` of
`K^{m+1}` satisfies `|det A|_𝔸 μ₁(A*)^m ≤ √2^{m(m-1)} μ₁(A)`. -/
theorem absDet_mul_dual_absMinimum_one_pow_le_of_forall {m : ℕ} (hm : 0 < m)
    (hB : ∀ (L : Type v) [Field L] [NumberField L] [Algebra L Ω] [Algebra.IsAlgebraic L Ω]
      (B : Twist L (Fin m)), B.absMinimum Ω 1 ^ m ≤ √2 ^ (m * (m - 1)) * B.absDet)
    (A : Twist K (Fin (m + 1))) :
    A.absDet * A.dual.absMinimum Ω 1 ^ m ≤ √2 ^ (m * (m - 1)) * A.absMinimum Ω 1 := by
  have hD := A.absDet_pos
  have hc : 0 ≤ √2 ^ (m * (m - 1)) := by positivity
  -- It suffices to bound by `H_A(x)` for every nonzero `x`.
  suffices h : ∀ x : Fin (m + 1) → Ω, x ≠ 0 →
      A.absDet * A.dual.absMinimum Ω 1 ^ m ≤ √2 ^ (m * (m - 1)) * A.absMulHeight x by
    by_contra! hlt
    have hc' : 0 < √2 ^ (m * (m - 1)) := by positivity
    obtain ⟨z, hz, hzμ⟩ := A.exists_linearIndependent_absMulHeight_lt (Ω := Ω) (i := 1)
      (by simp) (μ := A.absDet * A.dual.absMinimum Ω 1 ^ m / √2 ^ (m * (m - 1)))
      (by rwa [lt_div_iff₀' hc'])
    have h1 := h (z 0) (hz.ne_zero 0)
    have h2 := hzμ 0
    rw [lt_div_iff₀' hc'] at h2
    linarith
  intro x hx
  have := numberField_adjoin_range (K := K) x
  set F := adjoin K (Set.range x)
  have : Algebra.IsAlgebraic F Ω := Algebra.IsAlgebraic.tower_top (K := K) F
  set y : Fin (m + 1) → F := fun i ↦ ⟨x i, subset_adjoin K _ ⟨i, rfl⟩⟩
  have hxy : algebraMap F Ω ∘ y = x := rfl
  have hy : y ≠ 0 := fun h ↦ hx (by rw [← hxy, h]; ext; simp)
  obtain ⟨P, hP, hW⟩ := exists_col_span_eq_dual hy
  rw [hxy] at hW
  set B := (A.dual.baseChange F).pullback P hP
  have hdet : B.absDet = A.absDet⁻¹ * A.absMulHeight x := by
    rw [absDet_pullback (Ω := Ω), absSubspaceHeight_baseChange, hW, absSubspaceHeight_dual,
      A.absSubspaceHeight_span_singleton hx]
  have hli : LinearIndependent Ω fun j ↦ algebraMap F Ω ∘ P.col j :=
    linearIndependent_algebraMap_comp_iff.mpr hP
  have hmin : A.dual.absMinimum Ω 1 ≤ B.absMinimum Ω 1 := by
    refine le_csInf (B.absMinimumSet_nonempty (by simp; omega)) fun μ hμ ↦ ?_
    obtain ⟨z, hz, hμ⟩ := B.mem_absMinimumSet.mp hμ
    have hz0 : z 0 ≠ 0 := hz.ne_zero 0
    have hPz : P.map (algebraMap F Ω) *ᵥ z 0 = ∑ j, z 0 j • (algebraMap F Ω ∘ P.col j) := by
      ext i
      simp [Matrix.mulVec, dotProduct, Finset.sum_apply, mul_comm]
    have hPz0 : P.map (algebraMap F Ω) *ᵥ z 0 ≠ 0 := by
      rw [hPz]
      intro h0
      obtain ⟨j, hj⟩ : ∃ j, z 0 j ≠ 0 := by
        by_contra! h
        exact hz0 (funext h)
      exact hj (Fintype.linearIndependent_iff.mp hli _ h0 j)
    calc A.dual.absMinimum Ω 1 ≤ A.dual.absMulHeight (P.map (algebraMap F Ω) *ᵥ z 0) :=
          A.dual.absMinimum_one_le hPz0
      _ = B.absMulHeight (z 0) := by
          rw [absMulHeight_pullback, absMulHeight_baseChange]
      _ ≤ μ := hμ 0
  calc A.absDet * A.dual.absMinimum Ω 1 ^ m ≤ A.absDet * B.absMinimum Ω 1 ^ m := by
        have := A.dual.absMinimum_pos (Ω := Ω) one_pos (by simp)
        gcongr
    _ ≤ A.absDet * (√2 ^ (m * (m - 1)) * B.absDet) := by gcongr; exact hB F B
    _ = √2 ^ (m * (m - 1)) * A.absMulHeight x := by
        rw [hdet]
        field_simp

/-- The algebra of RT96 Prop. 6.2: (i) for `A` and for `A*` give (ii), in dimension `m + 1 ≥ 3`. -/
private theorem pow_le_of_dual {a b D : ℝ} {k : ℕ} (ha : 0 < a) (hD : 0 < D)
    (h1 : D * b ^ (k + 2) ≤ √2 ^ ((k + 2) * (k + 1)) * a)
    (h2 : D⁻¹ * a ^ (k + 2) ≤ √2 ^ ((k + 2) * (k + 1)) * b) :
    a ^ (k + 2 + 1) ≤ √2 ^ ((k + 2 + 1) * (k + 2)) * D := by
  set c := √2 ^ ((k + 2) * (k + 1))
  set s := √2 ^ ((k + 2 + 1) * (k + 2))
  have hc : 0 ≤ c := by positivity
  have hs : s ^ (k + 1) = c ^ (k + 2 + 1) := by
    rw [← pow_mul, ← pow_mul]
    congr 1
    ring
  have h2' : a ^ (k + 2) ≤ D * (c * b) := (inv_mul_le_iff₀ hD).mp h2
  have key : a * (a ^ (k + 2 + 1)) ^ (k + 1) ≤ a * (s * D) ^ (k + 1) :=
    calc a * (a ^ (k + 2 + 1)) ^ (k + 1) = (a ^ (k + 2)) ^ (k + 2) := by ring
      _ ≤ (D * (c * b)) ^ (k + 2) := pow_le_pow_left₀ (by positivity) h2' _
      _ = c ^ (k + 2) * D ^ (k + 1) * (D * b ^ (k + 2)) := by ring
      _ ≤ c ^ (k + 2) * D ^ (k + 1) * (c * a) := by gcongr
      _ = a * (c ^ (k + 2 + 1) * D ^ (k + 1)) := by ring
      _ = a * (s * D) ^ (k + 1) := by rw [mul_pow, hs]
  exact (pow_le_pow_iff_left₀ (by positivity) (by positivity) (by omega)).mp
    (le_of_mul_le_mul_left key ha)

variable [IsAlgClosed Ω]

/-- **RT96 Prop. 6.2 (ii), from (ii) in dimension `m`**: `μ₁(A)^{m+1} ≤ √2^{(m+1)m} |det A|_𝔸`
for a twist `A` of `K^{m+1}`. For `m = 1` this is RT96 Prop. 5.3 (`TwistedPlane.lean`); for
`m ≥ 2` it combines (i) for `A` and for `A*`. -/
theorem absMinimum_one_pow_le_of_forall {m : ℕ} (hm : 0 < m)
    (hB : ∀ (L : Type v) [Field L] [NumberField L] [Algebra L Ω] [Algebra.IsAlgebraic L Ω]
      (B : Twist L (Fin m)), B.absMinimum Ω 1 ^ m ≤ √2 ^ (m * (m - 1)) * B.absDet)
    (A : Twist K (Fin (m + 1))) :
    A.absMinimum Ω 1 ^ (m + 1) ≤ √2 ^ ((m + 1) * m) * A.absDet := by
  have ha := A.absMinimum_pos (Ω := Ω) one_pos (by simp)
  obtain rfl | hm2 := eq_or_lt_of_le (Nat.one_le_iff_ne_zero.mpr hm.ne')
  · have h12 := A.absMinimum_one_mul_absMinimum_two_le_two_mul Ω
    have hle := A.absMinimum_le_absMinimum (Ω := Ω) one_pos one_le_two (by simp)
    have h2 : √2 ^ ((1 + 1) * 1) = 2 := by norm_num
    rw [h2, pow_two]
    nlinarith [mul_le_mul_of_nonneg_left hle ha.le]
  obtain ⟨k, rfl⟩ : ∃ k, m = k + 2 := ⟨m - 2, by omega⟩
  have h1 := absDet_mul_dual_absMinimum_one_pow_le_of_forall hm hB A
  have h2 := absDet_mul_dual_absMinimum_one_pow_le_of_forall hm hB A.dual
  rw [dual_dual, absDet_dual] at h2
  have hk : k + 2 - 1 = k + 1 := rfl
  rw [hk] at h1 h2
  exact pow_le_of_dual ha A.absDet_pos h1 h2

/-- RT96 Prop. 6.2 (ii) over the number fields in the universe of `Ω`, by induction on `n`. -/
theorem absMinimum_one_pow_le_aux (n : ℕ) (hn : 0 < n) (L : Type v) [Field L] [NumberField L]
    [Algebra L Ω] [Algebra.IsAlgebraic L Ω] (B : Twist L (Fin n)) :
    B.absMinimum Ω 1 ^ n ≤ √2 ^ (n * (n - 1)) * B.absDet := by
  induction n, Nat.one_le_iff_ne_zero.mpr hn.ne' using Nat.le_induction generalizing L with
  | base => simpa using B.absMinimum_one_le_absDet
  | succ m hm ih =>
    simpa using absMinimum_one_pow_le_of_forall hm (fun L _ _ _ _ B ↦ ih hm L B) B

/-- **The first absolute minimum** (RT96 Prop. 6.2 (ii)): for a twist `A` of `Kⁿ`, `n ≥ 1`,
`μ₁(A)^n ≤ √2^{n(n-1)} |det A|_𝔸`, the minimum taken over an algebraically closed field. -/
theorem absMinimum_one_pow_le {n : ℕ} (hn : 0 < n) (A : Twist K (Fin n)) :
    A.absMinimum Ω 1 ^ n ≤ √2 ^ (n * (n - 1)) * A.absDet := by
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  obtain rfl | hm := Nat.eq_zero_or_pos m
  · simpa using A.absMinimum_one_le_absDet
  simpa using absMinimum_one_pow_le_of_forall hm (absMinimum_one_pow_le_aux m hm) A

/-- **The first absolute minimum** (RT96 Prop. 6.2 (ii)), in RT's form:
`μ₁(A) ≤ √2^{n-1} |det A|_𝔸^{1/n}`. -/
theorem absMinimum_one_le_rpow {n : ℕ} (hn : 0 < n) (A : Twist K (Fin n)) :
    A.absMinimum Ω 1 ≤ √2 ^ (n - 1) * A.absDet ^ ((n : ℝ)⁻¹) := by
  have hD := A.absDet_pos
  refine (pow_le_pow_iff_left₀ (A.absMinimum_pos (Ω := Ω) one_pos (by simp; omega)).le
    (by positivity) hn.ne').mp ?_
  rw [mul_pow, ← pow_mul, mul_comm (n - 1), Real.rpow_inv_natCast_pow hD.le hn.ne']
  exact A.absMinimum_one_pow_le (Ω := Ω) hn

/-- **The first minimum of the dual twist** (RT96 Prop. 6.2 (i)): for a twist `A` of `K^{m+1}`,
`m ≥ 1`, `|det A|_𝔸 μ₁(A*)^m ≤ √2^{m(m-1)} μ₁(A)`. -/
theorem absDet_mul_dual_absMinimum_one_pow_le {m : ℕ} (hm : 0 < m) (A : Twist K (Fin (m + 1))) :
    A.absDet * A.dual.absMinimum Ω 1 ^ m ≤ √2 ^ (m * (m - 1)) * A.absMinimum Ω 1 :=
  absDet_mul_dual_absMinimum_one_pow_le_of_forall hm (absMinimum_one_pow_le_aux m hm) A

end NumberField.Twist
