/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import QuantitativeSubspace.TwistedFirstMinimum
public import Mathlib.Analysis.InnerProductSpace.GramSchmidtOrtho

-- Used only inside proofs.
import ArithmeticHeights.Extension
import Mathlib.LinearAlgebra.LinearIndependent.BaseChange

/-!
# The absolute Minkowski theorem

D. Roy and J. L. Thunder, *An absolute Siegel's lemma*, J. reine angew. Math. **476** (1996),
1–26, Theorem 6.3: for a twist `A` of `Kⁿ` over a number field `K`, with the absolute minima taken
over an algebraically closed field,

```text
|det A|_𝔸 ≤ μ₁(A) ⋯ μₙ(A) ≤ 2^{n(n-1)/2} |det A|_𝔸.
```

The lower bound is Lemma 4.7 (`absSubspaceHeight_span_range_le_prod`) applied to a basis of
points of almost minimal height. The upper bound is RT's Lemma 3.3 argument with the auxiliary
place `u₀` **complex** (`QuantitativeSubspace/README.md`, Q2.2e):

1. Choose `ε > 0` below every jump of the minima (`exists_absMinimum_gap`) and a basis `x₁, …, xₙ`
   with `H_A(x_i) < μ_i + ε` (`exists_linearIndependent_absMulHeight_lt_absMinimum_add`). Then
   every point outside `span(x₁, …, x_{i-1})` has height at least `μ_i`
   (`absMinimum_le_absMulHeight_of_notMem_span`).
2. Let `E` be the field generated by the `x_i` and `√-1`, `φ₀` a complex embedding of `E` (never
   real, because of `√-1`), `X` the matrix of the `x_i` and `G = A_{φ₀} φ₀(X)`. Gram–Schmidt gives
   an upper triangular `R` with `Rᴴ R = Gᴴ G` (`Matrix.exists_isUpperTriangular_gram_eq`).
3. The twist `B` is `A` except at `φ₀`, where it is `M = diag(a) R φ₀(X)⁻¹` with
   `a_i = μ_i^{-[E:ℚ]/2}`, and at the conjugate of `φ₀`, where it is `conj M` (`Twist.modify`).
   A point with last nonzero coordinate `i` in the basis `x` has `‖M ψ(x)‖ ≥ a_i ‖A_{φ₀} ψ(x)‖`
   at every embedding `ψ` above `φ₀`, so `H_B(x) ≥ a_i^{2/[E:ℚ]} H_A(x) = μ_i⁻¹ H_A(x) ≥ 1`:
   `μ₁(B) ≥ 1`. And `|det B|_𝔸 = |det A|_𝔸 / ∏ μ_i` (`absDet_modify`).
4. RT96 Prop. 6.2 (`TwistedFirstMinimum.lean`) for `B` gives `1 ≤ μ₁(B)ⁿ ≤ √2^{n(n-1)} |det B|_𝔸`.

The weights `a_i` are real numbers, exactly `μ_i^{-[E:ℚ]/2}`: there are no `N`-th roots and no
approximation, and `ε` disappears from the bound. RT's own route, through a finite place, is
`TwistedSuccessiveMinimaFinite.lean`.

## Main definitions

* `NumberField.Twist.modify A hφ₀ M hM`: the twist `A` with its components at a non-real embedding
  `φ₀` and its conjugate replaced by `M` and `conj M`.

## Main results

* `Matrix.exists_isUpperTriangular_gram_eq`: an upper triangular `R` with `Rᴴ R = Gᴴ G`.
* `NumberField.Twist.le_absMulHeight_modify`, `NumberField.Twist.absDet_modify`.
* `NumberField.Twist.absDet_le_prod_absMinimum`: the lower bound `|det A|_𝔸 ≤ ∏ μ_i`.
* `NumberField.Twist.prod_absMinimum_le`: the upper bound `∏ μ_i ≤ √2^{n(n-1)} |det A|_𝔸`.

This is milestone Q2.2e of `QuantitativeSubspace/README.md` (the complex auxiliary place).
-/

@[expose] public section

open Finset Module Matrix IntermediateField NumberField.ComplexEmbedding

namespace Matrix

variable {n : Type*} [Fintype n] [LinearOrder n] [WellFoundedLT n] [LocallyFiniteOrderBot n]

/-- **The QR decomposition, `R` half**: every complex square matrix `G` has the Gram matrix of an
upper triangular matrix, `Rᴴ R = Gᴴ G` (`R` is the matrix of the columns of `G` in the
Gram–Schmidt basis built from them). -/
theorem exists_isUpperTriangular_gram_eq (G : Matrix n n ℂ) :
    ∃ R : Matrix n n ℂ, R.IsUpperTriangular ∧ Rᴴ * R = Gᴴ * G := by
  set g : n → EuclideanSpace ℂ n := fun l ↦ WithLp.toLp 2 fun i ↦ G i l
  set b := InnerProductSpace.gramSchmidtOrthonormalBasis (𝕜 := ℂ) (by simp) g
  refine ⟨Matrix.of fun k l ↦ inner ℂ (b k) (g l), fun k l hlk ↦ ?_, ?_⟩
  · exact InnerProductSpace.gramSchmidtOrthonormalBasis_inv_triangular _ g hlk
  · ext l m
    have h := b.sum_inner_mul_inner (g l) (g m)
    simp only [mul_apply, conjTranspose_apply, of_apply, RCLike.star_def, inner_conj_symm]
    rw [h, EuclideanSpace.inner_eq_star_dotProduct]
    simp [g, dotProduct, mul_comm]

end Matrix

namespace NumberField.Twist

section Modify

variable {E : Type*} [Field E] [NumberField E] {ι : Type*} [Fintype ι] [DecidableEq ι]
  (A : Twist E ι) {φ₀ : E →+* ℂ} (hφ₀ : conjugate φ₀ ≠ φ₀) (M : Matrix ι ι ℂ) (hM : M.det ≠ 0)

open scoped Classical in
/-- **Modifying a twist at a complex place**: the components at the non-real embedding `φ₀` and
at its conjugate become `M` and `conj M`; everything else is `A`. -/
noncomputable def modify : Twist E ι where
  arch φ := if φ = φ₀ then M else if φ = conjugate φ₀ then M.map (starRingEnd ℂ) else A.arch φ
  arch_det_ne_zero φ := by
    split_ifs
    · exact hM
    · rw [show M.map (starRingEnd ℂ) = (starRingEnd ℂ).mapMatrix M from rfl, ← RingHom.map_det]
      exact (map_ne_zero _).mpr hM
    · exact A.arch_det_ne_zero φ
  arch_conjugate φ := by
    have hinv := involutive_conjugate (K := E)
    by_cases h0 : φ = φ₀
    · subst h0
      simp [hφ₀]
    by_cases h1 : φ = conjugate φ₀
    · subst h1
      rw [hinv φ₀]
      simp only [hφ₀, ite_true, ite_false]
      ext
      simp
    have h0' : conjugate φ ≠ φ₀ := fun h ↦ h1 (by rw [← h, hinv])
    have h1' : conjugate φ ≠ conjugate φ₀ := fun h ↦ h0 (hinv.injective h)
    simp only [h0, h1, h0', h1', ite_false, A.arch_conjugate]
  fin := A.fin
  fin_det_ne_zero := A.fin_det_ne_zero
  finite_setOf_fin_ne_one := A.finite_setOf_fin_ne_one

open scoped Classical in
theorem modify_arch (φ : E →+* ℂ) : (A.modify hφ₀ M hM).arch φ =
    if φ = φ₀ then M else if φ = conjugate φ₀ then M.map (starRingEnd ℂ) else A.arch φ :=
  rfl

@[simp] theorem modify_fin : (A.modify hφ₀ M hM).fin = A.fin := rfl

include hφ₀ in
/-- A product over the complex embeddings of a factor that is `c` at `φ₀` and at its conjugate and
`1` elsewhere is `c²`. -/
theorem prod_eq_sq_of_conjugate {w : (E →+* ℂ) → ℝ} {c : ℝ} (h0 : w φ₀ = c)
    (h1 : w (conjugate φ₀) = c) (h : ∀ φ, φ ≠ φ₀ → φ ≠ conjugate φ₀ → w φ = 1) :
    ∏ φ, w φ = c ^ 2 := by
  classical
  rw [← Finset.prod_subset (subset_univ {φ₀, conjugate φ₀}) fun φ _ hφ ↦ h φ
    (fun h' ↦ hφ (by simp [h'])) (fun h' ↦ hφ (by simp [h'])), prod_pair hφ₀.symm, h0, h1, sq]

omit [DecidableEq ι] in
/-- The complex conjugate of `N v` has the same ℓ² norm. -/
theorem norm_toLp_map_conj_mulVec (N : Matrix ι ι ℂ) (v : ι → ℂ) :
    ‖(WithLp.toLp 2 (N.map (starRingEnd ℂ) *ᵥ (starRingEnd ℂ ∘ v)) : EuclideanSpace ℂ ι)‖ =
      ‖(WithLp.toLp 2 (N *ᵥ v) : EuclideanSpace ℂ ι)‖ := by
  have h : N.map (starRingEnd ℂ) *ᵥ (starRingEnd ℂ ∘ v) = starRingEnd ℂ ∘ (N *ᵥ v) :=
    funext fun i ↦ (RingHom.map_mulVec _ _ _ i).symm
  rw [h, EuclideanSpace.norm_eq, EuclideanSpace.norm_eq]
  simp

theorem norm_det_map_conj (N : Matrix ι ι ℂ) : ‖(N.map (starRingEnd ℂ)).det‖ = ‖N.det‖ := by
  rw [show N.map (starRingEnd ℂ) = (starRingEnd ℂ).mapMatrix N from rfl, ← RingHom.map_det,
    Complex.norm_conj]

end Modify

section ModifyDet

variable {E : Type*} [Field E] [NumberField E] {ι : Type*} [Fintype ι] [LinearOrder ι]
  (A : Twist E ι) {φ₀ : E →+* ℂ} (hφ₀ : conjugate φ₀ ≠ φ₀) (M : Matrix ι ι ℂ) (hM : M.det ≠ 0)

/-- **The determinant of the modified twist**:
`|det B|_𝔸 = (‖det M‖ / ‖det A_{φ₀}‖)^{2/[E:ℚ]} |det A|_𝔸`. -/
theorem absDet_modify : (A.modify hφ₀ M hM).absDet =
    (‖M.det‖ / ‖(A.arch φ₀).det‖) ^ ((2 : ℝ) / finrank ℚ E) * A.absDet := by
  classical
  set r := ‖M.det‖ / ‖(A.arch φ₀).det‖
  have hA0 : ‖(A.arch φ₀).det‖ ≠ 0 := norm_ne_zero_iff.mpr (A.arch_det_ne_zero φ₀)
  have hr : 0 ≤ r := by positivity
  set w : (E →+* ℂ) → ℝ := fun φ ↦ if φ = φ₀ ∨ φ = conjugate φ₀ then r else 1
  have hloc : ∀ φ, ‖((A.modify hφ₀ M hM).arch φ).det‖ = w φ * ‖(A.arch φ).det‖ := by
    intro φ
    rw [modify_arch]
    by_cases h0 : φ = φ₀
    · simp only [h0, ite_true, true_or, w, r, div_mul_cancel₀ _ hA0]
    by_cases h1 : φ = conjugate φ₀
    · simp only [h1, hφ₀, ite_true, ite_false, or_true, w, r, A.arch_conjugate, norm_det_map_conj,
        div_mul_cancel₀ _ hA0]
    · simp [h0, h1, w]
  have hw : ∏ φ, w φ = r ^ 2 := prod_eq_sq_of_conjugate hφ₀ (by simp [w]) (by simp [w])
    fun φ h0 h1 ↦ by simp [w, h0, h1]
  rw [absDet, absDet, modify_fin]
  simp_rw [hloc]
  rw [prod_mul_distrib, hw, mul_assoc, Real.mul_rpow (by positivity) (mul_nonneg
    (prod_nonneg fun _ _ ↦ norm_nonneg _) (finprod_nonneg fun _ ↦ apply_nonneg _ _)),
    ← Real.rpow_natCast r 2, ← Real.rpow_mul hr, div_eq_mul_inv]
  norm_num

end ModifyDet

/-- Every complex embedding of a field extends to an algebraic extension of it. -/
theorem _root_.RingHom.exists_comp_algebraMap_eq {F Ω : Type*} [Field F] [Field Ω] [Algebra F Ω]
    [Algebra.IsAlgebraic F Ω] (ψ : F →+* ℂ) : ∃ ψ' : Ω →+* ℂ, ψ'.comp (algebraMap F Ω) = ψ := by
  let := ψ.toAlgebra
  exact ⟨(IsAlgClosed.lift : Ω →ₐ[F] ℂ).toRingHom, (IsAlgClosed.lift : Ω →ₐ[F] ℂ).comp_algebraMap⟩

section ModifyHeight

variable {E : Type*} [Field E] [NumberField E] {ι : Type*} [Fintype ι] [DecidableEq ι]
  (A : Twist E ι) {φ₀ : E →+* ℂ} (hφ₀ : conjugate φ₀ ≠ φ₀) (M : Matrix ι ι ℂ) (hM : M.det ≠ 0)
  {Ω : Type*} [Field Ω] [Algebra E Ω] [Algebra.IsAlgebraic E Ω]

/-- **The height for the modified twist**: if `‖M ψ(x)‖ ≥ c ‖A_{φ₀} ψ(x)‖` at every embedding
`ψ` of `Ω` above `φ₀`, then `H_B(x) ≥ c^{2/[E:ℚ]} H_A(x)`. -/
theorem le_absMulHeight_modify {c : ℝ} (hc : 0 ≤ c) (x : ι → Ω)
    (h : ∀ ψ : Ω →+* ℂ, ψ.comp (algebraMap E Ω) = φ₀ →
      c * ‖(WithLp.toLp 2 (A.arch φ₀ *ᵥ (ψ ∘ x)) : EuclideanSpace ℂ ι)‖ ≤
        ‖(WithLp.toLp 2 (M *ᵥ (ψ ∘ x)) : EuclideanSpace ℂ ι)‖) :
    c ^ ((2 : ℝ) / finrank ℚ E) * A.absMulHeight x ≤ (A.modify hφ₀ M hM).absMulHeight x := by
  classical
  have := numberField_adjoin_range (K := E) x
  set F := adjoin E (Set.range x)
  have : Algebra.IsAlgebraic F Ω := Algebra.IsAlgebraic.tower_top (K := E) F
  set y : ι → F := fun i ↦ ⟨x i, subset_adjoin E _ ⟨i, rfl⟩⟩
  have hinv := involutive_conjugate (K := E)
  -- At an embedding `ψ` of `F` above `φ₀` the hypothesis applies to an extension of `ψ`.
  have hext : ∀ ψ : F →+* ℂ, ψ.comp (algebraMap E F) = φ₀ →
      c * ‖(WithLp.toLp 2 (A.arch φ₀ *ᵥ (ψ ∘ y)) : EuclideanSpace ℂ ι)‖ ≤
        ‖(WithLp.toLp 2 (M *ᵥ (ψ ∘ y)) : EuclideanSpace ℂ ι)‖ := by
    intro ψ hψ
    obtain ⟨ψ', hψ'⟩ := ψ.exists_comp_algebraMap_eq (Ω := Ω)
    have hx : ψ' ∘ x = ψ ∘ y := by rw [← hψ']; rfl
    have hE : ψ'.comp (algebraMap E Ω) = φ₀ := by
      rw [IsScalarTower.algebraMap_eq E F Ω, ← RingHom.comp_assoc, hψ', hψ]
    simpa only [hx] using h ψ' hE
  set w : (E →+* ℂ) → ℝ := fun φ ↦ if φ = φ₀ ∨ φ = conjugate φ₀ then c else 1
  have hloc : ∀ ψ : F →+* ℂ, w (ψ.comp (algebraMap E F)) * A.archFactor ψ y ≤
      (A.modify hφ₀ M hM).archFactor ψ y := by
    intro ψ
    rw [archFactor, archFactor, modify_arch]
    by_cases h0 : ψ.comp (algebraMap E F) = φ₀
    · simp only [h0, ite_true, true_or, w]
      exact hext ψ h0
    by_cases h1 : ψ.comp (algebraMap E F) = conjugate φ₀
    · simp only [h1, hφ₀, ite_true, ite_false, or_true, w, A.arch_conjugate]
      have hc' : (conjugate ψ).comp (algebraMap E F) = φ₀ := by
        rw [conjugate_comp, h1, hinv]
      have hψ : ψ ∘ y = starRingEnd ℂ ∘ (conjugate ψ ∘ y) := by
        funext i
        simp
      rw [hψ, norm_toLp_map_conj_mulVec, norm_toLp_map_conj_mulVec]
      exact hext _ hc'
    · simp [h0, h1, w]
  have hw : ∏ φ, w φ = c ^ 2 := prod_eq_sq_of_conjugate hφ₀ (by simp [w]) (by simp [w])
    fun φ h0 h1 ↦ by simp [w, h0, h1]
  have hw0 : ∀ φ, 0 ≤ w φ := fun φ ↦ by
    simp only [w]
    split_ifs
    exacts [hc, zero_le_one]
  have hrel : c ^ (2 * finrank E F) * A.mulHeight y ≤ (A.modify hφ₀ M hM).mulHeight y := by
    rw [mulHeight, mulHeight, ← mul_assoc]
    refine mul_le_mul_of_nonneg_right ?_ (finprod_nonneg fun _ ↦ A.finFactor_nonneg _ _)
    calc c ^ (2 * finrank E F) * ∏ ψ : F →+* ℂ, A.archFactor ψ y
        = ∏ ψ : F →+* ℂ, (w (ψ.comp (algebraMap E F)) * A.archFactor ψ y) := by
          rw [prod_mul_distrib, prod_comp_eq_prod_pow, hw, pow_mul]
      _ ≤ _ := Finset.prod_le_prod₀ (fun ψ _ ↦ mul_nonneg (hw0 _) (A.archFactor_nonneg _ _))
          fun ψ _ ↦ hloc ψ
  have hd := Module.finrank_mul_finrank ℚ E F
  have hE : (finrank ℚ E : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr finrank_pos.ne'
  have hFE : (finrank E F : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr finrank_pos.ne'
  rw [absMulHeight, absMulHeight]
  calc c ^ ((2 : ℝ) / finrank ℚ E) * A.mulHeight y ^ ((finrank ℚ F : ℝ))⁻¹
      = (c ^ (2 * finrank E F) * A.mulHeight y) ^ ((finrank ℚ F : ℝ))⁻¹ := by
        rw [Real.mul_rpow (pow_nonneg hc _) (A.mulHeight_nonneg _), ← Real.rpow_natCast,
          ← Real.rpow_mul hc, ← hd]
        congr 2
        push_cast
        field_simp
    _ ≤ _ := Real.rpow_le_rpow (mul_nonneg (pow_nonneg hc _) (A.mulHeight_nonneg _)) hrel
        (by positivity)

end ModifyHeight

/-! ### A basis adapted to the minima -/

section Flag

variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Fintype ι] [DecidableEq ι]
  (A : Twist K ι) {Ω : Type*} [Field Ω] [Algebra K Ω] [Algebra.IsAlgebraic K Ω]

/-- The junk value `μ₀ = 0`: every real number bounds `0` points. -/
theorem absMinimum_zero : A.absMinimum Ω 0 = 0 := by
  have h : A.absMinimumSet Ω 0 = Set.univ :=
    Set.eq_univ_of_forall fun μ ↦ ⟨Fin.elim0, linearIndependent_empty_type, fun k ↦ k.elim0⟩
  rw [absMinimum, h, Real.sInf_of_not_bddBelow not_bddBelow_univ]

theorem absMinimum_nonneg (i : ℕ) : 0 ≤ A.absMinimum Ω i := by
  rcases Nat.eq_zero_or_pos i with rfl | hi0
  · rw [absMinimum_zero]
  by_cases hi : i ≤ Fintype.card ι
  · exact (A.absMinimum_pos hi0 hi).le
  · have h : A.absMinimumSet Ω i = ∅ := Set.eq_empty_of_forall_notMem fun μ ⟨x, hx, _⟩ ↦
      hi (by simpa using hx.fintype_card_le_finrank)
    rw [absMinimum, h, Real.sInf_empty]

/-- `μ_i ≤ μ_j` for `i ≤ j ≤ n`, including the junk `μ₀ = 0`. -/
theorem absMinimum_mono {i j : ℕ} (hij : i ≤ j) (hj : j ≤ Fintype.card ι) :
    A.absMinimum Ω i ≤ A.absMinimum Ω j := by
  rcases Nat.eq_zero_or_pos i with rfl | hi0
  · rw [absMinimum_zero]
    exact A.absMinimum_nonneg j
  exact A.absMinimum_le_absMinimum hi0 hij hj

/-- **A basis of almost minimal heights**: `n` independent points with `H_A(x_k) < μ_{k+1} + ε`
(built greedily from `exists_linearIndependent_absMulHeight_lt`). -/
theorem exists_linearIndependent_absMulHeight_lt_absMinimum_add {n : ℕ}
    (hn : Fintype.card ι = n) {ε : ℝ} (hε : 0 < ε) :
    ∃ x : Fin n → ι → Ω, LinearIndependent Ω x ∧
      ∀ k, A.absMulHeight (x k) < A.absMinimum Ω (k + 1) + ε := by
  subst hn
  suffices h : ∀ m ≤ Fintype.card ι, ∃ x : Fin m → ι → Ω, LinearIndependent Ω x ∧
      ∀ k : Fin m, A.absMulHeight (x k) < A.absMinimum Ω (k + 1) + ε from h _ le_rfl
  intro m
  induction m with
  | zero => exact fun _ ↦ ⟨Fin.elim0, linearIndependent_empty_type, fun k ↦ k.elim0⟩
  | succ m ih =>
    intro hm
    obtain ⟨x, hx, hxε⟩ := ih (by omega)
    obtain ⟨y, hy, hyε⟩ := A.exists_linearIndependent_absMulHeight_lt (Ω := Ω) hm
      (lt_add_of_pos_right (A.absMinimum Ω (m + 1)) hε)
    obtain ⟨j, hj⟩ : ∃ j, y j ∉ Submodule.span Ω (Set.range x) := by
      by_contra! h
      have hle : Submodule.span Ω (Set.range y) ≤ Submodule.span Ω (Set.range x) :=
        Submodule.span_le.mpr (Set.range_subset_iff.mpr h)
      have := Submodule.finrank_mono hle
      rw [finrank_span_eq_card hy, finrank_span_eq_card hx, Fintype.card_fin,
        Fintype.card_fin] at this
      omega
    refine ⟨Fin.snoc x (y j), linearIndependent_finSnoc.mpr ⟨hx, hj⟩, fun k ↦ ?_⟩
    induction k using Fin.lastCases with
    | last => simpa using hyε j
    | cast k => simpa using hxε k

/-- **A gap below every jump of the minima**: some `ε > 0` with `μ_k + ε < μ_{k+1}` whenever
`μ_k < μ_{k+1}`. -/
theorem exists_absMinimum_gap {n : ℕ} (hn : Fintype.card ι = n) : ∃ ε > 0, ∀ k < n,
    A.absMinimum Ω k < A.absMinimum Ω (k + 1) →
      A.absMinimum Ω k + ε < A.absMinimum Ω (k + 1) := by
  subst hn
  have h : ∀ᶠ ε in nhdsWithin (0 : ℝ) (Set.Ioi 0), ∀ k ∈ range (Fintype.card ι),
      A.absMinimum Ω k < A.absMinimum Ω (k + 1) →
        A.absMinimum Ω k + ε < A.absMinimum Ω (k + 1) := by
    refine (Filter.eventually_all_finset _).mpr fun k _ ↦ ?_
    by_cases hk : A.absMinimum Ω k < A.absMinimum Ω (k + 1)
    · filter_upwards [(eventually_lt_nhds (sub_pos.mpr hk)).filter_mono nhdsWithin_le_nhds]
        with ε hε _
      linarith
    · exact Filter.Eventually.of_forall fun _ h ↦ absurd h hk
  obtain ⟨ε, hε, hε0⟩ := (h.and self_mem_nhdsWithin).exists
  exact ⟨ε, hε0, fun k hk ↦ hε k (mem_range.mpr hk)⟩

/-- **Points outside the flag are high** (RT96, proof of Thm 6.3): if `ε` is below every jump of
the minima and `H_A(x_k) < μ_{k+1} + ε`, then every point outside `span(x_k : k < i)` has height
at least `μ_{i+1}`. -/
theorem absMinimum_le_absMulHeight_of_notMem_span {n : ℕ} (hn : Fintype.card ι = n) {ε : ℝ}
    (hgap : ∀ k < n, A.absMinimum Ω k < A.absMinimum Ω (k + 1) →
      A.absMinimum Ω k + ε < A.absMinimum Ω (k + 1))
    {x : Fin n → ι → Ω} (hx : LinearIndependent Ω x)
    (hxε : ∀ k, A.absMulHeight (x k) < A.absMinimum Ω (k + 1) + ε) {i : Fin n}
    {z : ι → Ω} (hz : z ∉ Submodule.span Ω (x '' {k | k < i})) :
    A.absMinimum Ω (i + 1) ≤ A.absMulHeight z := by
  classical
  subst hn
  have hex : ∃ j, A.absMinimum Ω (j + 1) = A.absMinimum Ω (i + 1) := ⟨i, rfl⟩
  set j := Nat.find hex
  have hj : A.absMinimum Ω (j + 1) = A.absMinimum Ω (i + 1) := Nat.find_spec hex
  have hji : j ≤ i := Nat.find_min' hex rfl
  have hin : (i : ℕ) < Fintype.card ι := i.2
  have hlt : A.absMinimum Ω j < A.absMinimum Ω (j + 1) := by
    rcases Nat.eq_zero_or_pos j with h0 | hj0
    · rw [h0, absMinimum_zero]
      exact A.absMinimum_pos one_pos (by omega)
    obtain ⟨j', hj'⟩ : ∃ j', j = j' + 1 := ⟨j - 1, by omega⟩
    have hne : A.absMinimum Ω (j' + 1) ≠ A.absMinimum Ω (i + 1) :=
      Nat.find_min hex (by omega)
    rw [hj'] at hj ⊢
    exact lt_of_le_of_ne (A.absMinimum_mono (by omega) (by omega)) (hj ▸ hne)
  have hgap' := hgap j (by omega) hlt
  rw [← hj]
  by_contra! hzlt
  set v : Fin j → ι → Ω := fun k ↦ x ⟨k, by omega⟩
  have hv : LinearIndependent Ω v :=
    hx.comp _ fun k l h ↦ Fin.ext (by simpa using congrArg Fin.val h)
  have hzv : z ∉ Submodule.span Ω (Set.range v) := fun h ↦ hz <| Submodule.span_mono
    (by rintro _ ⟨k, rfl⟩; exact ⟨_, show (k : ℕ) < i by omega, rfl⟩) h
  have hle := A.absMinimum_le (Ω := Ω) (Nat.succ_pos j)
    (linearIndependent_finSnoc.mpr ⟨hv, hzv⟩)
    (μ := max (A.absMulHeight z) (A.absMinimum Ω j + ε)) fun k ↦ by
      induction k using Fin.lastCases with
      | last => simp
      | cast k =>
        simp only [Fin.snoc_castSucc, v]
        refine le_max_of_le_right ((hxε _).le.trans ?_)
        have := A.absMinimum_mono (Ω := Ω) (i := k + 1) (j := j) (by omega) (by omega)
        simpa using this
  exact absurd hle (not_le.mpr (max_lt hzlt hgap'))

end Flag

/-! ### The theorem -/

section Lower

variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Fintype ι] [LinearOrder ι]
  (A : Twist K ι) {Ω : Type*} [Field Ω] [Algebra K Ω] [Algebra.IsAlgebraic K Ω]

/-- **The lower bound of the absolute Minkowski theorem** (RT96 Thm 6.3):
`|det A|_𝔸 ≤ μ₁(A) ⋯ μₙ(A)`, from Lemma 4.7 for bases of almost minimal height. -/
theorem absDet_le_prod_absMinimum {n : ℕ} (hn : Fintype.card ι = n) :
    A.absDet ≤ ∏ i : Fin n, A.absMinimum Ω (i + 1) := by
  have hle : ∀ ε > 0, A.absDet ≤ ∏ i : Fin n, (A.absMinimum Ω (i + 1) + ε) := fun ε hε ↦ by
    obtain ⟨x, hx, hxε⟩ := A.exists_linearIndependent_absMulHeight_lt_absMinimum_add (Ω := Ω) hn hε
    have hspan : Submodule.span Ω (Set.range x) = ⊤ := by
      refine Submodule.eq_top_of_finrank_eq ?_
      rw [finrank_span_eq_card hx, Fintype.card_fin, Module.finrank_pi, hn]
    calc A.absDet = A.absSubspaceHeight (⊤ : Submodule Ω (ι → Ω)) :=
          (A.absSubspaceHeight_top (Ω := Ω)).symm
      _ ≤ ∏ i, A.absMulHeight (x i) := hspan ▸ A.absSubspaceHeight_span_range_le_prod hx
      _ ≤ _ := Finset.prod_le_prod₀ (fun i _ ↦ A.absMulHeight_nonneg _)
          fun i _ ↦ (hxε i).le
  have hc : Continuous fun ε : ℝ ↦ ∏ i : Fin n, (A.absMinimum Ω (i + 1) + ε) := by fun_prop
  have ht := (hc.tendsto 0).mono_left (nhdsWithin_le_nhds (s := Set.Ioi 0))
  simp only [add_zero] at ht
  exact ge_of_tendsto ht (eventually_nhdsWithin_of_forall hle)

end Lower

/-- `a_i ‖v‖ ≤ ‖diag(a) v‖` when `v` vanishes beyond `i` and the weights decrease up to `i`. -/
theorem mul_norm_le_norm_diagonal_mulVec {n : ℕ} {a : Fin n → ℝ} {i : Fin n} (ha : 0 ≤ a i)
    (hai : ∀ k ≤ i, a i ≤ a k) {v : Fin n → ℂ} (hv : ∀ k, i < k → v k = 0) :
    a i * ‖(WithLp.toLp 2 v : EuclideanSpace ℂ (Fin n))‖ ≤
      ‖(WithLp.toLp 2 (diagonal (fun k ↦ (a k : ℂ)) *ᵥ v) : EuclideanSpace ℂ (Fin n))‖ := by
  rw [EuclideanSpace.norm_eq, EuclideanSpace.norm_eq, ← Real.sqrt_sq ha,
    ← Real.sqrt_mul (sq_nonneg _), mul_sum]
  refine Real.sqrt_le_sqrt (sum_le_sum fun k _ ↦ ?_)
  simp only [mulVec_diagonal, norm_mul, Complex.norm_real, Real.norm_eq_abs, mul_pow, sq_abs]
  rcases le_or_gt k i with hk | hk
  · gcongr
    exact hai k hk
  · simp [hv k hk]

section Upper

variable {K : Type*} [Field K] [NumberField K] {Ω : Type*} [Field Ω] [Algebra K Ω]
  [Algebra.IsAlgebraic K Ω] [IsAlgClosed Ω]

/-- **The absolute Minkowski theorem**, upper bound (RT96 Thm 6.3), through a complex auxiliary
place: `μ₁(A) ⋯ μₙ(A) ≤ √2^{n(n-1)} |det A|_𝔸 = 2^{n(n-1)/2} |det A|_𝔸`. -/
theorem prod_absMinimum_le {n : ℕ} (hn : 0 < n) (A : Twist K (Fin n)) :
    ∏ i : Fin n, A.absMinimum Ω (i + 1) ≤ √2 ^ (n * (n - 1)) * A.absDet := by
  classical
  have hcard := Fintype.card_fin n
  have : Nonempty (Fin n) := ⟨⟨0, hn⟩⟩
  set μ : Fin n → ℝ := fun i ↦ A.absMinimum Ω (i + 1)
  have hpos : ∀ i, 0 < μ i := fun i ↦ A.absMinimum_pos (by omega) (by simp)
  obtain ⟨ε, hε, hgap⟩ := A.exists_absMinimum_gap (Ω := Ω) hcard
  obtain ⟨x, hx, hxε⟩ := A.exists_linearIndependent_absMulHeight_lt_absMinimum_add (Ω := Ω) hcard
    hε
  -- The field `E` of the basis and of `√-1`, and the matrix `X` of the basis over it.
  obtain ⟨I, hI⟩ := IsAlgClosed.exists_pow_nat_eq (-1 : Ω) two_pos
  set g : Option (Fin n × Fin n) → Ω := fun o ↦ o.elim I fun p ↦ x p.2 p.1
  have := numberField_adjoin_range (K := K) g
  set E := adjoin K (Set.range g)
  have : Algebra.IsAlgebraic E Ω := Algebra.IsAlgebraic.tower_top (K := K) E
  set X : Matrix (Fin n) (Fin n) E :=
    Matrix.of fun i k ↦ ⟨x k i, subset_adjoin K _ ⟨some (i, k), rfl⟩⟩
  have hXx : (fun k ↦ algebraMap E Ω ∘ X.col k) = x := rfl
  have hXdet : X.det ≠ 0 := by
    have hXli : LinearIndependent E X.col :=
      linearIndependent_algebraMap_comp_iff.mp (hXx ▸ hx)
    exact ((Matrix.isUnit_iff_isUnit_det X).mp (linearIndependent_cols_iff_isUnit.mp hXli)).ne_zero
  -- A complex embedding of `E`, not real because of `√-1`.
  obtain ⟨φ₀, -⟩ := (algebraMap ℚ ℂ).exists_comp_algebraMap_eq (Ω := E)
  set iE : E := ⟨I, subset_adjoin K _ ⟨none, rfl⟩⟩
  have hφ₀ : conjugate φ₀ ≠ φ₀ := by
    intro h
    have hsq : φ₀ iE ^ 2 = -1 := by
      rw [← map_pow, show iE ^ 2 = -1 from Subtype.ext (by simpa using hI), map_neg, map_one]
    have hre : (starRingEnd ℂ) (φ₀ iE) = φ₀ iE := by rw [← conjugate_coe_eq, h]
    have him := Complex.conj_eq_iff_im.mp hre
    have := congrArg Complex.re hsq
    simp only [sq, Complex.mul_re, him, mul_zero, sub_zero, Complex.neg_re, Complex.one_re] at this
    nlinarith [mul_self_nonneg (φ₀ iE).re]
  -- The matrices at `φ₀`: `G = A_{φ₀} φ₀(X) `, and `R` upper triangular with `Rᴴ R = Gᴴ G`.
  set A₀ := A.arch (φ₀.comp (algebraMap K E))
  set X₀ := X.map φ₀
  have hX₀ : X₀.det ≠ 0 := by
    rw [show X₀ = φ₀.mapMatrix X from rfl, ← RingHom.map_det]
    exact (map_ne_zero _).mpr hXdet
  have hA₀ : A₀.det ≠ 0 := A.arch_det_ne_zero _
  obtain ⟨R, hRup, hRG⟩ := (A₀ * X₀).exists_isUpperTriangular_gram_eq
  have hRdet : ‖R.det‖ = ‖A₀.det‖ * ‖X₀.det‖ := by
    have h := congrArg (fun N : Matrix (Fin n) (Fin n) ℂ ↦ ‖N.det‖) hRG
    simp only [det_mul, det_conjTranspose, norm_mul, norm_star] at h
    nlinarith [norm_nonneg R.det, norm_nonneg A₀.det, norm_nonneg X₀.det,
      mul_nonneg (norm_nonneg A₀.det) (norm_nonneg X₀.det)]
  -- The weights `a_k = μ_k^{-[E:ℚ]/2}` and the new component `M = diag(a) R φ₀(X)⁻¹`.
  set d := finrank ℚ E
  have hd : (d : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr finrank_pos.ne'
  set a : Fin n → ℝ := fun k ↦ μ k ^ (-(d : ℝ) / 2)
  have ha0 : ∀ k, 0 ≤ a k := fun k ↦ (Real.rpow_pos_of_pos (hpos k) _).le
  have hanti : ∀ k l, k ≤ l → a l ≤ a k := fun k l hkl ↦
    Real.rpow_le_rpow_of_nonpos (hpos k) (A.absMinimum_mono (by simpa using hkl) (by simp))
      (by have := (Nat.cast_nonneg d : (0 : ℝ) ≤ d); linarith)
  have hai : ∀ k, a k ^ ((2 : ℝ) / d) = (μ k)⁻¹ := fun k ↦ by
    rw [← Real.rpow_mul (hpos k).le, show -(d : ℝ) / 2 * (2 / d) = -1 by field_simp,
      Real.rpow_neg_one]
  set M := diagonal (fun k ↦ (a k : ℂ)) * R * X₀⁻¹
  have hMX : M * X₀ = diagonal (fun k ↦ (a k : ℂ)) * R := by
    rw [Matrix.mul_assoc, nonsing_inv_mul _ (isUnit_iff_ne_zero.mpr hX₀), Matrix.mul_one]
  have hMnorm : ‖M.det‖ = (∏ k, a k) * ‖A₀.det‖ := by
    have h := congrArg (fun N : Matrix (Fin n) (Fin n) ℂ ↦ ‖N.det‖) hMX
    simp only [det_mul, det_diagonal, norm_mul, norm_prod, Complex.norm_real, Real.norm_eq_abs,
      hRdet] at h
    simp_rw [abs_of_nonneg (ha0 _)] at h
    rw [← mul_assoc] at h
    exact mul_right_cancel₀ (norm_ne_zero_iff.mpr hX₀) h
  have hM : M.det ≠ 0 := by
    intro h0
    have := hMnorm
    rw [h0, norm_zero] at this
    have hprod : 0 < ∏ k, a k := prod_pos fun k _ ↦ Real.rpow_pos_of_pos (hpos k) _
    have : 0 < (∏ k, a k) * ‖A₀.det‖ := mul_pos hprod (norm_pos_iff.mpr hA₀)
    linarith
  -- The twist `B`: `A` over `E`, modified at `φ₀`.
  set B := (A.baseChange E).modify hφ₀ M hM
  -- Every nonzero point has `H_B ≥ 1`.
  have hB : ∀ z : Fin n → Ω, z ≠ 0 → 1 ≤ B.absMulHeight z := by
    intro z hz
    set bs := basisOfLinearIndependentOfCardEqFinrank hx (by simp)
    have hbs : ⇑bs = x := coe_basisOfLinearIndependentOfCardEqFinrank _ _
    set y := bs.equivFun z
    have hzy : z = ∑ k, y k • x k := by
      rw [← hbs]
      exact (bs.sum_equivFun z).symm
    have hy : y ≠ 0 := fun h ↦ hz (by rw [hzy, h]; simp)
    have hne : (univ.filter fun k ↦ y k ≠ 0).Nonempty := by
      obtain ⟨k, hk⟩ := Function.ne_iff.mp hy
      exact ⟨k, by simpa using hk⟩
    set i := (univ.filter fun k ↦ y k ≠ 0).max' hne
    have hi : y i ≠ 0 := (mem_filter.mp (max'_mem _ hne)).2
    have hgt : ∀ k, i < k → y k = 0 := fun k hk ↦ by
      by_contra h
      exact absurd (le_max' _ k (by simpa using h)) (not_le.mpr hk)
    have hzspan : z ∉ Submodule.span Ω (x '' {k | k < i}) := by
      rw [← hbs, Basis.mem_span_image]
      intro h
      have hmem : i ∈ (bs.repr z).support := by
        rw [Finsupp.mem_support_iff, ← Basis.equivFun_apply]
        exact hi
      exact lt_irrefl i (by simpa using h hmem)
    have hHA : μ i ≤ A.absMulHeight z :=
      A.absMinimum_le_absMulHeight_of_notMem_span hcard hgap hx hxε hzspan
    have hloc : ∀ ψ : Ω →+* ℂ, ψ.comp (algebraMap E Ω) = φ₀ →
        a i * ‖(WithLp.toLp 2 ((A.baseChange E).arch φ₀ *ᵥ (ψ ∘ z)) : EuclideanSpace ℂ (Fin n))‖ ≤
          ‖(WithLp.toLp 2 (M *ᵥ (ψ ∘ z)) : EuclideanSpace ℂ (Fin n))‖ := by
      intro ψ hψ
      set w : Fin n → ℂ := ψ ∘ y
      have hψE : ∀ e : E, ψ (algebraMap E Ω e) = φ₀ e := fun e ↦ by rw [← hψ]; rfl
      have hψz : ψ ∘ z = X₀ *ᵥ w := by
        funext j
        rw [hzy]
        simp only [Function.comp_apply, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, map_sum,
          map_mul, mulVec, dotProduct, X₀, w, Matrix.map_apply]
        refine sum_congr rfl fun k _ ↦ ?_
        rw [mul_comm, ← hψE]
        rfl
      have h1 : (A.baseChange E).arch φ₀ *ᵥ (ψ ∘ z) = (A₀ * X₀) *ᵥ w := by
        rw [hψz, mulVec_mulVec]
        rfl
      have h2 : M *ᵥ (ψ ∘ z) = diagonal (fun k ↦ (a k : ℂ)) *ᵥ (R *ᵥ w) := by
        rw [hψz, mulVec_mulVec, hMX, mulVec_mulVec]
      rw [h1, h2, ← norm_toLp_mulVec_eq_of_gram hRG]
      refine mul_norm_le_norm_diagonal_mulVec (ha0 i) (fun k hk ↦ hanti k i hk) fun k hk ↦ ?_
      simp only [mulVec, dotProduct]
      refine sum_eq_zero fun l _ ↦ ?_
      rcases lt_or_ge l k with hlk | hkl
      · rw [hRup hlk, zero_mul]
      · rw [show w l = 0 by simp [w, hgt l (lt_of_lt_of_le hk hkl)], mul_zero]
    have hmod := (A.baseChange E).le_absMulHeight_modify hφ₀ M hM (ha0 i) z hloc
    rw [absMulHeight_baseChange, hai] at hmod
    calc (1 : ℝ) = (μ i)⁻¹ * μ i := (inv_mul_cancel₀ (hpos i).ne').symm
      _ ≤ (μ i)⁻¹ * A.absMulHeight z :=
        mul_le_mul_of_nonneg_left hHA (inv_pos.mpr (hpos i)).le
      _ ≤ B.absMulHeight z := hmod
  have hμB : 1 ≤ B.absMinimum Ω 1 :=
    le_csInf (B.absMinimumSet_nonempty (by simp; omega)) fun ν ⟨z, hz, hzν⟩ ↦
      (hB _ (hz.ne_zero 0)).trans (hzν 0)
  have hdetB : B.absDet = (∏ k, μ k)⁻¹ * A.absDet := by
    rw [absDet_modify, absDet_baseChange, baseChange_arch, hMnorm,
      mul_div_cancel_right₀ _ (norm_ne_zero_iff.mpr hA₀),
      ← Real.finsetProd_rpow _ _ fun k _ ↦ ha0 k]
    have h : ∏ k, a k ^ ((2 : ℝ) / finrank ℚ E) = ∏ k, (μ k)⁻¹ := prod_congr rfl fun k _ ↦ hai k
    rw [h, prod_inv_distrib]
  -- RT96 Prop. 6.2 for `B`.
  have h62 := B.absMinimum_one_pow_le (Ω := Ω) hn
  rw [hdetB] at h62
  have key := (one_le_pow₀ hμB).trans h62
  have hP : 0 < ∏ k, μ k := prod_pos fun k _ ↦ hpos k
  calc ∏ k, μ k = (∏ k, μ k) * 1 := (mul_one _).symm
    _ ≤ (∏ k, μ k) * (√2 ^ (n * (n - 1)) * ((∏ k, μ k)⁻¹ * A.absDet)) := by gcongr
    _ = √2 ^ (n * (n - 1)) * A.absDet := by field_simp

end Upper

end NumberField.Twist
