/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import QuantitativeSubspace.ProductTheorem

-- Used only inside proofs.
import ForMathlib.RingTheory.MvPolynomial.Associativity
import ForMathlib.RingTheory.MvPolynomial.Product
import Mathlib.Algebra.Order.Sub.Prod

/-!
# The product theorem for the zeros of index `σ` (Rémond 2001, Thm. 1.1 and Cor. 1.1)

For a polynomial `P ∈ K[X]`, multihomogeneous of multidegree `δ` in the blocks `b : σ → ι`, the
*zeros of index `a`* of `P` are cut out by the ideal `indexIdeal b δ P a` generated by the Hasse
derivatives `∂_κ P` with `∑_s κ_s / δ_{b s} ≤ a`: this is Rémond's `Z_a(P)` and Evertse's
`Z_a(F, d)` (Evertse 1995, §1), with Hasse derivatives in place of ordinary ones (the same ideal in
characteristic `0`). A multihomogeneous prime `𝔭` with `H_𝔭 ≠ 0` is a component of `Z_a(P)` when it
is a minimal prime of `indexIdeal b δ P a`, and lies in `Z_{a+ε}(P)` when it contains
`indexIdeal b δ P (a + ε)`.

* `MvPolynomial.productTheorem_indexIdeal` is G. Rémond, *Sur le théorème du produit*, J. Théor.
  Nombres Bordeaux **13** (2001), Thm. 1.1, geometric part (and Evertse 1995, Thm. 1, with a
  better constant): a component `Z` of both `Z_a(P)` and `Z_{a+ε}(P)` is a component of the
  product of its projections, and `ε^c d(Z) ≤ c! / ∏_i c_i! ≤ m^c` with `c = codim Z` and
  `c_i = codim Z_i`, provided `δ_i / δ_{i+1} > (m/ε)^c`. It reduces to
  `MvPolynomial.productTheorem` by padding each `∂_κ P` to multidegree `δ` with a monomial in
  variables outside `𝔭`.
* `MvPolynomial.exists_productTheorem_indexIdeal` is Rémond's Cor. 1.1 (Evertse 1995, Corollary,
  geometric part): if `δ_i / δ_{i+1} > max(1, (m N/ε)^N)` with `N = |σ| - m` the dimension of the
  multiprojective space, every irreducible subvariety `W` of `Z_ε(P)` lies in a product
  `Z = Z_1 × ⋯ × Z_m ≠ ℙ`, a component of `Z_{jε/N}(P)` and `Z_{(j+1)ε/N}(P)` for some `j`.
  The proof is the usual descent along `Z_0 ⊇ Z_{ε/N} ⊇ ⋯ ⊇ Z_ε`: the heights of the components
  through `W` can only increase `N` times.

The vanishing hypothesis `IsUnmixedRing (Localization.AtPrime 𝔭)` is the Cohen–Macaulay property
of `K[X]`, which the Bézout side (`ForMathlib`, Q1.1d(iv)) still assumes.

This completes the geometric part of Layer Q1.2 of the `QuantitativeSubspace` roadmap; the
height bounds of Rémond's Thm. 1.1 and Cor. 1.1 are Layer Q1.3
(`QuantitativeSubspace.ZerosOfIndexHeight`). The descent of Cor. 1.1 is shared by both:
`MvPolynomial.exists_component_indexIdeal`.
-/

@[expose] public section

open Finset

namespace MvPolynomial

variable {σ ι K : Type*} [Field K]

/-- The ideal of the **zeros of index `a`** of `P` for the weights `1/δ_i` on the blocks: it is
generated by the Hasse derivatives `∂_κ P` with `∑_s κ_s / δ_{b s} ≤ a`. -/
noncomputable def indexIdeal (b : σ → ι) (δ : ι → ℕ) (P : MvPolynomial σ K) (a : ℝ) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span {Q | ∃ κ : σ →₀ ℕ, Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ a ∧
    hasseDeriv κ P = Q}

variable {b : σ → ι} {δ : ι → ℕ} {P : MvPolynomial σ K}

theorem hasseDeriv_mem_indexIdeal {a : ℝ} {κ : σ →₀ ℕ}
    (hκ : Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ a) :
    hasseDeriv κ P ∈ indexIdeal b δ P a :=
  Ideal.subset_span ⟨κ, hκ, rfl⟩

theorem mem_indexIdeal {a : ℝ} (ha : 0 ≤ a) : P ∈ indexIdeal b δ P a := by
  have h := hasseDeriv_mem_indexIdeal (b := b) (δ := δ) (P := P) (κ := 0) (by simpa using ha)
  rwa [hasseDeriv_zero_apply] at h

theorem indexIdeal_mono {a a' : ℝ} (h : a ≤ a') : indexIdeal b δ P a ≤ indexIdeal b δ P a' :=
  Ideal.span_mono fun _ ⟨κ, hκ, hQ⟩ ↦ ⟨κ, hκ.trans h, hQ⟩

/-- A Hasse derivative of a multihomogeneous polynomial is multihomogeneous. -/
theorem isWeightedHomogeneous_hasseDeriv {w : σ → ι → ℕ} {d : ι → ℕ}
    (hP : IsWeightedHomogeneous w P d) (κ : σ →₀ ℕ) :
    IsWeightedHomogeneous w (hasseDeriv κ P) (d - Finsupp.weight w κ) := by
  intro n hn
  rw [hasseDeriv_coeff] at hn
  have h := hP (right_ne_zero_of_mul hn)
  rw [map_add] at h
  rw [← h, add_tsub_cancel_right]

/-- A nonzero Hasse derivative of a multihomogeneous polynomial of multidegree `d` has order at
most `d`. -/
theorem weight_le_of_hasseDeriv_ne_zero {w : σ → ι → ℕ} {d : ι → ℕ}
    (hP : IsWeightedHomogeneous w P d) {κ : σ →₀ ℕ} (h0 : hasseDeriv κ P ≠ 0) :
    Finsupp.weight w κ ≤ d := by
  obtain ⟨n, hn⟩ := exists_coeff_ne_zero h0
  rw [hasseDeriv_coeff] at hn
  have h := hP (right_ne_zero_of_mul hn)
  rw [map_add] at h
  rw [← h]
  exact le_add_self

variable [DecidableEq ι]

theorem isWeightedHomogeneous_indexIdeal (hP : IsWeightedHomogeneous (multiWeight b) P δ)
    (a : ℝ) : (indexIdeal b δ P a).IsWeightedHomogeneous (multiWeight b) :=
  isWeightedHomogeneous_span fun _ ⟨κ, _, hQ⟩ ↦ ⟨_, hQ ▸ isWeightedHomogeneous_hasseDeriv hP κ⟩

/-- **Padding a Hasse derivative to multidegree `δ`.** Moving the exponents of `κ` to one
representative variable `rep i` of each block gives a monomial of the same multidegree as `κ`,
and `∂_κ P · X^{κ moved}` is multihomogeneous of multidegree `δ`. -/
theorem isWeightedHomogeneous_hasseDeriv_mul_monomial {rep : ι → σ} (hrep : ∀ i, b (rep i) = i)
    (hP : IsWeightedHomogeneous (multiWeight b) P δ) (κ : σ →₀ ℕ) :
    IsWeightedHomogeneous (multiWeight b)
      (hasseDeriv κ P * monomial (κ.mapDomain fun s ↦ rep (b s)) 1) δ := by
  by_cases h0 : hasseDeriv κ P = 0
  · rw [h0, zero_mul]
    exact isWeightedHomogeneous_zero _ _ _
  have hw : Finsupp.weight (multiWeight b) (κ.mapDomain fun s ↦ rep (b s)) =
      Finsupp.weight (multiWeight b) κ :=
    weight_mapDomain (AddMonoidHom.id _) (fun s ↦ by simp [multiWeight, hrep]) κ
  have h := (isWeightedHomogeneous_hasseDeriv hP κ).mul
    (isWeightedHomogeneous_monomial (multiWeight b) _ (1 : K) hw)
  rwa [tsub_add_cancel_of_le (weight_le_of_hasseDeriv_ne_zero hP h0)] at h

omit [DecidableEq ι] in
/-- A monomial in variables outside a prime is outside it. -/
theorem monomial_one_notMem {q : Ideal (MvPolynomial σ K)} [q.IsPrime] {j : σ →₀ ℕ}
    (h : ∀ s ∈ j.support, X s ∉ q) : monomial j (1 : K) ∉ q := by
  classical
  rw [monomial_eq, C_1, one_mul, Finsupp.prod]
  intro hmem
  obtain ⟨s, hs, hsq⟩ := Ideal.IsPrime.prod_mem_iff.mp hmem
  exact h s hs (‹q.IsPrime›.mem_of_pow_mem _ hsq)

omit [DecidableEq ι] in
/-- A prime containing a nonzero element has height at least `1`. -/
theorem one_le_height_of_mem {q : Ideal (MvPolynomial σ K)} [q.IsPrime]
    (hP0 : P ≠ 0) (hP : P ∈ q) : 1 ≤ q.height := by
  have hlt : (⊥ : Ideal (MvPolynomial σ K)) < q :=
    bot_lt_iff_ne_bot.mpr fun h ↦ hP0 (by rwa [h, Ideal.mem_bot] at hP)
  have := Ideal.height_add_one_le_of_lt_of_isPrime hlt
  rwa [Ideal.height_bot, zero_add] at this

section Product

variable [Finite σ] {m : ℕ} {b : σ → Fin m} {δ : Fin m → ℕ}

/-- A multihomogeneous prime with `H_𝔭 ≠ 0` has finite height `t` with `t + m ≤ |σ|`: the
codimension is at most the dimension `|σ| - m` of the multiprojective space. -/
theorem exists_height_eq_add_le [CharZero K] (hb : Function.Surjective b)
    (𝔭 : Ideal (MvPolynomial σ K)) [𝔭.IsPrime] (h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔭 ≠ 0) : ∃ t : ℕ, 𝔭.height = t ∧ t + m ≤ Nat.card σ := by
  have h := height_add_trdeg 𝔭
  have htop : 𝔭.height ≠ ⊤ := fun h' ↦ by
    rw [h', top_add] at h
    exact ENat.top_ne_natCast _ h
  obtain ⟨t, ht⟩ := ENat.ne_top_iff_exists.mp htop
  obtain ⟨T, -, -, hTb, hcard, -⟩ :=
    exists_transversal_fin_of_hilbertPoly_ne_zero hb 𝔭 h𝔭 hne ht.symm
  refine ⟨t, ht.symm, ?_⟩
  have hm : #(univ : Finset (Fin m)) ≤ #T :=
    Finset.card_le_card_of_surjOn b fun i _ ↦ by
      obtain ⟨s, hs, hsi⟩ := hTb i
      exact ⟨s, hs, hsi⟩
  rw [Finset.card_univ, Fintype.card_fin] at hm
  omega

/-- **Rémond's product theorem for the zeros of index `a`** (Rémond 2001, Thm. 1.1, geometric
part; Evertse 1995, Thm. 1). Let `P` be multihomogeneous of multidegree `δ`, `δ` decreasing, and
`𝔭` a multihomogeneous prime with `H_𝔭 ≠ 0` and height `t`, a component of both `Z_a(P)` and
`Z_{a+ε}(P)`: a minimal prime of `indexIdeal b δ P a` containing `indexIdeal b δ P (a + ε)`. If
`δ_i / δ_{i+1} > (m/ε)^t`, then `V(𝔭)` is a component of the product of its projections, and the
degree bound of `MvPolynomial.productTheorem` holds: `ε^t d_β(𝔭) ≤ c!/∏ c_i! ≤ m^t` with
`β_i = dim Z_i`. -/
theorem productTheorem_indexIdeal [CharZero K] (hb : Function.Surjective b) (hδ : ∀ i, 0 < δ i)
    (hP : IsWeightedHomogeneous (multiWeight b) P δ) {a ε : ℝ} (hε : 0 < ε)
    {𝔭 : Ideal (MvPolynomial σ K)} [𝔭.IsPrime] (hU : IsUnmixedRing (Localization.AtPrime 𝔭))
    (h𝔭a : 𝔭 ∈ (indexIdeal b δ P a).minimalPrimes) (h𝔭ε : indexIdeal b δ P (a + ε) ≤ 𝔭)
    (hne : hilbertPoly b 𝔭 ≠ 0) {t : ℕ} (ht : 𝔭.height = t) (hanti : Antitone δ)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → (m : ℝ) ^ t < ε ^ t * (δ i / δ j)) :
    𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes ∧
      ∃ β : Fin m →₀ ℕ, (∀ i, (β i : ℕ∞) + 1 = (varMatroid 𝔭).eRk {s | b s = i}) ∧
        1 ≤ multidegree b 𝔭 β ∧
        ε ^ t * multidegree b 𝔭 β ≤
          #(univ.filter fun f : Fin t → Fin m ↦
            β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ∧
        #(univ.filter fun f : Fin t → Fin m ↦
          β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ≤ m ^ t := by
  classical
  have h𝔭 : 𝔭.IsWeightedHomogeneous (multiWeight b) :=
    (isWeightedHomogeneous_indexIdeal hP a).of_mem_minimalPrimes h𝔭a
  -- One variable outside `𝔭` in each block.
  choose rep hrep hrep𝔭 using exists_X_notMem_of_hilbertPoly_ne_zero hb h𝔭 hne
  set R : Set (MvPolynomial σ K) := {Q | ∃ κ : σ →₀ ℕ,
    Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ a ∧
      hasseDeriv κ P * monomial (κ.mapDomain fun s ↦ rep (b s)) 1 = Q}
  set R' : Set (MvPolynomial σ K) := {Q | ∃ κ : σ →₀ ℕ,
    Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ a ∧ hasseDeriv κ P = Q}
  have hRR' : Ideal.span R ≤ Ideal.span R' := Ideal.span_le.mpr fun _ ⟨κ, hκ, hQ⟩ ↦
    hQ ▸ Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨κ, hκ, rfl⟩)
  have hR : ∀ r ∈ R, IsWeightedHomogeneous (multiWeight b) r δ := by
    rintro _ ⟨κ, -, rfl⟩
    exact isWeightedHomogeneous_hasseDeriv_mul_monomial hrep hP κ
  -- `𝔭` stays minimal over the padded generators: the padding monomials are outside `𝔭`.
  have h𝔭R : 𝔭 ∈ (Ideal.span R).minimalPrimes := by
    refine ⟨⟨‹_›, hRR'.trans h𝔭a.1.2⟩, fun q ⟨hq, hRq⟩ hq𝔭 ↦ h𝔭a.2 ⟨hq, ?_⟩ hq𝔭⟩
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨κ, hκ, rfl⟩
    have hmem : hasseDeriv κ P * monomial (κ.mapDomain fun s ↦ rep (b s)) 1 ∈ q :=
      hRq (Ideal.subset_span ⟨κ, hκ, rfl⟩)
    refine (hq.mem_or_mem hmem).resolve_right (monomial_one_notMem fun s hs ↦ ?_)
    obtain ⟨s', -, rfl⟩ := Finset.mem_image.mp (Finsupp.mapDomain_support hs)
    exact fun h ↦ hrep𝔭 _ (hq𝔭 h)
  -- The derivatives of order `≤ ε` of the generators of `Z_a(P)` vanish on `Z_{a+ε}(P)`.
  have hI : ∀ Q ∈ R', ∀ κ : σ →₀ ℕ, Finsupp.weight (fun s ↦ ((δ (b s) : ℝ))⁻¹) κ ≤ ε →
      hasseDeriv κ Q ∈ 𝔭 := by
    rintro _ ⟨μ, hμ, rfl⟩ κ hκ
    rw [hasseDeriv_comp]
    refine nsmul_mem (h𝔭ε (hasseDeriv_mem_indexIdeal ?_)) _
    rw [map_add]
    linarith
  exact productTheorem hb hU hR h𝔭R h𝔭 hne ht hδ hε hRR' hI hanti hratio

/-- **The descent along `Z_0 ⊇ Z_{ε'} ⊇ ⋯`.** A multihomogeneous prime `𝔮` with `H_𝔮 ≠ 0`,
containing `indexIdeal b δ P (k ε')` and of height `≤ k`, contains a multihomogeneous prime `𝔭`
with `H_𝔭 ≠ 0` which, for some `j`, is a minimal prime of `indexIdeal b δ P (j ε')` containing
`indexIdeal b δ P (j ε' + ε')`. -/
theorem exists_minimalPrimes_indexIdeal_le (hb : Function.Surjective b)
    (hP : IsWeightedHomogeneous (multiWeight b) P δ) (hP0 : P ≠ 0) {ε' : ℝ} (hε' : 0 ≤ ε')
    (k : ℕ) (𝔮 : Ideal (MvPolynomial σ K)) [𝔮.IsPrime]
    (h𝔮 : 𝔮.IsWeightedHomogeneous (multiWeight b)) (hne : hilbertPoly b 𝔮 ≠ 0)
    (hk : indexIdeal b δ P (k * ε') ≤ 𝔮) (hht : 𝔮.height ≤ k) :
    ∃ 𝔭 : Ideal (MvPolynomial σ K), 𝔭.IsPrime ∧ 𝔭 ≤ 𝔮 ∧ hilbertPoly b 𝔭 ≠ 0 ∧
      ∃ j : ℕ, 𝔭 ∈ (indexIdeal b δ P (j * ε')).minimalPrimes ∧
        indexIdeal b δ P (j * ε' + ε') ≤ 𝔭 := by
  induction k generalizing 𝔮 with
  | zero =>
    exfalso
    have h1 := one_le_height_of_mem hP0 (hk (mem_indexIdeal (by simp)))
    have := h1.trans hht
    simp at this
  | succ k ih =>
    have hk' : indexIdeal b δ P (k * ε') ≤ 𝔮 :=
      (indexIdeal_mono (by push_cast; nlinarith)).trans hk
    obtain ⟨𝔭, h𝔭min, h𝔭𝔮⟩ := Ideal.exists_minimalPrimes_le hk'
    have := h𝔭min.1.1
    have h𝔭h := (isWeightedHomogeneous_indexIdeal hP _).of_mem_minimalPrimes h𝔭min
    have hne𝔭 := hilbertPoly_ne_zero_of_le hb h𝔭h h𝔮 h𝔭𝔮 hne
    by_cases heq : 𝔭 = 𝔮
    · subst heq
      refine ⟨𝔭, inferInstance, le_rfl, hne𝔭, k, h𝔭min, ?_⟩
      have : (k : ℝ) * ε' + ε' = ((k + 1 : ℕ) : ℝ) * ε' := by push_cast; ring
      rw [this]
      exact hk
    · have h1 := Ideal.height_add_one_le_of_lt_of_isPrime (lt_of_le_of_ne h𝔭𝔮 heq)
      have hht' : 𝔭.height ≤ k := by
        have h2 := h1.trans hht
        rw [Nat.cast_add, Nat.cast_one] at h2
        exact (ENat.add_le_add_iff_right ENat.one_ne_top).mp h2
      obtain ⟨𝔭', h1', h2', h3', j, h4', h5'⟩ := ih 𝔭 h𝔭h hne𝔭 h𝔭min.1.2 hht'
      exact ⟨𝔭', h1', h2'.trans h𝔭𝔮, h3', j, h4', h5'⟩

/-- **The descent of Rémond's Cor. 1.1.** Under the hypotheses of
`MvPolynomial.exists_productTheorem_indexIdeal`, with `ε' = ε / N`, every irreducible subvariety
`V(𝔮)` of `Z_ε(P)` lies in some `V(𝔭)`, `𝔭` containing `P`, of height `t ≥ 1`, a component of both
`Z_{jε'}(P)` and `Z_{jε'+ε'}(P)`, for which the ratio condition of
`MvPolynomial.productTheorem_indexIdeal` holds at `ε'`. -/
theorem exists_component_indexIdeal [CharZero K] (hb : Function.Surjective b)
    (hP : IsWeightedHomogeneous (multiWeight b) P δ) (hP0 : P ≠ 0)
    {N : ℕ} (hN : N + m = Nat.card σ) {ε : ℝ} (hε : 0 < ε)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → max 1 ((m * N / ε) ^ N) < δ i / δ j)
    {𝔮 : Ideal (MvPolynomial σ K)} [𝔮.IsPrime] (h𝔮 : 𝔮.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔮 ≠ 0) (h𝔮ε : indexIdeal b δ P ε ≤ 𝔮) :
    ∃ (𝔭 : Ideal (MvPolynomial σ K)) (_ : 𝔭.IsPrime), 𝔭 ≤ 𝔮 ∧ hilbertPoly b 𝔭 ≠ 0 ∧ P ∈ 𝔭 ∧
      ∃ j : ℕ, 𝔭 ∈ (indexIdeal b δ P (j * (ε / N))).minimalPrimes ∧
        indexIdeal b δ P (j * (ε / N) + ε / N) ≤ 𝔭 ∧ 0 < ε / N ∧
        ∃ t : ℕ, 𝔭.height = t ∧
          ∀ i j : Fin m, (i : ℕ) + 1 = j → (m : ℝ) ^ t < (ε / N) ^ t * (δ i / δ j) := by
  classical
  set ε' : ℝ := ε / N with hε'
  have hε'0 : 0 ≤ ε' := div_nonneg hε.le (Nat.cast_nonneg N)
  -- `W` has height at most `N`, and lies in `Z_{N ε'}(P)`.
  obtain ⟨t𝔮, ht𝔮, ht𝔮N⟩ := exists_height_eq_add_le hb 𝔮 h𝔮 hne
  have hNε : indexIdeal b δ P (N * ε') ≤ 𝔮 := by
    refine (indexIdeal_mono ?_).trans h𝔮ε
    rcases eq_or_ne N 0 with h | h
    · simp [h, hε.le]
    · rw [hε', mul_div_cancel₀ _ (Nat.cast_ne_zero.mpr h)]
  obtain ⟨𝔭, h𝔭p, h𝔭𝔮, hne𝔭, j, h𝔭min, h𝔭next⟩ :=
    exists_minimalPrimes_indexIdeal_le hb hP hP0 hε'0 N 𝔮 h𝔮 hne hNε
      (by rw [ht𝔮]; exact_mod_cast (by omega : t𝔮 ≤ N))
  have h𝔭h := (isWeightedHomogeneous_indexIdeal hP _).of_mem_minimalPrimes h𝔭min
  obtain ⟨t, ht, htN⟩ := exists_height_eq_add_le hb 𝔭 h𝔭h hne𝔭
  have hP𝔭 : P ∈ 𝔭 := h𝔭min.1.2 (mem_indexIdeal (mul_nonneg (Nat.cast_nonneg j) hε'0))
  have ht1 : 1 ≤ t := by
    have := one_le_height_of_mem hP0 hP𝔭
    rw [ht] at this
    exact_mod_cast this
  have hN0 : (0 : ℝ) < N := Nat.cast_pos.mpr (by omega)
  have hε'pos : 0 < ε' := div_pos hε hN0
  refine ⟨𝔭, h𝔭p, h𝔭𝔮, hne𝔭, hP𝔭, j, h𝔭min, h𝔭next, hε'pos, t, ht, ?_⟩
  -- The ratio condition in the form of `MvPolynomial.productTheorem`.
  intro i j hij
  have hr := hratio i j hij
  have hx : (m : ℝ) / ε' = m * N / ε := by
    rw [hε']
    field_simp
  have hxt : ((m : ℝ) / ε') ^ t ≤ max 1 ((m * N / ε) ^ N) := by
    rw [hx]
    rcases le_or_gt 1 ((m : ℝ) * N / ε) with h1 | h1
    · exact (pow_le_pow_right₀ h1 (by omega)).trans (le_max_right _ _)
    · exact (pow_le_one₀ (by positivity) h1.le).trans (le_max_left _ _)
  have hm : (m : ℝ) ^ t = ε' ^ t * ((m : ℝ) / ε') ^ t := by
    rw [div_pow (m : ℝ) ε' t, mul_div_cancel₀ _ (pow_pos hε'pos t).ne']
  rw [hm]
  exact mul_lt_mul_of_pos_left (hxt.trans_lt hr) (pow_pos hε'pos t)

omit [Finite σ] in
/-- `Z ≠ ℙ`: if `P ≠ 0` lies in `𝔭` and `𝔭` is minimal over the ideal of its traces on the
blocks, that ideal is not `⊥`. -/
theorem span_traces_ne_bot {𝔭 : Ideal (MvPolynomial σ K)} (hP0 : P ≠ 0) (hP𝔭 : P ∈ 𝔭)
    (hmin : 𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes) :
    Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}} ≠ ⊥ := fun hbot ↦ by
  rw [hbot] at hmin
  have h𝔭bot : 𝔭 ≤ ⊥ := hmin.2 ⟨Ideal.isPrime_bot, le_rfl⟩ bot_le
  exact hP0 (by simpa using h𝔭bot hP𝔭)

/-- **Rémond's corollary of the product theorem** (Rémond 2001, Cor. 1.1, geometric part;
Evertse 1995, Corollary). Let `P ≠ 0` be multihomogeneous of multidegree `δ`, `δ` decreasing,
`N = |σ| - m` the dimension of the multiprojective space, and suppose
`δ_i / δ_{i+1} > max(1, (m N / ε)^N)`. Then every irreducible subvariety `W = V(𝔮)` of `Z_ε(P)`
(a multihomogeneous prime `𝔮 ⊇ indexIdeal b δ P ε` with `H_𝔮 ≠ 0`) lies in a product
`Z = V(𝔭) ≠ ℙ`, `𝔭 ⊆ 𝔮`, which is a component of the product of its projections, of height `t`,
with `(ε/N)^t d_β(𝔭) ≤ c!/∏ c_i! ≤ m^t` for `β_i = dim Z_i`. -/
theorem exists_productTheorem_indexIdeal [CharZero K] (hb : Function.Surjective b)
    (hδ : ∀ i, 0 < δ i) (hP : IsWeightedHomogeneous (multiWeight b) P δ) (hP0 : P ≠ 0)
    (hCM : ∀ (𝔭 : Ideal (MvPolynomial σ K)) [𝔭.IsPrime], IsUnmixedRing (Localization.AtPrime 𝔭))
    (hanti : Antitone δ) {N : ℕ} (hN : N + m = Nat.card σ) {ε : ℝ} (hε : 0 < ε)
    (hratio : ∀ i j : Fin m, (i : ℕ) + 1 = j → max 1 ((m * N / ε) ^ N) < δ i / δ j)
    {𝔮 : Ideal (MvPolynomial σ K)} [𝔮.IsPrime] (h𝔮 : 𝔮.IsWeightedHomogeneous (multiWeight b))
    (hne : hilbertPoly b 𝔮 ≠ 0) (h𝔮ε : indexIdeal b δ P ε ≤ 𝔮) :
    ∃ (𝔭 : Ideal (MvPolynomial σ K)) (_ : 𝔭.IsPrime), 𝔭 ≤ 𝔮 ∧
      Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}} ≠ ⊥ ∧
      𝔭 ∈ (Ideal.span {f | f ∈ 𝔭 ∧ ∃ i, f ∈ supported K {s | b s = i}}).minimalPrimes ∧
      ∃ t : ℕ, 𝔭.height = t ∧
        ∃ β : Fin m →₀ ℕ, (∀ i, (β i : ℕ∞) + 1 = (varMatroid 𝔭).eRk {s | b s = i}) ∧
          1 ≤ multidegree b 𝔭 β ∧
          (ε / N) ^ t * multidegree b 𝔭 β ≤
            #(univ.filter fun f : Fin t → Fin m ↦
              β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ∧
          #(univ.filter fun f : Fin t → Fin m ↦
            β + ∑ j, Finsupp.single (f j) 1 = bottomType b) ≤ m ^ t := by
  obtain ⟨𝔭, h𝔭p, h𝔭𝔮, hne𝔭, hP𝔭, j, h𝔭min, h𝔭next, hε', t, ht, hratio'⟩ :=
    exists_component_indexIdeal hb hP hP0 hN hε hratio h𝔮 hne h𝔮ε
  obtain ⟨hmin, β, hβ, hpos, hdeg, hcardF⟩ :=
    productTheorem_indexIdeal hb hδ hP hε' (hCM 𝔭) h𝔭min h𝔭next hne𝔭 ht hanti hratio'
  exact ⟨𝔭, h𝔭p, h𝔭𝔮, span_traces_ne_bot hP0 hP𝔭 hmin, hmin, t, ht, β, hβ, hpos, hdeg, hcardF⟩

end Product

end MvPolynomial
