/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Evertse1984.SUnitSums

-- Used only inside proofs.
import ArithmeticHeights.Northcott
import Evertse1984.Normalization
import Mathlib.NumberTheory.Height.NumberField

/-!
# Evertse's Theorem 1: admissible solutions of `x₀ + ⋯ + xₙ = 0`

**Theorem 1** (Evertse 1984, p. 227). Let `c > 0` and `0 ≤ d < 1`. There are only finitely many
points `X ∈ ℙⁿ(K)` with homogeneous coordinates `x_k` that are `S`-integers such that

```text
∏_k ∏_{v ∈ S∞ ∪ S} ‖x_k‖_v ≤ c · H(X) ^ d,    x₀ + ⋯ + xₙ = 0,
```

and no nonempty proper subsum of `x₀ + ⋯ + xₙ` vanishes.

The proof is Evertse's (§3). Normalize `x` by an `S`-unit to algebraic integers with
`‖x‖ ≤ C · H_S(x) ^ (1 / [K : ℚ])` (`Evertse1984.Normalization`), where `H_S(x)` is the product
of `max_k ‖x_k‖_v` over `S∞ ∪ S`; this changes neither side of the admissibility condition. Apply
Theorem 2 to `(x_k)_{k ≠ k₀}`, whose sum is `-x_{k₀}`, with all of `S∞ ∪ S` for `T` and
`ε = [K : ℚ] (1 - d) / 2`. The left side is then the admissibility product and the right side is
at least a constant times `H_S(x) ^ ((1 + d) / 2)`, so `H(X) ^ ((1 - d) / 2)` is bounded, since
`H(X) ≤ H_S(x)`. Northcott's theorem finishes.

## Main results

* `NumberField.exists_forall_admissible_mulHeight_le`: the admissible solutions have bounded
  height.
* `NumberField.finite_setOf_admissible_sum_eq_zero`: **Theorem 1**.
* `evertseTheorem1`: the statement `EvertseTheorem1` holds.

## Implementation notes

The hypothesis `c > 0` of the paper is not needed: for `c ≤ 0` there are no admissible points.

Evertse normalizes with a nonzero `λ ∈ K` that need not be an `S`-unit, and then compares the two
admissibility products through the ideal generated by the coordinates. Normalizing with an
`S`-unit makes that comparison an equality, the `S`-product formula.

## References

J.-H. Evertse, *On sums of `S`-units and linear recurrences*, Compositio Math. **53** (1984),
225–244, Theorem 1 and §3.
-/

@[expose] public section

open IsDedekindDomain Height Module

namespace NumberField

variable {K : Type*} [Field K] [NumberField K] (S : Finset (HeightOneSpectrum (𝓞 K)))

/-- From `C' · H ^ ((1 + d) / 2) ≤ c · H ^ d` with `d < 1`, a bound for `H`. -/
private theorem le_rpow_of_mul_rpow_le {H C' c d : ℝ} (hH : 0 < H) (hC' : 0 < C') (hd1 : d < 1)
    (h : C' * H ^ ((1 + d) / 2) ≤ c * H ^ d) : H ≤ (c / C') ^ (2 / (1 - d)) := by
  have hsplit : H ^ ((1 + d) / 2) = H ^ d * H ^ ((1 - d) / 2) := by
    rw [← Real.rpow_add hH]; ring_nf
  rw [hsplit, mul_comm (H ^ d), ← mul_assoc] at h
  have h' : C' * H ^ ((1 - d) / 2) ≤ c :=
    le_of_mul_le_mul_right h (Real.rpow_pos_of_pos hH d)
  have h'' : H ^ ((1 - d) / 2) ≤ c / C' := by rw [le_div_iff₀ hC']; linarith
  calc H = (H ^ ((1 - d) / 2)) ^ (2 / (1 - d)) := by
        rw [← Real.rpow_mul hH.le, show (1 - d) / 2 * (2 / (1 - d)) = 1 by
          field_simp [(sub_pos.mpr hd1).ne'], Real.rpow_one]
    _ ≤ (c / C') ^ (2 / (1 - d)) :=
        Real.rpow_le_rpow (Real.rpow_nonneg hH.le _) h'' (div_nonneg zero_le_two
          (sub_pos.mpr hd1).le)

/-- **The admissible solutions have bounded height.** For `0 ≤ d < 1` there is `B`
such that every nonzero tuple `x` of `S`-integers with
`∏_k ∏_{v ∈ S∞ ∪ S} ‖x_k‖_v ≤ c · H(x) ^ d`, `∑ x_k = 0` and no vanishing nonempty proper subsum
has `H(x) ≤ B`. -/
theorem exists_forall_admissible_mulHeight_le (ι : Type*) [Fintype ι] {c d : ℝ} (hd0 : 0 ≤ d)
    (hd1 : d < 1) :
    ∃ B, ∀ x : ι → K, x ≠ 0 → (∀ i, x i ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) →
      ∏ i, placeProd S Set.univ (fun v ↦ v (x i)) ≤ c * mulHeight x ^ d →
      ∑ i, x i = 0 → (∀ I : Finset ι, I.Nonempty → I ≠ Finset.univ → ∑ i ∈ I, x i ≠ 0) →
      mulHeight x ≤ B := by
  classical
  rcases isEmpty_or_nonempty ι with hι | ⟨⟨i₀⟩⟩
  · exact ⟨0, fun x hx ↦ absurd (Subsingleton.elim x 0) hx⟩
  set ι' := {i // i ≠ i₀}
  set D : ℝ := ((finrank ℚ K : ℕ) : ℝ) with hD
  have hDpos : 0 < D := Nat.cast_pos.mpr finrank_pos
  set ε : ℝ := D * ((1 - d) / 2) with hεdef
  have hε : 0 < ε := mul_pos hDpos (div_pos (sub_pos.mpr hd1) two_pos)
  obtain ⟨C₂, hC₂, h2⟩ := exists_pos_forall_placeProd_le S ι' hε
  obtain ⟨Cn, hCn, hn⟩ := exists_pos_forall_exists_unit_house_le S ι
  set μ : ℝ := (Fintype.card ι' : ℝ) + 1 with hμ
  have hμ1 : 1 ≤ μ := by rw [hμ]; linarith [(Nat.cast_nonneg (Fintype.card ι') : (0 : ℝ) ≤ _)]
  set κ : ℝ := placeProd S Set.univ (fun _ ↦ μ) with hκdef
  have hκ : 0 < κ := placeProd_pos S _ fun _ _ ↦ zero_lt_one.trans_le hμ1
  set C' : ℝ := C₂ / κ * Cn ^ (-ε) with hC'def
  have hC' : 0 < C' := mul_pos (div_pos hC₂ hκ) (Real.rpow_pos_of_pos hCn _)
  refine ⟨(c / C') ^ (2 / (1 - d)), fun x hx hxS hadm hsum hnv ↦ ?_⟩
  obtain ⟨u, huS, hint, hhouse⟩ := hn x hx hxS
  have hu0 : (u : K) ≠ 0 := Units.ne_zero u
  set y : ι → K := fun i ↦ (u : K) * x i with hy
  set h : ℝ := placeProd S Set.univ (fun v ↦ ⨆ i, v (x i)) with hh
  have hPu := placeProd_univ_eq_one_of_mem_unit S huS
  have hHh : mulHeight x ≤ h := mulHeight_le_placeProd_univ S hx hxS
  have hHpos : 0 < mulHeight x := mulHeight_pos x
  have hhpos : 0 < h := hHpos.trans_le hHh
  -- the admissibility product does not change
  have hPy : ∏ i, placeProd S Set.univ (fun v ↦ v (y i)) =
      ∏ i, placeProd S Set.univ (fun v ↦ v (x i)) := by
    refine Finset.prod_congr rfl fun i _ ↦ ?_
    simp only [hy, map_mul]
    rw [placeProd_mul, hPu, one_mul]
  -- `H_S` does not change
  have hhy : placeProd S Set.univ (fun v ↦ ⨆ i, v (y i)) = h := by
    have : ∀ v : AbsoluteValue K ℝ, ⨆ i, v (y i) = v (u : K) * ⨆ i, v (x i) := fun v ↦ by
      simp only [hy, map_mul]
      exact (Real.mul_iSup_of_nonneg (apply_nonneg _ _) _).symm
    simp only [this]
    rw [placeProd_mul, hPu, one_mul]
  -- the sum of the other coordinates
  have hysum : ∑ i, y i = 0 := by simp only [hy, ← Finset.mul_sum, hsum, mul_zero]
  have hsplit := Fintype.sum_eq_add_sum_subtype_ne y i₀
  rw [hysum] at hsplit
  set z : ι' → K := fun j ↦ y j with hz
  have hzsum : ∑ j, z j = -y i₀ := by rw [hz]; linear_combination -hsplit
  obtain ⟨j₀, hj₀⟩ : ∃ j : ι', z j ≠ 0 := by
    by_contra! hall
    have hy0 : y i₀ = 0 := by rw [← neg_neg (y i₀), ← hzsum, Finset.sum_eq_zero fun j _ ↦ hall j,
      neg_zero]
    refine hx (funext fun i ↦ ?_)
    by_cases hi : i = i₀
    · subst hi; exact (mul_eq_zero.mp hy0).resolve_left hu0
    · exact (mul_eq_zero.mp (hall ⟨i, hi⟩)).resolve_left hu0
  have : Nonempty ι' := ⟨j₀⟩
  have : Nonempty ι := ⟨i₀⟩
  have hzint : ∀ j, IsIntegral ℤ (z j) := fun j ↦ hint j
  have hznv : ∀ I : Finset ι', I.Nonempty → ∑ j ∈ I, z j ≠ 0 := by
    intro I hI
    have hmap : ∑ j ∈ I, z j = (u : K) * ∑ i ∈ I.map (Function.Embedding.subtype _), x i := by
      rw [Finset.sum_map, Finset.mul_sum]; rfl
    rw [hmap]
    refine mul_ne_zero hu0 (hnv _ (hI.map) fun hU ↦ ?_)
    have : i₀ ∈ I.map (Function.Embedding.subtype _) := hU ▸ Finset.mem_univ i₀
    obtain ⟨j, -, hj⟩ := Finset.mem_map.mp this
    exact j.2 hj
  have key := h2 Set.univ z hzint hznv
  -- the right side is the admissibility product
  have hRHS : (∏ j, placeProd S Set.univ (fun v ↦ v (z j))) *
      placeProd S Set.univ (fun v ↦ v (∑ j, z j)) =
      ∏ i, placeProd S Set.univ (fun v ↦ v (y i)) := by
    rw [Fintype.prod_eq_mul_prod_subtype_ne (fun i ↦ placeProd S Set.univ (fun v ↦ v (y i))) i₀,
      hzsum, mul_comm]
    simp only [AbsoluteValue.map_neg]
    rfl
  rw [hRHS, hPy] at key
  -- the house of `z` is at most `Cn · h ^ (1 / D)`
  have hhz : ⨆ j, house (z j) ≤ Cn * h ^ D⁻¹ :=
    ciSup_le fun j ↦ hhouse j
  have hhz1 : 1 ≤ ⨆ j, house (z j) := one_le_iSup_house (hzint j₀) hj₀
  have hA2 : Cn ^ (-ε) * h ^ (-((1 - d) / 2)) ≤ (⨆ j, house (z j)) ^ (-ε) := by
    refine (Real.rpow_le_rpow_of_nonpos (zero_lt_one.trans_le hhz1) hhz
      (neg_nonpos.mpr hε.le)).trans_eq' ?_
    rw [Real.mul_rpow hCn.le (Real.rpow_nonneg hhpos.le _), ← Real.rpow_mul hhpos.le]
    congr 2
    rw [hεdef]; field_simp
  -- `H_S(y) ≤ κ · ∏_v max_j ‖z_j‖_v`
  have hA1 : h / κ ≤ placeProd S Set.univ (fun v ↦ ⨆ j, v (z j)) := by
    rw [div_le_iff₀' hκ, ← hhy, hκdef, ← placeProd_mul]
    refine placeProd_le_placeProd S _ (fun v _ ↦ Real.iSup_nonneg fun i ↦ apply_nonneg _ _)
      fun v _ ↦ ?_
    have hM0 : 0 ≤ ⨆ j, v (z j) := Real.iSup_nonneg fun j ↦ apply_nonneg _ _
    have hMle : ∀ j, v (z j) ≤ ⨆ j, v (z j) :=
      fun j ↦ le_ciSup (f := fun j ↦ v (z j)) (Finite.bddAbove_range _) j
    refine ciSup_le fun i ↦ ?_
    by_cases hi : i = i₀
    · subst hi
      rw [show y i = -∑ j, z j by rw [hzsum, neg_neg], AbsoluteValue.map_neg]
      refine (v.sum_le _ _).trans ?_
      refine (Finset.sum_le_sum fun j _ ↦ hMle j).trans ?_
      rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul, hμ]
      nlinarith
    · exact (hMle ⟨i, hi⟩).trans (le_mul_of_one_le_left hM0 hμ1)
  have hlow : C' * h ^ ((1 + d) / 2) ≤ c * mulHeight x ^ d := by
    refine le_trans ?_ (key.trans hadm)
    have hexp : h ^ ((1 + d) / 2) = h * h ^ (-((1 - d) / 2)) := by
      rw [show (1 + d) / 2 = 1 + -((1 - d) / 2) by ring, Real.rpow_add hhpos, Real.rpow_one]
    calc C' * h ^ ((1 + d) / 2) = C₂ * (h / κ) * (Cn ^ (-ε) * h ^ (-((1 - d) / 2))) := by
          rw [hexp, hC'def]; ring
      _ ≤ C₂ * placeProd S Set.univ (fun v ↦ ⨆ j, v (z j)) * (⨆ j, house (z j)) ^ (-ε) :=
          mul_le_mul (mul_le_mul_of_nonneg_left hA1 hC₂.le) hA2
            (mul_nonneg (Real.rpow_nonneg hCn.le _) (Real.rpow_nonneg hhpos.le _))
            (mul_nonneg hC₂.le (placeProd_nonneg S _ fun v _ ↦
              Real.iSup_nonneg fun j ↦ apply_nonneg _ _))
  refine le_rpow_of_mul_rpow_le hHpos hC' hd1 (le_trans ?_ hlow)
  refine mul_le_mul_of_nonneg_left (Real.rpow_le_rpow hHpos.le hHh ?_) hC'.le
  linarith

/-- **Evertse's Theorem 1.** For `0 ≤ d < 1` only finitely many points `X ∈ ℙⁿ(K)`
have homogeneous coordinates that are `S`-integers with
`∏_k ∏_{v ∈ S∞ ∪ S} ‖x_k‖_v ≤ c · H(X) ^ d`, `x₀ + ⋯ + xₙ = 0` and no vanishing nonempty proper
subsum. -/
theorem finite_setOf_admissible_sum_eq_zero (ι : Type*) [Fintype ι] {c d : ℝ} (hd0 : 0 ≤ d)
    (hd1 : d < 1) :
    {X : Projectivization K (ι → K) | ∃ (x : ι → K) (hx : x ≠ 0), Projectivization.mk K x hx = X ∧
      (∀ i, x i ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) ∧
      ∏ i, placeProd S Set.univ (fun v ↦ v (x i)) ≤ c * mulHeight x ^ d ∧
      ∑ i, x i = 0 ∧ ∀ I : Finset ι, I.Nonempty → I ≠ Finset.univ → ∑ i ∈ I, x i ≠ 0}.Finite := by
  obtain ⟨B, hB⟩ := exists_forall_admissible_mulHeight_le S ι hd0 hd1
  refine (Projectivization.finite_setOfPred_mulHeight_le B).subset ?_
  rintro _ ⟨x, hx, rfl, hxS, hadm, hsum, hnv⟩
  rw [Set.mem_ofPred_eq, Projectivization.mulHeight_mk]
  exact hB x hx hxS hadm hsum hnv

end NumberField

/-- **Evertse's Theorem 1 holds.** -/
theorem evertseTheorem1 : EvertseTheorem1 :=
  fun _ _ _ ι _ S _ _ _ hd0 hd1 ↦ NumberField.finite_setOf_admissible_sum_eq_zero S ι hd0 hd1
