/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Evertse1984.ShiftedValues
public import Mathlib.Algebra.Polynomial.Splits

-- Used only inside proofs.
import DiophantineApproximation.DecomposableForm
import DiophantineApproximation.NormForm
import DiophantineApproximation.SIntegerSquares
import DiophantineApproximation.UnitEquation
import Evertse1984.Normalization

/-!
# Evertse's Lemma 2 for polynomials that split over `K`

**Lemma 2** (Evertse 1984, p. 236). Let `f, g ∈ K[X]` have degrees `m`, `n`, such that for no
integer `h ≠ 0` one of `f(X + h)`, `g(X)` divides the other. Let `β > 0` and
`0 ≤ γ < 1 / (m + n + 2)`. Then only finitely many pairs of integers `(r, s)` satisfy
`0 < |r - s| ≤ β |r| ^ γ` with `f(r) / g(s)` an `S`-unit.

Here `f` and `g` are assumed to split over `K`; Evertse reduces to that case by a finite extension
(the zeros of `f`, `g` lying in `K` is "no restriction"). The proof is Evertse's, with the ideals
replaced by places.

1. *The gcd bound.* Write `f(r) = A ∏_a (r - a)`, `g(s) = B ∏_b (s - b)` over the roots. The
   product `Q = ∏_{a, b} ((r - a) - (s - b))` lies in the ideal of the `S`-integers generated by
   `F = ∏_a (r - a)` and `G = ∏_b (s - b)` (`NumberField.exists_prod_product_sub_eq`). When
   `f(r) / g(s)` is an `S`-unit, `F / G` is one too, so `Q / F` is an `S`-integer, and
   `∏_{S∞ ∪ S} ‖F‖ ≤ ∏_{S∞ ∪ S} ‖Q‖ ≤ C |r - s| ^ (D m n)`, each factor `r - s - (a - b)` of `Q`
   having height `O(|r - s| ^ D)` — provided no `a - b` equals `r - s`. The smallest factor of
   `F` then has `∏_{S∞ ∪ S} ‖r - a‖ ≤ C |r - s| ^ (D n)`, and likewise for `G`: these are the
   hypotheses of `NumberField.finite_setOf_shifted_core`.
2. *The exceptional differences.* If `r - s = h` is one of the finitely many integers `a - b`,
   divide out `k = gcd(f(X), g(X - h))`: then `f(r) / g(s) = f₀(r) / g₀(s)` with
   `f₀ = f / k` and `g₀ = g / k(X + h)`, neither constant by the divisibility hypothesis, and `h`
   is no longer a difference of roots of `f₀` and `g₀`. Step 1 applies to them.

## Main results

* `NumberField.exists_prod_product_sub_eq`: the ideal membership of step 1.
* `NumberField.exists_forall_exists_roots_placeProd_le`: step 1.
* `NumberField.finite_setOf_eval_div_eval_mem_unit_of_splits`: **Lemma 2**, for split `f`, `g`.

## References

J.-H. Evertse, *On sums of `S`-units and linear recurrences*, Compositio Math. **53** (1984),
225–244, Lemma 2.
-/

@[expose] public section

open IsDedekindDomain Height Module Polynomial

namespace NumberField

section Ideal

variable {R σ : Type*} [CommRing R] [SetLike σ R] [SubringClass σ R] (A : σ)

/-- `∏_{y} (x - y) = γ x + δ ∏_y y` with `γ`, `δ` in any subring containing `x` and the `y`. -/
theorem exists_prod_map_sub_eq {x : R} (hx : x ∈ A) (ys : Multiset R) (hys : ∀ y ∈ ys, y ∈ A) :
    ∃ γ ∈ A, ∃ δ ∈ A, (ys.map (x - ·)).prod = γ * x + δ * ys.prod := by
  induction ys using Multiset.induction_on with
  | empty => exact ⟨0, zero_mem _, 1, one_mem _, by simp⟩
  | cons y ys ih =>
    obtain ⟨γ, hγ, δ, hδ, h⟩ := ih fun z hz ↦ hys z (Multiset.mem_cons_of_mem hz)
    have hy := hys y (Multiset.mem_cons_self y ys)
    refine ⟨(x - y) * γ + δ * ys.prod, add_mem (mul_mem (sub_mem hx hy) hγ)
      (mul_mem hδ (multiset_prod_mem _ fun z hz ↦ hys z (Multiset.mem_cons_of_mem hz))),
      -δ, neg_mem hδ, ?_⟩
    rw [Multiset.map_cons, Multiset.prod_cons, Multiset.prod_cons, h]
    ring

/-- **The ideal membership behind the gcd bound**: `∏_{x, y} (x - y)` lies in the ideal generated
by `∏_x x` and `∏_y y`, with coefficients in any subring containing all the `x` and `y`. -/
theorem exists_prod_product_sub_eq (xs ys : Multiset R) (hxs : ∀ x ∈ xs, x ∈ A)
    (hys : ∀ y ∈ ys, y ∈ A) :
    ∃ α ∈ A, ∃ β ∈ A,
      ((xs ×ˢ ys).map fun p ↦ p.1 - p.2).prod = α * xs.prod + β * ys.prod := by
  induction xs using Multiset.induction_on with
  | empty => exact ⟨1, one_mem _, 0, zero_mem _, by simp⟩
  | cons x xs ih =>
    obtain ⟨α, hα, β, hβ, h⟩ := ih fun z hz ↦ hxs z (Multiset.mem_cons_of_mem hz)
    have hx := hxs x (Multiset.mem_cons_self x xs)
    obtain ⟨γ, hγ, δ, hδ, h'⟩ := exists_prod_map_sub_eq A hx ys hys
    have hY : ys.prod ∈ A := multiset_prod_mem _ hys
    have hX : xs.prod ∈ A := multiset_prod_mem _ fun z hz ↦ hxs z (Multiset.mem_cons_of_mem hz)
    refine ⟨γ * α, mul_mem hγ hα, γ * x * β + δ * (α * xs.prod + β * ys.prod),
      add_mem (mul_mem (mul_mem hγ hx) hβ) (mul_mem hδ (add_mem (mul_mem hα hX)
        (mul_mem hβ hY))), ?_⟩
    rw [Multiset.cons_product, Multiset.map_add, Multiset.prod_add, Multiset.map_map, h,
      Multiset.prod_cons]
    have : (Multiset.map ((fun p : R × R ↦ p.1 - p.2) ∘ Prod.mk x) ys).prod =
        (ys.map (x - ·)).prod := rfl
    rw [this, h']
    ring

end Ideal

variable {K : Type*} [Field K] [NumberField K] (S : Finset (HeightOneSpectrum (𝓞 K)))

/-- **The product formula for a nonzero `S`-integer**: its sizes at the places of `S∞ ∪ S`
multiply to at least `1`. -/
theorem one_le_placeProd_univ_of_mem_integer {x : K}
    (hx : x ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) (hx0 : x ≠ 0) :
    1 ≤ placeProd S Set.univ (fun v ↦ v x) := by
  have h := mulHeight_le_placeProd_univ S (x := fun _ : Unit ↦ x) (fun h ↦ hx0 (congrFun h ()))
    fun _ ↦ hx
  rw [mulHeight_eq_one_of_subsingleton] at h
  simpa using h

/-- The product over the places is multiplicative on a multiset product. -/
theorem placeProd_multiset_prod (T : Set (AbsoluteValue K ℝ)) (xs : Multiset K) :
    placeProd S T (fun v ↦ v xs.prod) = (xs.map fun x ↦ placeProd S T (fun v ↦ v x)).prod := by
  induction xs using Multiset.induction_on with
  | empty => simp [placeProd]
  | cons x xs ih =>
    simp only [Multiset.prod_cons, map_mul, Multiset.map_cons]
    rw [placeProd_mul, ih]

private theorem pow_mul_rearrange (x y : ℝ) (D m n : ℕ) :
    (x * y ^ D) ^ (m * n) = (x ^ n * y ^ (D * n)) ^ m := by
  simp only [mul_pow, ← pow_mul]
  ring_nf

open scoped Classical in
/-- **Step 1 of Lemma 2: the gcd bound.** For `f`, `g` splitting over `K` with `S`-unit leading
coefficients and `S`-integral roots, there is `c` such that whenever `r ≠ s`, `f(r) / g(s)` is an
`S`-unit and `r - s` is not a difference `a - b` of roots, some roots `a` of `f` and `b` of `g`
have `∏_{S∞ ∪ S} ‖r - a‖ ≤ c |r - s| ^ (D deg g)` and `∏_{S∞ ∪ S} ‖s - b‖ ≤ c |r - s| ^ (D deg f)`.
-/
theorem exists_forall_exists_roots_placeProd_le {f g : K[X]} (hf : f.Splits) (hg : g.Splits)
    (hf0 : 0 < f.natDegree) (hg0 : 0 < g.natDegree)
    (hlf : ∃ u : Kˣ, u ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧ (u : K) = f.leadingCoeff)
    (hlg : ∃ u : Kˣ, u ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧ (u : K) = g.leadingCoeff)
    (hrf : ∀ a ∈ f.roots, a ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K)
    (hrg : ∀ b ∈ g.roots, b ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K) :
    ∃ c ≥ 0, ∀ r s : ℤ, r ≠ s →
      (∃ u : Kˣ, u ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
        (u : K) = f.eval (r : K) / g.eval (s : K)) →
      (∀ a ∈ f.roots, ∀ b ∈ g.roots, (r : K) - s ≠ a - b) →
      ∃ a ∈ f.roots, ∃ b ∈ g.roots,
        placeProd S Set.univ (fun v ↦ v ((r : K) - a)) ≤
          c * |(r : ℝ) - s| ^ (finrank ℚ K * g.natDegree) ∧
        placeProd S Set.univ (fun v ↦ v ((s : K) - b)) ≤
          c * |(r : ℝ) - s| ^ (finrank ℚ K * f.natDegree) := by
  obtain ⟨uf, huf, hufe⟩ := hlf
  obtain ⟨ug, hug, huge⟩ := hlg
  set m := f.natDegree with hm
  set n := g.natDegree with hn
  have hcf : Multiset.card f.roots = m := hf.natDegree_eq_card_roots.symm
  have hcg : Multiset.card g.roots = n := hg.natDegree_eq_card_roots.symm
  obtain ⟨Hs, hHs0, hHs⟩ : ∃ Hs : ℝ, 0 ≤ Hs ∧
      ∀ a ∈ f.roots, ∀ b ∈ g.roots, mulHeight₁ (a - b) ≤ Hs := by
    obtain ⟨B, hB⟩ := ((f.roots ×ˢ g.roots).toFinset.finite_toSet.image
      fun p : K × K ↦ mulHeight₁ (p.1 - p.2)).bddAbove
    refine ⟨max B 0, le_max_right _ _, fun a ha b hb ↦ le_max_of_le_left (hB ⟨(a, b), ?_, rfl⟩)⟩
    exact Finset.mem_coe.mpr (Multiset.mem_toFinset.mpr (Multiset.mem_product.mpr ⟨ha, hb⟩))
  set C₁ : ℝ := 2 ^ totalWeight K * (Hs + 1) with hC₁def
  have hC₁ : 1 ≤ C₁ := one_le_mul_of_one_le_of_one_le (one_le_pow₀ one_le_two) (by linarith)
  refine ⟨C₁ ^ (m + n), by positivity, fun r s hrs ⟨u, hu, hue⟩ hdiff ↦ ?_⟩
  set τ := |(r : ℝ) - s| with hτ
  have hτ1 : 1 ≤ τ := by
    have := Int.one_le_abs (sub_ne_zero.mpr hrs)
    rw [hτ]; exact_mod_cast this
  set xs := f.roots.map fun a ↦ (r : K) - a with hxs
  set ys := g.roots.map fun b ↦ (s : K) - b with hys
  have hfr : f.eval (r : K) = f.leadingCoeff * xs.prod := hf.eval_eq_prod_roots _
  have hgs : g.eval (s : K) = g.leadingCoeff * ys.prod := hg.eval_eq_prod_roots _
  have hu0 := Units.ne_zero u
  have hfr0 : f.eval (r : K) ≠ 0 := fun h ↦ hu0 (by rw [hue, h, zero_div])
  have hgs0 : g.eval (s : K) ≠ 0 := fun h ↦ hu0 (by rw [hue, h, div_zero])
  have hlf0 : f.leadingCoeff ≠ 0 := by rw [← hufe]; exact Units.ne_zero _
  have hlg0 : g.leadingCoeff ≠ 0 := by rw [← huge]; exact Units.ne_zero _
  have hF0 : xs.prod ≠ 0 := fun h ↦ hfr0 (by rw [hfr, h, mul_zero])
  have hG0 : ys.prod ≠ 0 := fun h ↦ hgs0 (by rw [hgs, h, mul_zero])
  have hSint : ∀ z : ℤ, (z : K) ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K :=
    fun z ↦ intCast_mem _ _
  have hxsS : ∀ x ∈ xs, x ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K := by
    intro x hx
    obtain ⟨a, ha, rfl⟩ := Multiset.mem_map.mp hx
    exact sub_mem (hSint r) (hrf a ha)
  have hysS : ∀ y ∈ ys, y ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K := by
    intro y hy
    obtain ⟨b, hb, rfl⟩ := Multiset.mem_map.mp hy
    exact sub_mem (hSint s) (hrg b hb)
  -- the product `Q` and its ideal membership
  set Q := ((xs ×ˢ ys).map fun p ↦ p.1 - p.2).prod with hQ
  obtain ⟨α, hα, β, hβ, hQeq⟩ :=
    exists_prod_product_sub_eq ((S : Set (HeightOneSpectrum (𝓞 K))).integer K) xs ys hxsS hysS
  have hmemxy : ∀ p ∈ xs ×ˢ ys, ∃ a ∈ f.roots, ∃ b ∈ g.roots,
      p.1 - p.2 = ((r - s : ℤ) : K) + -(a - b) := by
    intro p hp
    obtain ⟨hp1, hp2⟩ := Multiset.mem_product.mp hp
    obtain ⟨a, ha, h1⟩ := Multiset.mem_map.mp hp1
    obtain ⟨b, hb, h2⟩ := Multiset.mem_map.mp hp2
    exact ⟨a, ha, b, hb, by rw [← h1, ← h2]; push_cast; ring⟩
  have hQ0 : Q ≠ 0 := by
    rw [hQ]
    refine Multiset.prod_ne_zero fun h0 ↦ ?_
    obtain ⟨p, hp, hp0⟩ := Multiset.mem_map.mp h0
    obtain ⟨a, ha, b, hb, hpe⟩ := hmemxy p hp
    rw [hpe] at hp0
    exact hdiff a ha b hb (by push_cast at hp0; linear_combination hp0)
  -- `G / F` and `F / G` are `S`-integers
  have hGF : ys.prod / xs.prod ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K := by
    have hmem : uf * u⁻¹ * ug⁻¹ ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K :=
      mul_mem (mul_mem huf (inv_mem hu)) (inv_mem hug)
    convert Set.mem_integer_of_mem_unit hmem using 1
    simp only [Units.val_mul, Units.val_inv_eq_inv_val, hufe, huge, hue, hfr, hgs]
    field_simp
  have hFG : xs.prod / ys.prod ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K := by
    have hmem : u * ug * uf⁻¹ ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K :=
      mul_mem (mul_mem hu hug) (inv_mem huf)
    convert Set.mem_integer_of_mem_unit hmem using 1
    simp only [Units.val_mul, Units.val_inv_eq_inv_val, hufe, huge, hue, hfr, hgs]
    field_simp
  have hQF : Q / xs.prod ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K := by
    rw [show Q = α * xs.prod + β * ys.prod from hQeq, add_div, mul_div_cancel_right₀ _ hF0,
      mul_div_assoc]
    exact add_mem hα (mul_mem hβ hGF)
  have hQG : Q / ys.prod ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K := by
    rw [show Q = α * xs.prod + β * ys.prod from hQeq, add_div, mul_div_cancel_right₀ _ hG0,
      mul_div_assoc]
    exact add_mem (mul_mem hα hFG) hβ
  have hle_Q : ∀ {X : K}, X ≠ 0 → Q / X ∈ (S : Set (HeightOneSpectrum (𝓞 K))).integer K →
      placeProd S Set.univ (fun v ↦ v X) ≤ placeProd S Set.univ (fun v ↦ v Q) := by
    intro X hX hQX
    have h1 := one_le_placeProd_univ_of_mem_integer S hQX (div_ne_zero hQ0 hX)
    have hsplit : placeProd S Set.univ (fun v ↦ v Q) =
        placeProd S Set.univ (fun v ↦ v (Q / X)) * placeProd S Set.univ (fun v ↦ v X) := by
      rw [← placeProd_mul]
      refine placeProd_congr S _ fun v _ ↦ ?_
      rw [← map_mul, div_mul_cancel₀ _ hX]
    rw [hsplit]
    exact le_mul_of_one_le_left (placeProd_nonneg S _ fun v _ ↦ apply_nonneg _ _) h1
  -- the size of `Q`
  have hz : ∀ p ∈ xs ×ˢ ys, placeProd S Set.univ (fun v ↦ v (p.1 - p.2)) ≤
      C₁ * τ ^ finrank ℚ K := by
    intro p hp
    obtain ⟨a, ha, b, hb, hpe⟩ := hmemxy p hp
    rw [hpe]
    refine (placeProd_le_mulHeight₁ S _ _).trans ((mulHeight₁_add_le _ _).trans ?_)
    have ht : ((r - s : ℤ) : ℝ) = (r : ℝ) - s := by push_cast; rfl
    rw [mulHeight₁_intCast, mulHeight₁_neg, ht, ← hτ, max_eq_left hτ1, hC₁def]
    have h2 : (0 : ℝ) < 2 ^ totalWeight K := by positivity
    have hτD : 0 ≤ τ ^ finrank ℚ K := by positivity
    have hab : mulHeight₁ (a - b) ≤ Hs + 1 := by linarith [hHs a ha b hb]
    nlinarith [mul_le_mul_of_nonneg_left hab (mul_nonneg h2.le hτD)]
  have hQle : placeProd S Set.univ (fun v ↦ v Q) ≤ (C₁ * τ ^ finrank ℚ K) ^ (m * n) := by
    rw [hQ, placeProd_multiset_prod, Multiset.map_map]
    have hcard : Multiset.card ((xs ×ˢ ys).map fun p ↦ p.1 - p.2) = m * n := by
      rw [Multiset.card_map, Multiset.card_product, hxs, hys, Multiset.card_map,
        Multiset.card_map, hcf, hcg]
    calc _ ≤ (((xs ×ˢ ys).map fun p ↦ p.1 - p.2).map fun _ ↦ C₁ * τ ^ finrank ℚ K).prod := by
          rw [Multiset.map_map]
          exact Multiset.prod_map_le_prod_map₀ _ _
            (fun p _ ↦ placeProd_nonneg S _ fun v _ ↦ apply_nonneg _ _) fun p hp ↦ hz p hp
      _ = (C₁ * τ ^ finrank ℚ K) ^ (m * n) := by
          rw [Multiset.map_const', Multiset.prod_replicate, hcard]
  -- the smallest factors
  have hτD0 : 0 ≤ τ := by positivity
  obtain ⟨a, ha, hamin⟩ := f.roots.toFinset.exists_min_image
    (fun a ↦ placeProd S Set.univ (fun v ↦ v ((r : K) - a)))
    (Multiset.toFinset_nonempty.mpr (Multiset.card_pos.mp (hcf ▸ hf0)))
  obtain ⟨b, hb, hbmin⟩ := g.roots.toFinset.exists_min_image
    (fun b ↦ placeProd S Set.univ (fun v ↦ v ((s : K) - b)))
    (Multiset.toFinset_nonempty.mpr (Multiset.card_pos.mp (hcg ▸ hg0)))
  rw [Multiset.mem_toFinset] at ha hb
  refine ⟨a, ha, b, hb, ?_, ?_⟩
  · have hpow : placeProd S Set.univ (fun v ↦ v ((r : K) - a)) ^ m ≤
        placeProd S Set.univ (fun v ↦ v xs.prod) := by
      rw [placeProd_multiset_prod, hxs, Multiset.map_map, ← hcf, ← Multiset.prod_replicate,
        ← Multiset.map_const']
      exact Multiset.prod_map_le_prod_map₀ _ _
        (fun _ _ ↦ placeProd_nonneg S _ fun v _ ↦ apply_nonneg _ _)
        fun a' ha' ↦ hamin a' (Multiset.mem_toFinset.mpr ha')
    have hbound := hpow.trans ((hle_Q hF0 hQF).trans hQle)
    rw [pow_mul_rearrange] at hbound
    have hle := (pow_le_pow_iff_left₀ (placeProd_nonneg S _ fun v _ ↦ apply_nonneg _ _)
      (by positivity) hf0.ne').mp hbound
    refine hle.trans (mul_le_mul_of_nonneg_right ?_ (by positivity))
    exact pow_le_pow_right₀ hC₁ (Nat.le_add_left n m)
  · have hpow : placeProd S Set.univ (fun v ↦ v ((s : K) - b)) ^ n ≤
        placeProd S Set.univ (fun v ↦ v ys.prod) := by
      rw [placeProd_multiset_prod, hys, Multiset.map_map, ← hcg, ← Multiset.prod_replicate,
        ← Multiset.map_const']
      exact Multiset.prod_map_le_prod_map₀ _ _
        (fun _ _ ↦ placeProd_nonneg S _ fun v _ ↦ apply_nonneg _ _)
        fun b' hb' ↦ hbmin b' (Multiset.mem_toFinset.mpr hb')
    have hbound := hpow.trans ((hle_Q hG0 hQG).trans hQle)
    rw [Nat.mul_comm m n, pow_mul_rearrange] at hbound
    have hle := (pow_le_pow_iff_left₀ (placeProd_nonneg S _ fun v _ ↦ apply_nonneg _ _)
      (by positivity) hg0.ne').mp hbound
    refine hle.trans (mul_le_mul_of_nonneg_right ?_ (by positivity))
    exact pow_le_pow_right₀ hC₁ (Nat.le_add_right m n)

omit [NumberField K] in
/-- Composing with a shift and back. -/
theorem comp_X_sub_C_comp_X_add_C (p : K[X]) (h : K) :
    (p.comp (X - C h)).comp (X + C h) = p := by
  rw [comp_assoc]; simp

omit [NumberField K] in
/-- Composing with a shift and back. -/
theorem comp_X_add_C_comp_X_sub_C (p : K[X]) (h : K) :
    (p.comp (X + C h)).comp (X - C h) = p := by
  rw [comp_assoc]; simp

omit [NumberField K] in
/-- Divisibility is preserved by composition on the right. -/
theorem comp_dvd_comp {p q : K[X]} (hpq : p ∣ q) (r : K[X]) : p.comp r ∣ q.comp r := by
  obtain ⟨t, rfl⟩ := hpq
  exact ⟨t.comp r, mul_comp _ _ _⟩

open scoped Classical in
/-- **Lemma 2 away from the exceptional differences.** For `f`, `g` splitting over `K` and not
constant, and `γ (deg f + deg g + 2) < 1`, only finitely many pairs of integers `(r, s)` with
`0 < |r - s| ≤ β |r| ^ γ` and `f(r) / g(s)` an `S`-unit have `r - s` different from every
difference `a - b` of a root of `f` and a root of `g`. -/
theorem finite_setOf_eval_div_eval_mem_unit_of_forall_ne {f g : K[X]} (hf : f.Splits)
    (hg : g.Splits) (hf0 : 0 < f.natDegree) (hg0 : 0 < g.natDegree) {β γ : ℝ} (hβ : 0 < β)
    (hγ0 : 0 ≤ γ) (hγ : γ * (f.natDegree + g.natDegree + 2) < 1) :
    {p : ℤ × ℤ | p.1 ≠ p.2 ∧ |(p.1 : ℝ) - p.2| ≤ β * |(p.1 : ℝ)| ^ γ ∧
      (∃ u : Kˣ, u ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
        (u : K) = f.eval (p.1 : K) / g.eval (p.2 : K)) ∧
      ∀ a ∈ f.roots, ∀ b ∈ g.roots, (p.1 : K) - p.2 ≠ a - b}.Finite := by
  have hfne : f ≠ 0 := fun h ↦ by simp [h] at hf0
  have hgne : g ≠ 0 := fun h ↦ by simp [h] at hg0
  -- enlarge `S`
  obtain ⟨Tf, hTf⟩ := exists_finset_mem_unit (Units.mk0 _ (leadingCoeff_ne_zero.mpr hfne))
  obtain ⟨Tg, hTg⟩ := exists_finset_mem_unit (Units.mk0 _ (leadingCoeff_ne_zero.mpr hgne))
  obtain ⟨Tr, -, hTr'⟩ := exists_finset_forall_mem_integer S
    (fun x : (f.roots + g.roots).toFinset ↦ (x : K))
  have hTr : ∀ x ∈ f.roots + g.roots, x ∈ (Tr : Set (HeightOneSpectrum (𝓞 K))).integer K :=
    fun x hx ↦ hTr' ⟨x, Multiset.mem_toFinset.mpr hx⟩
  set S' := S ∪ Tf ∪ Tg ∪ Tr with hS'
  have hsub : ∀ T : Finset (HeightOneSpectrum (𝓞 K)), T ⊆ S' →
      (T : Set (HeightOneSpectrum (𝓞 K))) ⊆ S' := fun T hT ↦ by exact_mod_cast hT
  have hSS' : (S : Set (HeightOneSpectrum (𝓞 K))) ⊆ S' := hsub S (by
    intro x hx; simp [hS', hx])
  obtain ⟨c, hc, hcx⟩ := exists_forall_exists_roots_placeProd_le S' hf hg hf0 hg0
    ⟨_, mem_unit_of_subset (hsub Tf (by intro x hx; simp [hS', hx])) hTf, rfl⟩
    ⟨_, mem_unit_of_subset (hsub Tg (by intro x hx; simp [hS', hx])) hTg, rfl⟩
    (fun a ha ↦ mem_integer_of_subset (hsub Tr (by intro x hx; simp [hS', hx]))
      (hTr a (Multiset.mem_add.mpr (Or.inl ha))))
    (fun b hb ↦ mem_integer_of_subset (hsub Tr (by intro x hx; simp [hS', hx]))
      (hTr b (Multiset.mem_add.mpr (Or.inr hb))))
  have hcore : ∀ a ∈ f.roots.toFinset, ∀ b ∈ g.roots.toFinset,
      {p : ℤ × ℤ | p.1 ≠ p.2 ∧ |(p.1 : ℝ) - p.2| ≤ β * |(p.1 : ℝ)| ^ γ ∧
        (p.1 : K) - p.2 ≠ a - b ∧ (p.1 : K) ≠ a ∧ (p.2 : K) ≠ b ∧
        placeProd S' Set.univ (fun v ↦ v ((p.1 : K) - a)) ≤
          c * |(p.1 : ℝ) - p.2| ^ (finrank ℚ K * g.natDegree) ∧
        placeProd S' Set.univ (fun v ↦ v ((p.2 : K) - b)) ≤
          c * |(p.1 : ℝ) - p.2| ^ (finrank ℚ K * f.natDegree)}.Finite := by
    intro a ha b hb
    rw [Multiset.mem_toFinset] at ha hb
    exact finite_setOf_shifted_core S'
      (mem_integer_of_subset (hsub Tr (by intro x hx; simp [hS', hx]))
        (hTr a (Multiset.mem_add.mpr (Or.inl ha))))
      (mem_integer_of_subset (hsub Tr (by intro x hx; simp [hS', hx]))
        (hTr b (Multiset.mem_add.mpr (Or.inr hb)))) f.natDegree g.natDegree hc hβ hγ0 hγ
  refine (Set.Finite.biUnion f.roots.toFinset.finite_toSet fun a ha ↦
    Set.Finite.biUnion g.roots.toFinset.finite_toSet fun b hb ↦ hcore a ha b hb).subset ?_
  rintro p ⟨hne, hbd, ⟨u, hu, hue⟩, hdiff⟩
  have hu0 := Units.ne_zero u
  have hfr0 : f.eval (p.1 : K) ≠ 0 := fun h ↦ hu0 (by rw [hue, h, zero_div])
  have hgs0 : g.eval (p.2 : K) ≠ 0 := fun h ↦ hu0 (by rw [hue, h, div_zero])
  obtain ⟨a, ha, b, hb, h1, h2⟩ := hcx p.1 p.2 hne ⟨u, mem_unit_of_subset hSS' hu, hue⟩ hdiff
  simp only [Set.mem_iUnion]
  refine ⟨a, Multiset.mem_toFinset.mpr ha, b, Multiset.mem_toFinset.mpr hb, hne, hbd,
    hdiff a ha b hb, fun h ↦ hfr0 ?_, fun h ↦ hgs0 ?_, h1, h2⟩
  · rw [h]; exact (mem_roots hfne).mp ha
  · rw [h]; exact (mem_roots hgne).mp hb

omit [NumberField K] in
/-- A nonzero constant divides everything. -/
private theorem C_dvd_of_natDegree_eq_zero {p : K[X]} (hp : p ≠ 0) (h0 : p.natDegree = 0)
    (q : K[X]) : p ∣ q := by
  rw [eq_C_of_natDegree_eq_zero h0]
  refine (isUnit_C.mpr (Ne.isUnit fun hc ↦ hp ?_)).dvd
  rw [eq_C_of_natDegree_eq_zero h0, hc, C_0]

open scoped Classical in
/-- **Evertse's Lemma 2**, for polynomials that split over `K`. Let `f`, `g` split over `K`, and
suppose that for no integer `h ≠ 0` one of `f(X + h)`, `g(X)` divides the other. For `β > 0` and
`0 ≤ γ < 1 / (deg f + deg g + 2)`, only finitely many pairs of integers `(r, s)` satisfy
`0 < |r - s| ≤ β |r| ^ γ` with `f(r) / g(s)` an `S`-unit. -/
theorem finite_setOf_eval_div_eval_mem_unit_of_splits {f g : K[X]} (hf : f.Splits) (hg : g.Splits)
    (hfg : ∀ h : ℤ, h ≠ 0 → ¬ f.comp (X + C (h : K)) ∣ g ∧ ¬ g ∣ f.comp (X + C (h : K)))
    {β γ : ℝ} (hβ : 0 < β) (hγ0 : 0 ≤ γ) (hγ : γ < 1 / (f.natDegree + g.natDegree + 2)) :
    {p : ℤ × ℤ | p.1 ≠ p.2 ∧ |(p.1 : ℝ) - p.2| ≤ β * |(p.1 : ℝ)| ^ γ ∧
      ∃ u : Kˣ, u ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
        (u : K) = f.eval (p.1 : K) / g.eval (p.2 : K)}.Finite := by
  have hγ' : γ * (f.natDegree + g.natDegree + 2) < 1 := by
    rwa [lt_div_iff₀ (by positivity)] at hγ
  obtain ⟨hf1, hg1⟩ := hfg 1 one_ne_zero
  have hfne : f ≠ 0 := fun h ↦ hg1 (by rw [h, zero_comp]; exact dvd_zero g)
  have hgne : g ≠ 0 := fun h ↦ hf1 (by rw [h]; exact dvd_zero _)
  have hf0 : 0 < f.natDegree := by
    refine Nat.pos_of_ne_zero fun h0 ↦ hf1 ?_
    rw [eq_C_of_natDegree_eq_zero h0, C_comp, ← eq_C_of_natDegree_eq_zero h0]
    exact C_dvd_of_natDegree_eq_zero hfne h0 g
  have hg0 : 0 < g.natDegree :=
    Nat.pos_of_ne_zero fun h0 ↦ hg1 (C_dvd_of_natDegree_eq_zero hgne h0 _)
  -- the exceptional differences
  set H : Set ℤ := {h | ∃ a ∈ f.roots, ∃ b ∈ g.roots, (h : K) = a - b} with hH
  have hHfin : H.Finite := by
    refine ((((f.roots ×ˢ g.roots).toFinset.finite_toSet.image fun p : K × K ↦ p.1 - p.2)).preimage
      (Int.cast_injective (α := K)).injOn).subset ?_
    rintro h ⟨a, ha, b, hb, hab⟩
    exact ⟨(a, b), Multiset.mem_toFinset.mpr (Multiset.mem_product.mpr ⟨ha, hb⟩), hab.symm⟩
  have hexc : ∀ h ∈ H, {p : ℤ × ℤ | p.1 ≠ p.2 ∧ |(p.1 : ℝ) - p.2| ≤ β * |(p.1 : ℝ)| ^ γ ∧
      (∃ u : Kˣ, u ∈ (S : Set (HeightOneSpectrum (𝓞 K))).unit K ∧
        (u : K) = f.eval (p.1 : K) / g.eval (p.2 : K)) ∧ p.1 - p.2 = h}.Finite := by
    intro h _
    by_cases hh : h = 0
    · refine Set.finite_empty.subset fun p hp ↦ hp.1 (sub_eq_zero.mp (hp.2.2.2.trans hh))
    obtain ⟨hfh, hgh⟩ := hfg h hh
    set q := g.comp (X - C (h : K)) with hq
    set k := EuclideanDomain.gcd f q with hk
    obtain ⟨f₀, hkf⟩ := EuclideanDomain.gcd_dvd_left f q
    obtain ⟨g₁, hkg⟩ := EuclideanDomain.gcd_dvd_right f q
    set g₀ := g₁.comp (X + C (h : K)) with hg₀
    have hk0 : k ≠ 0 := fun h0 ↦ hfne (EuclideanDomain.gcd_eq_zero_iff.mp h0).1
    have hg_eq : g = k.comp (X + C (h : K)) * g₀ := by
      conv_lhs => rw [← comp_X_sub_C_comp_X_add_C g (h : K)]
      rw [← hq, hkg, mul_comp]
    have hg₁ : g₁ = g₀.comp (X - C (h : K)) := (comp_X_add_C_comp_X_sub_C g₁ _).symm
    have hf₀ne : f₀ ≠ 0 := by rintro rfl; rw [mul_zero] at hkf; exact hfne hkf
    have hg₀ne : g₀ ≠ 0 := by rintro h0; rw [h0, mul_zero] at hg_eq; exact hgne hg_eq
    have hf₀dvd : f₀ ∣ f := ⟨k, by rw [hkf, mul_comm]⟩
    have hg₀dvd : g₀ ∣ g := ⟨k.comp (X + C (h : K)), by rw [hg_eq, mul_comm]⟩
    have hkq : k ∣ q := EuclideanDomain.gcd_dvd_right f q
    have hkfd : k ∣ f := EuclideanDomain.gcd_dvd_left f q
    have hf₀0 : 0 < f₀.natDegree := by
      refine Nat.pos_of_ne_zero fun h0 ↦ hfh ?_
      set c := f₀.coeff 0 with hcdef
      have hc : f₀ = C c := eq_C_of_natDegree_eq_zero h0
      have hc0 : c ≠ 0 := fun hc0 ↦ hf₀ne (by rw [hc, hc0, C_0])
      have hfk : f ∣ k := ⟨C c⁻¹, by rw [hkf, hc, mul_assoc, ← C_mul, mul_inv_cancel₀ hc0,
        C_1, mul_one]⟩
      have := comp_dvd_comp (hfk.trans hkq) (X + C (h : K))
      rwa [hq, comp_X_sub_C_comp_X_add_C] at this
    have hg₀0 : 0 < g₀.natDegree := by
      refine Nat.pos_of_ne_zero fun h0 ↦ hgh ?_
      set c := g₀.coeff 0 with hcdef
      have hc : g₀ = C c := eq_C_of_natDegree_eq_zero h0
      have hc0 : c ≠ 0 := fun hc0 ↦ hg₀ne (by rw [hc, hc0, C_0])
      have hgk : g ∣ k.comp (X + C (h : K)) := ⟨C c⁻¹, by rw [hg_eq, hc, mul_assoc, ← C_mul,
        mul_inv_cancel₀ hc0, C_1, mul_one]⟩
      exact hgk.trans (comp_dvd_comp hkfd _)
    have hroots : ∀ a ∈ f₀.roots, ∀ b ∈ g₀.roots, (h : K) ≠ a - b := by
      intro a ha b hb hab
      have ha' : f₀.IsRoot a := (mem_roots hf₀ne).mp ha
      have hb' : g₀.IsRoot b := (mem_roots hg₀ne).mp hb
      have hg₁a : g₁.IsRoot a := by
        rw [hg₁, IsRoot, eval_comp, eval_sub, eval_X, eval_C,
          show a - (h : K) = b by rw [hab]; ring]
        exact hb'
      have hdvd : k * (X - C a) ∣ k := EuclideanDomain.dvd_gcd
        (by rw [hkf]; exact mul_dvd_mul_left k (dvd_iff_isRoot.mpr ha'))
        (by rw [hkg]; exact mul_dvd_mul_left k (dvd_iff_isRoot.mpr hg₁a))
      have := natDegree_le_of_dvd hdvd hk0
      rw [natDegree_mul hk0 (X_sub_C_ne_zero a), natDegree_X_sub_C] at this
      omega
    have hdeg : γ * (f₀.natDegree + g₀.natDegree + 2) < 1 := by
      refine lt_of_le_of_lt (mul_le_mul_of_nonneg_left ?_ hγ0) hγ'
      have h1 : (f₀.natDegree : ℝ) ≤ f.natDegree := by
        exact_mod_cast natDegree_le_of_dvd hf₀dvd hfne
      have h2 : (g₀.natDegree : ℝ) ≤ g.natDegree := by
        exact_mod_cast natDegree_le_of_dvd hg₀dvd hgne
      linarith
    refine (finite_setOf_eval_div_eval_mem_unit_of_forall_ne S (hf.of_dvd hfne hf₀dvd)
      (hg.of_dvd hgne hg₀dvd) hf₀0 hg₀0 hβ hγ0 hdeg).subset ?_
    rintro p ⟨hne, hbd, ⟨u, hu, hue⟩, hpe⟩
    have hrs : (p.1 : ℝ) = p.2 + h := by
      have : ((p.1 - p.2 : ℤ) : ℝ) = h := by exact_mod_cast hpe
      push_cast at this; linarith
    have hrsK : (p.1 : K) = p.2 + h := by
      have : ((p.1 - p.2 : ℤ) : K) = h := by exact_mod_cast hpe
      push_cast at this; linear_combination this
    have hfr : f.eval (p.1 : K) = k.eval (p.1 : K) * f₀.eval (p.1 : K) := by
      rw [hkf, eval_mul]
    have hgs : g.eval (p.2 : K) = k.eval (p.1 : K) * g₀.eval (p.2 : K) := by
      rw [hg_eq, eval_mul, eval_comp, eval_add, eval_X, eval_C, ← hrsK]
    have hu0 := Units.ne_zero u
    have hfr0 : f.eval (p.1 : K) ≠ 0 := fun h ↦ hu0 (by rw [hue, h, zero_div])
    have hkr : k.eval (p.1 : K) ≠ 0 := fun h0 ↦ hfr0 (by rw [hfr, h0, zero_mul])
    refine ⟨hne, hbd, ⟨u, hu, by rw [hue, hfr, hgs, mul_div_mul_left _ _ hkr]⟩, ?_⟩
    intro a ha b hb hab
    exact hroots a ha b hb (by rw [← hab, hrsK]; ring)
  -- assemble
  refine ((finite_setOf_eval_div_eval_mem_unit_of_forall_ne S hf hg hf0 hg0 hβ hγ0 hγ').union
    (hHfin.biUnion hexc)).subset ?_
  rintro p ⟨hne, hbd, hunit⟩
  by_cases hdiff : ∀ a ∈ f.roots, ∀ b ∈ g.roots, (p.1 : K) - p.2 ≠ a - b
  · exact Or.inl ⟨hne, hbd, hunit, hdiff⟩
  · push Not at hdiff
    obtain ⟨a, ha, b, hb, hab⟩ := hdiff
    refine Or.inr (Set.mem_biUnion (x := p.1 - p.2) ⟨a, ha, b, hb, by push_cast; exact hab⟩
      ⟨hne, hbd, hunit, rfl⟩)

end NumberField
