/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Mathlib.LinearAlgebra.Determinant
public import Mathlib.RingTheory.DiscreteValuationRing.Basic

-- Used only inside proofs.
import Mathlib.LinearAlgebra.FreeModule.PID
import Mathlib.LinearAlgebra.Quotient.Pi
import Mathlib.RingTheory.Length

/-!
# The ideal of maximal minors of a submodule of `ι → R`

For a submodule `N` of `ι → R` (`ι` finite), `N.detIdeal` is the ideal generated by the
determinants of the square matrices whose rows lie in `N`. If `N` is the image of a matrix `φ`,
this is the ideal of maximal minors of `φ`, the Fitting ideal `Fitt₀` of the cokernel
`(ι → R) ⧸ N`.

* `Submodule.detIdeal_span`: for `N = span S` the rows may be taken in `S`
  (multilinearity of the determinant, `MultilinearMap.map_mem_span_image_pi`).
* `Submodule.detIdeal_span_image`: base change along a ring hom.
* `Submodule.detIdeal_map_le`, `Submodule.detIdeal_map_linearEquiv`: invariance under
  automorphisms of `ι → R`.
* `Submodule.detIdeal_pi_span_singleton`: the diagonal case.
* `Submodule.length_quotient_detIdeal`: over a discrete valuation ring, `R ⧸ N.detIdeal` and
  `(ι → R) ⧸ N` have the same length. With `IsDiscreteValuationRing.le_pow_maximalIdeal_iff`
  this is G. Rémond's Lemma 3.1 (*Élimination multihomogène*, Chapter 5 of Nesterenko–Philippon
  (eds.), *Introduction to algebraic independence theory*, LNM 1752 (2001)): the length of the
  cokernel is the least valuation of a maximal minor. The proof uses the Smith normal form.
-/

@[expose] public section

open Submodule

section Multilinear

variable {R ι M N : Type*} [CommSemiring R] [AddCommMonoid M] [Module R M] [AddCommMonoid N]
  [Module R N]

/-- A multilinear map sends a family of vectors in `span S` into the span of its values on
families in `S`. -/
theorem MultilinearMap.map_mem_span_image_pi [Finite ι]
    (f : MultilinearMap R (fun _ : ι ↦ M) N) {S : Set M} {v : ι → M}
    (hv : ∀ i, v i ∈ span R S) : f v ∈ span R (f '' Set.univ.pi fun _ ↦ S) := by
  classical
  have : Fintype ι := Fintype.ofFinite ι
  suffices key : ∀ s : Finset ι, ∀ v : ι → M, (∀ i, v i ∈ span R S) → (∀ i ∉ s, v i ∈ S) →
      f v ∈ span R (f '' Set.univ.pi fun _ ↦ S) from key Finset.univ v hv (by simp)
  intro s
  induction s using Finset.induction_on with
  | empty => exact fun v _ hS ↦ subset_span ⟨v, fun i _ ↦ hS i (Finset.notMem_empty i), rfl⟩
  | insert a s ha ih =>
    intro v hv hS
    suffices h : ∀ x ∈ span R S, f (Function.update v a x) ∈ span R (f '' Set.univ.pi fun _ ↦ S) by
      simpa using h _ (hv a)
    intro x hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
      refine ih _ (fun i ↦ ?_) (fun i hi ↦ ?_)
      · rcases eq_or_ne i a with rfl | hia
        · simpa using subset_span hx
        · simpa [hia] using hv i
      · rcases eq_or_ne i a with rfl | hia
        · simpa using hx
        · simpa [hia] using hS i (by simp [hia, hi])
    | zero => simp
    | add x y _ _ hx hy => simpa [f.map_update_add] using add_mem hx hy
    | smul c x _ hx => simpa [f.map_update_smul] using smul_mem _ c hx

end Multilinear

namespace Submodule

variable {R : Type*} [CommRing R] {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The ideal generated by the determinants of the square matrices whose rows lie in `N`: the
ideal of maximal minors of any matrix with image `N`. -/
noncomputable def detIdeal (N : Submodule R (ι → R)) : Ideal R :=
  Ideal.span {x | ∃ v : ι → ι → R, (∀ j, v j ∈ N) ∧ (Matrix.of v).det = x}

theorem det_mem_detIdeal {N : Submodule R (ι → R)} {v : ι → ι → R} (hv : ∀ j, v j ∈ N) :
    (Matrix.of v).det ∈ N.detIdeal :=
  Ideal.subset_span ⟨v, hv, rfl⟩

theorem detIdeal_mono {N N' : Submodule R (ι → R)} (h : N ≤ N') : N.detIdeal ≤ N'.detIdeal :=
  Ideal.span_le.mpr fun _ ⟨_, hv, hx⟩ ↦ hx ▸ det_mem_detIdeal fun j ↦ h (hv j)

/-- For `N = span S`, the rows may be taken in `S`. -/
theorem detIdeal_span (S : Set (ι → R)) :
    (span R S).detIdeal =
      Ideal.span {x | ∃ v : ι → ι → R, (∀ j, v j ∈ S) ∧ (Matrix.of v).det = x} := by
  refine le_antisymm (Ideal.span_le.mpr ?_) (Ideal.span_mono fun _ ⟨v, hv, hx⟩ ↦
    ⟨v, fun j ↦ subset_span (hv j), hx⟩)
  rintro _ ⟨v, hv, rfl⟩
  have := (Matrix.detRowAlternating (R := R) (n := ι)).toMultilinearMap.map_mem_span_image_pi hv
  refine (span_mono ?_) this
  rintro _ ⟨w, hw, rfl⟩
  exact ⟨w, fun j ↦ hw j trivial, rfl⟩

/-- **Base change**: along a ring hom `ρ`, the submodule spanned by the image of `N` has the
image of `N.detIdeal` as ideal of maximal minors. -/
theorem detIdeal_span_image {R' : Type*} [CommRing R'] (ρ : R →+* R')
    (N : Submodule R (ι → R)) :
    (span R' ((fun w ↦ ρ ∘ w) '' (N : Set (ι → R)))).detIdeal = N.detIdeal.map ρ := by
  rw [detIdeal_span, detIdeal, Ideal.map_span]
  congr 1
  ext x
  constructor
  · rintro ⟨v, hv, rfl⟩
    choose w hw hwv using hv
    refine ⟨(Matrix.of w).det, ⟨w, hw, rfl⟩, ?_⟩
    rw [RingHom.map_det]
    congr 1
    ext i j
    simp [← hwv i]
  · rintro ⟨_, ⟨w, hw, rfl⟩, rfl⟩
    refine ⟨fun j ↦ ρ ∘ w j, fun j ↦ ⟨w j, hw j, rfl⟩, ?_⟩
    rw [RingHom.map_det]
    rfl

/-- Linear maps of `ι → R` can only shrink the ideal of maximal minors. -/
theorem detIdeal_map_le (N : Submodule R (ι → R)) (g : (ι → R) →ₗ[R] ι → R) :
    (N.map g).detIdeal ≤ N.detIdeal := by
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨v, hv, rfl⟩
  choose w hw hwv using hv
  have : Matrix.of v = Matrix.of w * (LinearMap.toMatrix' g).transpose := by
    ext j i
    rw [Matrix.of_apply, ← hwv j, ← LinearMap.toMatrix'_mulVec]
    simp [Matrix.mulVec, dotProduct, Matrix.mul_apply, mul_comm]
  rw [this, Matrix.det_mul]
  exact Ideal.mul_mem_right _ _ (det_mem_detIdeal hw)

theorem detIdeal_map_linearEquiv (N : Submodule R (ι → R)) (e : (ι → R) ≃ₗ[R] ι → R) :
    (N.map (e : (ι → R) →ₗ[R] ι → R)).detIdeal = N.detIdeal := by
  refine le_antisymm (detIdeal_map_le N _) ?_
  have : (N.map (e : (ι → R) →ₗ[R] ι → R)).map (e.symm : (ι → R) →ₗ[R] ι → R) = N := by
    ext x
    simp
  conv_lhs => rw [← this]
  exact detIdeal_map_le _ _

/-- **Maximal minors annihilate the cokernel**: `det V • w ∈ N` for every `w` when the rows of
`V` lie in `N`, by `adj V * V = det V • 1`. -/
theorem detIdeal_le_annihilator (N : Submodule R (ι → R)) :
    N.detIdeal ≤ Module.annihilator R ((ι → R) ⧸ N) := by
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨v, hv, rfl⟩
  refine Module.mem_annihilator.mpr fun x ↦ ?_
  obtain ⟨w, rfl⟩ := Submodule.Quotient.mk_surjective N x
  rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero]
  have : (Matrix.of v).det • w =
      Matrix.vecMul (Matrix.vecMul w (Matrix.of v).adjugate) (Matrix.of v) := by
    rw [Matrix.vecMul_vecMul, Matrix.adjugate_mul, Matrix.vecMul_smul, Matrix.vecMul_one]
  rw [this, Matrix.vecMul_eq_sum]
  exact sum_mem fun j _ ↦ smul_mem _ _ (hv j)

/-- For the rows of a square matrix, the ideal of maximal minors is generated by its
determinant. -/
theorem detIdeal_span_range (v : ι → ι → R) :
    (span R (Set.range v)).detIdeal = Ideal.span {(Matrix.of v).det} := by
  refine le_antisymm ?_ (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr
    (det_mem_detIdeal fun j ↦ subset_span ⟨j, rfl⟩)))
  rw [detIdeal_span, Ideal.span_le]
  rintro _ ⟨w, hw, rfl⟩
  choose τ hτ using hw
  have : Matrix.of w = Matrix.of (fun i j ↦ if τ i = j then (1 : R) else 0) * Matrix.of v := by
    ext i k
    simp [Matrix.mul_apply, ← hτ i]
  rw [SetLike.mem_coe, this, Matrix.det_mul, Ideal.mem_span_singleton]
  exact dvd_mul_left _ _

/-- An annihilator of the cokernel has its `|ι|`-th power among the maximal minors. -/
theorem pow_card_mem_detIdeal {N : Submodule R (ι → R)} {a : R}
    (ha : a ∈ Module.annihilator R ((ι → R) ⧸ N)) : a ^ Fintype.card ι ∈ N.detIdeal := by
  have hrow : ∀ j, a • (Pi.single j 1 : ι → R) ∈ N := fun j ↦ by
    rw [← Submodule.Quotient.mk_eq_zero, Submodule.Quotient.mk_smul]
    exact Module.mem_annihilator.mp ha _
  convert det_mem_detIdeal hrow
  rw [← mul_one (a ^ _), ← Matrix.det_one (n := ι) (R := R), ← Matrix.det_smul]
  congr 1
  ext i j
  simp [Matrix.one_apply, Pi.single_apply, eq_comm]

/-- The diagonal case. -/
theorem detIdeal_pi_span_singleton (a : ι → R) :
    (pi Set.univ fun k ↦ (Ideal.span {a k} : Submodule R R)).detIdeal =
      Ideal.span {∏ k, a k} := by
  refine le_antisymm (Ideal.span_le.mpr ?_) ?_
  · rintro _ ⟨v, hv, rfl⟩
    rw [SetLike.mem_coe, ← Ideal.prod_span_singleton, Matrix.det_apply]
    refine sum_mem fun σ _ ↦ ?_
    rw [Units.smul_def]
    refine zsmul_mem (Ideal.prod_mem_prod fun i _ ↦ ?_) _
    exact hv (σ i) i trivial
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe]
    have := det_mem_detIdeal (N := pi Set.univ fun k ↦ (Ideal.span {a k} : Submodule R R))
      (v := fun j ↦ Pi.single j (a j)) fun j k _ ↦ by
        rcases eq_or_ne k j with rfl | hkj
        · simp
        · simp [hkj]
    convert this
    rw [← Matrix.det_diagonal]
    congr 1
    ext i j
    simp [Matrix.diagonal_apply, Pi.single_apply, eq_comm]

end Submodule

namespace IsDiscreteValuationRing

variable {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]

/-- The length of `R ⧸ I` is the valuation of a generator of `I`. -/
theorem length_quotient_eq_addVal (I : Ideal R) :
    Module.length R (R ⧸ I) = addVal R (Submodule.IsPrincipal.generator I) := by
  rw [Module.length_quotient, ← Order.coheight_orderIso (idealOrderIsoENat R) I,
    idealOrderIsoENat_apply, Order.coheight_toDual, Order.height_enat]

theorem length_quotient_span_singleton (x : R) :
    Module.length R (R ⧸ Ideal.span {x}) = addVal R x := by
  rw [length_quotient_eq_addVal, addVal_eq_iff_associated]
  exact Submodule.IsPrincipal.associated_generator_span_self x

theorem addVal_prod {ι : Type*} (s : Finset ι) (a : ι → R) :
    addVal R (∏ i ∈ s, a i) = ∑ i ∈ s, addVal R (a i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert i s hi ih => rw [Finset.prod_insert hi, Finset.sum_insert hi, addVal_mul, ih]

/-- An ideal lies in `𝔪 ^ n` iff its quotient has length at least `n`. -/
theorem le_pow_maximalIdeal_iff (I : Ideal R) (n : ℕ) :
    I ≤ IsLocalRing.maximalIdeal R ^ n ↔ (n : ℕ∞) ≤ Module.length R (R ⧸ I) := by
  rw [← idealOrderIsoENat_symm_apply_coe, ← (idealOrderIsoENat R).le_iff_le,
    OrderIso.apply_symm_apply, length_quotient_eq_addVal, idealOrderIsoENat_apply]
  rfl

end IsDiscreteValuationRing

namespace Submodule

variable {R : Type*} [CommRing R] {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **Lemma 3.1 of Rémond** (in the form `ℓ(R ⧸ Fitt₀ M) = ℓ(M)`): over a discrete valuation
ring, the ideal of maximal minors of `N` and the cokernel `(ι → R) ⧸ N` give quotients of the
same length. -/
theorem length_quotient_detIdeal [IsDomain R] [IsDiscreteValuationRing R]
    (N : Submodule R (ι → R)) :
    Module.length R (R ⧸ N.detIdeal) = Module.length R ((ι → R) ⧸ N) := by
  obtain ⟨n, snf⟩ := N.smithNormalForm (Pi.basisFun R ι)
  let e : (ι → R) ≃ₗ[R] ι → R := snf.bM.equiv (Pi.basisFun R ι) (Equiv.refl ι)
  let a : ι → R := Function.extend snf.f snf.a 0
  have ha : ∀ i, a (snf.f i) = snf.a i := fun i ↦ snf.f.injective.extend_apply _ _ i
  have hN : N.map (e : (ι → R) →ₗ[R] ι → R) =
      pi Set.univ fun k ↦ (Ideal.span {a k} : Submodule R R) := by
    have hspan : (pi Set.univ fun k ↦ (Ideal.span {a k} : Submodule R R)) =
        span R (Set.range fun k ↦ Pi.single k (a k)) := by
      refine le_antisymm (fun x hx ↦ ?_) (span_le.mpr ?_)
      · rw [← Finset.univ_sum_single x]
        refine sum_mem fun k _ ↦ ?_
        obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp (hx k trivial)
        rw [← hc, ← smul_eq_mul, Pi.single_smul']
        exact smul_mem _ c (subset_span ⟨k, rfl⟩)
      · rintro _ ⟨k, rfl⟩ j -
        rcases eq_or_ne j k with rfl | hjk
        · simp
        · simp [hjk]
    have hrange : span R (Set.range fun k ↦ Pi.single k (a k)) =
        span R (Set.range fun i ↦ Pi.single (snf.f i) (snf.a i)) := by
      refine le_antisymm (span_le.mpr ?_) (span_mono ?_)
      · rintro _ ⟨k, rfl⟩
        by_cases hk : ∃ i, snf.f i = k
        · obtain ⟨i, rfl⟩ := hk
          exact subset_span ⟨i, by simp [ha]⟩
        · simp [a, Function.extend_apply' _ _ _ hk]
      · rintro _ ⟨i, rfl⟩
        exact ⟨snf.f i, by simp [ha]⟩
    have hN0 : N = span R (Set.range fun i ↦ snf.a i • snf.bM (snf.f i)) := by
      conv_lhs => rw [← N.map_subtype_top, ← snf.bN.span_eq, Submodule.map_span, ← Set.range_comp]
      congr 1
      ext x
      simp [snf.snf]
    rw [hspan, hrange, show N.map (e : (ι → R) →ₗ[R] ι → R) = _ from congrArg _ hN0,
      Submodule.map_span, ← Set.range_comp]
    congr 1
    ext x
    simp only [Set.mem_range, Function.comp_apply, map_smul, e]
    simp only [LinearEquiv.coe_coe, Module.Basis.equiv_apply, Pi.basisFun_apply,
      Equiv.refl_apply, ← Pi.single_smul', smul_eq_mul, mul_one]
  have hval : Module.length R ((ι → R) ⧸ N) = ∑ k, IsDiscreteValuationRing.addVal R (a k) := by
    rw [(Submodule.Quotient.equiv N _ e rfl).length_eq, hN,
      (Submodule.quotientPi _).length_eq, Module.length_pi_of_fintype]
    simp only [IsDiscreteValuationRing.length_quotient_span_singleton]
  rw [hval, ← detIdeal_map_linearEquiv N e, hN, detIdeal_pi_span_singleton,
    IsDiscreteValuationRing.length_quotient_span_singleton,
    IsDiscreteValuationRing.addVal_prod]

end Submodule
