/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import AdamczewskiBugeaud2007.AutomaticComplexity
public import Mathlib.Data.Nat.Digits.Defs

-- Used only inside proofs.
import Mathlib.Data.Nat.Digits.Lemmas
import Mathlib.Data.Fintype.EquivFin

/-!
# Finite automata: the definition of Adamczewski–Bugeaud 2007, §3

The paper defines `k`-automatic sequences by automata. A `k`-automaton has a finite set of states
`Q`, a transition function `δ : Q × Σ_k → Q` on the digits `Σ_k = {0, …, k - 1}`, an initial state
`q₀` and an output function `τ`. It generates `a` if `a n = τ (δ (q₀, W_n))` for every `n ≥ 0`,
where `W_n = w₀ w₁ … w_r` lists the base-`k` digits of `n` **least significant first** and
`δ (q, W)` reads `W` from the left. This file proves that this is the kernel definition
`Function.IsAutomatic` of `AutomaticSequence.lean`, and restates Theorem 2 with automata.

## Main definitions

* `Function.IsGeneratedByAutomaton k a`: `a` is generated by a `k`-automaton.

## Main results

* `Function.finite_kKernel_iff_isGeneratedByAutomaton`: for `k ≥ 2`, the `k`-kernel is finite if
  and only if a `k`-automaton generates the sequence (Eilenberg).
* `Function.isAutomatic_iff`: `IsAutomatic` is the paper's notion.
* `Real.transcendental_ofDigits_of_isGeneratedByAutomaton`: **Theorem 2** in the paper's words.

## Implementation notes

⚠ **`W_n` is `Nat.digits k n`**, least significant digit first, as in the paper. For `n = 0` it is
the empty word, so `a 0 = τ q₀`; the paper leaves the expansion of `0` unspecified.

⚠ **The states are `Fin N`.** The paper asks for a finite set; `Fin N` loses nothing, and keeps
the definition in `Prop` without a universe of states.

⚠ **Digits enter the transition function through `Fin k`.** `Nat.digits` produces natural numbers;
each is `< k`, and `Function.automatonRun` casts it (a digit `≥ k`, which never occurs, would leave
the state unchanged).

## References

B. Adamczewski and Y. Bugeaud, *On the complexity of algebraic numbers I. Expansions in integer
bases*, Annals of Mathematics **165** (2007), 547–565, §3; S. Eilenberg, *Automata, Languages, and
Machines*, Vol. A, Academic Press, 1974; J.-P. Allouche and J. Shallit, *Automatic Sequences*,
Cambridge University Press, 2003, Theorem 6.6.2.
-/

@[expose] public section

namespace Function

variable {α : Type*}

/-- The state `δ (q, W)` reached from `q` by reading the word `W` of base-`k` digits from the
left. -/
def automatonRun {k : ℕ} {Q : Type*} (δ : Q → Fin k → Q) (q : Q) (W : List ℕ) : Q :=
  W.foldl (fun q d ↦ if h : d < k then δ q ⟨d, h⟩ else q) q

/-- **A sequence generated by a `k`-automaton** (Adamczewski–Bugeaud 2007, §3): there are finitely
many states `Fin N`, a transition function `δ`, an initial state `q₀` and an output `τ` with
`a n = τ (δ (q₀, W_n))`, where `W_n` is the base-`k` expansion of `n`, least significant digit
first. -/
def IsGeneratedByAutomaton (k : ℕ) (a : ℕ → α) : Prop :=
  ∃ (N : ℕ) (δ : Fin N → Fin k → Fin N) (q₀ : Fin N) (τ : Fin N → α),
    ∀ n, a n = τ (automatonRun δ q₀ (Nat.digits k n))

theorem automatonRun_append {k : ℕ} {Q : Type*} (δ : Q → Fin k → Q) (q : Q) (W W' : List ℕ) :
    automatonRun δ q (W ++ W') = automatonRun δ (automatonRun δ q W) W' :=
  List.foldl_append

theorem automatonRun_cons {k : ℕ} {Q : Type*} (δ : Q → Fin k → Q) (q : Q) {d : ℕ} (hd : d < k)
    (W : List ℕ) : automatonRun δ q (d :: W) = automatonRun δ (δ q ⟨d, hd⟩) W := by
  simp [automatonRun, hd]

/-- **An automaton has a finite kernel.** The kernel member `n ↦ a (k ^ i * n + r)` is determined
by its value at `0` and by the state reached after reading `r`, padded with zeros to `i` digits:
for `n ≥ 1` the expansion of `k ^ i * n + r` is that padded word followed by the expansion of
`n`. -/
theorem IsGeneratedByAutomaton.finite_kKernel {k : ℕ} (hk : 2 ≤ k) {a : ℕ → α}
    (h : IsGeneratedByAutomaton k a) : (kKernel k a).Finite := by
  classical
  obtain ⟨N, δ, q₀, τ, ha⟩ := h
  have := (Set.finite_range τ).to_subtype
  let G : Fin N × Set.range τ → ℕ → α := fun p n ↦
    if n = 0 then p.2.1 else τ (automatonRun δ p.1 (Nat.digits k n))
  refine (Set.finite_range G).subset ?_
  rintro _ ⟨i, r, hr, rfl⟩
  have hlen : (Nat.digits k r).length ≤ i := (Nat.digits_length_le_iff (by omega) r).mpr hr
  refine ⟨(automatonRun δ q₀
    (Nat.digits k r ++ List.replicate (i - (Nat.digits k r).length) 0), ⟨a r, ha r ▸ ⟨_, rfl⟩⟩),
    funext fun n ↦ ?_⟩
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · simp [G]
  · have hd := Nat.digits_append_zeroes_append_digits (b := k)
      (k := i - (Nat.digits k r).length) (n := r) (by omega) hn
    rw [Nat.add_sub_cancel' hlen] at hd
    simp only [G, hn.ne', ↓reduceIte]
    rw [ha, add_comm, ← hd]
    simp only [automatonRun_append]

/-- The kernel is closed under the transitions `s ↦ (n ↦ s (k n + d))`, `d < k`. -/
theorem mem_kKernel_step {k : ℕ} {a s : ℕ → α} (hs : s ∈ kKernel k a) {d : ℕ} (hd : d < k) :
    (fun n ↦ s (k * n + d)) ∈ kKernel k a := by
  obtain ⟨i, r, hr, rfl⟩ := hs
  refine ⟨i + 1, k ^ i * d + r, ?_, funext fun n ↦ ?_⟩
  · calc k ^ i * d + r < k ^ i * d + k ^ i := by omega
      _ = k ^ i * (d + 1) := by ring
      _ ≤ k ^ i * k := Nat.mul_le_mul_left _ hd
      _ = k ^ (i + 1) := (pow_succ k i).symm
  · beta_reduce
    congr 1
    ring

/-- **A finite kernel gives an automaton**: the states are the kernel, reading `d` maps `s` to
`n ↦ s (k n + d)`, the initial state is `a` and the output is the value at `0`. -/
theorem isGeneratedByAutomaton_of_finite_kKernel {k : ℕ} (hk : 2 ≤ k) {a : ℕ → α}
    (h : (kKernel k a).Finite) : IsGeneratedByAutomaton k a := by
  have := h.to_subtype
  let e := Finite.equivFin (kKernel k a)
  let δ' : kKernel k a → Fin k → kKernel k a := fun s d ↦ ⟨_, mem_kKernel_step s.2 d.2⟩
  have ha : a ∈ kKernel k a := ⟨0, 0, by simp, by simp⟩
  -- reading `W` from `s` gives `m ↦ s (k ^ |W| m + ofDigits W)`
  have hrun : ∀ (W : List ℕ), (∀ d ∈ W, d < k) → ∀ s : kKernel k a,
      (automatonRun δ' s W).1 = fun m ↦ s.1 (k ^ W.length * m + Nat.ofDigits k W) := by
    intro W
    induction W with
    | nil => intro _ s; simp [automatonRun]
    | cons d W ih =>
      intro hW s
      have hd : d < k := hW d (by simp)
      rw [automatonRun_cons δ' s hd, ih (fun x hx ↦ hW x (by simp [hx]))]
      funext m
      simp only [δ', List.length_cons, Nat.ofDigits_cons]
      exact congrArg s.1 (by ring)
  refine ⟨Nat.card (kKernel k a), fun q d ↦ e (δ' (e.symm q) d), e ⟨a, ha⟩,
    fun q ↦ (e.symm q).1 0, fun n ↦ ?_⟩
  -- transport the run along `e`
  have htr : ∀ (W : List ℕ) (s : kKernel k a),
      automatonRun (fun q d ↦ e (δ' (e.symm q) d)) (e s) W = e (automatonRun δ' s W) := by
    intro W
    induction W with
    | nil => intro s; rfl
    | cons d W ih =>
      intro s
      by_cases hd : d < k
      · rw [automatonRun_cons _ _ hd, automatonRun_cons _ _ hd, Equiv.symm_apply_apply, ih]
      · simp only [automatonRun, List.foldl_cons, hd, dite_false] at ih ⊢
        exact ih s
  simp only [htr, Equiv.symm_apply_apply]
  rw [hrun _ (fun d hd ↦ Nat.digits_lt_base (by omega) hd) ⟨a, ha⟩]
  simp [Nat.ofDigits_digits]

/-- **Eilenberg's theorem**: for `k ≥ 2`, a sequence has a finite `k`-kernel if and only if it is
generated by a `k`-automaton. -/
theorem finite_kKernel_iff_isGeneratedByAutomaton {k : ℕ} (hk : 2 ≤ k) {a : ℕ → α} :
    (kKernel k a).Finite ↔ IsGeneratedByAutomaton k a :=
  ⟨isGeneratedByAutomaton_of_finite_kKernel hk, fun h ↦ h.finite_kKernel hk⟩

/-- `IsAutomatic` is the paper's notion: some `k`-automaton, `k ≥ 2`, generates the sequence. -/
theorem isAutomatic_iff {a : ℕ → α} :
    IsAutomatic a ↔ ∃ k, 2 ≤ k ∧ IsGeneratedByAutomaton k a := by
  refine exists_congr fun k ↦ ⟨fun ⟨hk, h⟩ ↦ ⟨hk, ?_⟩, fun ⟨hk, h⟩ ↦ ⟨hk, ?_⟩⟩
  · exact (finite_kKernel_iff_isGeneratedByAutomaton hk).mp h
  · exact (finite_kKernel_iff_isGeneratedByAutomaton hk).mpr h

end Function

namespace Real

/-- **Theorem 2 (Adamczewski–Bugeaud 2007), in the paper's words.** For `b ≥ 2`, the base-`b`
expansion of an irrational algebraic number cannot be generated by a finite automaton: if some
`k`-automaton, `k ≥ 2`, generates the digits `a` and `∑ k, a k / b ^ (k + 1)` is irrational, it
is transcendental. -/
theorem transcendental_ofDigits_of_isGeneratedByAutomaton {b : ℕ} (hb : 2 ≤ b) {a : ℕ → Fin b}
    {k : ℕ} (hk : 2 ≤ k) (hauto : Function.IsGeneratedByAutomaton k a)
    (hirr : Irrational (ofDigits a)) : Transcendental ℚ (ofDigits a) :=
  transcendental_ofDigits_of_isAutomatic hb (Function.isAutomatic_iff.mpr ⟨k, hk, hauto⟩) hirr

end Real
