/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

-- For `Nat.instMonoid`, so that `k ^ i` in `kKernel` elaborates through `Monoid.npow` as it does
-- wherever Mathlib's algebra is loaded, and in the single-file challenge (see `COMPARATOR.md`).
public import Mathlib.Algebra.Group.Nat.Defs
public import Mathlib.Data.Set.Finite.Basic

/-!
# Automatic sequences

A sequence `a : ℕ → α` is **`k`-automatic** if it is generated by a deterministic finite
automaton with output reading the base-`k` digits of `n`; by Eilenberg's theorem this holds if and
only if its **`k`-kernel**, the set of subsequences `n ↦ a (k ^ i * n + r)` with `r < k ^ i`, is
finite. A sequence is **automatic** if it is `k`-automatic for some `k ≥ 2`. Theorem 2 of
Adamczewski–Bugeaud 2007 is about the numbers whose expansion in an integer base is automatic.

The kernel is taken as the definition, so that no automata are needed.

## Main definitions

* `Function.kKernel`: the `k`-kernel of a sequence.
* `Function.IsAutomatic`: the `k`-kernel is finite for some `k ≥ 2`.

## Main results

* `Function.IsAutomatic.finite_range`: an automatic sequence takes finitely many values.
* `Function.kKernel_comp`: the kernel of `g ∘ a` is the image of the kernel of `a`.
* `Function.isAutomatic_comp_iff`: automaticity is invariant under a relabelling of the alphabet
  that is injective on the range; `Function.IsAutomatic.comp` is the direction that needs nothing.
* `Function.not_isAutomatic_of_injective`: an injective sequence is never automatic.
* `Function.isAutomatic_const`: a constant sequence is automatic.

## Implementation notes

⚠ **No finite alphabet is assumed.** Finiteness of the kernel already forces the range to be
finite (`Function.IsAutomatic.finite_range`): `a m` is the value at `0` of the kernel member
`n ↦ a (k ^ m * n + m)`.

⚠ **Relabelling is free in one direction only.** `IsAutomatic a → IsAutomatic (g ∘ a)` for every
`g`, but a non-injective `g` can make an injective, hence non-automatic, sequence constant. So the
converse needs `g` injective on the range of `a`, and nowhere else.

## References

J.-P. Allouche and J. Shallit, *Automatic Sequences: Theory, Applications, Generalizations*,
Cambridge University Press, 2003 (the kernel characterization is Theorem 6.6.2; closure under
codings is Theorem 6.8.1); S. Eilenberg, *Automata, Languages, and Machines*, Vol. A, Academic
Press, 1974. Ported from `CITED/AlloucheShallitBasic.lean` of the author's `lean-code` corpus.
-/

@[expose] public section

namespace Function

variable {α β : Type*}

/-- The **`k`-kernel** of a sequence: the subsequences `n ↦ a (k ^ i * n + r)` for `i ≥ 0` and
`r < k ^ i`. -/
def kKernel (k : ℕ) (a : ℕ → α) : Set (ℕ → α) :=
  {s | ∃ i r, r < k ^ i ∧ s = fun n ↦ a (k ^ i * n + r)}

/-- A sequence is **automatic** if its `k`-kernel is finite for some `k ≥ 2`; equivalently, it is
generated by a deterministic finite automaton with output. -/
def IsAutomatic (a : ℕ → α) : Prop :=
  ∃ k, 2 ≤ k ∧ (kKernel k a).Finite

/-- **An automatic sequence takes finitely many values**: `a m` is the value at `0` of the kernel
member `n ↦ a (k ^ m * n + m)`. -/
theorem IsAutomatic.finite_range {a : ℕ → α} (h : IsAutomatic a) : (Set.range a).Finite := by
  obtain ⟨k, hk, hfin⟩ := h
  refine (hfin.image fun s ↦ s 0).subset ?_
  rintro _ ⟨m, rfl⟩
  exact ⟨fun n ↦ a (k ^ m * n + m), ⟨m, m, Nat.lt_pow_self hk, rfl⟩, by simp⟩

/-- Relabelling commutes with decimation: the `k`-kernel of `g ∘ a` is the image of the
`k`-kernel of `a`. -/
theorem kKernel_comp (k : ℕ) (a : ℕ → α) (g : α → β) :
    kKernel k (g ∘ a) = (g ∘ ·) '' kKernel k a := by
  ext s
  constructor
  · rintro ⟨i, r, hr, rfl⟩
    exact ⟨_, ⟨i, r, hr, rfl⟩, rfl⟩
  · rintro ⟨t, ⟨i, r, hr, rfl⟩, rfl⟩
    exact ⟨i, r, hr, rfl⟩

/-- Every member of the `k`-kernel of `a` takes its values among those of `a`. -/
theorem range_subset_of_mem_kKernel {k : ℕ} {a s : ℕ → α} (hs : s ∈ kKernel k a) :
    Set.range s ⊆ Set.range a := by
  rintro _ ⟨n, rfl⟩
  obtain ⟨i, r, -, rfl⟩ := hs
  exact ⟨_, rfl⟩

/-- A relabelling injective on the range of `a` preserves finiteness of the kernel, both ways. -/
theorem finite_kKernel_comp_iff {k : ℕ} {a : ℕ → α} {g : α → β}
    (hg : Set.InjOn g (Set.range a)) : (kKernel k (g ∘ a)).Finite ↔ (kKernel k a).Finite := by
  rw [kKernel_comp]
  refine ⟨fun h ↦ h.of_finite_image fun s hs t ht hst ↦ ?_, fun h ↦ h.image _⟩
  funext n
  exact hg (range_subset_of_mem_kKernel hs ⟨n, rfl⟩) (range_subset_of_mem_kKernel ht ⟨n, rfl⟩)
    (congrFun hst n)

/-- **Automaticity is invariant under a relabelling injective on the range.** -/
theorem isAutomatic_comp_iff {a : ℕ → α} {g : α → β} (hg : Set.InjOn g (Set.range a)) :
    IsAutomatic (g ∘ a) ↔ IsAutomatic a :=
  exists_congr fun _ ↦ and_congr_right fun _ ↦ finite_kKernel_comp_iff hg

/-- **A relabelling of an automatic sequence is automatic**, with no condition on the
relabelling. -/
theorem IsAutomatic.comp {a : ℕ → α} (h : IsAutomatic a) (g : α → β) : IsAutomatic (g ∘ a) := by
  obtain ⟨k, hk, hfin⟩ := h
  exact ⟨k, hk, kKernel_comp k a g ▸ hfin.image _⟩

/-- **An injective sequence is never automatic**: the decimations `n ↦ a (k ^ i * n)` are pairwise
distinct, since at `n = 1` they read `a (k ^ i)`. -/
theorem not_isAutomatic_of_injective {a : ℕ → α} (ha : Injective a) : ¬ IsAutomatic a := by
  rintro ⟨k, hk, hfin⟩
  refine Set.infinite_of_injective_forall_mem (f := fun i : ℕ ↦ fun n ↦ a (k ^ i * n)) ?_ ?_ hfin
  · exact fun i j hij ↦ Nat.pow_right_injective hk (ha (by simpa using congrFun hij 1))
  · exact fun i ↦ ⟨i, 0, Nat.pow_pos (by omega), by simp⟩

/-- A constant sequence is automatic: its kernel is a singleton. -/
theorem isAutomatic_const (x : α) : IsAutomatic fun _ : ℕ ↦ x := by
  refine ⟨2, le_rfl, (Set.finite_singleton fun _ : ℕ ↦ x).subset ?_⟩
  rintro _ ⟨_, _, -, rfl⟩
  rfl

end Function
