/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import AdamczewskiBugeaud2007.Automaton
public import AdamczewskiBugeaud2007.Morphism
public import AdamczewskiBugeaud2007.PisotTranscendence
public import AdamczewskiBugeaud2007.SchmidtPeriodicity
public import DiophantineApproximation.FactorComplexity
public import ForMathlib.Analysis.Real.BetaExpansion

-- Used only inside proofs.
import AdamczewskiBugeaud2007.AutomaticComplexity

/-!
# `β`-expansions of algebraic numbers: Theorems 1A–5A

**Theorems 1A–5A of Adamczewski–Bugeaud 2007, §§2, 4.** For a Pisot or Salem number `β`, the
conclusions of Theorems 1–4 hold for the `β`-expansion (Rényi's greedy expansion) of an algebraic
number of `(0, 1)` outside `ℚ(β)`, in place of the base-`b` expansion of an algebraic irrational:

* **1A**: its complexity satisfies `p (n) / n → ∞`;
* **2A**: it is not generated by a finite automaton;
* **3A**: if it is binary, it is not generated by a morphism;
* **4A**: it is not generated by a recurrent morphism;
* **5A** (`β` Pisot): a stammering, not eventually periodic `β`-expansion is transcendental.

The first four follow from Theorem 5 (`Real.mem_adjoin_of_isStammering`) as Theorems 1–4 follow
from the criterion in base `b`: each hypothesis makes the digits stammering. Non-periodicity, where
it is needed (Theorem 3A), comes from `Real.tsum_mem_adjoin_of_isEventuallyPeriodic`. Theorem 5A
adds K. Schmidt's theorem (`Real.isEventuallyPeriodic_betaDigits_of_mem_adjoin`).

## Main results

* `Real.betaDigitsFin`: the `β`-digits as letters of the alphabet `{0, …, ⌊β⌋}`.
* `Real.mem_adjoin_of_isStammering_fin`: Theorem 5 for digits in a finite alphabet `Fin N`.
* `Real.tendsto_complexity_betaDigitsFin_div_atTop`: **Theorem 1A**.
* `Real.not_isAutomatic_betaDigitsFin`, `Real.not_isGeneratedByAutomaton_betaDigitsFin`:
  **Theorem 2A**.
* `Real.not_isGeneratedByMorphism_of_betaDigits`: **Theorem 3A**.
* `Real.not_isGeneratedByMorphism_betaDigitsFin_of_isRecurrent`: **Theorem 4A**.
* `Real.transcendental_of_isStammering_betaDigits`: **Theorem 5A**, for a Pisot number, from
  Theorem 5 and K. Schmidt's theorem (`Real.isEventuallyPeriodic_betaDigits_of_mem_adjoin`).

## Implementation notes

⚠ **The conjugate condition replaces "Pisot or Salem".** All four theorems are stated for a real
algebraic integer `β > 1` whose conjugates other than `β` lie in the closed unit disc, the only
property of Pisot and Salem numbers the proof uses (`IsPisot.norm_le_one`, `IsSalem`).

⚠ **The alphabet is `Fin (⌊β⌋₊ + 1)`.** The `β`-digits of `x ∈ [0, 1)` are at most `⌊β⌋`
(`Real.betaDigits_le_floor`), and the complexity and automata of the paper are about words over
this alphabet. `Real.betaDigitsFin` truncates with `min … ⌊β⌋₊` so that it needs no hypothesis to
be defined; on `[0, 1)` it agrees with `Real.betaDigits` (`Real.val_betaDigitsFin`).

⚠ **"Binary" in Theorem 3A is a hypothesis on the digits**: a sequence `a : ℕ → Fin 2` whose
values are the `β`-digits of `x`. For `β < 2` every `β`-expansion is binary.

## References

B. Adamczewski and Y. Bugeaud, *On the complexity of algebraic numbers I. Expansions in integer
bases*, Annals of Mathematics **165** (2007), 547–565, Theorems 1A–5A; A. Rényi,
*Representations for real numbers and their ergodic properties*, Acta Math. Acad. Sci. Hungar.
**8** (1957), 477–493.
-/

@[expose] public section

open Filter

namespace Function

variable {α γ : Type*}

/-- **Stammering survives a change of alphabet**: the image of a stammering sequence under any
map is stammering, with the same repetitions. -/
theorem IsStammering.comp {a : ℕ → α} (h : IsStammering a) (f : α → γ) : IsStammering (f ∘ a) := by
  obtain ⟨w, hw, h⟩ := h
  obtain ⟨C, -, r, s, hs, hs1, hrs, hper⟩ := h.exists_periodic (by linarith)
  exact ⟨w, hw, isStammeringWith_of_periodic (by linarith) hs hs1 hrs fun k i h1 h2 ↦ by
    simp only [Function.comp_apply, hper k i h1 h2]⟩

/-- The image of an eventually periodic sequence under any map is eventually periodic. -/
theorem IsEventuallyPeriodic.comp {a : ℕ → α} (h : IsEventuallyPeriodic a) (f : α → γ) :
    IsEventuallyPeriodic (f ∘ a) := by
  obtain ⟨N, p, hp, h⟩ := h
  exact ⟨N, p, hp, fun n hn ↦ by simp only [Function.comp_apply, h n hn]⟩

end Function

namespace Real

open IntermediateField

variable {β x : ℝ}

/-- **The `β`-digits as letters** of the alphabet `{0, …, ⌊β⌋}`. On `[0, 1)` they are the
`β`-digits (`Real.val_betaDigitsFin`); the truncation only makes the definition total. -/
noncomputable def betaDigitsFin (β x : ℝ) (k : ℕ) : Fin (⌊β⌋₊ + 1) :=
  ⟨min (betaDigits β x k) ⌊β⌋₊, Nat.lt_succ_of_le (min_le_right _ _)⟩

theorem val_betaDigitsFin (hβ : 0 < β) (hx : x ∈ Set.Ico (0 : ℝ) 1) (k : ℕ) :
    (betaDigitsFin β x k : ℕ) = betaDigits β x k :=
  min_eq_left (betaDigits_le_floor hβ hx k)

/-- The `β`-expansion, read on the letters: `x = ∑ k, d k / β ^ (k + 1)`. -/
theorem tsum_betaDigitsFin (hβ : 1 < β) (hx : x ∈ Set.Ico (0 : ℝ) 1) :
    ∑' k, ((betaDigitsFin β x k : ℕ) : ℝ) / β ^ (k + 1) = x := by
  simp only [val_betaDigitsFin (by linarith) hx]
  exact (hasSum_betaDigits hβ hx).tsum_eq

section Fin

variable {N : ℕ} {a : ℕ → Fin N}

/-- The integer digits of a sequence of letters of `Fin N`, bounded by `N`. -/
theorem bddAbove_abs_fin (a : ℕ → Fin N) :
    BddAbove (Set.range fun k ↦ |((a k : ℕ) : ℤ)|) :=
  ⟨N, fun _ ⟨k, hk⟩ ↦ by
    rw [← hk]
    change |((a k : ℕ) : ℤ)| ≤ N
    rw [abs_of_nonneg (Int.natCast_nonneg _)]
    exact_mod_cast (a k).2.le⟩

theorem tsum_intCast_fin (β : ℝ) (a : ℕ → Fin N) :
    ∑' k, (((a k : ℕ) : ℤ) : ℝ) / β ^ (k + 1) = ∑' k, ((a k : ℕ) : ℝ) / β ^ (k + 1) := by
  simp only [Int.cast_natCast]

/-- **Theorem 5 for digits in a finite alphabet.** For a real algebraic integer `β > 1` whose other
conjugates lie in the closed unit disc, if the letters `a` of `Fin N` are stammering and
`∑ k, a k / β ^ (k + 1)` is algebraic, it lies in `ℚ(β)`. -/
theorem mem_adjoin_of_isStammering_fin (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hst : Function.IsStammering a) (halg : IsAlgebraic ℚ (∑' k, ((a k : ℕ) : ℝ) / β ^ (k + 1))) :
    ∑' k, ((a k : ℕ) : ℝ) / β ^ (k + 1) ∈ ℚ⟮β⟯ := by
  rw [← tsum_intCast_fin] at halg ⊢
  exact mem_adjoin_of_isStammering hβ hint hconj (bddAbove_abs_fin a)
    (hst.comp fun d ↦ ((d : ℕ) : ℤ)) halg

/-- An eventually periodic sequence of letters of `Fin N` has its value in `ℚ(β)`. -/
theorem tsum_mem_adjoin_of_isEventuallyPeriodic_fin (hβ : 1 < β)
    (hper : Function.IsEventuallyPeriodic a) :
    ∑' k, ((a k : ℕ) : ℝ) / β ^ (k + 1) ∈ ℚ⟮β⟯ := by
  rw [← tsum_intCast_fin]
  exact tsum_mem_adjoin_of_isEventuallyPeriodic hβ (bddAbove_abs_fin a)
    (hper.comp fun d ↦ ((d : ℕ) : ℤ))

end Fin

/-- **The `β`-expansion of an algebraic number outside `ℚ(β)` is not stammering.** -/
theorem not_isStammering_betaDigitsFin (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) :
    ¬ Function.IsStammering (betaDigitsFin β x) := fun hst ↦ by
  rw [← tsum_betaDigitsFin hβ hx] at halg hxK
  exact hxK (mem_adjoin_of_isStammering_fin hβ hint hconj hst halg)

/-- **Theorem 1A (Adamczewski–Bugeaud 2007).** For a real algebraic integer `β > 1` whose other
conjugates lie in the closed unit disc (a Pisot or a Salem number), the complexity of the
`β`-expansion of an algebraic number of `[0, 1)` outside `ℚ(β)` satisfies `p (n) / n → ∞`. -/
theorem tendsto_complexity_betaDigitsFin_div_atTop (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) :
    Tendsto (fun n ↦ (Function.complexity (betaDigitsFin β x) n : ℝ) / n) atTop atTop := by
  rw [tendsto_atTop]
  by_contra! hC
  obtain ⟨C, hC⟩ := hC
  refine not_isStammering_betaDigitsFin hβ hint hconj hx halg hxK
    (Function.isStammering_of_frequently_complexity_le (C := C) ?_)
  refine (hC.and_eventually (eventually_ge_atTop 1)).mono fun n ⟨hn, hn1⟩ ↦ ?_
  have : (0 : ℝ) < n := by exact_mod_cast hn1
  exact ((div_lt_iff₀ this).mp hn).le

/-- **Theorem 2A (Adamczewski–Bugeaud 2007)**, in the `k`-kernel form: the `β`-expansion of an
algebraic number of `[0, 1)` outside `ℚ(β)` is not automatic. -/
theorem not_isAutomatic_betaDigitsFin (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) :
    ¬ Function.IsAutomatic (betaDigitsFin β x) := fun h ↦
  not_isStammering_betaDigitsFin hβ hint hconj hx halg hxK h.isStammering

/-- **Theorem 2A (Adamczewski–Bugeaud 2007)**, as printed: no `k`-automaton generates the
`β`-expansion of an algebraic number of `[0, 1)` outside `ℚ(β)`. -/
theorem not_isGeneratedByAutomaton_betaDigitsFin (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) {k : ℕ}
    (hk : 2 ≤ k) : ¬ Function.IsGeneratedByAutomaton k (betaDigitsFin β x) := fun h ↦
  not_isAutomatic_betaDigitsFin hβ hint hconj hx halg hxK
    (Function.isAutomatic_iff.mpr ⟨k, hk, h⟩)

/-- **Theorem 3A (Adamczewski–Bugeaud 2007).** A binary `β`-expansion of an algebraic number of
`[0, 1)` outside `ℚ(β)` is not generated by a morphism: if the letters `a` of `{0, 1}` are the
`β`-digits of `x`, no morphism generates them. -/
theorem not_isGeneratedByMorphism_of_betaDigits (hβ : 1 < β) (hint : IsIntegral ℤ β)
    (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯) {a : ℕ → Fin 2}
    (ha : ∀ k, (a k : ℕ) = betaDigits β x k) (φ : Fin 2 → List (Fin 2)) :
    ¬ Function.IsGeneratedByMorphism φ a := by
  intro h
  have hsum : ∑' k, ((a k : ℕ) : ℝ) / β ^ (k + 1) = x := by
    simp only [ha]
    exact (hasSum_betaDigits hβ hx).tsum_eq
  rw [← hsum] at halg hxK
  have hper : ¬ Function.IsEventuallyPeriodic a := fun hp ↦
    hxK (tsum_mem_adjoin_of_isEventuallyPeriodic_fin hβ hp)
  exact hxK (mem_adjoin_of_isStammering_fin hβ hint hconj
    (h.isStammering (Function.isRecurrent_of_not_isEventuallyPeriodic hper)) halg)

/-- **Theorem 4A (Adamczewski–Bugeaud 2007).** The `β`-expansion of an algebraic number of
`[0, 1)` outside `ℚ(β)` is not generated by a recurrent morphism. -/
theorem not_isGeneratedByMorphism_betaDigitsFin_of_isRecurrent (hβ : 1 < β)
    (hint : IsIntegral ℤ β) (hconj : ∀ z ∈ (minpoly ℚ β).aroots ℂ, z ≠ (β : ℂ) → ‖z‖ ≤ 1)
    (hx : x ∈ Set.Ico (0 : ℝ) 1) (halg : IsAlgebraic ℚ x) (hxK : x ∉ ℚ⟮β⟯)
    (φ : Fin (⌊β⌋₊ + 1) → List (Fin (⌊β⌋₊ + 1)))
    (hrec : Function.IsRecurrent (betaDigitsFin β x)) :
    ¬ Function.IsGeneratedByMorphism φ (betaDigitsFin β x) := fun h ↦
  not_isStammering_betaDigitsFin hβ hint hconj hx halg hxK (h.isStammering hrec)

/-- **Theorem 5A (Adamczewski–Bugeaud 2007).** For a Pisot number `β`, if the `β`-expansion of
`x ∈ [0, 1)` is stammering and not eventually periodic, then `x` is transcendental. By Theorem 5
an algebraic `x` would lie in `ℚ(β)`, and by K. Schmidt's theorem its expansion would then be
eventually periodic. -/
theorem transcendental_of_isStammering_betaDigits (hβ : IsPisot β) (hx : x ∈ Set.Ico (0 : ℝ) 1)
    (hst : Function.IsStammering (betaDigits β x))
    (hper : ¬ Function.IsEventuallyPeriodic (betaDigits β x)) : Transcendental ℚ x := by
  intro halg
  have hfin : betaDigitsFin β x = (fun d ↦ (⟨min d ⌊β⌋₊, Nat.lt_succ_of_le (min_le_right _ _)⟩ :
      Fin (⌊β⌋₊ + 1))) ∘ betaDigits β x := rfl
  by_cases hxK : x ∈ ℚ⟮β⟯
  · exact hper (isEventuallyPeriodic_betaDigits_of_mem_adjoin hβ hx hxK)
  · exact not_isStammering_betaDigitsFin hβ.1 hβ.2.1 hβ.norm_le_one hx halg hxK
      (hfin ▸ hst.comp _)

end Real
