/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import AdamczewskiBugeaud2007.Automaton
public import AdamczewskiBugeaud2007.Morphism

-- Used only inside proofs.
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.Nat.Digits.Lemmas
import Mathlib.Data.Nat.Prime.Basic

/-!
# The examples of Adamczewski–Bugeaud 2007

The paper illustrates its definitions and theorems with four examples, formalized here.

* **The Thue–Morse sequence** (§3), generated by the `2`-automaton with two states whose
  transitions add the digit read. It is not eventually periodic, so by Theorem 2 the Thue–Morse
  number `∑ t n / 2 ^ (n + 1)` is transcendental (Mahler 1929; §7).
* **Kempner's number** `∑ 2 ^ (-2 ^ n)` (§3): its digits, `1` exactly at the powers of `2`, are
  `2`-automatic and not eventually periodic, so it is transcendental (Kempner 1916).
* **Morton–Mourant's exception** (§7): `α (3, 1, 2) = ∑ e (n) / 2 ^ n = 2 / 3`, where `e (n)` is
  the number of digits `1` in the ternary expansion of `n`, modulo `2`. It is `n mod 2`.
* **The ternary morphism** `0 ↦ 012, 1 ↦ 12, 2 ↦ 2` (§2), for which the method fails: its fixed
  points are not recurrent, so Theorem 4 does not apply.

## Main results

* `transcendental_ofDigits_thueMorse`: the Thue–Morse number is transcendental.
* `transcendental_tsum_kempner`: Kempner's number is transcendental.
* `tsum_mortonMourant312`: `α (3, 1, 2) = 2 / 3`.
* `not_isRecurrent_of_isGeneratedByMorphism_ternaryMorphism`: the ternary fixed points are not
  recurrent.

## References

B. Adamczewski and Y. Bugeaud, *On the complexity of algebraic numbers I. Expansions in integer
bases*, Annals of Mathematics **165** (2007), 547–565, §§2, 3 and 7; K. Mahler, *Arithmetische
Eigenschaften der Lösungen einer Klasse von Funktionalgleichungen*, Math. Ann. **101** (1929),
342–366; A. J. Kempner, *On transcendental numbers*, Trans. Amer. Math. Soc. **17** (1916),
476–482; P. Morton and W. J. Mourant, *Digit patterns and transcendental numbers*, J. Austral.
Math. Soc. Ser. A **51** (1991), 216–236.
-/

@[expose] public section

open Function

/-! ### The Thue–Morse sequence -/

/-- The **Thue–Morse sequence** as the output of the `2`-automaton of Adamczewski–Bugeaud 2007,
§3: states `0` and `1`, reading the digit `d` adds `d`, the output is the state. So `thueMorse n`
is the parity of the number of digits `1` in the binary expansion of `n`. -/
def thueMorse (n : ℕ) : Fin 2 :=
  automatonRun (fun q d : Fin 2 ↦ q + d) 0 (Nat.digits 2 n)

/-- The Thue–Morse sequence is generated by the automaton that defines it. -/
theorem isGeneratedByAutomaton_thueMorse : IsGeneratedByAutomaton 2 thueMorse :=
  ⟨2, fun q d ↦ q + d, 0, id, fun _ ↦ rfl⟩

/-- Starting the Thue–Morse automaton in `q + c` shifts its state by `c`. -/
theorem automatonRun_thueMorse_add (q c : Fin 2) (W : List ℕ) :
    automatonRun (fun q d : Fin 2 ↦ q + d) (q + c) W =
      automatonRun (fun q d : Fin 2 ↦ q + d) q W + c := by
  induction W generalizing q with
  | nil => rfl
  | cons d W ih =>
    by_cases hd : d < 2
    · rw [automatonRun_cons _ _ hd, automatonRun_cons _ _ hd, ← ih, add_right_comm]
    · simp only [automatonRun, List.foldl_cons, hd, dite_false] at ih ⊢
      exact ih q

theorem thueMorse_two_mul (n : ℕ) : thueMorse (2 * n) = thueMorse n := by
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · rfl
  · have e : Nat.digits 2 (2 * n) = 0 :: Nat.digits 2 n := by
      rw [Nat.digits_def' (by norm_num) (by omega)]
      congr 1
      · omega
      · rw [Nat.mul_div_cancel_left n (by norm_num)]
    rw [thueMorse, e, automatonRun_cons _ _ (by norm_num)]
    rfl

theorem thueMorse_two_mul_add_one (n : ℕ) : thueMorse (2 * n + 1) = thueMorse n + 1 := by
  have e : Nat.digits 2 (2 * n + 1) = 1 :: Nat.digits 2 n := by
    rw [Nat.digits_def' (by norm_num) (by omega)]
    congr 1
    · omega
    · congr 1
      omega
  rw [thueMorse, e, automatonRun_cons _ _ (by norm_num)]
  exact automatonRun_thueMorse_add 0 1 (Nat.digits 2 n)

/-- **The Thue–Morse sequence is not eventually periodic.** An even period `2 q` halves to the
period `q`. An odd period `2 q + 1` gives `t (n + q) ≠ t n` and `t (n + q + 1) ≠ t n`, so
`t (n + q) = t (n + q + 1)` for large `n`, against `t (2 m + 1) ≠ t (2 m)`. -/
theorem not_isEventuallyPeriodic_thueMorse : ¬ IsEventuallyPeriodic thueMorse := by
  rintro ⟨N, p, hp, h⟩
  induction p using Nat.strong_induction_on generalizing N with
  | _ p ih =>
  have hne : ∀ x : Fin 2, x + 1 ≠ x := by decide
  have htwo : ∀ x y z : Fin 2, x ≠ y → z ≠ y → x = z := by decide
  rcases Nat.even_or_odd' p with ⟨q, rfl | rfl⟩
  · refine ih q (by omega) N (by omega) fun n hn ↦ ?_
    have := h (2 * n) (by omega)
    rwa [show 2 * n + 2 * q = 2 * (n + q) by ring, thueMorse_two_mul, thueMorse_two_mul] at this
  · have h1 : ∀ n, N ≤ n → thueMorse (n + q) ≠ thueMorse n := fun n hn e ↦ by
      have := h (2 * n) (by omega)
      rw [show 2 * n + (2 * q + 1) = 2 * (n + q) + 1 by ring, thueMorse_two_mul_add_one,
        thueMorse_two_mul, e] at this
      exact hne _ this
    have h2 : ∀ n, N ≤ n → thueMorse (n + q + 1) ≠ thueMorse n := fun n hn e ↦ by
      have := h (2 * n + 1) (by omega)
      rw [show 2 * n + 1 + (2 * q + 1) = 2 * (n + q + 1) by ring, thueMorse_two_mul,
        thueMorse_two_mul_add_one, e] at this
      exact hne _ this.symm
    set m := N + q
    have e := htwo _ _ _ (h1 (2 * m - q) (by omega)) (h2 (2 * m - q) (by omega))
    rw [show 2 * m - q + q = 2 * m by omega, thueMorse_two_mul, thueMorse_two_mul_add_one] at e
    exact hne _ e.symm

/-- **The Thue–Morse number is transcendental** (Mahler 1929), as a case of Theorem 2. -/
theorem transcendental_ofDigits_thueMorse : Transcendental ℚ (Real.ofDigits thueMorse) :=
  Real.transcendental_ofDigits_of_isGeneratedByAutomaton le_rfl le_rfl
    isGeneratedByAutomaton_thueMorse (Real.irrational_ofDigits not_isEventuallyPeriodic_thueMorse)

/-! ### Kempner's number -/

open Classical in
/-- The binary digits of `∑ 2 ^ (-(2 ^ j + 1))`, half of Kempner's number: `1` at the powers of
`2`, `0` elsewhere. -/
noncomputable def kempnerDigits (n : ℕ) : Fin 2 :=
  if ∃ j, n = 2 ^ j then 1 else 0

theorem kempnerDigits_eq_one_iff {n : ℕ} : kempnerDigits n = 1 ↔ ∃ j, n = 2 ^ j := by
  unfold kempnerDigits
  split_ifs with h <;> simp [h]

/-- Two elements of `Fin 2` are equal when they are `1` together. -/
theorem Fin.two_eq_iff {x y : Fin 2} : x = y ↔ (x = 1 ↔ y = 1) := by
  revert x y
  decide

/-- **The Kempner digits are `2`-automatic.** The kernel member `n ↦ a (2 ^ i n + r)` is `a` for
`r = 0`, and vanishes off `n = 0` for `0 < r < 2 ^ i`: `2 ^ i` divides every power of `2` above
it, but not `2 ^ i n + r`. -/
theorem isAutomatic_kempnerDigits : IsAutomatic kempnerDigits := by
  refine ⟨2, le_rfl, ?_⟩
  let G : Option (Fin 2) → ℕ → Fin 2 := fun o ↦
    match o with
    | none => kempnerDigits
    | some c => fun n ↦ if n = 0 then c else 0
  refine (Set.finite_range G).subset ?_
  rintro _ ⟨i, r, hr, rfl⟩
  rcases Nat.eq_zero_or_pos r with rfl | hr0
  · refine ⟨none, funext fun n ↦ Fin.two_eq_iff.mpr ?_⟩
    simp only [G, add_zero, kempnerDigits_eq_one_iff]
    constructor
    · rintro ⟨k, rfl⟩
      exact ⟨i + k, (pow_add 2 i k).symm⟩
    · rintro ⟨j, hj⟩
      obtain ⟨k, -, hk⟩ := (Nat.dvd_prime_pow Nat.prime_two).mp (hj ▸ Dvd.intro_left _ rfl)
      exact ⟨k, hk⟩
  · refine ⟨some (kempnerDigits r), funext fun n ↦ ?_⟩
    rcases Nat.eq_zero_or_pos n with rfl | hn
    · simp [G]
    · simp only [G, hn.ne', ite_false]
      refine (Fin.two_eq_iff.mpr ?_)
      simp only [kempnerDigits_eq_one_iff, zero_ne_one, false_iff, not_exists]
      intro j hj
      have hlt : 2 ^ i < 2 ^ j := by
        rw [← hj]
        nlinarith [Nat.one_le_two_pow (n := i)]
      have hij : i ≤ j := ((Nat.pow_lt_pow_iff_right (by norm_num)).mp hlt).le
      have hdvd : 2 ^ i ∣ r :=
        (Nat.dvd_add_right (Dvd.intro n rfl)).mp (hj ▸ pow_dvd_pow 2 hij)
      exact absurd (Nat.le_of_dvd hr0 hdvd) (by omega)

/-- The Kempner digits are not eventually periodic: `2 ^ j + p` is not a power of `2` for
`0 < p < 2 ^ j`. -/
theorem not_isEventuallyPeriodic_kempnerDigits : ¬ IsEventuallyPeriodic kempnerDigits := by
  rintro ⟨N, p, hp, h⟩
  set j := N + p
  have hj : j < 2 ^ j := Nat.lt_two_pow_self
  have e := h (2 ^ j) (by omega)
  have h1 : kempnerDigits (2 ^ j) = 1 := kempnerDigits_eq_one_iff.mpr ⟨j, rfl⟩
  rw [h1, kempnerDigits_eq_one_iff] at e
  obtain ⟨k, hk⟩ := e
  have hlt : 2 ^ j < 2 ^ k := by omega
  have hjk : j + 1 ≤ k := (Nat.pow_lt_pow_iff_right (by norm_num)).mp hlt
  have := Nat.pow_le_pow_right (by norm_num : 0 < 2) hjk
  rw [pow_succ] at this
  omega

/-- The binary number with the Kempner digits is half of Kempner's number. -/
theorem ofDigits_kempnerDigits : Real.ofDigits kempnerDigits = (∑' j, ((2 : ℝ) ^ 2 ^ j)⁻¹) / 2 := by
  have hsupp : support (Real.ofDigitsTerm kempnerDigits) ⊆ Set.range (2 ^ · : ℕ → ℕ) := by
    intro n hn
    by_contra hr
    refine hn ?_
    have : kempnerDigits n = 0 := by
      classical
      unfold kempnerDigits
      exact ite_eq_right_iff.mpr fun ⟨j, hj⟩ ↦ absurd ⟨j, hj.symm⟩ hr
    simp [Real.ofDigitsTerm, this]
  rw [Real.ofDigits, ← (Nat.pow_right_injective le_rfl).tsum_eq hsupp, ← tsum_div_const]
  refine tsum_congr fun j ↦ ?_
  have : kempnerDigits (2 ^ j) = 1 := kempnerDigits_eq_one_iff.mpr ⟨j, rfl⟩
  simp only [Real.ofDigitsTerm, this, Fin.val_one, Nat.cast_one, one_mul, Nat.cast_ofNat, pow_succ]
  rw [mul_inv, div_eq_mul_inv]

/-- **Kempner's number `∑ 2 ^ (-2 ^ j)` is transcendental** (Kempner 1916), as a case of
Theorem 2. -/
theorem transcendental_tsum_kempner : Transcendental ℚ (∑' j, ((2 : ℝ) ^ 2 ^ j)⁻¹) := by
  have h := Real.transcendental_ofDigits_of_isAutomatic le_rfl isAutomatic_kempnerDigits
    (Real.irrational_ofDigits not_isEventuallyPeriodic_kempnerDigits)
  rw [ofDigits_kempnerDigits] at h
  refine fun halg ↦ h ?_
  have e : (∑' j, ((2 : ℝ) ^ 2 ^ j)⁻¹) / 2 =
      (∑' j, ((2 : ℝ) ^ 2 ^ j)⁻¹) * algebraMap ℚ ℝ (1 / 2) := by
    simp [div_eq_mul_inv]
  rw [e]
  exact (halg.isIntegral.mul isIntegral_algebraMap).isAlgebraic

/-! ### Morton–Mourant's exception -/

/-- Morton–Mourant's `e_{3,1,2}(n)`: the number of digits `1` in the ternary expansion of `n`,
modulo `2`. -/
def mortonMourant312 (n : ℕ) : ℕ := (Nat.digits 3 n).count 1 % 2

/-- `e_{3,1,2}(n) = n mod 2`: a ternary digit is congruent to `1` modulo `2` exactly when it is
`1`, and `3 ≡ 1`. -/
theorem mortonMourant312_eq (n : ℕ) : mortonMourant312 n = n % 2 := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · rfl
  · have h := ih (n / 3) (by omega)
    unfold mortonMourant312 at h ⊢
    rw [Nat.digits_def' (by norm_num) hn, List.count_cons]
    split_ifs with h1 <;> simp only [beq_iff_eq] at h1 <;> omega

/-- **Morton–Mourant's exception: `α (3, 1, 2) = 2 / 3`.** -/
theorem tsum_mortonMourant312 : ∑' n, (mortonMourant312 n : ℝ) / 2 ^ n = 2 / 3 := by
  have hsupp : support (fun n ↦ (mortonMourant312 n : ℝ) / 2 ^ n) ⊆
      Set.range (fun k : ℕ ↦ 2 * k + 1) := by
    intro n hn
    have hn' : n % 2 ≠ 0 := fun h0 ↦ hn (by simp [mortonMourant312_eq, h0])
    exact ⟨n / 2, by simp only; omega⟩
  have hinj : Injective (fun k : ℕ ↦ 2 * k + 1) := fun a b h ↦ by simp only at h; omega
  rw [← hinj.tsum_eq hsupp]
  have e : ∀ k : ℕ, (mortonMourant312 (2 * k + 1) : ℝ) / 2 ^ (2 * k + 1) = 1 / 2 * (1 / 4) ^ k :=
    fun k ↦ by
      rw [mortonMourant312_eq, show (2 * k + 1) % 2 = 1 by omega, pow_succ, pow_mul, one_div_pow]
      norm_num
  simp only [e]
  rw [tsum_mul_left, tsum_geometric_of_lt_one (by norm_num) (by norm_num)]
  norm_num

/-! ### The ternary morphism of §2 -/

/-- The morphism `0 ↦ 012, 1 ↦ 12, 2 ↦ 2` of Adamczewski–Bugeaud 2007, §2. -/
def ternaryMorphism : Fin 3 → List (Fin 3) := ![[0, 1, 2], [1, 2], [2]]

/-- **Rejection: the method does not reach the ternary example.** Every fixed point of
`0 ↦ 012, 1 ↦ 12, 2 ↦ 2` begins with a letter that never occurs again, so it is not recurrent
and Theorem 4 does not apply. (The fixed point `0121221222…` is transcendental by other means,
as the paper notes.) -/
theorem not_isRecurrent_of_isGeneratedByMorphism_ternaryMorphism {a : ℕ → Fin 3}
    (h : IsGeneratedByMorphism ternaryMorphism a) : ¬ IsRecurrent a := by
  obtain ⟨W, hc, hW⟩ := h.1
  have hW0 := hW 0
  simp only [morphismIter_zero, ne_eq] at hW0
  generalize ha0 : a 0 = c at hc hW0
  fin_cases c
  · exact h.not_isRecurrent (S := {1, 2}) (W := [1, 2]) (by rw [ha0]; rfl) (by rw [ha0]; decide)
      (by decide) (by decide)
  · exact h.not_isRecurrent (S := {2}) (W := [2]) (by rw [ha0]; rfl) (by rw [ha0]; decide)
      (by decide) (by decide)
  · have hc' : [(2 : Fin 3)] = 2 :: W := hc
    exact absurd (List.cons.inj hc').2.symm hW0
