/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import DiophantineApproximation.StammeringWords
public import Mathlib.Basic.Finite.Defs
public import Mathlib.Order.Filter.AtTopBot.Defs

-- Used only inside proofs.
import Mathlib.Data.Fintype.Pigeonhole
import Mathlib.Data.Set.Finite.Lattice
import Mathlib.Order.Filter.Cofinite
import Mathlib.Data.Finset.Max
import Mathlib.Order.Filter.AtTopBot.Finite

/-!
# Sequences generated by a morphism, and why they stammer

A **morphism** of the free monoid on `α` is a map `φ : α → List α`, extended to words by
concatenation (`List.flatMap`). It is **prolongable** at a letter `c` if `φ c = c W` with
`φ^k (W)` nonempty for every `k ≥ 0`; the words `φ^k (c)` then converge to an infinite word `a`,
a fixed point of `φ`, and `a` is **generated by** `φ`. A sequence is **recurrent** if every letter
occurring in it occurs at least twice (Adamczewski–Bugeaud 2007, §3).

The proof of Theorems 3 and 4 of Adamczewski–Bugeaud 2007 (§5) turns on one observation. Pick a
letter `b` whose image `φ^n (b)` is, for infinitely many `n`, at least as long as `φ^n` of every
letter occurring in `a`. If `b` occurs twice, `W₁ b W₂ b` is a prefix of `a`, so is
`φ^n (W₁) φ^n (b W₂) φ^n (b)`, and `a` satisfies Condition `(∗)_w` with `U = φ^n (W₁)`,
`V = φ^n (b W₂)` and `w = 1 + 1 / (|W₂| + 1)`.

## Main definitions

* `Function.morphismIter φ n W`: the word `φ^n (W)`.
* `Function.IsProlongable φ c`: `φ` is prolongable at `c`.
* `Function.HasPrefix a L`: the finite word `L` is a prefix of the sequence `a`.
* `Function.IsGeneratedByMorphism φ a`: `a` is the fixed point of `φ` generated from `a 0`.
* `Function.IsRecurrent a`: every letter occurring in `a` occurs at least twice.

## Main results

* `Function.IsProlongable.le_length`: `|φ^n (c)| ≥ n + 1`, so the prefixes exhaust `a`.
* `Function.IsGeneratedByMorphism.hasPrefix_morphismIter`: the image of a prefix of `a` is a prefix.
* `Function.IsGeneratedByMorphism.isStammering_of_frequently`: **the key step** — a letter of
  maximal growth occurring twice makes `a` stammering.
* `Function.IsGeneratedByMorphism.isStammering`: a recurrent fixed point over a finite alphabet is
  stammering.
* `Function.isRecurrent_of_not_isEventuallyPeriodic`: over two letters, non-periodicity implies
  recurrence.

## Implementation notes

⚠ **The letter of maximal growth is chosen among the letters that occur.** The paper chooses it
over the whole alphabet (proof of Theorem 3), and in the proof of Theorem 4 uses recurrence to
see it twice; a letter that never occurs in `a` is not covered by recurrence. Maximizing over the
occurring letters closes this gap and costs nothing: every letter of `W₁` and `W₂` occurs.

⚠ **"Generated by" is stated through prefixes**: `a 0 = c`, `φ` is prolongable at `c`, and every
`φ^k (c)` is a prefix of `a`. Since `|φ^k (c)| → ∞` this is the paper's `a = lim φ^k (c)`.

⚠ **Erasing morphisms are allowed**, as in the paper: `φ` may send a letter to the empty word.

## References

B. Adamczewski and Y. Bugeaud, *On the complexity of algebraic numbers I. Expansions in integer
bases*, Annals of Mathematics **165** (2007), 547–565, §3 and the proofs of Theorems 3 and 4 in §5.
-/

@[expose] public section

open Filter

namespace Function

variable {α : Type*}

/-- The word `φ^n (W)`, for a morphism `φ : α → List α` extended to words by concatenation. -/
def morphismIter (φ : α → List α) (n : ℕ) (W : List α) : List α :=
  (fun W ↦ W.flatMap φ)^[n] W

variable {φ : α → List α}

@[simp]
theorem morphismIter_zero (φ : α → List α) (W : List α) : morphismIter φ 0 W = W := rfl

theorem morphismIter_succ (φ : α → List α) (n : ℕ) (W : List α) :
    morphismIter φ (n + 1) W = morphismIter φ n (W.flatMap φ) :=
  iterate_succ_apply _ _ _

theorem morphismIter_add (φ : α → List α) (m n : ℕ) (W : List α) :
    morphismIter φ (m + n) W = morphismIter φ m (morphismIter φ n W) :=
  iterate_add_apply _ _ _ _

theorem morphismIter_append (φ : α → List α) (n : ℕ) (W W' : List α) :
    morphismIter φ n (W ++ W') = morphismIter φ n W ++ morphismIter φ n W' := by
  induction n generalizing W W' with
  | zero => rfl
  | succ n ih => simp only [morphismIter_succ, List.flatMap_append, ih]

theorem morphismIter_cons (φ : α → List α) (n : ℕ) (x : α) (W : List α) :
    morphismIter φ n (x :: W) = morphismIter φ n [x] ++ morphismIter φ n W :=
  morphismIter_append φ n [x] W

@[simp]
theorem morphismIter_nil (φ : α → List α) (n : ℕ) : morphismIter φ n [] = [] := by
  induction n with
  | zero => rfl
  | succ n ih => rw [morphismIter_succ, List.flatMap_nil, ih]

/-- If `φ^n` of every letter of `W` has length at most `L`, then `|φ^n (W)| ≤ |W| L`. -/
theorem length_morphismIter_le (φ : α → List α) (n : ℕ) {W : List α} {L : ℕ}
    (h : ∀ x ∈ W, (morphismIter φ n [x]).length ≤ L) :
    (morphismIter φ n W).length ≤ W.length * L := by
  induction W with
  | nil => simp
  | cons x W ih =>
    have h1 := h x (by simp)
    have h2 := ih fun y hy ↦ h y (by simp [hy])
    rw [morphismIter_cons, List.length_append, List.length_cons]
    nlinarith

/-- `φ` is **prolongable** at `c`: `φ c = c W` with `φ^k (W)` nonempty for every `k ≥ 0`. -/
def IsProlongable (φ : α → List α) (c : α) : Prop :=
  ∃ W, φ c = c :: W ∧ ∀ k, morphismIter φ k W ≠ []

/-- The words `φ^n (c)` grow: `|φ^n (c)| ≥ n + 1`. -/
theorem IsProlongable.le_length {c : α} (h : IsProlongable φ c) (n : ℕ) :
    n + 1 ≤ (morphismIter φ n [c]).length := by
  obtain ⟨W, hc, hW⟩ := h
  induction n with
  | zero => simp
  | succ n ih =>
    have e : morphismIter φ (n + 1) [c] = morphismIter φ n [c] ++ morphismIter φ n W := by
      rw [morphismIter_succ, List.flatMap_singleton, hc, morphismIter_cons]
    have := List.length_pos_iff_ne_nil.mpr (hW n)
    rw [e, List.length_append]
    omega

/-- The finite word `L` is a **prefix** of the sequence `a`. -/
def HasPrefix (a : ℕ → α) (L : List α) : Prop :=
  ∀ i < L.length, L[i]? = some (a i)

theorem hasPrefix_map_range (a : ℕ → α) (m : ℕ) : HasPrefix a ((List.range m).map a) := by
  intro i hi
  simp only [List.length_map, List.length_range] at hi
  simp [List.getElem?_range hi]

theorem HasPrefix.of_append {a : ℕ → α} {L L' : List α} (h : HasPrefix a (L ++ L')) :
    HasPrefix a L := fun i hi ↦ by
  rw [← List.getElem?_append_left hi]
  exact h i (by rw [List.length_append]; omega)

/-- A prefix of `a` is the initial segment of any longer prefix. -/
theorem HasPrefix.eq_take {a : ℕ → α} {L Q : List α} (hL : HasPrefix a L) (hQ : HasPrefix a Q)
    (hlen : L.length ≤ Q.length) : L = Q.take L.length := by
  refine List.ext_getElem? fun i ↦ ?_
  by_cases hi : i < L.length
  · rw [List.getElem?_take_of_lt hi, hL i hi, hQ i (by omega)]
  · push Not at hi
    rw [List.getElem?_eq_none hi, List.getElem?_eq_none (by simp; omega)]

/-- **`a` is generated by the morphism `φ`**: `φ` is prolongable at `c = a 0`, and every
`φ^k (c)` is a prefix of `a`, so that `a = lim φ^k (c)`. -/
def IsGeneratedByMorphism (φ : α → List α) (a : ℕ → α) : Prop :=
  IsProlongable φ (a 0) ∧ ∀ k, HasPrefix a (morphismIter φ k [a 0])

/-- **Every letter occurring in `a` occurs at least twice.** -/
def IsRecurrent (a : ℕ → α) : Prop :=
  ∀ i, ∃ j, j ≠ i ∧ a j = a i

/-- **The image of a prefix is a prefix.** `L` is an initial segment of `φ^m (c)` for `m ≥ |L|`,
so `φ^n (L)` is an initial segment of `φ^(n + m) (c)`, a prefix of `a`. -/
theorem IsGeneratedByMorphism.hasPrefix_morphismIter {a : ℕ → α}
    (h : IsGeneratedByMorphism φ a) {L : List α} (hL : HasPrefix a L) (n : ℕ) :
    HasPrefix a (morphismIter φ n L) := by
  set Q := morphismIter φ L.length [a 0]
  have hQ : L.length ≤ Q.length := (h.1.le_length L.length).trans' (Nat.le_succ _)
  have e2 : L ++ Q.drop L.length = Q := by
    have := List.take_append_drop L.length Q
    rwa [← hL.eq_take (h.2 _) hQ] at this
  have e : morphismIter φ (n + L.length) [a 0] =
      morphismIter φ n L ++ morphismIter φ n (Q.drop L.length) := by
    rw [morphismIter_add, ← morphismIter_append, e2]
  have := h.2 (n + L.length)
  rw [e] at this
  exact this.of_append

/-- Positions in `A (B C) B`: the copy of `B` after `A`, and the copy at the end. -/
theorem getElem?_append_append_self {A B C : List α} {u : ℕ} (hu : u < B.length) :
    (A ++ (B ++ C) ++ B)[A.length + u]? = B[u]? ∧
      (A ++ (B ++ C) ++ B)[A.length + u + (B ++ C).length]? = B[u]? := by
  constructor
  · rw [List.getElem?_append_left (by simp only [List.length_append]; omega),
      List.getElem?_append_right (by omega), Nat.add_sub_cancel_left,
      List.getElem?_append_left hu]
  · rw [List.getElem?_append_right (by simp only [List.length_append]; omega)]
    congr 1
    simp only [List.length_append]
    omega

/-- **The key step of the proofs of Theorems 3 and 4.** Let `a` be generated by `φ`, and let the
letter `a i` occur again at `j > i` and be, for infinitely many `n`, of maximal growth among the
letters of `a`: `|φ^n (a k)| ≤ |φ^n (a i)|` for all `k`. Then `a` is stammering, with
`w = 1 + 1 / (j - i)`. -/
theorem IsGeneratedByMorphism.isStammering_of_frequently {a : ℕ → α}
    (h : IsGeneratedByMorphism φ a) {i j : ℕ} (hij : i < j) (haij : a j = a i)
    (hmax : ∃ᶠ n in atTop,
      ∀ k, (morphismIter φ n [a k]).length ≤ (morphismIter φ n [a i]).length) :
    IsStammering a := by
  obtain ⟨m, rfl⟩ : ∃ m, j = i + 1 + m := ⟨j - i - 1, by omega⟩
  -- the prefix `a₀ … a_j = X (a i) R' (a j)`
  set X := (List.range i).map a
  set R' := (List.range m).map fun t ↦ a (i + 1 + t)
  have hP : (List.range (i + 1 + m + 1)).map a = X ++ (a i :: R') ++ [a (i + 1 + m)] := by
    rw [List.range_succ, List.range_add, List.range_succ]
    simp [X, R', Function.comp_def]
  set A : ℕ → List α := fun n ↦ morphismIter φ n X
  set B : ℕ → List α := fun n ↦ morphismIter φ n [a i]
  set C : ℕ → List α := fun n ↦ morphismIter φ n R'
  have hpre : ∀ n, HasPrefix a (A n ++ (B n ++ C n) ++ B n) := by
    intro n
    have := h.hasPrefix_morphismIter (hasPrefix_map_range a (i + 1 + m + 1)) n
    rwa [hP, morphismIter_append, morphismIter_append, morphismIter_cons, haij] at this
  set P : ℕ → Prop := fun n ↦ ∀ k, (morphismIter φ n [a k]).length ≤ (B n).length
  have hbound : ∀ n, P n → (A n).length ≤ i * (B n).length ∧
      (B n ++ C n).length ≤ (m + 1) * (B n).length ∧ n + 1 ≤ (B n).length := by
    intro n hn
    refine ⟨?_, ?_, (h.1.le_length n).trans (hn 0)⟩
    · have := length_morphismIter_le φ n (W := X) (L := (B n).length) fun x hx ↦ by
        obtain ⟨k, -, rfl⟩ := List.mem_map.mp hx
        exact hn k
      simpa [X] using this
    · have := length_morphismIter_le φ n (W := R') (L := (B n).length) fun x hx ↦ by
        obtain ⟨k, -, rfl⟩ := List.mem_map.mp hx
        exact hn _
      simp only [List.length_append]
      simp only [R', List.length_map, List.length_range] at this
      nlinarith
  -- a subsequence of the frequent `n` along which `s = |B C|` strictly increases
  set ss : ℕ → ℕ := fun n ↦ (B n ++ C n).length
  obtain ⟨f, hf⟩ : ∃ f : ℕ → ℕ, ∀ N, N ≤ f N ∧ P (f N) := by
    choose f hf using frequently_atTop.mp hmax
    exact ⟨f, hf⟩
  let g : ℕ → ℕ := fun k ↦ Nat.rec (f 0) (fun _ m ↦ f (ss m)) k
  have hgP : ∀ k, P (g k) := fun k ↦ by cases k <;> exact (hf _).2
  have hBs : ∀ n, (B n).length ≤ ss n := fun n ↦ by simp [ss]
  have hss : ∀ n, P n → n + 1 ≤ ss n := fun n hn ↦ (hbound n hn).2.2.trans (hBs n)
  have hmono : StrictMono (ss ∘ g) := strictMono_nat_of_lt_succ fun k ↦ by
    have h1 : ss (g k) ≤ g (k + 1) := (hf _).1
    have h2 := hss _ (hgP (k + 1))
    simp only [comp_apply]
    omega
  -- Condition `(∗)_w` in its periodic form, with `w = 1 + 1 / (m + 1)`
  have hd : (0 : ℝ) < (m : ℝ) + 1 := by positivity
  refine ⟨1 + 1 / ((m : ℝ) + 1), by simp [hd], ?_⟩
  refine isStammeringWith_of_periodic (C := i) (r := fun k ↦ (A (g k)).length) (s := ss ∘ g)
    (by positivity) hmono (fun k ↦ by have := hss _ (hgP k); simp only [comp_apply]; omega)
    (fun k ↦ ?_) (fun k t hrt hts ↦ ?_)
  · obtain ⟨h1, -, -⟩ := hbound _ (hgP k)
    simp only [comp_apply]
    exact_mod_cast h1.trans (Nat.mul_le_mul_left i (hBs _))
  · simp only [comp_apply] at hts ⊢
    set n := g k
    obtain ⟨-, h2, -⟩ := hbound _ (hgP k)
    -- `⌈w s⌉ ≤ s + |B|`, so the position lies in the copy of `B` after `A`
    have hceil : ⌈(1 + 1 / ((m : ℝ) + 1)) * ss n⌉₊ ≤ ss n + (B n).length := by
      refine Nat.ceil_le.mpr ?_
      have h2' : (ss n : ℝ) ≤ ((m : ℝ) + 1) * (B n).length := by exact_mod_cast h2
      push_cast
      rw [add_mul, one_mul, add_le_add_iff_left, div_mul_eq_mul_div, one_mul, div_le_iff₀ hd]
      linarith
    obtain ⟨u, rfl⟩ : ∃ u, t = (A n).length + u := ⟨t - (A n).length, by omega⟩
    have hu : u < (B n).length := by omega
    obtain ⟨hA', hB'⟩ := getElem?_append_append_self (A := A n) (C := C n) hu
    have hlen : (A n ++ (B n ++ C n) ++ B n).length = (A n).length + ss n + (B n).length := by
      simp [ss]; omega
    have hA := hpre n ((A n).length + u) (by rw [hlen]; omega)
    have hB := hpre n ((A n).length + u + ss n) (by rw [hlen]; omega)
    rw [hA'] at hA
    rw [hB'] at hB
    exact Option.some_injective _ (hB.symm.trans hA)

/-- A letter of maximal growth: over a finite alphabet, some letter `a i` is, for infinitely many
`n`, at least as long under `φ^n` as every letter occurring in `a`. -/
theorem exists_frequently_forall_length_le [Finite α] (φ : α → List α) (a : ℕ → α) :
    ∃ i, ∃ᶠ n in atTop,
      ∀ k, (morphismIter φ n [a k]).length ≤ (morphismIter φ n [a i]).length := by
  have hmax : ∀ n, ∃ i, ∀ k, (morphismIter φ n [a k]).length ≤ (morphismIter φ n [a i]).length :=
    fun n ↦ by
      obtain ⟨x, hx, hi⟩ := (Set.toFinite (Set.range a)).toFinset.exists_max_image
        (fun x ↦ (morphismIter φ n [x]).length) ⟨a 0, by simp⟩
      obtain ⟨i, rfl⟩ := (Set.Finite.mem_toFinset _).mp hx
      exact ⟨i, fun k ↦ hi (a k) (by simp)⟩
  choose idx hidx using hmax
  -- the maximizing letter takes some value `a (idx n₀)` infinitely often
  obtain ⟨x, hx⟩ := Finite.exists_infinite_fiber fun n ↦ a (idx n)
  have hS := Set.infinite_coe_iff.mp hx
  obtain ⟨n₀, hn₀⟩ := hS.nonempty
  refine ⟨idx n₀, Nat.frequently_atTop_iff_infinite.mpr (hS.mono fun n hn k ↦ ?_)⟩
  have e : a (idx n) = a (idx n₀) := by
    simp only [Set.mem_preimage, Set.mem_singleton_iff] at hn hn₀
    rw [hn, hn₀]
  rw [← e]
  exact hidx n k

/-- **A recurrent sequence generated by a morphism over a finite alphabet is stammering**
(Adamczewski–Bugeaud 2007, proofs of Theorems 3 and 4). -/
theorem IsGeneratedByMorphism.isStammering [Finite α] {a : ℕ → α}
    (h : IsGeneratedByMorphism φ a) (hrec : IsRecurrent a) : IsStammering a := by
  obtain ⟨i, hi⟩ := exists_frequently_forall_length_le φ a
  obtain ⟨j, hji, haj⟩ := hrec i
  rcases lt_or_gt_of_ne hji with hlt | hlt
  · exact h.isStammering_of_frequently hlt haj.symm (hi.mono fun n hn k ↦ haj ▸ hn k)
  · exact h.isStammering_of_frequently hlt haj hi

/-- **A criterion for non-recurrence.** If `φ (a 0) = a 0 W` with the letters of `W` in a set `S`
that avoids `a 0` and that `φ` maps into itself, then `a 0` never occurs again in `a`. -/
theorem IsGeneratedByMorphism.not_isRecurrent {a : ℕ → α} (h : IsGeneratedByMorphism φ a)
    {S : Set α} {W : List α} (hc : φ (a 0) = a 0 :: W) (h0 : a 0 ∉ S) (hW : ∀ x ∈ W, x ∈ S)
    (hS : ∀ x ∈ S, ∀ y ∈ φ x, y ∈ S) : ¬ IsRecurrent a := by
  have hinv : ∀ k, ∃ L, morphismIter φ k [a 0] = a 0 :: L ∧ ∀ x ∈ L, x ∈ S := by
    intro k
    induction k with
    | zero => exact ⟨[], rfl, by simp⟩
    | succ k ih =>
      obtain ⟨L, hL, hLS⟩ := ih
      refine ⟨W ++ L.flatMap φ, ?_, fun x hx ↦ ?_⟩
      · rw [add_comm, morphismIter_add, hL]
        simp [morphismIter, hc]
      · rcases List.mem_append.mp hx with hx | hx
        · exact hW x hx
        · obtain ⟨y, hy, hxy⟩ := List.mem_flatMap.mp hx
          exact hS y (hLS y hy) x hxy
  intro hrec
  obtain ⟨j, hj, haj⟩ := hrec 0
  obtain ⟨L, hL, hLS⟩ := hinv j
  have hlen := h.1.le_length j
  have hpre := h.2 j j (by omega)
  rw [hL] at hlen hpre
  obtain ⟨j', rfl⟩ : ∃ j', j = j' + 1 := ⟨j - 1, by omega⟩
  rw [List.getElem?_cons_succ] at hpre
  have hmem : a (j' + 1) ∈ L := List.mem_of_getElem? hpre
  exact h0 (haj ▸ hLS _ hmem)

/-- **Over two letters, a sequence that is not eventually periodic is recurrent**: if the letter
`a i` never occurred again, `a` would be constant after `i`. -/
theorem isRecurrent_of_not_isEventuallyPeriodic {a : ℕ → Fin 2}
    (h : ¬ IsEventuallyPeriodic a) : IsRecurrent a := by
  intro i
  by_contra hne
  push Not at hne
  refine h ⟨i + 1, 1, one_pos, fun n hn ↦ ?_⟩
  have h1 := hne n (by omega)
  have h2 := hne (n + 1) (by omega)
  rw [Ne, Fin.ext_iff] at h1 h2
  ext
  have := (a n).isLt
  have := (a (n + 1)).isLt
  have := (a i).isLt
  omega

end Function
