/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import AdamczewskiBugeaud2007.Morphism
public import AdamczewskiBugeaud2007.PadicTranscendence

/-!
# Numbers generated by a morphism: Theorems 3, 4, 3B and 4B

**Theorem 3** of Adamczewski–Bugeaud 2007: binary algebraic irrational numbers cannot be generated
by a morphism. **Theorem 4**: for `b ≥ 3`, the base-`b` expansion of an algebraic irrational
number cannot be generated by a recurrent morphism. Theorems 3B and 4B are the `p`-adic versions
(§6). All four follow from the combinatorial transcendence criteria (Theorem 5 for `β = b`,
Theorem 6) and the fact that the fixed points in question are stammering
(`Function.IsGeneratedByMorphism.isStammering`).

The file also records the estimate (1) of the paper's §2, `p (n) - n → ∞`, which Ferenczi and
Mauduit proved and Theorem 1 improves.

## Main results

* `Real.transcendental_ofDigits_of_isGeneratedByMorphism`: **Theorem 3**.
* `Real.transcendental_ofDigits_of_isGeneratedByMorphism_of_isRecurrent`: **Theorem 4**, for every
  `b ≥ 2`.
* `Padic.transcendental_ofDigits_of_isGeneratedByMorphism`: **Theorem 3B**.
* `Padic.transcendental_ofDigits_of_isGeneratedByMorphism_of_isRecurrent`: **Theorem 4B**.
* `Real.tendsto_complexity_sub_atTop`: (1), `p (n) - n → ∞` for an algebraic irrational.

## Implementation notes

⚠ **Theorem 4 is stated for `b ≥ 2`**, not only `b ≥ 3`. The paper separates `b = 2` because
Theorem 3 needs no recurrence there; the proof of Theorem 4 works for every base.

⚠ **Theorem 3B is for `p = 2`**, which is what "binary" means for Hensel expansions; for other
primes Theorem 4B applies. In both, "irrational" is `ofDigits a ∉ Set.range ((↑) : ℚ → ℚ_[p])`.

## References

B. Adamczewski and Y. Bugeaud, *On the complexity of algebraic numbers I. Expansions in integer
bases*, Annals of Mathematics **165** (2007), 547–565, Theorems 3, 4, 3B, 4B and (1); S. Ferenczi
and C. Mauduit, *Transcendence of numbers with a low complexity expansion*, J. Number Theory
**67** (1997), 146–161.
-/

@[expose] public section

open Filter

namespace Real

/-- **Theorem 3 (Adamczewski–Bugeaud 2007): binary algebraic irrational numbers cannot be
generated by a morphism.** If the binary digits `a` are a fixed point of a morphism and
`∑ k, a k / 2 ^ (k + 1)` is irrational, it is transcendental. -/
theorem transcendental_ofDigits_of_isGeneratedByMorphism {a : ℕ → Fin 2}
    {φ : Fin 2 → List (Fin 2)} (h : Function.IsGeneratedByMorphism φ a)
    (hirr : Irrational (ofDigits a)) : Transcendental ℚ (ofDigits a) := by
  have hper := (irrational_ofDigits_iff le_rfl).mp hirr
  exact transcendental_ofDigits_of_isStammering le_rfl
    (h.isStammering (Function.isRecurrent_of_not_isEventuallyPeriodic hper)) hper

/-- **Theorem 4 (Adamczewski–Bugeaud 2007).** The base-`b` expansion of an algebraic irrational
number cannot be generated by a recurrent morphism: if the digits `a` are a recurrent fixed point
of a morphism and `∑ k, a k / b ^ (k + 1)` is irrational, it is transcendental. -/
theorem transcendental_ofDigits_of_isGeneratedByMorphism_of_isRecurrent {b : ℕ} (hb : 2 ≤ b)
    {a : ℕ → Fin b} {φ : Fin b → List (Fin b)} (h : Function.IsGeneratedByMorphism φ a)
    (hrec : Function.IsRecurrent a) (hirr : Irrational (ofDigits a)) :
    Transcendental ℚ (ofDigits a) :=
  transcendental_ofDigits_of_isStammering hb (h.isStammering hrec)
    ((irrational_ofDigits_iff hb).mp hirr)

/-- **(1) of Adamczewski–Bugeaud 2007** (Ferenczi–Mauduit): the complexity of the base-`b`
expansion of an algebraic irrational number satisfies `p (n) - n → ∞`. It follows from Theorem 1,
`p (n) / n → ∞`. -/
theorem tendsto_complexity_sub_atTop {b : ℕ} (hb : 2 ≤ b) {a : ℕ → Fin b}
    (hirr : Irrational (ofDigits a)) (halg : IsAlgebraic ℚ (ofDigits a)) :
    Tendsto (fun n ↦ (Function.complexity a n : ℝ) - n) atTop atTop := by
  have h2 := (tendsto_atTop.mp (tendsto_complexity_div_atTop hb hirr halg)) 2
  refine tendsto_atTop_mono' atTop ?_ tendsto_natCast_atTop_atTop
  filter_upwards [h2, eventually_ge_atTop 1] with n hn hn1
  have : (0 : ℝ) < n := by exact_mod_cast hn1
  rw [le_div_iff₀ this] at hn
  linarith

end Real

namespace Padic

/-- **Theorem 3B (Adamczewski–Bugeaud 2007).** An irrational `2`-adic number whose Hensel
expansion is generated by a morphism is transcendental. -/
theorem transcendental_ofDigits_of_isGeneratedByMorphism {a : ℕ → Fin 2}
    {φ : Fin 2 → List (Fin 2)} (h : Function.IsGeneratedByMorphism φ a)
    (hirr : ofDigits a ∉ Set.range ((↑) : ℚ → ℚ_[2])) : Transcendental ℚ (ofDigits a) := by
  have hper : ¬ Function.IsEventuallyPeriodic a := fun ha ↦
    hirr (ofDigits_mem_range_ratCast_iff.mpr ha)
  exact transcendental_ofDigits_of_isStammering
    (h.isStammering (Function.isRecurrent_of_not_isEventuallyPeriodic hper)) hper

/-- **Theorem 4B (Adamczewski–Bugeaud 2007).** An irrational `p`-adic number whose Hensel
expansion is generated by a recurrent morphism is transcendental. -/
theorem transcendental_ofDigits_of_isGeneratedByMorphism_of_isRecurrent {p : ℕ} [Fact p.Prime]
    {a : ℕ → Fin p} {φ : Fin p → List (Fin p)} (h : Function.IsGeneratedByMorphism φ a)
    (hrec : Function.IsRecurrent a) (hirr : ofDigits a ∉ Set.range ((↑) : ℚ → ℚ_[p])) :
    Transcendental ℚ (ofDigits a) :=
  transcendental_ofDigits_of_isStammering (h.isStammering hrec)
    fun ha ↦ hirr (ofDigits_mem_range_ratCast_iff.mpr ha)

end Padic
