/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import AdamczewskiBugeaud2007.MorphicTranscendence

/-!
# The open problems of Adamczewski–Bugeaud 2007

Two statements of the paper's §2 are left open there, and are stated here as propositions, not
proved.

* **The Conjecture** (after Theorem 2): *irrational morphic numbers are transcendental.* A real
  number is morphic if, for some integer `b ≥ 2`, its base-`b` expansion is morphic (§3): the
  image `σ (u)` under a morphism `σ` of a sequence `u` generated by a morphism. Theorems 2, 3 and 4
  are the cases the paper proves: automatic sequences, binary fixed points, and recurrent fixed
  points.
* **The ternary problem** (after Theorem 4): "Unfortunately, we are unable to prove that ternary
  algebraic numbers cannot be generated by a morphism." That is, an irrational number whose
  base-`3` expansion is a fixed point of a morphism, recurrent or not, should be transcendental.
  The paper's example is the fixed point `0121221222…` of `0 ↦ 012, 1 ↦ 12, 2 ↦ 2`, which is not
  recurrent (`not_isRecurrent_of_isGeneratedByMorphism_ternaryMorphism`); that particular number
  is transcendental by results on theta series (Bertrand; Duverney–Nishioka–Nishioka–Shiokawa).

Both are open. The Conjecture implies the ternary problem
(`MorphicConjecture.ternaryMorphismProblem`), since a fixed point is morphic
(`Function.IsGeneratedByMorphism.isMorphic`).

## Main definitions

* `Function.IsMorphismImage σ u a`: the sequence `a` is the image `σ (u)` of the sequence `u`.
* `Function.IsMorphic a`: `a` is morphic.
* `MorphicConjecture`: the Conjecture.
* `TernaryMorphismProblem`: the ternary problem.

## Implementation notes

⚠ **`σ (u)` is defined through prefixes**: every `σ (u 0 ⋯ u (n - 1))` is a prefix of `a`, and
their lengths are unbounded. The second condition says that `σ (u)` is an infinite word; `σ` may
erase letters, as the paper allows.

⚠ **The alphabet of `u` is `Fin m`.** The paper's alphabet `B` is any finite set; `Fin m` is one
of each size, and keeps `IsMorphic` in the universe of `a`.

⚠ **A morphic number is stated through its digits**, as in Theorems 2 to 4: the Conjecture is
about `Real.ofDigits a = ∑ k, a k / b ^ (k + 1)` for morphic `a`. A real number differs from the
number formed by its digits by an integer, which changes neither irrationality nor
transcendence.

## References

B. Adamczewski and Y. Bugeaud, *On the complexity of algebraic numbers I. Expansions in integer
bases*, Annals of Mathematics **165** (2007), 547–565, §2 and §3; D. Bertrand, *Theta functions
and transcendence*, Ramanujan J. **1** (1997), 339–350; D. Duverney, Ke. Nishioka, Ku. Nishioka and
I. Shiokawa, *Transcendence of Jacobi's theta series*, Proc. Japan Acad. Ser. A **72** (1996),
202–203.
-/

@[expose] public section

namespace Function

variable {α β : Type*}

/-- **`a` is the image `σ (u)` of the sequence `u` under the morphism `σ : β → List α`**: every
`σ (u 0 ⋯ u (n - 1))` is a prefix of `a`, and these prefixes are arbitrarily long. -/
def IsMorphismImage (σ : β → List α) (u : ℕ → β) (a : ℕ → α) : Prop :=
  (∀ n, HasPrefix a (((List.range n).map u).flatMap σ)) ∧
    ∀ N, ∃ n, N ≤ (((List.range n).map u).flatMap σ).length

/-- **`a` is morphic** (Adamczewski–Bugeaud 2007, §3): `a = σ (u)` for a sequence `u` over a finite
alphabet generated by a morphism `ψ`, and a morphism `σ`. -/
def IsMorphic (a : ℕ → α) : Prop :=
  ∃ (m : ℕ) (u : ℕ → Fin m) (ψ : Fin m → List (Fin m)) (σ : Fin m → List α),
    IsGeneratedByMorphism ψ u ∧ IsMorphismImage σ u a

/-- **A sequence generated by a morphism is morphic**, with `σ` the identity. -/
theorem IsGeneratedByMorphism.isMorphic {b : ℕ} {a : ℕ → Fin b} {φ : Fin b → List (Fin b)}
    (h : IsGeneratedByMorphism φ a) : IsMorphic a := by
  refine ⟨b, a, φ, fun x ↦ [x], h, fun n ↦ ?_, fun N ↦ ⟨N, ?_⟩⟩
  · rw [List.flatMap_singleton']
    exact hasPrefix_map_range a n
  · simp [List.flatMap_singleton']

end Function

/-- **The Conjecture of Adamczewski–Bugeaud 2007** (§2, open): *irrational morphic numbers are
transcendental.* If the base-`b` digits `a` are morphic and `∑ k, a k / b ^ (k + 1)` is
irrational, it is transcendental. -/
def MorphicConjecture : Prop :=
  ∀ ⦃b : ℕ⦄, 2 ≤ b → ∀ ⦃a : ℕ → Fin b⦄, Function.IsMorphic a →
    Irrational (Real.ofDigits a) → Transcendental ℚ (Real.ofDigits a)

/-- **The ternary problem of Adamczewski–Bugeaud 2007** (§2, after Theorem 4, open): *ternary
algebraic irrational numbers cannot be generated by a morphism.* If the base-`3` digits `a` are a
fixed point of a morphism and `∑ k, a k / 3 ^ (k + 1)` is irrational, it is transcendental. Theorem
4 (`Real.transcendental_ofDigits_of_isGeneratedByMorphism_of_isRecurrent`) is the recurrent
case. -/
def TernaryMorphismProblem : Prop :=
  ∀ ⦃a : ℕ → Fin 3⦄ ⦃φ : Fin 3 → List (Fin 3)⦄, Function.IsGeneratedByMorphism φ a →
    Irrational (Real.ofDigits a) → Transcendental ℚ (Real.ofDigits a)

/-- **The Conjecture settles the ternary problem.** -/
theorem MorphicConjecture.ternaryMorphismProblem (h : MorphicConjecture) :
    TernaryMorphismProblem :=
  fun _ _ hφ hirr ↦ h (by norm_num) hφ.isMorphic hirr
